### ISSUE TITLE
Only the first matcher is considered

### ISSUE THREAD

**Issue by mizgeliko** [pac4j/pac4j#1002]
In case several filters with different matchers were configured for the same url only the first one is checked.

**Comment by leleuj** [comment]
Indeed, it's by design: all matchers must be satisfied, based on the default: `DefaultMatchingChecker` in the `DefaultSecurityLogic`. So if the first matcher is not satisfied, the second one is not tried.

We could rename it as `AllMatcherChecker` or something like that and create an `AnyMatcherChecker` with the behavior you propose...

**Comment by mizgeliko** [comment]
Thanks for you answer, Jérôme. In my opinion everything works fine if it is a path matcher. The situation is different if we try to use  http method or http header matchers. For example, lets take a combination of authorizers and matchers for the case below
path    |  role       | method
--------------------------
/books | view      | get
/books | remove | delete

when I tried creating security filters I had doubts about the right approach:
on the one hand an approach with configuring of the several filters for the same url does not work, on the other hand I can't rely on 'matcher'-s because of DefaultSecurityLogic / DefaultMatchingChecker permits access if a first "configured" matcher fails.
So an attempt to distinguish the authorization for particular path via having http method matchers failed. As result I implemented a custom Authorizer that considered http method and role.

What is your opinion about this? Is there any other approach to resolve this pretty common task in more elegant way?
I thought about annotations but it's another topic to discuss.

**Comment by leleuj** [comment]
I'm not sure to understand, why don't you have two `SecurityFilter`s  with different matchers (one for GET, the other for DELETE) and authorizers?

**Comment by mizgeliko** [comment]
back to original post - because it doesn't work properly :confused:

**Comment by leleuj** [comment]
Can you elaborate a little more? "it doesn't work properly"

**Comment by millross** [comment]
Please could you provide a github project which demonstrates the problem? That's probably the easiest way to elaborate.

**Comment by leleuj** [comment]
This is something that should be discussed on the mailing list. At least, I will rename the `DefaultMatchingChecker` in `RequireAllMatchersChecker`. See: https://github.com/pac4j/pac4j/pull/1011
