### ISSUE TITLE
How to config the passwordAttribute of Mongo on Meteor?

### ISSUE THREAD

**Issue by zonglu520** [pac4j/pac4j#1013]
This is my mongoDB :
```
{
   "username" : "cas",
    "services" : {
        "password" : {
            "bcrypt" : "123456"
        }
    }
}
```
when I use cas and config  :
`cas.authn.mongo.passwordAttribute=services.password.bcrypt`
it can not authentication.

**Comment by leleuj** [comment]
Please ask your question on the mailing list.
