### ISSUE TITLE
loadProfileFromSession

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#1015]
The `saveProfileInSession` property is used to save the profiles into the session after a web services authentication.

It would make sense to have a `loadProfileFromSession` property as well.

**Comment by millross** [comment]
I disagree slightly The two should be combined into a profile storage strategy interface. You wouldn’t expect to save to one location and load from another, so it’s a storage strategy interface implementor which is supplied to everywhere which does profile storage/retrieval.

**Comment by leleuj** [comment]
I admit that the double properties are certainly cumbersome compared to a clean interface.

But these are two different use cases:

1) you perform a UI authentication and want to call your REST API (single page application): you need to load the profiles from the session
2) you perform a web service authentication and want to use the UI then (authentication by token from a link in an email for example): you want to save the profiles into the session

**Comment by millross** [comment]
But surely both reflect the same storage strategy - storage into the session.
