### ISSUE TITLE
SAML2MetadataGenerator not honoring NameIdPolicyFormat on client configuration

### ISSUE THREAD

**Issue by scoldwell** [pac4j/pac4j#1026]
The SAML2MetadataGenerator outputs all NameId formats in the generated metadata even though you can specify the specific NameIdFormatPolicy via SAML2ClientConfiguration.setNameIdPolicyFormat(String).  That policy is never passed to SAML2MetadataGenerator and as such SAML2MetadataGenerator.buildNameIDFormat() ends up including all formats.

**Comment by leleuj** [comment]
Thanks for reporting. Would you mind submitting a pull request to fix that? Thanks
