### ISSUE TITLE
State Parameter prevents login with more than one tabs open when requiresStateParameter() returns true

### ISSUE THREAD

**Issue by qinfchen** [pac4j/pac4j#103]
When requiresStateParameter returns true, a new state parameter is generated every time retrieveAuthorizationUrl is called. As a result, the old state parameter gets replaced in the context.  If two urls were generated from two login attempts, the first authorization Url generated is no longer valid and, if the first attempt is authenticated after the second attempt started, parameter mismatch will prevent login and return an OAuthCredentialsException.

**Comment by hoegertn** [comment]
I agree with @leleuj  The state parameter is a one time token and this is how it is designed to be. I currently do not see the use case of multiple logins at the same time.
