### ISSUE TITLE
Improve user access to profiles retrieved by a SecurityLogic

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#1032]
To implement pac4j/j2e-pac4j#44 as well as to implement profile injection in user code in jax-rs-pac4j, I need, once a `SecurityLogic` has been passed through, to retrieve the list of profiles that were retrieved for this filter.

My original solution with jax-rs-pac4j was to let the user decide if the profile was t be retrieved from session or not. This is similar to instantiating the `ProfileManager` from the `WebContext` in user code (see https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/jersey/features/Pac4JValueFactoryProvider.java#L236).

Concerning pac4j/j2e-pac4j#44, this question arises in the implementation of the `SecurityGrantedAccessAdapter` that takes over once `SecurityLogic` has finished its job: I need the profiles in order to build a `HttpServletRequestWrapper` that is pac4j aware. I thus devised #1028 in order to implement that.

My problem with all of this is that:
 1. they are actually the same problem (accessing the profiles retrieved by the `SecurityLogic` from user code) and they have different solutions.
 2. The jax-rs-pac4j solution implies that the user must keep knowledge between filter configuration (read/write from session) and its code (passing a boolean to the `ProfileManager`).

I think there is something to be done here.
I think there is some links to #1019 too maybe (@millross).

After the `SecurityLogic` has done its job, we should be at least able to access all the retrieved profiles from one place. And maybe other request-related information (so #1028 is not enough).

One part of the problem is that the `WebContext` is not really a context, it is a wrapper over the requests and responses: why can't I simply ask the `WebContext` for the profiles of the current request?
Another part of the problem is that the `WebContext` is not really meant to be passer along the chain of handler of the request, it is as if it had no actual state, everything is stored in the session and/or in the request, even though we shouldn't be worried about knowing where to look for the profiles.

**Comment by millross** [comment]
Let's see how that shakes out and then I might propose improvements if I get round to referencing pac4j 3 from the pac4j-async stuff I'm working on. However, my primary focus is on providing an implementation for pac4j 2.1 rather than trying to hit a moving target, and to use that as a feed in for changes we will need in pac4j if we want to support Async (large numbers of classes will have to change by becoming polymorphic so we can auto-reuse them for async where appropriate).

**Comment by leleuj** [comment]
Let's see how @victornoel feels about that before proceeding...

**Comment by victornoel** [comment]
Sorry for the delay :)

Yes all of this sounds good to me! I will update #1028 to match what you said this week-end.

**Comment by leleuj** [comment]
Great! Step 1: merged #1031

Working on #1019

**Comment by leleuj** [comment]
Step 2: merged #1028 

Step 3: will merge #1019
