### ISSUE TITLE
Retrieve Access Token from Refresh Token stored in OIDC profile

### ISSUE THREAD

**Issue by mores** [pac4j/pac4j#1043]
Here are the docs to add support for the AzureAdClient: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code#refreshing-the-access-tokens

If you can provide some direction ( gist ) I can make a PR.

**Comment by leleuj** [comment]
Would you mind submitting a pull request? Thanks

**Comment by mores** [comment]
DiscoveryURI is "https://login.microsoftonline.com/" + microsoftTenant + "/.well-known/openid-configuration"
AcceessTokenFromRefreshURI is "https://login.microsoftonline.com/" + microsoftTenant + "/oauth2/token"

What would be the best way to configure the microsoftTenant inside of pac4j ?

**Comment by leleuj** [comment]
No, I don't have a better idea, it seems the best option.

**Comment by kunalsumbly** [comment]
Hi ..wanted to know if we have the feature of access token and refresh token available in normal oidc client as well. e.g. if we want to check the expiry of the access token which we got from an OIDC server and use refresh token to get a new access token after the previous access token is no more valid.

**Comment by leleuj** [comment]
Please use the mailing list for questions. And yes: https://github.com/pac4j/pac4j/blob/3.6.x/pac4j-oidc/src/main/java/org/pac4j/oidc/profile/OidcProfile.java#L107
