### ISSUE TITLE
Merge both "authRequestSigned"?

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#1044]
I noticed we have: `forceSignRedirectBindingAuthnRequest` and `authnRequestSigned`: shouldn't we merge both in a `mustSignAuthRequest`?

@mmoayyed : what do you think?

**Comment by mmoayyed** [comment]
I agree; We should. I actually don't know why there exists a `forceSignRedirectBindingAuthnRequest` but we should merge.

**Comment by leleuj** [comment]
Thanks. This is what I had in mind...
