### ISSUE TITLE
Create AzureAdMemberGroupAuthorizationGenerator

### ISSUE THREAD

**Issue by mores** [pac4j/pac4j#1052]
AzureAdMemberGroupAuthorizationGenerator could call https://graph.microsoft.com/v1.0/me/getMemberGroups with the authority of the user that is logged in
 - or -
https://graph.microsoft.com/v1.0/users/{id | userPrincipalName}/getMemberGroups with the authority of a service account ( user and password that gets the token ), in which case could be used with ANY Authentication mechanism.

Documentation can be found here: https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/user_getmembergroups

**Comment by leleuj** [comment]
Closing for now. Feel free to reopen with a contribution.
