### ISSUE TITLE
JwtGenerator claimset builder mentions issuetime but it isnt actually set

### ISSUE THREAD

**Issue by andre-doherty** [pac4j/pac4j#1053]
It looks like issueTime should be set on default claimset (comment mentions it) but it isnt actually set.

Shouldn't it be like this ? 

`// claims builder with subject and issue time`
`final JWTClaimsSet.Builder builder = new JWTClaimsSet.Builder()`
`                .subject(profile.getTypedId())`
`		.issueTime(new Date());`

**Comment by leleuj** [comment]
It seems so, but I have the feeling there was a reason behind this. Anyway, can you submit a PR and ensure the tests still pass? Thanks
