### ISSUE TITLE
J2EContext getFullRequestURL append a query string again and again

### ISSUE THREAD

**Issue by kawhii** [pac4j/pac4j#1062]
https://github.com/pac4j/pac4j/blob/e8b3366e4cb93521c6d3b778f85c5634a8cd5614/pac4j-core/src/main/java/org/pac4j/core/context/J2EContext.java#L171

when not authentication, first debug message on 
https://github.com/pac4j/pac4j/blob/ccc72b7c45892182306edefcfc39a9e3578f60aa/pac4j-core/src/main/java/org/pac4j/core/engine/DefaultSecurityLogic.java#L87

after save request url https://github.com/pac4j/pac4j/blob/ccc72b7c45892182306edefcfc39a9e3578f60aa/pac4j-core/src/main/java/org/pac4j/core/engine/DefaultSecurityLogic.java#L144

it will append a query string if request have query string.

![image](https://user-images.githubusercontent.com/9932775/34027379-372b6760-e197-11e7-9210-d4c9331fc7ca.png)

---
and then have a callback request, the request url is not the first time request.

**Comment by leleuj** [comment]
This is really strange as the spec says that the `getRequestURL` method does not have the query string: "Reconstructs the URL the client used to make the request. The returned URL contains a protocol, server name, port number, and server path, but it does not include query string parameters."

What's your application server?

**Comment by kawhii** [comment]
Tomcat.

OK!
I found the problem.
We wrapper the request and return the samle requestUrl and change that for append a query string again and again .
---
But in that code, consider not direct append query string?

**Comment by leleuj** [comment]
We follow the spec, I don't think we can do better.
