### ISSUE TITLE
Move the redirect/getLogoutAction methods outside the Client interface

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#1069]
And inside the `IndirectClient` class?

**Comment by giflw** [comment]
I think we should have one interface with access to both direct and indirect actions, but wiht the indirect ones encapsulated in an Optional. In this way, the type of client is indiferent for autentication code, and only one Optional/check would suffice to use indirect clients

```java
interface Client {
    String getName();
    Optional<C> getCredentials(...);
    Optional<U> getUserProfile(...);
    Optional<IndirectActions> getIndirectActions();
}

interface IndirectActions {
    HttpAction redirect(...);
    Optional<RedirectAction> getLogoutAction(...);
}
```

**Comment by leleuj** [comment]
This is a fairly interesting approach which has the benefit to highlight that we may have indirection actions in the clients.

**Comment by leleuj** [comment]
Thinking more about that, I think the original proposal was the best one: make the `redirect` and `getLogoutAction` methods return `Optional`.
So closing this one in favor of https://github.com/pac4j/pac4j/issues/926.
