### ISSUE TITLE
Potential regression on 2.2.x : ProtocolBinding in SAML2 AuthnRequest is set according to saml2Config.destinationBindingType

### ISSUE THREAD

**Issue by andre-doherty** [pac4j/pac4j#1071]
It looks like the saml2Config.destinationBindingType is used both by to generate the sp-metadata and generate the authnrequest (protocol binding) 

but also to determine how the idp is going be the accessed.

**Comment by andre-doherty** [comment]
seems the change on pac4j-saml/src/main/java/org/pac4j/saml/metadata/SAML2MetadataGenerator.java is the cause for that change.
Specifically as a new field binding makes use of destinationBindingType : 
`this.binding = configuration.getDestinationBindingType();`

What is the intended purpose of that configuration element ?

**Comment by andre-doherty** [comment]
There is as well : 

`public SAML2AuthnRequestBuilder(final SAML2ClientConfiguration cfg) {
..
this.bindingType = cfg.getDestinationBindingType();`

I suggest the creation of a new field in SAML2ClientConfiguration, eg serviceProviderBindingType which would bear the binding type of the callback 

The other destinationBindingType would be kept for the hooking to the idp

**Comment by leleuj** [comment]
I guess you tested the version 2.2.0 and indeed, there was a bug in the binding. It's fixed in version 2.2.1.

**Comment by andre-doherty** [comment]
That's correct.
Thank you
