### ISSUE TITLE
Restore originally requested URL using all HTTP methods: POST, HEAD... and not only GET

### ISSUE THREAD

**Issue by S66D** [pac4j/pac4j#1074]
Hi, I am currently using pac4j with Jooby, and times there are some login issues when redirecting to the requested URL after a successful login, where I have found out that you will be redirected to the last requested URL from the browser even if its an css.map file requested by a HEAD method so is there a way to distinguish between GET and HEAD methods.

We could set LAST_REQUESTED_URL and LAST_GET_REQUESTED_URL if this is a standard use case.

**Comment by leleuj** [comment]
The question has never been raised, but I think there is some improvement in the way the request is saved and restored (your use case, but what about POST requests also?)

Currently, you can override the `saveRequestedUrl` method of the `DefaultSecurityLogic` component.

**Comment by S66D** [comment]
Thanks for your interest, and sorry for the late reply,
I'm not so sure about POST request, but what I know is if a POST request is being sent and the client is not authenticated the client should be redirected to the login page and after the client logged-in he should resend the request again by visiting the page or the location where he sent the POST request unless if `pac4j ` have some kind of cache for POST requests body, even so I think it should be server side business, also `pac4j ` could gave some interfaces on implementing cached POST requests.

best of luck.

**Comment by S66D** [comment]
I have found out that it is even more reasonable and convenient if there was a condition for last requested url to be type of html mime by the requested `Accept` header

**Comment by aruis** [comment]
I got the same issues when i use a cas server. And I think use 307 http status instead of 302 will be ok.
so I suggest `org.pac4j.core.context.TEMP_REDIRECT = 307`

**Comment by onnoweb** [comment]
I would like to check in on this issue and specifically POST requests. When my POST request will be authenticated by an indirect method (specifically SAML) then the body is stripped and not restored after successful authentication. 

Are there plans to address this?

I can, and probably will need to, address this in my own code but it seems something that pc4j should do out of the box.

Thoughts?

**Comment by leleuj** [comment]
It has been fixed in pac4j v4.

**Comment by onnoweb** [comment]
Thanks for the quick response. pac4j v4 was not been released yet? I see an RC1?

**Comment by leleuj** [comment]
Indeed, a RC2 is in progress.

**Comment by mukulchakane** [comment]
Hi , pac4j 4.0 is released or it is still in RC??

**Comment by mmoayyed** [comment]
Still in RC.
*- Misagh*
