### ISSUE TITLE
[pac4j-core] Headers might need to be trimmed upon extraction

### ISSUE THREAD

**Issue by andre-doherty** [pac4j/pac4j#1078]
The HeaderExtractor class doesn't remove trailing blank on parsed headers.
The following issue is met : 
In case of a header formated like this (as in RFC6750) : 
`Authorization:Bearer eyJhbGciOiJIUzI1NiJ9.e.....`
And : 
headerName = Authorization
prefixHeader = Bearer

The token extracted cannot be validated properly as it has a trailing space

On the other side, shiro doesn't provide any mecanism to set a property value with a trailing space .

A complementary call to trim() in HeaderExtractor would solve the issue.

**Comment by leleuj** [comment]
OK. We already have a fix to do for the headers: https://github.com/pac4j/pac4j/issues/1067

**Comment by leleuj** [comment]
Have you tried defining the `prefixHeader` as "Bearer " (with a trailing space)? In any case, I think it's certainly a good idea to trim the name.

**Comment by leleuj** [comment]
I realized you were talking about the value and I don't think we should touch the value, except in custom header extractors. Closing this one...

**Comment by andre-doherty** [comment]
well i didn't find any way to specify a value with a blank character in shiro.ini.
The quotes seems to be treated as a normal character and values (and keys) strings are trimmed during the parsing.
But maybe there is a trick ?

**Comment by andre-doherty** [comment]
I have looked again into shiro's ini. I can confirm that when used quotes are treated as normal characters and are not interpreted by shiro parsing engine.
The HeaderExtractor is unfortunately hardcoded in HeaderClient. So maybe the solution would be to allow a custom HeaderExtractor.

Otherwise, you might reconsider the solution to trim header values. 
After watching carefully again I really believe it's quite harmless, as its content is only ascii and spaces (LWS) as the RFC 2616 and 822 specify it.  
As a matter of facts multiple spaces separating headers are probably removed by the container ;)
The trim() jdk function is targeting spaces (head and trail) which fits the goal perfectly.

**Comment by leleuj** [comment]
I think this behavior (trimming the header value) should NOT be the default. Nonetheless, it could be an option.
So from my POV, we should have some boolean property in the `HeaderExtractor` to enable this trimming and then, you could set this specific configured `HeaderExtractor` to the `HeaderClient` (this already exists via the `setCredentialsExtractor` method).
