### ISSUE TITLE
[core] use of shiro's noSessionCreation raises DisabledSessionException

### ISSUE THREAD

**Issue by andre-doherty** [pac4j/pac4j#1085]
I have a rest backend  which is secured using pac4j saml2 indirectclient and headerclient directclient.
It has to be stateless so to comply with that i have used the shiro's dedicated filter (noSessionCreation).

It appears that some unnecessary session creation are done in several places (mainly by setting blank values for some session attributes).
I have focused on *logic classes and also in SAML2Client

There is also a hardcoded value in defaultcallbacklogic (saveUserProfile) that would require the creation of a supplementory parameter in callbackfilter (eg saveInSession)

I have already worked on a fix applying to the 2.2.x branch

**Comment by leleuj** [comment]
Regarding the session, things are not easy: I'll see your PR...

Please start by targeting the master branch and then backport to the 2.2.x branch.
