### ISSUE TITLE
Google cert without private key

### ISSUE THREAD

**Issue by zeljkogbg** [pac4j/pac4j#1102]
I try to setup Google SSO with pac4j-saml and get an error:

org.pac4j.core.exception.TechnicalException: privateKeyPassword cannot be blank

When i import Google's PEM file in my keystore i only get the prompt to fill in keystore password, not private key password. So i assume that there is only the public key in the file.
In the SAML2ClientConfiguration i can see that you check for blank values in the internalInit:

CommonHelper.assertNotBlank("privateKeyPassword", this.privateKeyPassword);

Do i do something wrong?

**Comment by leleuj** [comment]
Please use the mailing list: https://groups.google.com/forum/#!forum/pac4j-users
