### ISSUE TITLE
Check how authentication attributes are restored in addition to user attributes

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#1103]
In the `ProfileHelper` component...

**Comment by jkacer** [comment]
Hi Jerome, I have create pull request #1110 for this issue. It's for branch 2.2.x. If you find it OK, I can add another one for master later.

I just noticed one thing: The 2.2.x branch now contains version 2.3.0-SNAPSHOT, so we should probably create a new branch after the merge. Or create it before and then target the PR against the new branch. I'll leave it up to you...

**Comment by leleuj** [comment]
The PR is good, see my minor comments to address. Please open a new PR for the master before I merge anything (you don't need to make things backward-compatible for the master branch).

Yes, the 2.2.x is now at 2.3.0-SNAPSHOT as there is already a new backward-compatible change in it. I think I'll cut a 2.3.0 release after I merge and test your changes.

**Comment by jkacer** [comment]
Hi! Thank you for the review, I'll have a look and fix the remaining issues, then make a new PR for master.

**Comment by jkacer** [comment]
Hi Jerome, here is the pull request for master: https://github.com/pac4j/pac4j/pull/1112.
It contains the same changes, ported from 2.2.x, plus removal of the 3 deprecated methods and adequate adjustments in clients (one more parameter).
