### ISSUE TITLE
Expired SAML IdP metadata not refreshed

### ISSUE THREAD

**Issue by threepines** [pac4j/pac4j#1109]
When the SAML IdP metadata contains a validUntil date, pac4j does not attempt to refresh the metadata from the metadata URL when the validUntil date is reached.  Because the metadata has expired, Pac4j ultimately throws the following error: org.pac4j.saml.exceptions.SAMLException: No idp entityId found.

**Comment by leleuj** [comment]
Yes, we should return a better error. Would you mind submitting a PR for that?

That said, we can't refresh IdP metadata as they can be downloaded and installed by a user for example.

**Comment by threepines** [comment]
Re refresh:  think the metadata should be refreshed (or at least have the option to be refreshed per some property setting) if the metadata path is a URL.

**Comment by leleuj** [comment]
Why not? Feel free to submit a pull request for that. Thanks.

**Comment by gwm** [comment]
wow... real helpful!

**Comment by runger1101001** [comment]
Will someone take a look at this?
It is a standard feature in other SAML SP Implementations, e.g. spring-security-saml or shibboleth.

If the IdP Metadata is an URL, you refresh it from that URL. If it is a file, you simply refresh it from that file (the user could change the file). The interval for refreshing should be configurable.

The interval-based refresh is necessary to capture changes to the Metadata that occur before the validUntil expires.
In addition, there should be a refresh when validUntil is over.

This behaviour is in fact implemented in opensaml, see: https://github.com/apigee/java-opensaml2/blob/master/src/main/java/org/opensaml/saml2/metadata/provider/HTTPMetadataProvider.java
So all you would have to do is expose the configuration in pac4j-saml...

**Comment by mmoayyed** [comment]
As was pointed out earlier, you're most welcome to submit a pull request. The person you're waiting for, is you.

**Comment by mukulchakane** [comment]
Have we added the support for IdP Metadata refresh @runger1101001 can you please provide PR link??

**Comment by jeevanprakashgali** [comment]
is this added?

**Comment by leleuj** [comment]
See: https://github.com/pac4j/pac4j/pull/1459 and a
