### ISSUE TITLE
[SAML] AuthnRequestSigned can't be set in 2.2.x

### ISSUE THREAD

**Issue by eesprit** [pac4j/pac4j#1111]
During some refactoring (starting at https://github.com/pac4j/pac4j/commit/15a88bb3886485a40cd10c2bdc5cd6b7562c55f3#diff-5403deed0d82a1b510f272e7815628b8) the `setAuthnRequestSigned(boolean authnRequestSigned)` method got lost (after several renamings).
It is available in master, but not in 2.2.x. Would it be possible to add it again ?

As I understand, it should still be enabled using IDP metadata (if it ask for it), but it doesn't seem to work (couldn't test further why for the moment), so having the option to force it from code would be nice.

**Comment by eesprit** [comment]
Doesn't it should take in account if the IDP Metadata says it wants them signed ?(WantAuthnRequestsSigned="true") ?

**Comment by leleuj** [comment]
Yes, the IdP should be able to force the signing of the auth request. But I think that it's not taken into account in pac4j and should be explicitly set via the `setAuthnRequestSigned` method: https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/sso/impl/SAML2WebSSOMessageSender.java#L118

We should certainly change that: what do you think @mmoayyed ?

**Comment by mmoayyed** [comment]
We can add the method make to forcefully sign authn requests regardless of metadata semantics, sure.

**Comment by leleuj** [comment]
@mmoayyed 

Sorry if I was unclear. That was not what I meant.

Regarding the source code, I think that the `idp.getWantAuthnRequestsSigned()` information is not taken into account. So, even if the IdP requires in its metadata that the SP signs its authn requests, it is ignored.

I think it should be taken into account, shouldn't it?

**Comment by mmoayyed** [comment]
Ah, I understand. Yes, it should. An identity provider that has this flag set to true in its metadata in theory must produce an error message if the SP sends an authn request that is unsigned. So, yes I'd say this should be taken into account.

I'd also imagine it would be useful to force the signing; in case the SP metadata is unclear and the IdP metadata does not strictly ask for this, it would be good to *force* the signing of the authn request if needed to account for situations where either the SP nor IdP metadata is in one's control. (And many operators whether SP or IdP may not be quite careful about what goes into the metadata).

**Comment by mmoayyed** [comment]
> So, yes I'd say this should be taken into account.

I'd be glad to add this to the current master. If someone needs this, it can be backported to 2.x separately.
