### ISSUE TITLE
SAML Direct client implementation

### ISSUE THREAD

**Issue by jakkamprashanth** [pac4j/pac4j#1123]
@LELEU Jérôme 
Hi, 
My use case is:
User enters credentials at login page of my application and backend of my application has to communicate to IDP and authenticate entered credentials. I do not want to redirect user to other login screen of IDP.
Which i understand above as direct client implementation (saml is my protocol).
how can i achieve this ? i.e without browser intervention.

**Comment by leleuj** [comment]
Please use the mailing list for questions: http://www.pac4j.org/mailing-lists.html
