### ISSUE TITLE
Upgrade scribe to 5.3.0

### ISSUE THREAD

**Issue by aindlq** [pac4j/pac4j#1124]
Would be great to have scribe updated to the latest version, currently used one doesn't support multiple scopes in OAuth2 reponse, see https://github.com/scribejava/scribejava/commit/255a8e622a343b3b7401916af6cf92baa538bf16

**Comment by leleuj** [comment]
Sure. Would you mind submitting a pull request for that?

**Comment by aindlq** [comment]
sure, should it go into `2.3.x` branch?
