### ISSUE TITLE
Entity Identifier must omit NameQualifier

### ISSUE THREAD

**Issue by EngOpenPlatform** [pac4j/pac4j#1132]
I am using version 3.0.0-RC1 of pac4j-saml.
I am implementing integration with ADFS 3.0.

I have the following error in ADFS:
System.Xml.XmlException: ID4263: The SAML NameIdentifier 'https://xxxxxx.com' is of format 'urn:oasis:names:tc:SAML:2.0:nameid-format:entity' and NameQualifier/SPNameQualifier/SPProvidedID is not omitted.

SAML specifications (https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf)  describes in 8.3.6 Entity Identifier that "The NameQualifier, SPNameQualifier, and SPProvidedID attributes MUST be omitted."

I have downloaded and modified the class **SAML2AuthnRequestBuilder** removing in method **getIssuer** what follows:

issuer.setNameQualifier(spEntityId);

with this correction the integration with ADFS 3.0 works correctly.

It seems to me a bug, but I am not a SAML expert, so I submit to you what I have discovered.

**Comment by leleuj** [comment]
It seems so to me. @EngOpenPlatform can you submit a PR for that? Thanks

@mmoayyed does it seem right to you? Thanks

**Comment by mmoayyed** [comment]
Yes, that certainly is accurate to me. @EngOpenPlatform, you probably should start by exposing a configuration option for each of the SPNameQualifier, SPProvidedID, etc, but dont force any restrictions. Just warnings. Chances are, there is an IDP out there that is not very spec-compliant and we ought  make sure those edge scenarios work too.

**Comment by leleuj** [comment]
@EngOpenPlatform I'm about to release the 3.0.0-RC2 version. Do you plan to submit a PR very soon? Thx

**Comment by EngOpenPlatform** [comment]
@leleuj when are you going to release it? I hope to work on it this weekend

**Comment by leleuj** [comment]
I wanted to release this week, but I can wait until next week...

**Comment by EngOpenPlatform** [comment]
@leleuj I have created a PR. Regards.

**Comment by spidgorny** [comment]
Which PR is this?
Has it been merged?
Which minimal version is it in?

**Comment by gicat** [comment]
It has been released from in the pac4j-3.0.0-RC2
