### ISSUE TITLE
Suboptimal default behavior choosing ClientAuthenticationMethod

### ISSUE THREAD

**Issue by haumacher** [pac4j/pac4j#1138]
If no `ClientAuthenticationMethod` is configured (`null`), the very first method that is suggested by the `OIDCProviderMetadata` is choosen. This is pretty clumsy, since only `client_secret_post` and `client_secret_basic` are supported. This causes the code to fail few lines later with a `TechnicalException("Unsupported client authentication method: " + chosenMethod)`:

https://github.com/pac4j/pac4j/blob/ad0072a4a40ae983980dfcb261b667534beb8790/pac4j-oidc/src/main/java/org/pac4j/oidc/credentials/authenticator/OidcAuthenticator.java#L57-L74

Better would be to iterate the provider-supported methods an choose the first one that is supported by pac4j.

**Comment by leleuj** [comment]
Yes, you're right. Would you mind submitting a PR for that? Thanks

**Comment by haumacher** [comment]
Yes, I'll prepare one.
