### ISSUE TITLE
SAML2 and multiple roles

### ISSUE THREAD

**Issue by lrozenblyum** [pac4j/pac4j#1145]
SCENARIO:
I'm using SAML2 (with combination with spring security), with keycloak as identity provider.
The user has multiple roles.

EXPECTED:
SAML2Profile contains multiple roles in the attribute 'Role'

ACTUALLY:
SAML2Profile contains just a single role in the attribute 'Role'.

Code reasons:
SAML2Credentials receive multiple attributes for the Role

so e.g.
Attribute1: Role -> Value1
Attribute2: Role -> Value2

Code in SAML2Authenticator calls  getProfileDefinition().convertAndAdd which in turn - overwrites the value in the org.pac4j.core.profile.UserProfile.attributes field.

So just the last role is accessible.

**Comment by lrozenblyum** [comment]
Should it be made configurable or by default? E.g. if the attribute value type is collection - then always merge?

**Comment by leleuj** [comment]
It should be configurable but disabled by default as it will go in the version 3.1.0 which must be backward compatible (compilation/runtime) with the version 3.0.0.

**Comment by lrozenblyum** [comment]
@leleuj Please take a look at https://github.com/pac4j/pac4j/pull/1146
I've added configuration possibilities, and the default behaviour is compatible with 3.0.0
