### ISSUE TITLE
SAMLException: No valid subject assertion found in response

### ISSUE THREAD

**Issue by asmita2201** [pac4j/pac4j#1149]
After a successful login at the IDP, Pac4J throws this exception while trying to validate the response.

I have the idp metadata with a sigining cert and SP metadata with signing and encryption cert. What could be causing this error?

I receive an encrypted assertion from Idp but seems like Pac4j is not able to decrypt it. 

Please help.

Here is the stack trace.

org.pac4j.saml.exceptions.SAMLException: No valid subject assertion found in response at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateSamlSSOResponse(SAML2DefaultResponseValidator.java:313) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validate(SAML2DefaultResponseValidator.java:138) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.saml.sso.impl.SAML2WebSSOMessageReceiver.receiveMessage(SAML2WebSSOMessageReceiver.java:77) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.receive(SAML2WebSSOProfileHandler.java:35) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.saml.client.SAML2Client.lambda$clientInit$0(SAML2Client.java:110) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:61) ~[pac4j-core-2.1.0.jar:?] at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:125) ~[pac4j-core-2.1.0.jar:?] at .CallbackController.callback(CallbackController.java:153) [classes/:?]

**Comment by leleuj** [comment]
Please use the pac4j-users mailing list for questions.
