### ISSUE TITLE
Version compatibility broken

### ISSUE THREAD

**Issue by andreaTP** [pac4j/pac4j#1151]
From `git blame` I can see that 4 months ago the `perform` method has changed signature.
It's an API change of a public method, so the `major` version of pac4j should be increased because of that.
Especially important due to the fact that it is used in `bujio` project.

reference:
https://github.com/pac4j/pac4j/blob/da8a9c258a75f3faff813005f312bbbfbe370a20/pac4j-core/src/main/java/org/pac4j/core/engine/CallbackLogic.java#L29

**Comment by leleuj** [comment]
The 2.x version API has remained stable, only the master (v3.x) has been changed. I'm not sure to see the issue here.
