### ISSUE TITLE
Include default PasswordEncoder

### ISSUE THREAD

**Issue by lukehutch** [pac4j/pac4j#1155]
I suggest including a default PasswordEncoder in pac4j, based on jBCrypt:

http://www.mindrot.org/projects/jBCrypt/
https://github.com/jeremyh/jBCrypt

The implementation is tiny, and it would be nice not to have to pull in all of shiro-core or spring-security-crypto in order to properly encrypt and salt passwords. Plus pac4j should really be secure by default, and unencrypted (or unsalted) password databases have caused major headaches for numerous companies.

**Comment by leleuj** [comment]
A few versions ago, we had more `PasswordEncoder` implementations and we had that exact implementation: https://github.com/pac4j/pac4j/blob/1.9.x/pac4j-core/src/main/java/org/pac4j/core/credentials/password/JBCryptPasswordEncoder.java

We cleaned things a bit as there seems to be no use for libraries other than Spring and Shiro.

But we can bring it back.

**Comment by lukehutch** [comment]
@leleuj Shiro and Spring are enormous overkill to add as dependencies just to get password hashing (which is the only thing I would need them for, for my usecase).

Thanks for the link to the removed code. Obviously it's a tiny amount of code to add your own PasswordEncoder, and I could have done so. But I am suggesting not just that pac4j include this `JBCryptPasswordEncoder.java`, but that you actually pull in jBCrypt itself, into the pac4j repository (it's MIT licensed), so that you don't have to add another dependency.

In general, I have been surprised that pac4j is configured to be insecure by default: you have to manually add a PasswordEncoder, you have to manually enable all the standard security headers and CSRF protection in authorizers (those options are all off by default), etc.  These should all be opt-out configuration options, not opt-in configuration options!

So what I am proposing is that all passwords be encrypted by default with jBCrypt, unless you override the password encoder with another encoder.

**Comment by victornoel** [comment]
Just notice that it is not the full spring dependency, but only spring security, so this can make sense.

Though I was personally in favour of keeping `JBCryptPasswordEncoder` when the change happened ;)

**Comment by leleuj** [comment]
I wanted to limit the number of options, but indeed pulling Spring Security or Shiro may be overkill for only one class. So let's bring back the `JBCryptPasswordEncoder` with the optional `jBCrypt` dependency. Commit: https://github.com/pac4j/pac4j/commit/bdb6051cabcc9aabea74583229eaf9abf3f48435

That said, "manually add a PasswordEncoder" does not make pac4j "insecure by default": you choose the password encoder you want given the best suited cryptographic library you can/want to use.

About the security headers and the CSRF protection, you're right: we should turn them on by default ("csrf,securityheaders"), but it's a breaking change in the runtime behavior (especially the CSRF protection), so let's target that for pac4j v4: https://github.com/pac4j/pac4j/issues/1156

**Comment by lukehutch** [comment]
Great, thanks for considering these changes. So if jBCrypt is not on the class path, you will just get a `ClassNotFoundException` at runtime?

**Comment by leleuj** [comment]
Yes, as there are multiple choices and as we want to limit the dependencies pulled by default, you need to explicitly add it.
