### ISSUE TITLE
OpenId Connect login fails against the latest Keycloak server

### ISSUE THREAD

**Issue by aurelien-minvielle** [pac4j/pac4j#1189]
Following this thread: https://groups.google.com/forum/#!topic/pac4j-users/aI0zvnvimDk

There seems to be a bug/limitation in pac4j when login against some OpenId Connect providers.

An OP can support a broad range of id-token signature algorithms, as specified in its discovery document:

```
 ...
  "id_token_signing_alg_values_supported": [
    "ES384",
    "RS384",
    "HS256",
    "HS512",
    "ES256",
    "RS256",
    "HS384",
    "ES512",
    "RS512"
  ],
  ...
```

The OP will then use one of those algorithm when signing its id-tokens.

In the absence of a pre-configured "preferred" algorithm on the pac4j side, pac4j's OidcProfileCreator#internalInit() picks the first one in the _id_token_signing_alg_values_supported_ list and will use it later to check all incoming signed id-token, no matter what algorithm is specified in the JWT's header.

**Observed behaviour:**
Given that _id_token_signing_alg_values_supported_ list and a token signed using RS256, login fails with the following error 

> com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found

**Expected behaviour:**
Login succeeds without any errors nor extra "preferredJwsAlgorithm" configuration needed on pac4j side.

**How to reproduce:**
Try to login against the Keycloak 4.5.0.Final as an OpenId Connect provider, with the default configuration.

**Possible workaround**
Force the right algorithm if you know it as the "preferredJwsAlgorithm":
`oidcConfiguration.setPreferredJwsAlgorithm(JWSAlgorithm.RS256);`

**Comment by leleuj** [comment]
It's now fixed in the 3.4.0-SNAPSHOT version.
