### ISSUE TITLE
KeycloakOidcProfile roles support

### ISSUE THREAD

**Issue by brunojcm** [pac4j/pac4j#1196]
As requested here:
https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/MDVA_4H24Bo

I'm using pac4j to authenticate against my Keycloak instance in a web app project.

One of the things that I missed is that `KeycloakOidcProfile` does not load roles by default, I had to write an `AuthorizationGenerator` for that. I understand that in Keycloak roles come in a non-standard way in the access token (unless you use a mapper), but having configured an `org.pac4j.oidc.client.KeycloakOidcClient` one would expect that the roles would be recognized an set in the KeycloakOidcProfile.

Follows the AuthorizationGenerator I had to write (in Koltin):

```
import com.nimbusds.jwt.JWT
import com.nimbusds.jwt.SignedJWT
import net.minidev.json.JSONArray
import net.minidev.json.JSONObject
import org.pac4j.core.authorization.generator.AuthorizationGenerator
import org.pac4j.core.context.WebContext
import org.pac4j.oidc.profile.keycloak.KeycloakOidcProfile

class KeycloakRolesAuthorizationGenerator(private val clientId: String) : AuthorizationGenerator<KeycloakOidcProfile> {

    override fun generate(context: WebContext, profile: KeycloakOidcProfile): KeycloakOidcProfile {
        val jwt: JWT = SignedJWT.parse(profile.accessToken.value)

        val realmRolesJsonArray = jwt.jwtClaimsSet.getJSONObjectClaim("realm_access")["roles"] as JSONArray

        val clientRolesJsonObject = jwt.jwtClaimsSet.getJSONObjectClaim("resource_access")[clientId] as JSONObject
        val vmsRolesJsonArray = clientRolesJsonObject["roles"] as JSONArray

        for (value in realmRolesJsonArray) {
            profile.addRole(value as String)
        }
        for (value in vmsRolesJsonArray) {
            profile.addRole(value as String)
        }

        return profile
    }

}
```
As far as I could understand, something similar could have been done by `org.pac4j.oidc.profile.creator.OidcProfileCreator#create` or a new `org.pac4j.oidc.profile.creator.KeycloakOidcProfileCreator#create`, without requiring the users to write this generator themselves.

**Comment by leleuj** [comment]
It's now available in the 3.4.0-SNAPSHOT version.

**Comment by maxfahl** [comment]
I see that you can read out the "realm_access" claim from your jwt token. I'm trying to do the same but can't find the claim when parsing the token though SignedJWT.parse(). All I get is the following:

`
0 = {HashMap$Node@12547} "sub" -> "aace4603-14f2-4467-890c-c33059d5e65c"
1 = {HashMap$Node@12548} "email_verified" -> "true"
2 = {HashMap$Node@12549} "id_token" -> "..."
3 = {HashMap$Node@12550} "iss" -> "http://10.0.1.24:9090/auth/realms/test"
4 = {HashMap$Node@12551} "typ" -> "ID"
5 = {HashMap$Node@12552} "preferred_username" -> "max"
6 = {HashMap$Node@12553} "given_name" -> "Max"
7 = {HashMap$Node@12554} "access_token" -> "..."
8 = {HashMap$Node@12555} "token_expiration_advance" -> "-1"
9 = {HashMap$Node@12556} "refresh_token" -> "..."
10 = {HashMap$Node@12557} "aud" -> " size = 1"
11 = {HashMap$Node@12558} "acr" -> "1"
12 = {HashMap$Node@12559} "nbf" -> "Thu Jan 01 01:00:00 CET 1970"
13 = {HashMap$Node@12560} "azp" -> "account"
14 = {HashMap$Node@12561} "auth_time" -> "Tue Mar 05 14:40:22 CET 2019"
15 = {HashMap$Node@12562} "name" -> "Max Fahl"
16 = {HashMap$Node@12563} "exp" -> "Tue Mar 05 14:45:22 CET 2019"
17 = {HashMap$Node@12564} "session_state" -> "020e2ad7-2d4e-428c-8331-bfc969cec61b"
18 = {HashMap$Node@12565} "family_name" -> "Fahl"
19 = {HashMap$Node@12566} "iat" -> "Tue Mar 05 14:40:22 CET 2019"
20 = {HashMap$Node@12567} "email" -> "max@pixilab.se"
21 = {HashMap$Node@12568} "jti" -> "fad200c9-23da-4008-a145-8ff95ea768c9"
`

When I parse the same token at https://jwt.io/ i can see the "realm_access" token visible in the list.

What i happening here? Do you guys know if this claim gets stripped somehow, somewhere? Any pointers?

**Comment by brunojcm** [comment]
@maxfahl, if the token is the same, the `realm_access` must (or must not) be there, no matter the tool you use.

This output you posted looks like some debug console or something, which is probably using some kind of `toString()`, so I would not trust much on it. Try to get the claim or really take a deep look at the object in the memory, the `realm_access` is probably there.

**Comment by maxfahl** [comment]
It's not in the raw data either. I've looked at the raw JSON string, and it's not there either. What I don't get is where jwt.io is getting the claim from when they both come from the same token. Weird si what it is :)
