### ISSUE TITLE
File system resource incorrectly required for SAML metadata generation

### ISSUE THREAD

**Issue by scoldwell** [pac4j/pac4j#1210]
Commit https://github.com/pac4j/pac4j/commit/3806174df54b939ed2785ee493f63b9851fcd03e has changed the way SAML2ServiceProviderMetadataResolver and SAML2MetadataGenerator work.  A file system resource is now always required for metadata generation to work.  Confirmed with Jerome that this is a bug.  See https://groups.google.com/forum/#!topic/pac4j-dev/CeGKSBVg-0M

**Comment by davido** [comment]
Not sure it' related here, or should be filed as its own issue. Starting from 3.4.0 we have to explicitly set `serviceProviderMetadataResourceFilepath`, even though it was already passed in to the ctor of `SAML2Configuration`:

```
SAML2Configuration samlClientConfig =
        new SAML2Configuration(
            samlConfig.getKeystorePath(), samlConfig.getKeystorePassword(),
            samlConfig.getPrivateKeyPassword(), samlConfig.getMetadataPath());

    samlClientConfig.setServiceProviderMetadataResourceFilepath(samlConfig.getMetadataPath());
```
I'm already passing samlConfig.getMetadataPath() to ctor, so it seems it shouldn't be necessary to set it again.

**Comment by leleuj** [comment]
I think we stay in the same scope here: the idea is to be able to get rid of the SP metadata file and make the SAML support still work.

Regarding this "new" issue, this might be, I have always used the `setServiceProviderMetadataResourceFilepath` method but I'll ensure we don't need it when I'll work on this issue.

Nonetheless, you are mistaken with the last parameter of the constructor: it's the IdP metadata, not the SP metadata.

**Comment by davido** [comment]
> Nonetheless, you are mistaken with the last parameter of the constructor: it's the IdP metadata, not the SP metadata.

Yes, you are right `samlConfig.getMetadataPath())` is supposed to be IdP metadata URL in gerrit-saml-plugin.

**Comment by davido** [comment]
I think, that in 3806174 this was a behavioural change: [1].

old code:

```java
return metadataGenerator.buildMetadataResolver();
```

new code:


```
return metadataGenerator.buildMetadataResolver(configuration.getServiceProviderMetadataResource());
```

If `configuration.getServiceProviderMetadataResource()` was not set we have a NPE.

[1] https://github.com/pac4j/pac4j/commit/3806174df54b939ed2785ee493f63b9851fcd03e#diff-4bae18472e8e67e252c5c30c3f18cfefR100

**Comment by leleuj** [comment]
I think the best option is to use the "old logic" in case no SP metadata file is defined. See: https://github.com/pac4j/pac4j/pull/1229 and https://github.com/pac4j/pac4j/pull/1230

**Comment by davido** [comment]
FWIW, in pac4j v3.4.0 I was able to fix the problem by setting the SP metadata file in this change: [1].

```java
  samlClientConfig.setServiceProviderMetadataPath(
        pluginDataDirectory.resolve("sp-metadata.xml").toString());
```

* [1] https://gerrit-review.googlesource.com/c/plugins/saml/+/209232/4/src/main/java/com/thesamet/gerrit/plugins/saml/SamlWebFilter.java

**Comment by leleuj** [comment]
Sure. This is an option. But I just merged both PRs so you should be able to not set the SP metadata path using the 3.5.0-SNAPSHOT version. Can you confirm? Thanks

**Comment by davido** [comment]
I tried with:

```python
  maven_jar(
       name = "pac4j-core",
       artifact = "org.pac4j:pac4j-core:3.5.0-SNAPSHOT-20190112.120241-16",
       sha1 = "da2b1cb68a8f87bfd40813179abd368de9f3a746",
  )
```

and commented out this line:

```java
//samlClientConfig.setServiceProviderMetadataPath(
    //    ensureExists(sitePaths.data_dir).resolve("sp-metadata.xml").toString());
```

And now I'm getting this NPE: http://paste.openstack.org/show/742291/

**Comment by leleuj** [comment]
You also need the `pac4j-saml` library to be in version 3.5.0-SNAPSHOT...

**Comment by leleuj** [comment]
1. I think this might come from your environment and the use (or not) of the Java Policy Unlimited Strength.

2. I just replaced the class in the 3.5.x and master branches.
