### ISSUE TITLE
Nullptr when using Azure AD OIDC and Apache Knox

### ISSUE THREAD

**Issue by RenePingen** [pac4j/pac4j#1224]
Hi,

Currently im trying to configure Azure AD authentication using Apache Knox and Pac4J. 

Unfortunately configuration results in a NullPointerException:
at org.pac4j.oidc.config.OidcConfiguration.getLogoutUrl(OidcConfiguration.java:299)
at org.pac4j.oidc.config.AzureAdOidcConfiguration.<init>(AzureAdOidcConfiguration.java:36)
at org.pac4j.config.builder.OidcClientBuilder.tryCreateOidcClient(OidcClientBuilder.java:72)
at org.pac4j.config.client.PropertiesConfigFactory.build(PropertiesConfigFactory.java:89)
at org.apache.knox.gateway.pac4j.filter.Pac4jDispatcherFilter.init(Pac4jDispatcherFilter.java:153)

Although Knox still uses version 3.2, i have been able to reproduce the issue manually with 3.4. It seems to be caused by the fact that providermetadata is never initiated, which occurs when 
the init function on the configuration is called.

Manually it seems to be resolved when calling init() manually, although we cannot test this when using Apache Knox as it is working with property files. Fix seems to be to ensure init is called on the configuration before the getLogout function is called? (and maybe prevent the possibility  a nullpointer from that function as well).

Ideas for a fix or workaround are greatly appreciated. 

Thanks!

**Comment by leleuj** [comment]
Yes, it seems to be the problem: the missing `init()` call. See this commit: https://github.com/pac4j/pac4j/commit/7553610abebf8acca21693007c1f609e68ee80c6 Can you try the 3.5.0-SNAPSHOT version?

Notice the method will be named `findLogoutUrl` in pac4j v4: https://github.com/pac4j/pac4j/commit/4e2491f79230842e53297dbd827d6a5bf09eacfd

**Comment by RenePingen** [comment]
Thanks, the nullptr issue is now resolved. I did however find a new issue:
- AzureADClient expects the tenant to be set, but the OidcClientBuilder class does not set the variable.

I did manage to hack it in by adding the following (and the OIDC_tenant constant), but i think it deserves a more elegant solution :)

if (OIDC_AZURE_TYPE.equalsIgnoreCase(type)) {
                    final AzureAdOidcConfiguration adConfig=new AzureAdOidcConfiguration(configuration);
                    final String tenant = getProperty(OIDC_TENANT, i);
                    if (isNotBlank(tenant)) {
                        adConfig.setTenant(tenant);
                    }
                    oidcClient = new AzureAdClient(adConfig);

**Comment by leleuj** [comment]
Indeed, via configuration, the tenant is not set. What you propose is the best solution. See: https://github.com/pac4j/pac4j/commit/8c9fe856d3f4c3c10761449493c53bb0e35f09e4 and https://github.com/pac4j/pac4j/commit/bda237ac79e43e6a918f0b42fd5e9c4a5bdcf9fc

Can you test again the 3.5.0-SNAPSHOT version? The key is `oidc.azure.tenant`.
