### ISSUE TITLE
Google+ API Being Deprecated

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#1228]
Discussion on the mailing list: https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/xlFNWXEMEog

**Comment by JohnBergant** [comment]
@leleuj  I have a branch I've been working on locally, would you mind if I run with this?

**Comment by leleuj** [comment]
Sure. Go ahead. Notice we have a master branch (v4.0.0-SNAPSHOT) and a 3.5.x branch (v3.5.0-SNAPSHOT). You need to target at least the master branch, but you may want to target both...

**Comment by ottboy4** [comment]
@JohnBergant - Do you have any updates on the progress of this? Thanks!

**Comment by NgSekLong** [comment]
I have make an PR which attempt to solve this issue (see #1249), see if that PR is suitable, thanks.
