### ISSUE TITLE
SAML2 logout response builder should be able to override in the SAML2 credentials extractor

### ISSUE THREAD

**Issue by krzysztof-zych** [pac4j/pac4j#1234]
In the https://github.com/pac4j/pac4j/blob/85089d08ffdaeadf18edd846fb737e80c7ebe331/pac4j-saml/src/main/java/org/pac4j/saml/credentials/extractor/SAML2CredentialsExtractor.java#L46 line, constructor create an instance of SAML2LogoutResponseBuilder and assign it to the final field.

Field should not be the final and new instance of logout response builder should be received from the method that can be easily overridden.

This issue is agreed with Jérôme LELEU at https://groups.google.com/d/msg/pac4j-dev/1yKt-HVtMVk/XeBuWbF1EwAJ

**Comment by leleuj** [comment]
We should fix the `inResponseTo` issue also.

**Comment by leleuj** [comment]
Fixed via https://github.com/pac4j/pac4j/commit/87955919cb59c95e2aa8e815030b2c854858dbbe. Can you test with the latest v3.5.0-SNAPSHOT?
