### ISSUE TITLE
SAML2 LogoutResponse should be send with configurable RelayState

### ISSUE THREAD

**Issue by krzysztof-zych** [pac4j/pac4j#1235]
In this line https://github.com/pac4j/pac4j/blob/cccd61c00845a6d2fa8f0a72da717c72775ab8a7/pac4j-saml/src/main/java/org/pac4j/saml/credentials/extractor/SAML2CredentialsExtractor.java#L61 SAML2LogoutResponseMessageSender send a LogoutResponse message with RelayState explicitly sets to null.
RelayState in a LogoutResponse message should be configurable or at least set to the corresponding RelayState in the LogoutRequest.

**Comment by leleuj** [comment]
Fixed via https://github.com/pac4j/pac4j/commit/87955919cb59c95e2aa8e815030b2c854858dbbe. Can you test with the latest v3.5.0-SNAPSHOT?
