### ISSUE TITLE
Spring Boot and Spring MVC implementations both support ABAC?

### ISSUE THREAD

**Issue by Kiddinglife** [pac4j/pac4j#1237]
Hi guys,

I have checked mailing lists: http://www.pac4j.org/mailing-lists.html and sure there is no similar issue reported before.

My question:
spring does not support abac by default and it only supports rbac.
But I found this interface from document  `RequireAnyAttributeAuthorizer()`. 
So, does that mean they are supported in pac4j?
Regards.

**Comment by leleuj** [comment]
Yes, you can check the roles or the attributes of the user.
