### ISSUE TITLE
cannot set multiple `AuthnContextClassRef` in saml request (using apereo CAS)

### ISSUE THREAD

**Issue by leopal77** [pac4j/pac4j#1245]
We need to define two `AuthnContextClassRef` in our saml request. This is allowed by the [xsd](https://docs.oasis-open.org/security/saml/v2.0/saml-schema-protocol-2.0.xsd)

```
<complexType name="RequestedAuthnContextType">
  <choice>
    <element ref="saml:AuthnContextClassRef" maxOccurs="unbounded"/>
    <element ref="saml:AuthnContextDeclRef" maxOccurs="unbounded"/>
  </choice>
  <attribute name="Comparison" type="samlp:AuthnContextComparisonType" use="optional"/>
</complexType>
```

However we cannot find the configuration for this.

Tried the following properties in application.properties but did not work:
1.
```
cas.authn.pac4j.saml[0].authnContextClassRef=urn:class1|urn:class2
```

2.
```
cas.authn.pac4j.saml[0].authnContextClassRef=urn:class1,urn:class2
```

3.
```
cas.authn.pac4j.saml[0].authnContextClassRef[0]=urn:class1
cas.authn.pac4j.saml[0].authnContextClassRef[1]=urn:class2
```
in combination with all available `ComparisonTypes`.

We have seen that [SAML2Configuration](https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/config/SAML2Configuration.java#L446) accepts a string value for `authnContextClassRef`. We would expect that at some later point in the code there is some string splitting that takes place. Is this the case? 

If yes what is the delimiter?  
If no, what is the way to define multiple `authnContextClassRef` elements?

**Comment by leleuj** [comment]
Currently, you can't. But we could turn that string into a real list in pac4j and set multiple values. And we could use a list in CAS as well.

**Comment by leleuj** [comment]
See: https://github.com/pac4j/pac4j/pull/1246 and https://github.com/pac4j/pac4j/pull/1247
