### ISSUE TITLE
Clean shutdown of SAML2 Client

### ISSUE THREAD

**Issue by roeder82** [pac4j/pac4j#1248]
As already mentioned in the mailinglist (https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/jddj9x_w_eo) the SAML2 client spawns a timer thread upon initialisation. Thus opening multiple clients in a dynamically way (e.g. for single use) results in a thread creep which could lead to a JVM crash.

There shall be a functionality for a clean shutdown of the client terminating all spawned threads.

**Comment by leleuj** [comment]
Can you test the `destroy` method in version 3.6.0-SNAPSHOT?

**Comment by roeder82** [comment]
Yes, I will do so.
