### ISSUE TITLE
IndirectClient (re)generating state token for ajax requests

### ISSUE THREAD

**Issue by brunojcm** [pac4j/pac4j#1258]
I have an application here that performs a lot of AJAX requests in parallel for a few reasons, and what is happening is that I get state check errors every now and then, which are pretty hard to debug.

I took a look at `org.pac4j.core.client.IndirectClient#getRedirectAction`, it has:

```
        if (ajaxRequestResolver.isAjax(context)) {
            logger.info("AJAX request detected -> returning the appropriate action");
            RedirectAction action = redirectActionBuilder.redirect(context);
            cleanRequestedUrl(context);
            return ajaxRequestResolver.buildAjaxResponse(action.getLocation(), context);
        }
```

What is very weird for me is that it calls `redirectActionBuilder.redirect(context)` even when it is an AJAX method, probably just to calculate the location, but it doesn't actually redirect. 

So far, so good, but it causes an issue: if `redirectActionBuilder.redirect(context)` is called, a new `State` is put in the session store. If I had already started my authentication redirection by a previous request (and this is just an AJAX call being performed by an iframe, for example, which I believe is the case here), by the time my SSO solution returns the result for the first process we have another state token in the session store (put by the AJAX request that happened in parallel), so my auth fails with a "State parameter is different from the one sent in authentication request. Session expired or possible threat of cross-site request forgery" message.

I tried to extend `OidcRedirectActionBuilder` so we don't overwrite the state for AJAX requests, but at that point, there is no way to check if the request is an AJAX or not (unless I do some ugly stuff), so that's why I'm creating this issue.

I believe that, if it is an AJAX, we should not call `redirectActionBuilder.redirect(context)` at all. Probably separating the logic to create the location from the actual redirect, but I'm not so sure about that.

Can you help, please?

**Comment by brunojcm** [comment]
Started a PR with just a failing test case for now:

https://github.com/pac4j/pac4j/pull/1259

Please, let me know what you think.

**Comment by leleuj** [comment]
The redirection URL is computed to be added as a header to the 401 HTTP response. I don't think it is used in most cases.
So I'm in line that it should be better not to compute it, although it should be possible.

So the `redirectActionBuilder.redirect(context)` should certainly happen in the `AjaxRequestResolver.buildAjaxResponse` method if it is necessary. Controlled by some `addRedirectionUrlAsHeader` property which is `false` by default.
We can do that in v4 (master branch) as it's a breaking change.

In your case (v3.x), I think the easiest is to override the `OidcRedirectActionBuilder` with a new class using the `AjaxRequestResolver` to know if it should do something.

Does it make sense?

**Comment by brunojcm** [comment]
@leleuj, please evaluate my proposed solution. The test is now passing and I can confirm the problem is gone in my app as well.

> So the `redirectActionBuilder.redirect(context)` should certainly happen in the `AjaxRequestResolver.buildAjaxResponse` method if it is necessary

By this phrase I understood that `AjaxRequestResolver.buildAjaxResponse`  should now be the one deciding if the redirect needs to be calculated or not, so that's what I did.

I also kept the original signature of the `org.pac4j.core.http.ajax.DefaultAjaxRequestResolver#buildAjaxResponse(org.pac4j.core.exception.http.RedirectionAction, org.pac4j.core.context.WebContext)` is case someone is extending `DefaultAjaxRequestResolver`, so it should be just a matter of setting the new boolean to restore the old behaviour.

**Comment by leleuj** [comment]
I'm in line with your proposal. See my proposal on the source code refactoring...
