### ISSUE TITLE
Use the NameID instead of the SessionIndex to track the SAML session

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#1260]
Because the SessionIndex is **optional**.

**Comment by mmoayyed** [comment]
I believe NameID *may* also be optional; perhaps the assertion id instead?

**Comment by leleuj** [comment]
The SAML spec is hard to read, it seems that the subject is optional indeed. We could maybe rely no both.
About the assertionID (of the SAML response), it's never returned in a logout request, isn't it?

**Comment by mmoayyed** [comment]
> About the assertionID (of the SAML response), it's never returned in a logout request, isn't it?

Yes, that's true. I skipped on the fact that logout is a two-way street. 

I think using both factors is fine. It would generally be simpler, of course, to just claim that "If session-index is not present -> you don't get logout functionality".

**Comment by leleuj** [comment]
For backward compatibility, sessionIndex first, then nameID as fallback.
