### ISSUE TITLE
LinkedIn API upgrade

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#1266]
https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/migration-faq?context=linkedin/consumer/context

**Comment by leleuj** [comment]
The LinkedIn v1 API still works, it's only deprecated. Close for now

**Comment by miloradvojnovic** [comment]
The LinkedIn v1 API doesn't work anymore. Do you have plans for migration to the v2 API?

**Comment by leleuj** [comment]
No plan yet, but we should do it.
