### ISSUE TITLE
org.pac4j.core.engine.DefaultSecurityLogic#ajaxRequestResolver is inconsistent

### ISSUE THREAD

**Issue by brunojcm** [pac4j/pac4j#1292]
I have set a custom `AjaxRequestResolver` in my app like this:

``` koltin
        clients.setClients(keycloakOidcClient)
        clients.ajaxRequestResolver = CustomAjaxRequestResolver()
```

Even after https://github.com/pac4j/pac4j/issues/1258 fix (I'm using 4.0.0-SNAPSHOT) I was still experiencing some issues, my redirections where going to weird AJAX endpoints, so I started investigating and find out that I have indeed no double redirections anymore, but the wrong request URL was being saved.

`DefaultSecurityLogic` seems to properly check AJAX:

```java
    protected void saveRequestedUrl(final C context, final List<Client> currentClients) {
        if (ajaxRequestResolver == null || !ajaxRequestResolver.isAjax(context)) {
            savedRequestHandler.save(context);
        }
    }
```

But the `ajaxRequestResolver` is the default one, not the one I set in the `clients` configuration, which is very unexpected.

For now, I'm doing `(this.securityLogic as ShiroSecurityLogic).ajaxRequestResolver = CustomAjaxRequestResolver()` during my filter setup, but I propose that we remove the `ajaxRequestResolver` property from the `DefaultSecurityLogic` and get it from the configuration.

If you are happy with that, I can submit a PR.
Please, let me know what you think.

**Comment by leleuj** [comment]
I see your point. In fact, we should have the following logic:
1) first, we try to get it from the `DefaultSecurityLogic` if it is defined (`null` by default)
2) then, we try to get it from the `config` (`null` by default)
3) finally, we use the `DefaultAjaxRequestResolver`.

Yes, please a submit a PR.

**Comment by leleuj** [comment]
And thanks for the early adoption. It's good to have feedbacks...

**Comment by brunojcm** [comment]
> And thanks for the early adoption. It's good to have feedbacks...
No worries, it's my duty to report issues on software that I'm using for free :)

I see your idea of trying to find a suitable `AjaxRequestResolver`, it makes sense, but do you really see value in being able to override the `AjaxRequestResolver` in at the `DefaultSecurityLogic` level? Is there any real case where we set one `AjaxRequestResolver` for all clients, but still need some different behaviour in the `DefaultSecurityLogic`?

If there is, I'm fine to implement it as you suggested, but I really don't see any advantages in allowing such a fine-grained configuration possibility, it's probably just gonna cause confusion.

Let me know what you think and I'll work on that.

**Comment by leleuj** [comment]
I've seen several requests about the `AjaxRequestResolver`,  but indeed, being able to setup a specific one for a specific security filter seems to be a bit overkill!

Remove the local setter and we'll see if people ask for it. Just keep the `config` setter option...
