### ISSUE TITLE
URGENT: pac4j jars disappeared from maven central !

### ISSUE THREAD

**Issue by vidma** [pac4j/pac4j#1305]
see https://repo1.maven.org/maven2/org/pac4j/pac4j/3.6.1/
same for any other pac4j version.

P.S. other libs still have jars:
 https://repo1.maven.org/maven2/org/apache/spark/spark-core_2.11/2.4.3/

so we get build failure on a fresh jenkins branch, which do not have cached jars:

```
....
[warn] 	[FAILED     ] org.pac4j#pac4j;3.6.1!pac4j.jar: invalid sha1: expected=<!doctype computed=3a08b17598cc540c37049370768c2d42c88ece7e (600ms)
[warn] 	Detected merged artifact: [FAILED     ] org.pac4j#pac4j;3.6.1!pac4j.jar:  (0ms).
[warn] ==== local: tried
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/pac4j/pac4j/3.6.1/pac4j-3.6.1.jar
[warn] ==== Shibboleth: tried
...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::              FAILED DOWNLOADS            ::
[warn] 	:: ^ see resolution messages for details  ^ ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.pac4j#pac4j;3.6.1!pac4j.jar
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[error] sbt.librarymanagement.ResolveException: download failed: org.pac4j#pac4j;3.6.1!pac4j.jar
```

@leleuj

**Comment by leleuj** [comment]
Indeed, that's very strange! Let's wait a few minutes to see if it comes back. If it doesn't, I'll try to reach the guys from Maven...

**Comment by vidma** [comment]
it disappeared around or before yesterday evening. so at least 15h so far.

**Comment by vidma** [comment]
interesting,  https://mvnrepository.com/artifact/org.pac4j/pac4j/3.6.1 now lists pac4j as pomOnly, so as a aggregate of dependencies without a jar:
```
// https://mvnrepository.com/artifact/org.pac4j/pac4j
libraryDependencies += "org.pac4j" % "pac4j" % "3.6.1" pomOnly()
```

maybe the jar shouldn't actually exist (as other jars exist, like pac4j-core.jar ), and maven central just did some cleanup? or is it the inverse - maybe this pomOnly shown as a result of some fuckup on maven central?

@leleuj

**Comment by vidma** [comment]
Fixed by marking `"org.pac4j" % "pac4j" % "3.6.1" pomOnly()` as pomOnly()

**Comment by leleuj** [comment]
Ah yes, it was the pom dependency! `pac4j-*` dependencies are still there. You shouldn't pull the `pac4j` dependency, it doesn't make any sense, you should pull `pac4j-oauth`, `pac4j-oidc`, ...
