### ISSUE TITLE
Support France Connect

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#131]

**Comment by sebastien-prudhomme** [comment]
Doc here: https://doc.integ01.dev-franceconnect.fr/

No discovery URL unfortunately, so org.pac4j.openid.client.BaseOpenIdClient not really usefull

**Comment by leleuj** [comment]
I'm not sure to follow you. I thought the France Connect support was based on OpenID Connect (`pac4j-oidc` module) while you are talking about OpenID (`pac4j-openid` module).

In any case, I will welcome any improving change and pull request.

**Comment by sebastien-prudhomme** [comment]
You're right

**Comment by leleuj** [comment]
Any update on this?

**Comment by leleuj** [comment]
No more request on this. Closing for now. Feel free to reopen with a contribution.

**Comment by teddyber** [comment]
Hello,

I'm trying to make this work, here's where I am:
- I created a test account at FranceConnect => I got client id & secret and setted-up redirect URIs to https://cas.example.org:8443/cas/login?client_name=OidcClient
- I created a dummy discovery json using the sample at https://openid.net/specs/openid-connect-discovery-1_0.html,§4.2
- I edited the relevant values (mostly URLs)

so far I am correctly redirected to FranceConnect, I can login and I'm redirected back with an authorization code but this fails and log log tells me the state parameter has been altered (which is false, see a few logs below)

request:
curl "https://fcp.integ01.dev-franceconnect.fr/api/v1/authorize?response_type=code&client_id=df903d1e699a238fe5378ace028526bcb4a8e99fb9d48c25f99ffbf422e433b9&redirect_uri=https"%"3A"%"2F"%"2Fcas.example.org"%"3A8443"%"2Fcas"%"2Flogin"%"3Fclient_name"%"3DOidcClient&scope=openid+profile&state=hWqt5FZSauNDkl74Wr31kA28IpDVbcWviffFna_frHA&nonce=i3lxezyitOxf6jpN5ii-4AawadszIi2FHKXPRrqMM88" -H "Host: fcp.integ01.dev-franceconnect.fr"

response:
curl "https://cas.example.org:8443/cas/login?client_name=OidcClient&code=bac36dca5f267344d50c429b8c412b9340867486eb82186fe86b98a9eb600824&state=hWqt5FZSauNDkl74Wr31kA28IpDVbcWviffFna_frHA" -H "Host: cas.example.org:8443"


lastly, if I manually validate the authorization code againt the FC token endpoint, it works! So we're close!
POST /api/v1/token HTTP/1.1
Host: fcp.integ01.dev-franceconnect.fr
Content-Type: application/x-www-form-urlencoded
Cache-Control: no-cache

code=f50b4aabf5fc3b0dae09fd62d2ea9770e56cbe3453cb364ccdbb504c35d2bbc1&grant_type=authorization_code&client_id=df903d1e699a238fe5378ace028526bcb4a8e99fb9d48c25f99ffbf422e433b9&client_secret=<redacted>&redirect_uri=https%3A%2F%2Fcas.example.org%3A8443%2Fcas%2Flogin%3Fclient_name%3DOidcClient

**Comment by leleuj** [comment]
The state is saved into session: https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/redirect/OidcRedirectActionBuilder.java#L94 and then retrieved from the session: https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/credentials/extractor/OidcExtractor.java#L79

Your issue is strange! Keep us posted...

**Comment by teddyber** [comment]
OK, my bad, that was #fatFingers I guess. I made it work like a charm with the attached discovery document (shamlessly dropped on a static web server :) ).
changes made:
- client authentication : client_secret_post
- signing alg : HS256

I'll test attributes retrieval from CAS 5 tomorrow!
great job Jérôme! that was so easy to make that integration!

[oidc.txt](https://github.com/pac4j/pac4j/files/1157372/oidc.txt)

**Comment by leleuj** [comment]
Please submit a PR when you'll be ready and think about the documentation update also. See: http://www.pac4j.org/docs/contribute.html#2-documentation

**Comment by leleuj** [comment]
@teddyber : any update on this?

**Comment by leleuj** [comment]
Closing for now. Feel free to re-open with your contribution.
