### ISSUE TITLE
failed: (404)[localhost could not be found or is considered invalid

### ISSUE THREAD

**Issue by janierj** [pac4j/pac4j#1310]
I have the following code to get an ST from my CAS server hosted on my localhost.
So the method requestTicketGrantingTicket in the CasRestAuthenticator.class is retrieving as locationHeader = https://localhost:6443/cas/v1/tickets/TGT-12-Qc3BgeIJASAHldSMKdoFEJZNL3-SpxF4OkE-mqrNhttps://localhost
and them do....
``` var9 = locationHeader.substring(locationHeader.lastIndexOf("/") + 1);``` 
and only get "localhost" who is an invalid ticket instead of  **TGT-12-Qc3BgeIJASAHldSMKdoFEJZNL3-SpxF4OkE-mqrNhttps://localhost**

``` final MockHttpServletRequest request = new MockHttpServletRequest();
        final MockHttpServletResponse response = new MockHttpServletResponse();
        final WebContext webContext = new J2EContext(request, response);

        UsernamePasswordCredentials usernamePasswordCredentials = new UsernamePasswordCredentials(user.getUsername() , user.getPassword());

        CasConfiguration casConfiguration = config.getClients().findClient(CasClient.class).getConfiguration();
        final CasRestAuthenticator casRestAuthenticator = new CasRestAuthenticator(casConfiguration);

        // authenticate with credentials (validate credentials)
        casRestAuthenticator.validate(usernamePasswordCredentials, webContext);

        // get user profile
        final CasRestProfile userProfile = (CasRestProfile) usernamePasswordCredentials.getUserProfile();```

**Comment by leleuj** [comment]
Pleas use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
