### ISSUE TITLE
AbstractProfileService::convertAttributesToProfile sets profile id with username instead of id

### ISSUE THREAD

**Issue by marcadella** [pac4j/pac4j#1350]
AbstractProfileService::convertAttributesToProfile sets profile id with username instead of id

**Comment by mmoayyed** [comment]
https://github.com/pac4j/pac4j/pull/1351

**Comment by mmoayyed** [comment]
Please do not create an issue only to then follow up with a pull request for said issue. Just submit the pull request; Less paperwork that way :)
