### ISSUE TITLE
UserProfile::addAttributeToMap prints clear passwords in log!

### ISSUE THREAD

**Issue by marcadella** [pac4j/pac4j#1354]
UserProfile::addAttributeToMap prints clear passwords in log!

**Comment by marcadella** [comment]
Why closing it? Sensitive information should not be printed in log.
Note: this happens aven when using a password encoder.

**Comment by mmoayyed** [comment]
I would have hoped that this sort of thing should not be publicly reported, given the security sensitive nature of it. If you feel there is a problem, discuss privately and we'll patch it accordingly.

**Comment by mmoayyed** [comment]
And once more, if you think you have found a problem in general, consider sending a pull request. The pull request is the issue, no need for extra paperwork. Thanks!
