### ISSUE TITLE
Unable to set expires attribute in Cookie

### ISSUE THREAD

**Issue by davoustp** [pac4j/pac4j#1356]
Class `org.pac4j.core.context.Cookie` does not allow to set the `expires` attribute, only `max-age` is supported.

This is a problem to cope with oldies, such as Internet Explorer 11 or less, because these browsers just ignore the `max-age` attribute and stick to the stone age and only accept the `expires` header to control the cookie expiration.
See https://balanceiskey.github.io/2015/11/25/ie11-cookies.html

This is true that this attribute is not supported in the Servlet specs (see `org.pac4j.core.context.J2EContext.addResponseCookie(Cookie)`), but **is** supported by the JAXRS spec.
See `org.pac4j.jax.rs.pac4j.JaxRsContext.addResponseCookie(Cookie)` which has a note about this:

>         // Note: expiry is not in servlet and is meant to be superseeded by
>         // max-age, so we simply make it null

So instead of making it null, adding a `Date expiry` member to class `Cookie` and propagating it to the JaxRsContext would fix this entirely.

J2Context would still conform to the Servlet spec and therefore ignore this class member.

Note that adding the `expires` attribute and settings both `max-age` and `expires` attributes in a cookie is no big deal since newer browsers will honor the `max-age` attribute if present and disregard the `expires` attribute entirely.

**Comment by leleuj** [comment]
It makes sense.

**Comment by davoustp** [comment]
Hi Jérome,
Any planned date for 3.8 release?
