### ISSUE TITLE
Google OAuth2 support for refresh_token

### ISSUE THREAD

**Issue by srini156** [pac4j/pac4j#136]
Currently `Google2Client` doesn't support using **refresh_token** which can be used to refresh access_token.

It is currently only persisting access_tokens which is short lived (1 hour). 

I am in the process of making changes to `Google2Client`, `GoogleApi20` and `Google2JsonExtractor` (and if required, few more changes) to support the concept of refresh_tokens and ability for `Google2Client` to regenerate access_tokens.

I would raise PR in next few days.

**Comment by leleuj** [comment]
Great! I'll carefully review your PR when I'll receive it to add this feature. Thanks.

**Comment by leleuj** [comment]
Any update on this?

**Comment by srini156** [comment]
Hey @leleuj haven't worked on that post our discussion. In fact, we dropped using Google OAuth2 in our flows.

**Comment by leleuj** [comment]
OK. Marked as "Future" if ever.

**Comment by leleuj** [comment]
No more request on this. Closing for now. Feel free to reopen with a contribution.
