### ISSUE TITLE
Canonical way to retrieve user attributes in type safety manner

### ISSUE THREAD

**Issue by davido** [pac4j/pac4j#1406]
There is `Object getAttribute(String name)` method for retrieving of user profile attributes.

Is there any recommended way how to access the attributes in safety way? The reason for asking is that we have inherited this code in Saml-plugin in Gerrit Code Review project:

```java
private static String getAttribute(SAML2Profile user, String attrName) {
    List<?> names = (List<?>) user.getAttribute(attrName);
    if (names != null && !names.isEmpty()) {
      return (String) names.get(0);
    }
}
```

and this attempt to read ID:

```java
private static String getAttributeOrElseId(SAML2Profile user, String attrName) {
    String value = getAttribute(user, attrName);
    if (value != null) {
      return value;
    }
    return user.getId();
  }
```

This code is apparently not correct, as we received this CL: [1] to fix the type detection, in case the attribute type is not a list: [1], with this attempt to fix it:

```
  private static String getAttribute(SAML2Profile user, String attrName) {
    String value = String.valueOf(user.getAttribute(attrName));
    if (value != null) {
      return value.replace("[", "").replace("]", "");
    }
  }
```

But this sounds like a hack to me. Is there any canonical ways?

Could a `Utility#extractUserProfileAttribute(String)` (or some such) method be provided? Looking at the code, there is `InternalAttributeHandler` that is type aware, or there is `AbstractJwtProfile#getAudience()` method: 

```
public List<String> getAudience() {
        final Object audience = getAttribute(JwtClaims.AUDIENCE);
        if (audience instanceof String) {
            return Collections.singletonList((String) audience);
        } else if (audience instanceof String[]) {
            return Arrays.asList((String[]) audience);
        } else if (audience instanceof List) {
            return (List<String>) audience;
        } else {
            return null;
        }
    }
```

[1] https://gerrit-review.googlesource.com/c/plugins/saml/+/238118

**Comment by mmoayyed** [comment]
You could probably refactor `AbstractJwtProfile#getAudience()` and extract a method out of it to move it up the parent hierarchy. Something like this:

```
public static List<String> extractAttributeValues(String name) {
        final Object value = getAttribute(name);
        if (value instanceof String) {
            return Collections.singletonList((String) value);
        } else if (value instanceof String[]) {
            return Arrays.asList((String[]) value);
        } else if (value instanceof List) {
            return (List<String>) value;
        } else {
            return null;
        }
    }
```

Then modify `getAudience()` to call this with the right claim, and then use this method where you need it. You're welcome to submit a pull request.

Also, in the future please discuss such changes on the dev mailing list before opening up issues. 

Thanks in advance :)

**Comment by leleuj** [comment]
We have many options here. One thing to know is that a `ProfileDefinition` is used to generate the profile: https://github.com/pac4j/pac4j/blob/3.8.x/pac4j-saml/src/main/java/org/pac4j/saml/credentials/authenticator/SAML2Authenticator.java#L68
In the profile, we have user attributes and authentication attributes.

In SAML2, the user attributes are always a list of values. The identifier of the profile and the mapped attributes can be defined.
I tend to think the audience is more an authentication attribute and should be added as this.

**Comment by vladsf** [comment]
Looking at restore() in https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/InternalAttributeHandler.java it does not always return a list of values for an attribute.
