### ISSUE TITLE
Refresh SAML Metadata

### ISSUE THREAD

**Issue by runger1101001** [pac4j/pac4j#1410]
Please see: https://github.com/pac4j/pac4j/issues/1109

Will someone take another look at this?
It is a standard feature in other SAML SP Implementations, e.g. spring-security-saml or shibboleth.

If the IdP Metadata is an URL, you refresh it from that URL. If it is a file, you simply refresh it from that file (the user could change the file), although that is much less important a use-case. The interval for refreshing should be configurable.

The interval-based refresh is necessary to capture changes to the Metadata that occur before the validUntil expires.
In addition, there should be a refresh when validUntil is over.

This behaviour is in fact implemented in opensaml, see: https://github.com/apigee/java-opensaml2/blob/master/src/main/java/org/opensaml/saml2/metadata/provider/HTTPMetadataProvider.java
So all you would have to do is expose the configuration in pac4j-saml...

**Comment by mmoayyed** [comment]
Do not create duplicate issues please. See https://github.com/pac4j/pac4j/issues/1109#issuecomment-539522096

**Comment by jeevanprakashgali** [comment]
is this added?
