### ISSUE TITLE
Csrf state storage in session does not currently allow for more than one client of the same type

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#1424]
The session key variable needs to be namespaced by client name. 

In our app we allow the user to configure any number of clients and there could for instance be 2 oidc clients displaying href links. When link is generated state gets stored so it can be checked when the redirect occurs back to app. Currently one state is clobbering the other and then only one link works.

**Comment by leleuj** [comment]
Indeed, it's done properly for the OAuth protocol, but not for the OpenID Connect protocol. Would you mind submitting a PR for that? Thanks

**Comment by leleuj** [comment]
@garpinc See: https://github.com/pac4j/pac4j/pull/1440

**Comment by garpinc** [comment]
Awesome.. Unfortunately I didn’t have the time to create a PR but thanks.. What version will that hit? Guess it will be time for another  upgrade.. Hope it won’t be as painful this time.. 😊

________________________________

**Comment by leleuj** [comment]
It will go in the future v4 release
