### ISSUE TITLE
Support for openid scope in Google2Scope

### ISSUE THREAD

**Issue by gsmet** [pac4j/pac4j#148]
Hi,

Our artifact-listener.org website was using the Google OpenID API which is now deprecated.

As part of the migration path to OAuth2, we need to be able to request the openid scope to get the mapping between the OpenID account and the new OAuth2 account.

Currently, Google2Scope doesn't allow us to get this information.

Could you add EMAIL_OPENID and EMAIL_PROFILE_OPENID scopes to Google2Scope so that we can have a migration path for our users?

Thanks!

**Comment by gsmet** [comment]
By the way, it might be even nicer to provide an easy way to get the openid account information.

**Comment by leleuj** [comment]
I'm looking for contributors: would you min trying to push a PR for that? Thank

**Comment by gsmet** [comment]
Hi Jérôme,

I gave it a try but it's far from being obvious to provide a clean migration path at the authentication level without adding too much mess (and moreover soon to be deprecated mess).

I finally decided to handle the migration at the application level: people will have to create a new account and I will migrate all their data to the new account.

Closing this issue!

**Comment by leleuj** [comment]
OK. Thanks for the try.
