### ISSUE TITLE
In OidcClient expireSessionOnTokenExpiration should respect refresh grant

### ISSUE THREAD

**Issue by SoerenSilkjaer** [pac4j/pac4j#1486]
Based on this thread
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/pac4j-dev/UQi0kwqMeMU/tfniFq_dBgAJ

Actual behavor
When expireSessionOnTokenExpiration is enabled in OidcClient, the session is expired when the access token expires.

Expected behavior
The session should expire when the access token has expired and the user can no longer be refreshed with a refresh grant.

**Comment by leleuj** [comment]
I guess this is the actual behavior. If the access token is expired, the `OidcProfile` is expired and the `ProfileManager` tries to renew it thanks to the refresh token if it exists and is not expired (method `renewUserProfile` of the `OidcClient`).
Can you elaborate on this?

**Comment by SoerenSilkjaer** [comment]
I see your point. I might have misunderstood something here. I will have to go back to this issue and verify if there is a problem. You can close this issue in the meanwhile if you want to

**Comment by leleuj** [comment]
OK. We'll re-open it if need be.
