### ISSUE TITLE
Description of UserInfoErrorResponse suppressed in log

### ISSUE THREAD

**Issue by mischwarz** [pac4j/pac4j#1488]
When an error occurs in UserInfoOidcAuthenticator.fetchOidcProfile, I only get the error code of the ErrorObject, but not the description since the ErrorObject.toString() only uses the code. The description derived from the WWW-Authenticate and it would be very valuable for log analysis to see the cause of the problem without need to debug into the code.

I  would suggest to simply print the toJSONObject in the error log. I can provide a PR if this is a welcome improvement.

**Comment by leleuj** [comment]
Sure. Please submit a PR. Thanks
