### ISSUE TITLE
Basic JPMS compliance

### ISSUE THREAD

**Issue by gneuvill** [pac4j/pac4j#1497]
Currently, when used in a modular setting (app or lib with a `module-info.java`), each pac4j artifacts is automatically assigned a module name, which is a bit unsound (for example, artifact `org.pac4j.jax-rs:core` gets to be named simply `core`, which might clash with other modules from other libraries).

A simple and non invasive workaround would be to declare an `Automatic-Module-Name` clause in the `MANIFEST.MF` files of each of the pac4j artifacts, thus  formalising the module names.

Before issuing a pull request, those names should be discussed : there is a convention to use full packages names as module names (see https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html) ; personally, I find those names a bit cumbersome and since the name `pac4j` is a good discriminator, I'd suggest to use names such as `pac4j.core`, `pac4j.cas`, etc... in this project and then `jaxrs.pac4j`, `ratpack.pac4j`, etc... in implementations projects.

Thoughts ?

**Comment by leleuj** [comment]
The page on the blog does not exist, but anyway, I get the idea and I'm in line: we should find easy names.

Your convention looks good, but how would you name this module: https://github.com/pac4j/jax-rs-pac4j/tree/master/jersey225?

**Comment by gneuvill** [comment]
> The page on the blog does not exist

Oops, fixed !


> Your convention looks good, but how would you name this module: https://github.com/pac4j/jax-rs-pac4j/tree/master/jersey225?

Hmm, not sure... `pac4j.jersey225` should compile, although with a warning ("module name component should avoid terminal digits") ; a workaround is to add a `_` at the end (`pac4j.jersey225_`), otherwise I don't know : `pac4j.jersey.old` ?

**Comment by leleuj** [comment]
I think I would have expected something like `jaxrs.pac4j.jersey225` and thus `jaxrs.pac4j.core` for the main module...

**Comment by gneuvill** [comment]
Ah sorry ! I thought your concern was about the `jersey225` name ending with digits (which is indeed not recommended, hence the warning). Anyway, yes, your proposed scheme seems a logical one.

**Comment by leleuj** [comment]
Excellent! Please submit PRs for these changes...

**Comment by gneuvill** [comment]
@leleuj Concerning implementation projects, I now think it would be better make the module name begin with `pac4j` (thus instead of `ratpack.pac4j`, we'd have `pac4j.ratpack` or `pac4j.impl.ratpack`). Do you agree ?

**Comment by leleuj** [comment]
I think this is what we said: "I'd suggest to use names such as pac4j.core, pac4j.cas, etc... in this project and then jaxrs.pac4j, ratpack.pac4j, etc... in implementations projects."

**Comment by gneuvill** [comment]
Ok, but don't you fear that `ratpack.pac4j` maybe the name of a possible module in the ratpack project ?

**Comment by leleuj** [comment]
I misunderstood things.

Let's follow your last proposal: `pac4j.core`, `pac4j.ratpack`, ... Everything starts with `pac4j`, be it a pac4j module or a pac4j implementation...
