### ISSUE TITLE
Add REST / stateless HTTP clients

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#152]
In the `pac4j-http` module, add:
- DirectBasicAuthClient -> UsernamePasswordCredentials
- HeaderClient -> StringCredentials
- ParameterClient (for GET / POST) -> StringCredentials
- IpClient -> StringCredentials

**Comment by mmoayyed** [comment]
You may also consider adding a CAS client for cas rest. I could work on that bit.

**Comment by mmoayyed** [comment]
See https://github.com/Jasig/cas/issues/963

**Comment by leleuj** [comment]
That's a good idea. I'm wondering why I didn't think about it before ;-)

You would need a `CasRestAuthenticator` which checks credentials against the CAS REST API.

**Comment by danielpacak** [comment]
+1

I can help you on that as well. Actually I've already wrote such a client here [CasRestClient](https://github.com/danielpacak/cas_poc/blob/master/cas-rest-client-java/src/main/java/com/github/danielpacak/cas/client/CasRestClient.java).

It's a quick and somehow naive implementation, but it's working.

**Comment by leleuj** [comment]
Thanks.

First, I will push a pull request to restructure the classes hierarchy of the clients to properly introduce the new REST clients. Then, we'll see how to adapt that to a `CasRestClient`...

**Comment by leleuj** [comment]
Draft PR: https://github.com/pac4j/pac4j/pull/166

@miremond : this is a first commit to refactor the classes hierarchy and distinguish between "indirect" and "direct" clients, before creating "direct" clients. Any feedback will be appreciated.

**Comment by mmoayyed** [comment]
@leleuj are we ready to move on this issue? I'd like to see if we can port over the CAS rest client, drawing from what @danielpacak has.

**Comment by leleuj** [comment]
The master has been updated with the necessary classes. The `CasRestClient` should certainly inherit from the `DirectHttpClient` and be stored in the `pac4j-cas` module which must have a compile / optional dependency on the `pac4j-http` module.

The way credentials are retrieved from the HTTP request are handed by an `Extractor<UsernamePasswordCredentials>`, it should be settable in this client. There should be a specific `CasRestAuthenticator` inheriting from `Authenticator<UsernamePasswordCredentials>` which send an HTTP request to the CAS server with the retrieved username/password credentials. This `CesRestAuthenticator` should save a very basic `HttpProfile` in the credentials to allow an https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/profile/creator/AuthenticatorProfileCreator.java to directly retrieve it.

Hope these guidelines helps. Just let me know if you need more information...

**Comment by mmoayyed** [comment]
Great! thanks for the info. I'll start working on this and should have something by the weekend hopefully.

**Comment by mmoayyed** [comment]
So I started down the path you recommended, and have a few questions:

Based on this design, it seems like the authenticator it going to retrieve and restore a user-profile into a credential object that it receives. This does not work well (or at all) with the CAS rest API because:

1. A profile can only be created once you validate a service ticket. Validating a service ticket requires a service url, which I dont have in the authenticator, or I guess I am not sure how that is to be specified in validate(). 

2. The TGT can certianly be reused to acquire more service tickets for a variety of applications. Is the caching of that TGT a responsibility of the authenticator? such that it locally tracks that and it's not part of the profile? What happens when the TGT is expired? is the authenticator going to retry itself?

**Comment by leleuj** [comment]
The primary role of the `Authenticator` is to validate credentials and if ever, a user profile can be created during the credentials validation, the `Authenticator` can create it and store it in the credentials. It's the `AuthenticatorProfileCreator` which retrieves the user profile stored in the credentials. Of course, another `ProfileCreator` can be used and no profile can be created by the `Authenticator`. New credentials can be created for various purposes by inheriting from `UsernamePasswordCredentials` or `HttpCredentials` or even `Credentials`.

The CAS REST API does not fit so easily in the `Client` mechanism.

The username/password are actually the credentials of the user and then we retrieve a TGT. So I would create a `CasRestAuthenticator` which checks these username/password against the CAS server and creates a specific `HttpTGTProfile` (inheriting from `HttpProfile`) which would have the username as identifier and a new field: TicketGrantingTicket to store the returned TGT. The built user profile would be stored in the credentials and the `AuthenticatorProfileCreator` would be used.

Then, what's the use case? We want to get a service ticket to call a CAS service with it, right? (it's the CAS service which will validate the service ticket via the CAS server and get the user profile, not the current client).
So the `CasRestClient` (inheriting from `DirectHttpClient`) should have a new method: `ServiceTicketCredentials getServiceTicket(HttpTGTProfile tgtProfile)`. This method would call the CAS server with the TGT retrieved from the profile and get the service ticket.

Last question: expiration. It's something which is not handled in the `pac4j` library yet. If you authenticate through Facebook, you are seen as a Facebook user till your web session is not expired and you can use the OAuth access token to use the Facebook API but your Facebook session can expire before the web session does and you can no longer be able to perform Facebook calls. It's the same here, your TGT can expire and your calls to get a service ticket will fail. The easiest solution would be to throw a specific `NoLongerAuthenticatedException` (you can find a better name) that we would use in all cases where the user is not longer authenticated even if the web session is still alive.
I'm open to suggestion.

**Comment by mmoayyed** [comment]
Thanks for the suggestions! Very valuable. I'll resume working on this and will have a PR for review shortly. 

How does one interact with the `AuthenticatorProfileCreator`?

**Comment by mmoayyed** [comment]
Another question, how is the getMechanism() used, and do we need a new flag for?

```
return Mechanism.CAS_REST_PROTOCOL;
```

?

**Comment by leleuj** [comment]
For a subclass of a `DirectHttpClient` (like this one: https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/client/direct/BasicAuthClient.java), you have to define the `Authenticator` and the `ProfileCreator`. If your specific *authenticator* is already generating a user profile and storing it in the credentials, you just need to provide an instance of the `AuthenticatorProfileCreator`  as the `ProfileCreator` and it will pick up the user profile from the credentials and return it: https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/profile/creator/AuthenticatorProfileCreator.java#L36

Example:

```
BasicAuthClient baClient = new BasicAuthClient(new MyAuthenticator(),
                                          new AuthenticatorProfileCreator());
```

**Comment by leleuj** [comment]
I'm not completely satisfied by the `Mechanism` concept. At first, it was just the protocols used: OAuth, OpenID, ...

Everything was good until I started the REST support: I can say that it's the HTTP protocol or even be more precise like `FORM_MECHANISM`, but it does not reflect the fact that it uses a `LdapAuthenticator` for these username/password or that it uses a `DbProfileCreator`.

For the CAS REST API, it should be `FORM_MECHANISM` if the username/password are provided through a form or  `BASICAUTH_MECHANISM` if the credentials are provided via a basic auth.

There is something to do with this `Mechanism` concept, but I'm not sure what to do yet. I'm open to suggestions.

**Comment by mmoayyed** [comment]
So, I guess I first need to ask: what is the intent behind specifying a mechanism? where is it used and why is it needed?

**Comment by leleuj** [comment]
Good question. The only place where this information is used, is in the CAS server to say that only some protocols and mechanims are supported and not the HTTP protocol for example: https://github.com/Jasig/cas/blob/master/cas-server-support-pac4j/src/main/java/org/jasig/cas/support/pac4j/web/flow/ClientAction.java#L145

It's meant to reflect the authentication mechanism, but it's a bit ambiguous as it may be related with the extractor and the authenticator and for the CAS REST protocol, it's both a form authentication and a CAS authentication mechanism.

**Comment by mmoayyed** [comment]
Ah ic; well in that case could we for CAS simply make that a matter of documentation and education? Such that if a deployer uses/configures an httpclient, that just be an error on their part and code will eventually crash at some point? this will allow us to remove the mechanism. 

I think the client class type reflects the mechanism used. If you use the SAML2Client, it's clear you're using SAML2, or CasClient indicates CAS already. If we cant remove it, is there a way for the base client to automatically figure out what the mechanism is? compare types against a pre-defined set of clients?

**Comment by mmoayyed** [comment]
Added this https://github.com/pac4j/pac4j/pull/175

The mechanism issue is no big deal at this point, but I think it needs to be eventually reworked into the extractor perhaps somehow, or removed.

**Comment by leleuj** [comment]
Yes, the `Mechanism` concept may need to be rethought. I opened: https://github.com/pac4j/pac4j/issues/176 to track that.

**Comment by leleuj** [comment]
@danielpacak : I just merged the new CAS REST clients: https://github.com/pac4j/pac4j/blob/master/pac4j-cas/src/main/java/org/pac4j/cas/client/rest/CasRestFormClient.java & https://github.com/pac4j/pac4j/blob/master/pac4j-cas/src/main/java/org/pac4j/cas/client/rest/CasRestBasicAuthClient.java

**Comment by danielpacak** [comment]
Thanks @leleuj and @mmoayyed ! I'll play with this new client shortly and give my feedback.

**Comment by mmoayyed** [comment]
Thanks Jérôme for handling this.

**Comment by siminghasemi** [comment]
Hello all,
In our project, we need to secure our API (web service URLs).
I followed this discussion and  I think I should use `CasRestFormClient `in pac4j (v2.5).

We need a scenario for authentication as follow:
1- First web service call, return _notAuthentication_.
2- In Front-end, the login page is shown and get username and password from user.
3- Front-end calls  _/login_ and pass username and password through form attributes.
4- In pac4j, a TGT is requested and a `CasProfile `is created and a **Service Ticket (ST)** is returned.
5- In Front-end, **ST** is saved in _localStorage_.
6- From this moment on, any ajax call (for example _GET /api/action_ ) is requested with embedded ST in request header as credential.
7- In pac4j,the passed credential (ST) is validated and without need of re-authentication, grant access to resource and return resource.
8- All other web service calls are validated with ST until session is expired.
9- If call, _GET /logout_ the ST and related _TGT_ is destroyed.

My question is that, `CasRestAuthenticator `seems to use username and password for every request validation. I found `LocalCachingAuthenticator `too, but I do not know how does it authenticate second, third and so on web service requests?
Besides, I am not sure that this solution is appropriate for our scenario. 
Any Suggestion is appreciated ...

**Comment by leleuj** [comment]
The `CasRestFormClient` will allow you to send the user CAS credentials (login + password) as basic auth to the web service which will then be validated via the CAS REST API.
Every time you call the web service, you will pass the user credentials and they will be validated via the CAS REST API. Using the `LocalCachingAuthenticator` will cache the resulted user profile for the given credentials and will avoid calling the CAS REST API for every request when it's the same credentials.

Reading "login page" in your previous post, I'm not sure you really want to use the CAS REST API unless you host the login page.
I think you're more in a scenario where first, you log in via the CAS login page and then call web services using the CAS user identity: this is feasible with proxy support.
Login to the CAS server via the login page will grant you a TGT and an ST for the application access. Then, if you define proxy support, you will also get a PGT (proxy granting ticket) and be able to request PT for various web services. Finally, you will call your web service with this PT and use some caching (`LocalCachingAuthenticator`) if you want to reuse the PT and avoid getting a new one for each request (you could also rely on the web session but this is unlikely for web services call scenario).

You should carefully read: http://www.pac4j.org/docs/clients/cas.html

**Comment by siminghasemi** [comment]
Thank you for your reply.
Actually we have a multi tiers architecture software which has a separated AngularJS front-end hosted on a nodeJS server and an api server hosted on netty (play framework) as the backend.
What we need is to have our login page in front-end and fully secured REST APIs in our backend (play framework) and SSO mechanism for authentication.
We want to use Pac4j as a CAS client but we need to implement claim based authentication based on JWT.  
After reading the Pac4j and CAS documents I couldn't figure out how I can configure Pac4j and CAS to implement the above mechanism.
Please give me some clue or kindly explain the way I can have this kind of authentication mechanism

**Comment by leleuj** [comment]
If you want SSO (ant not only authentication), you'll need to use the CAS login page. So you must have a protected URL on your front app (AngularJS) which is protected by the pac4j `CasClient` to perform a CAS login process.
As soon as you are authenticated, you can turn the `CasProfile` into a JWT, save it in session and make it available for your front app.
This JWT will be used to call the backend (Play) which will be protected by a `ParameterClient` and a `JwtAuthenticator`,  assuming you want to send the JWT as a request parameter.
