### ISSUE TITLE
New authorizer concept

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#153]
Inspired by the Ratpack project

In the `pac4j-core` module, `org.pac4j.core.authorization` package:
- add a `Authorizer` interface with one method: `isAuthorized(WebContext, ? extends UserProfile)`
- move the "requireAnyRole / requireAllRoles" logic (from `UserProfile`) in specific authorizers

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/163

**Comment by jeroen4now** [comment]
This is exactly what we need for play 2.*, can this be added/used in play-pac4j?

**Comment by leleuj** [comment]
Yes, it will. I'm implementing REST support for pac4j v1.8, then I will "rebuild" every library based on it.
