### ISSUE TITLE
ADFS issue when migrating from pac4j 2 to pac4j 4

### ISSUE THREAD

**Issue by len-ro** [pac4j/pac4j#1534]
Hello, I recently migrated from pac4j 2 to pac4j 4. We have multiple SAML and CAS providers. All of them seem to work fine except ADFS. The old version generated:

```
<saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">diapasonSA
ML2Client</saml2:Issuer>
```

which works fine. The new version is generating:

```
<saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                  Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
                  >diapasonSAML2Client</saml2:Issuer>
```

The ADFS error is:

```
Exception details: 
System.Xml.XmlException: ID4262: The SAML NameIdentifier 'diapasonSAML2Client' is of format 'urn:oasis:names:tc:SAML:2.0:nameid-format:entity' and its value is not a valid URI.
```

I did some research on the topic in the similar issues, pull requests and in the mailing list and the issue which seemed to be related to the setUseNameQualifier. However this is not fixing the issue. The default value is false. Setting it to true generates:

```
<saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                  Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
                  NameQualifier="diapasonSAML2Client"
                  >diapasonSAML2Client</saml2:Issuer>
```

Is there any known way of removing the Format attribute?

Thank you,
Len

**Comment by leleuj** [comment]
Currently, you can't.

Is there a value for the format which works with ADFS or should we remove it (by configuration)?

**Comment by len-ro** [comment]
Is there a way to control the value of the Format field? I want to test the :unspecified to see if it works.

**Comment by leleuj** [comment]
Currently, you can't by configuration. But you can duplicate the `SAML2AuthnRequestBuilder` class and change its code to do that.

**Comment by len-ro** [comment]
How can I specify a custom builder? Thank you.

**Comment by leleuj** [comment]
For a test, the best is to copy/paste the pac4j class and make your change in it.

**Comment by leleuj** [comment]
OK. I just committed a `setIssuerFormat` at the `SAML2Configuration` level: https://github.com/pac4j/pac4j/commit/94e74cb6f26257d954a70be7706149a29c2d53f9

Can you try with `pac4j-saml` v4.0.0-RC4-SNAPSHOT? Thx

**Comment by len-ro** [comment]
Hello, thank you, I did the test locally, just by removing: issuer.setFormat(Issuer.ENTITY); and recompiled and it works. It took just some time to compile everything.

**Comment by leleuj** [comment]
Excellent! So now, you can do: `configuration.setIssuerFormat(null);`.

**Comment by len-ro** [comment]
Thank you. Just to confirm that: 

```
<saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"
                  Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified"
                  >diapasonSAML2Client</saml2:Issuer>
```

also works, with Format unspecified.

**Comment by leleuj** [comment]
Good. Thanks
