### ISSUE TITLE
SAML2.0 - Authentication issue instant is too old or in the future

### ISSUE THREAD

**Issue by ziedbe** [pac4j/pac4j#1578]
I have a SAML client that has been throwing this error lately: 

> Authentication issue instant is too old or in the future. 

The max lifetime is set in the backend service to 1 hour: `cfg.setMaximumAuthenticationLifetime(3600)`
as well as on the iDP side. According to the [docs](https://www.pac4j.org/1.9.x/docs/clients/saml.html#b-maximum-authentication-time), the issue pops up when the max age is not properly configured between pac4j client and the Idp. But this is not the case here, both are set to 1 hour.

**Comment by mmoayyed** [comment]
Please report issues for discussion on the pac4j mailing list first and then when needed file pull requests to address fixes. Thank you
