### ISSUE TITLE
response_type is static

### ISSUE THREAD

**Issue by Khorsan** [pac4j/pac4j#1583]
Hello,

I have a requirement to use the `response_type` value as `token`, but this value is set to static. Is it possible to add a getter and setter instead?

https://github.com/pac4j/pac4j/blob/8b21a40dcdf3b6444864eccc6e4a6cacb26b9819/pac4j-oauth/src/main/java/org/pac4j/oauth/config/OAuth20Configuration.java#L23

I don't mind doing it, just checking with the maintainers.

Thanks

**Comment by leleuj** [comment]
Sure. No problem. I just committed: https://github.com/pac4j/pac4j/commit/9ef4f5186e971cc14adc59544867e4a18feff560

Please re-open if there is an issue.

**Comment by Khorsan** [comment]
Thanks for the fast reponse.

Although you updated the configuration class, the `GenericOauth20Client` doesn't allow changing this variable, as you can see arround here:

https://github.com/pac4j/pac4j/blob/9ef4f5186e971cc14adc59544867e4a18feff560/pac4j-oauth/src/main/java/org/pac4j/oauth/client/GenericOAuth20Client.java#L60

As far as I know, `GenericOAuth20ProfileDefinition` this class ultimately extends the [`OAuth20Configuration`](https://github.com/pac4j/pac4j/blob/9ef4f5186e971cc14adc59544867e4a18feff560/pac4j-oauth/src/main/java/org/pac4j/oauth/config/OAuth20Configuration.java) (that opened this issue). I think it may be wise to be able to set the `response_type` through here.

What are your thoughts?

**Comment by leleuj** [comment]
OK. My change was unnecessary, I reverted it.
