### ISSUE TITLE
Cannot change GenericOAuthClient response_type (code)

### ISSUE THREAD

**Issue by Khorsan** [pac4j/pac4j#1586]
Continuing, #1583:

Although you updated the configuration class, the `GenericOauth20Client` doesn't allow changing this variable, as you can see arround here:

https://github.com/pac4j/pac4j/blob/9ef4f5186e971cc14adc59544867e4a18feff560/pac4j-oauth/src/main/java/org/pac4j/oauth/client/GenericOAuth20Client.java#L60

As far as I know, `GenericOAuth20ProfileDefinition` this class ultimately extends the [`OAuth20Configuration`](https://github.com/pac4j/pac4j/blob/9ef4f5186e971cc14adc59544867e4a18feff560/pac4j-oauth/src/main/java/org/pac4j/oauth/config/OAuth20Configuration.java) (that opened this issue). I think it may be wise to be able to set the `response_type` through here.

What are your thoughts?

I'm trying to pass this to [CAS, in this line of code](https://github.com/apereo/cas/blob/c2223ae8a857cc95aa4a279e7fde1ccfda85baf7/support/cas-server-support-pac4j-core-clients/src/main/java/org/apereo/cas/support/pac4j/authentication/DefaultDelegatedClientFactory.java#L510). I seem to need to update `GenericOAuth20Client`.

**Comment by leleuj** [comment]
You can change the `response_type` via: `oauth20GenericClient.getConfiguration().setResponseType("token")`. Allowing that in CAS is another problem.

**Comment by leleuj** [comment]
Something to solve on CAS side. Closing
