### ISSUE TITLE
Question about BaseHttpClient

### ISSUE THREAD

**Issue by mgoellnitz** [pac4j/pac4j#160]
Why was setUsernamePasswordAuthenticator() removed from this class in December? I'm running into some configuration trouble with a flexible DI based configuration using a number of clients and configurable authentication source etc. where a setter was very handy.

**Comment by leleuj** [comment]
As `pac4j` is moving towards REST support, there is now a more generic concept of: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/credentials/Authenticator.java. So you just need to use it instead (https://github.com/pac4j/pac4j/tree/master/pac4j-http/src/main/java/org/pac4j/http/credentials).

**Comment by leleuj** [comment]
More explanation: https://groups.google.com/forum/?fromgroups#!topic/pac4j-dev/ineGrFCmkrk
