### ISSUE TITLE
Not sure why Bean is for this class org/pac4j/core/exception/http/ForbiddenAction

### ISSUE THREAD

**Issue by UdayrapuruCLS** [pac4j/pac4j#1603]
Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration'

 BeanPostProcessor before
instantiation of bean failed; nested exception is java.lang.NoClassDefFoundError: org/pac4j/core/exception/http/ForbiddenAction

Used version v3.3.0

**Comment by leleuj** [comment]
Please use the mailling list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
