### ISSUE TITLE
Allow Resource for specifying SAML idp metadata and keystore

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#161]
A Spring resource could be a reasonable abstraction to provide input to the saml module.

**Comment by leleuj** [comment]
Could you elaborate a little more? As the `pac4j-saml` module is meant to be deployed in various environments, the aim is to have the smallest number of dependencies...

**Comment by mmoayyed** [comment]
Sure. Right now, I have a sample configuration that looks something like this:

```xml
<bean id="samlClient" class="org.pac4j.saml.client.Saml2Client"
      p:idpMetadataPath="/opt/shibboleth-idp/metadata/idp-metadata.xml"
      p:forceAuth="false"
      p:keystorePath="/etc/samlKeystore.jks"
      p:keystorePassword="cas-sp-psw"
      p:privateKeyPassword="cas-sp-psw"
      p:spEntityId="https://mmoayyed.unicon.net/cas/samlsp" />
```

The metadata path is assumed to be a physical location somewhere. I want to be able to specify a URL. Opensaml provide various types of metadata providers and resources. You could add support for those. Example:


```xml
<bean class="org.springframework.security.saml.metadata.ExtendedMetadataDelegate">
    <constructor-arg>
        <bean class="org.opensaml.saml2.metadata.provider.ResourceBackedMetadataProvider">
            <constructor-arg>
                <bean class="java.util.Timer"/>
            </constructor-arg>
            <constructor-arg>
                <bean class="org.opensaml.util.resource.FilesystemResource">
                    <constructor-arg value="${idp.metadata}"/>
                </bean>
            </constructor-arg>
            <property name="parserPool" ref="parserPool"/>
        </bean>
    </constructor-arg>
    <constructor-arg>
        <bean class="org.springframework.security.saml.metadata.ExtendedMetadata">
        </bean>
    </constructor-arg>
</bean>
```

**Comment by leleuj** [comment]
I find the current configuration capabilities fairly satisfying but I'm not against providing something more evolved if the **dependency on Spring is optional** and seamlessly integrated with the current configuration strategy (Spring dependencies should be marked as `provided` so that deployers only declared them when they really want to use them).

I'm sure you can provide a great PR on your own ;-)

The only caveat is that the master in now on version 1.8 and won't be released until a few months, though I could cut a 1.7.1 release if you also provide a PR for branch 1.7.x.

**Comment by mmoayyed** [comment]
Problem with the current configuration is, it assumes the application and the idp are on the same physical hardware. In enterprise deployments, that is hardly the case. Apps need to be able to consume metadata from a variety of resources to fully support the federation use case. 

Spring does not have to play a role here actually. Rather than using `ExtendedMetadataDelegate`, you could provide a set (or a single instance) of opensaml2 resources. That would be sufficient. opensaml has providers that can talk to classpath, filesystem, urls and is able to cache, etc. That would require a API change of course, so I think 1.8 would be a better fit. 

I'd be happy to post a PR, but before I do, I am more concerned about #162. I'd rather we do something about #162 first before starting with this one.

**Comment by leleuj** [comment]
Yes, #162 is the priority for 1.7.x while this can be done in 1.8.

**Comment by mmoayyed** [comment]
Also handled via #162 and #171

**Comment by mmoayyed** [comment]
Think we can safely close this now.
