### ISSUE TITLE
need the algorithm to be set to HS512 

### ISSUE THREAD

**Issue by chengc843988** [pac4j/pac4j#1619]
I need set the signature algorithm to HS512, I don't know how to do.
Then I modify the source, and add a function:
	public void setAlgorithmName(String algorithm) {
		JWSAlgorithm alg = null;
		alg = JWSAlgorithm.parse(algorithm);
		if (alg != null)
			super.setAlgorithm(alg);
	}

and modify the shiro.ini as this (using buji) 
signingConfig.algorithmName=HS512 

or any configuration item I can set .

**Comment by mmoayyed** [comment]
This is not a support channel. Please discuss support questions on lists.
