### ISSUE TITLE
Upgrade to OpenSAML 3.1.1

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#162]
Using the pac4j-saml module in CAS 4.1 causes various kinds of exceptions, all seem to stem from the fact that pac4j uses opensaml 2.5 while CAS uses Open saml 3.1.1. Would be very helpful if pac4j started supporting 3.1.1 as well.

**Comment by mmoayyed** [comment]
I can try to work on this if you want. Seems like something I could contribute.

**Comment by leleuj** [comment]
Indeed, the CAS server is ahead of the `pac4j-saml` module. Your help would be great!

The only caveat is that the master in now on version 1.8 and won't be released until a few months, though I could cut a 1.7.1 release if you also provide a PR for branch 1.7.x.

**Comment by mmoayyed** [comment]
Very good. I'll see what the breaking changes are. If there are none, I'll target for 1.7. Chances are there will be some, and given that this is sort of a major upgrade, 1.8 might eventually be a more natural target.

**Comment by leleuj** [comment]
Even when upgrading with OpenSAML 3.1.1, I'm fairly confident that the pac4j API can remain unchanged and can thus fit in a 1.7.1 release. Just let me know...

**Comment by mmoayyed** [comment]
I have made a number of changes, but this is proving more difficult than I thought. Would you be able to assist if I posted a PR? I do need a 2nd pair of eyes to review and make adjustments. I can either push the PR to this repo or your fork, given that it's still in dev and not ready for compile

**Comment by leleuj** [comment]
It's always more difficult than expected ;-) Sure, I'll help you with the PR, but please push it against this main repo: https://github.com/pac4j/pac4j...

**Comment by mmoayyed** [comment]
The API changes are a lot more variable than what I had thought. I event thought about using spring saml as an optional dependency but even they are also on an older version of open saml.

**Comment by leleuj** [comment]
@mmoayyed : as we merged your update in the branch 1.7.x, I guess it's time to have the same patch for the master. Thx

**Comment by mmoayyed** [comment]
Sure. At a conference this week but I'll see if I can find the time to do the merging. I assume you need another PR that is targeted at master?

**Comment by leleuj** [comment]
Yes, I need another PR for the master (with the fix on the letter case)

**Comment by mmoayyed** [comment]
Added PR #171

**Comment by mmoayyed** [comment]
Also can be closed.

**Comment by leleuj** [comment]
Let's keep this one open till the latest issues are fixed (missing dependency found in the j2e-pac4j-demo)...
