### ISSUE TITLE
DirectBasicAuthClient and the response header

### ISSUE THREAD

**Issue by decebals** [pac4j/pac4j#1628]
I use `DirectBasicAuthClient` to deal with a basic authentication request sent via an Angular application (LoginComponent -> login form).
My problem is that on an unauthorized response (401), `DirectBasicAuthClient` adds a [header](https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/client/direct/DirectBasicAuthClient.java#L49) that makes Chrome pops up the sign in dialog by default. If you respond with a 401 and WWW-Authenticate: Basic Chrome catches the Basic 401 response before it gets to Angular.

So , I don't want to add that header to response.
For the moment the only one solution found by me is to copy paste the content of `DirectBasicAuthClient` in a `CustomDirectBasicAuthClient` and to delete `retrieveCredentials` method. It's an ugly hack but for the moment it solves my problem (it's not possible in Java to call `super.super.retrieveCredentials`).

**Comment by leleuj** [comment]
This edge use case will remain a customisation, though this commit should make your life easier: https://github.com/pac4j/pac4j/commit/3f8a4ed1ede1b06d554672f53fb0024d6ef8c0b5

You just need to override the class with an empty implementation for the `addAuthenticateHeader`.

It's available in v4.0.3-SNAPSHOT for now.
