### ISSUE TITLE
Missing checks in Saml2ResponseValidator : inResponseTo, Destination, AuthnContext

### ISSUE THREAD

**Issue by elklaaso** [pac4j/pac4j#165]
I have compared Saml2ReponseValidator with spring security saml's WebSSOProfileConsumerImpl and found some missing checks, of most i found TODO's in the pac4j Saml2Response Validator, the TODO's in there are:

validateSamlProtocolResponse: add Destination and inResponseTo Validation
isValidBearerSubjectConfirmationData: Validate inResponseTo
validateAuthenticationStatements: implement authnContext validation

Do you have any idea when and if you will implement these?

To what degree does this effect how secure pac4j saml is? For example, are there other checks that make these checks not so important?

thank you!

**Comment by elklaaso** [comment]
And is there any way to replace the Saml2ReponseValidator with my own without modifying the code, i cant change the responseValidator in SAML2Client, because there is no getter used which i can override.

**Comment by miremond** [comment]
Hi,

You are really relevant in your analysis. There are some checks not
implemented yet because when I wrote pac4j-saml, it was to bring a first
working version of SAMLv2 to pac4j.
I omitted these checks because they are not the most critical to me. They
just enforce additional security checks to be more confident about the SAML
assertion.

The class Saml2ResponseValidator can not currently be overriden as it is an
internal class but feel free to submit a pull request to implement the
checks or introduce a customization mechanism.

Regards,

Michaël

2015-05-17 17:13 GMT+02:00 elklaaso <notifications@github.com>:

**Comment by leleuj** [comment]
Maintaining all `pac4j` projects is a tremendous: any contribution will be welcome.

**Comment by elklaaso** [comment]
Hi,

I have made a simple implementation of response.inresponseto / response.getdestination and subject inresponseto validation. I got access to the private properties of Saml2Client using java reflect. I know this is bad, but i dont have time to download and rebuild this project etc.

The files are here:
https://www.dropbox.com/s/03q59bkdbhgpk0q/EnhancedSaml2Client.java?dl=0
https://www.dropbox.com/s/9iiseejatw8j1a4/EnhancedSaml2ResponseValidator.java?dl=0

Its a really easy implementation, i'm not sure if its how its supposed to happen but maybe you guys can use it as a starting point.

**Comment by leleuj** [comment]
OK. Thanks for sharing. Maybe it can give @miremond some ideas...

**Comment by mmoayyed** [comment]
This is now done via the move to opensaml. If you find other missing checks, please let me know.

**Comment by leleuj** [comment]
Great!

**Comment by elklaaso** [comment]
@mmoayyed Could you explain a bit more? I do not understand

**Comment by mmoayyed** [comment]
The pac4j codebase has shifted its saml support to use the latest of OpenSAML v3. This was done via #171 and will feature the missing checks you had in mind, once it's released.

**Comment by elklaaso** [comment]
Is this implemented in OpenSAML v3 ? Or in the pac4j code?
Do you have any links to the pac4j code or opensaml v3 where this is mentioned?

**Comment by mmoayyed** [comment]
It is implemented in the pac4j-saml module code. Review the pac4j-saml module either in 1.7 or soon in master.
