### ISSUE TITLE
Travis should not attempt to deploy PRs

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#173]
Reports:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project pac4j: Failed to deploy artifacts: Could not transfer artifact org.pac4j:pac4j:pom:1.8.0-20150608.225607-7 from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/): Failed to transfer file: https://oss.sonatype.org/content/repositories/snapshots/org/pac4j/pac4j/1.8.0-SNAPSHOT/pac4j-1.8.0-20150608.225607-7.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

**Comment by leleuj** [comment]
You're completely right. We should certainly do something like for CAS.

**Comment by mmoayyed** [comment]
Already taken care of :) only commits to master are pushed.

**Comment by mmoayyed** [comment]
We should try to devote some time to this PR. It's now difficult to determine if a PR actually passes, or the failure is just  noise because Travis is trying deploy that over to sonatype.

**Comment by leleuj** [comment]
You're right. Here it is: https://github.com/pac4j/pac4j/pull/190, greatly inspired from CAS ;-)

**Comment by mmoayyed** [comment]
Awesome! Thanks for doing this.
