### ISSUE TITLE
when use nginx must override DefaultSavedRequestHandler.getRequestedUrl??? 

### ISSUE THREAD

**Issue by duanhairuo** [pac4j/pac4j#1736]
return this.serviceUrl + new URI(context.getFullRequestURL()).getPath();

this is my override content, Is there any other way?

the serviceUrl is the url by proxy by nginx , i try to change the config file of nginx to resolve but not success

**Comment by leleuj** [comment]
Please use the mailing lists for questions: http://www.pac4j.org/mailing-lists.html

You can create your own `SavedRequestHandler` and assign it to the `DefaultSecurityLogic` or to the `DefaultCallbackLogic`.
