### ISSUE TITLE
Study Jooby and reference it

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#178]
Update the "big picture" at least.

**Comment by leleuj** [comment]
Here: http://www.pac4j.org/#18

**Comment by mmoayyed** [comment]
Should this be closed?

**Comment by leleuj** [comment]
Not yet. I took a quick look at the framework, referenced it in pac4j but didn't work on the demo: https://github.com/pac4j/jooby-pac4j-demo

**Comment by leleuj** [comment]
Just spent a little more time reading the doc, I finally opened: https://github.com/pac4j/jooby-pac4j-demo/issues/2
