### ISSUE TITLE
Support CAS4 for Integration Tests

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#179]

**Comment by leleuj** [comment]
CAS server v4.1

**Comment by mmoayyed** [comment]
I might recommend that we target this towards 4.2-SNAPSHOTs. Would help the CAS project also with automated tests for all protocols.

**Comment by leleuj** [comment]
There is certainly an intermediary step by upgrading to 4.1.

**Comment by leleuj** [comment]
Maintaining a full Maven module just for CAS tests is a bit too much: tests will be turned into unit ones and integration / manual ones against the online CAS server on Heroku
