### ISSUE TITLE
Make pac4j non blocking

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#180]

**Comment by leleuj** [comment]
Making pac4j a full async lib is almost impossible: the first step is to clean the source code and makes things reusable as much as possible to see what comes out this new picture.

**Comment by leleuj** [comment]
Closing this one in favor of https://github.com/pac4j/pac4j/issues/622 to have many subcomponents with can be re-used asynchronously or replicated to support async calls.

**Comment by leleuj** [comment]
@millross is working hard on making pac4j async: https://github.com/millross/pac4j-async

We'll hope to integrate all these improvements in the version 3.0.0.

**Comment by millross** [comment]
Personally I wouldn't make any release version dependent on completion of the async stuff. Keep this open by all means, but there will need to be some pretty big core changes to enable async exposure. And I think my free time is going to decrease. My gut feeling is that we are well over a year away from this at the moment, pac4j is VERY tightly coupled to sync structures, and I need to unpick a lot of that coupling along the way.

**Comment by leleuj** [comment]
OK. No problem. I reopened this issue as the hope remains. I'll mark it as `FUTURE` though.

**Comment by millross** [comment]
I'm still hopeful :) But it is time-consuming and so far I'm still working on enough structure to make DefaultSecurityLogic viable as an async version, we're quite a way from that. Where possible I'm creating structures that can largely be reused by both Sync and Async code, so we can focus better on the divergences.

**Comment by gneuvill** [comment]
👍 This is an essential feature nowadays.

But all implementations may not be able to benefit from it. `jax-rs-pac4j` for example could come up against https://github.com/jersey/jersey/issues/2596

**Comment by leleuj** [comment]
We should certainly have an async `SessionStore`.

**Comment by ihostage** [comment]
Any update? 😄

**Comment by leleuj** [comment]
Apart from the "async" fashion, I see less interest and requests on that
today. Above all, turning pac4j asynchronous would require an
outstanding work if possible, I'm not sure it's worth the deal.

Le ven. 30 oct. 2020 à 21:47, Sergey Morgunov <notifications@github.com> a
écrit :

**Comment by mmoayyed** [comment]
> Above all, turning pac4j asynchronous would require an outstanding work if possible, I'm not sure it's worth the deal.

I completely agree. I'd say let's close. If someone wants to see this capability, they can always submit a pull request or fund the effort.

**Comment by leleuj** [comment]
Yes.

**Comment by leleuj** [comment]
@mmoayyed I'm also thinking about removing the Github "Issues" tab along with the v5 release. Like for the CAS server...

**Comment by mmoayyed** [comment]
Sure. I certainly support the idea!
