### ISSUE TITLE
Stormpath support

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#182]

**Comment by mmoayyed** [comment]
@leleuj would you want me to adapt the existing stormpath authentication handler we have for CAS for pac4j? 

I am thinking that once this support is built into pac4j, we could then write a wrapper-authN-handler in CAS that uses pac4j's authenticators, we could do the same for JWT and Mongo, etc

**Comment by mmoayyed** [comment]
Since we have the code available already, it would take little effort to fit this into 1.8 I think

**Comment by leleuj** [comment]
Yes, please. Thanks.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/264
