### ISSUE TITLE
pac4j-oidc using Jackson Databind version incompatible with the one used by Play

### ISSUE THREAD

**Issue by marcadella** [pac4j/pac4j#1824]
I get the following error when using pac4j-oidc 4.3.1 (and Play 2.8.7):
```
com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.10.5 requires Jackson Databind version >= 2.10.0 and < 2.11.0
```
The problem is that Play 2.8 uses Jackson 2.10.5, while play-oidc uses Jackson 2.11.3. Using them in the same project, 2.11.3 evicts 2.10.5 and therefore Play is unhappy.
Would it be acceptable to use Jackson 2.10.5 instead (looks like the version of Jackson has been updated in 4.0.1)?

**Comment by leleuj** [comment]
`pac4j` tries to stay up-to-date in terms of library versions. But we could maybe force the Jackson version in `play-pac4j`.

Please open a PR for that in the dedicated project.

**Comment by marcadella** [comment]
@leleuj do you mean to "force" Play using Jackson 2.11? How could that be done from `play-pac4j`??

**Comment by leleuj** [comment]
I mean forcing Jackson 2.10.5 in `play-pac4j`. I think we could explicitly add the jackson dependency.

**Comment by marcadella** [comment]
Even if you add explicitly Jackson 2.10.5 in `play-pac4j`, it will still get evicted by `pac4j-oidc`... Or am I missing something?
(I created an issue in [play-pac4j](https://github.com/pac4j/play-pac4j/issues/382))

**Comment by leleuj** [comment]
I'm not sure, it must be tested

**Comment by marcadella** [comment]
Just for completeness: Jackson got automatically updated by renovate  (https://github.com/pac4j/pac4j/pull/1580)
