### ISSUE TITLE
SAML callback in PlayFramework blocked by CSP

### ISSUE THREAD

**Issue by kryton** [pac4j/pac4j#183]
Hi.
I'm trying to use the Pac4J with SAML on my play framework app.
I am also utilizing the Content Security Policy directives filter that stops malicious scripts and so on from being executed on the page.
It does this by requiring a token in <script> calls to ensure I know what is going on.
Sadly the callback function generates the following.

    <body onload="document.forms[0].submit()">

I'm not sure where it is, but I'd like to be able to change this to
<script nonce='XXXXX'>
document.onload = function(e){ 
   document.forms[0].submit()
}
</script>

where XXXX would be passed in as a parameter or something.
Thanks!
Ian

**Comment by miremond** [comment]
Hi,

I think your message is missing some part, can you complete it?
From what I can understand, you need to allow the auto-submit javascript to execute for SAML authentication right?
The SAML authentication request is generated via an auto-submit html form constructed here https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/sso/impl/SAML2WebSSOMessageSender.java#L155.

If you want to customize this process, I think you should start here. Feel free to submit a PR if you find a robust solution.

**Comment by kryton** [comment]
Hi Michael.
The message is there, but the HTML tags got stripped/ignored in markdown.

So I'll start again, and be a bit more verbose ;-)

I have a site using the play-framework (2.3) that I am attempting to move to using our internal SAML authentication service. This site makes use of CSP, which in a nutshell tells the browser not to execute javascript unless I supply a special nonce[1] which I supply in a header.

the callback page (org.pac4j.play.CallbackController.callback ) generates some html that does a 'onsubmit' call in the body tag so that it can generate a POST request back to itself to start the SAML authentication dance.

Sadly when CSP is enabled, the browser refuses to execute the javascript (as the security header told it not too).. so I'd like a way to provide the nonce to the callback call, so it could be executed with CSP enabled. my current workaround is to manually bypass the security feature for all URL's that start with /callback. 

I will investigate the code you outlined and see if we could add a 'template' option so that users can supply their own template code in that would make the page look like they want (and enable nonces too) 

Thanks.
Ian


[1] the header for my site looks like this for example. 
Content-Security-Policy: default-src 'self';style-src 'self' http://fonts.googleapis.com 'unsafe-inline'; font-src 'self' http://fonts.gstatic.com; frame-src 'self' https://www.youtube.com; script-src 'self' 'nonce-GRAPHOK' 'unsafe-eval';

**Comment by leleuj** [comment]
Any update on this?

**Comment by kryton** [comment]
Hi @leleuj .. I added some custom filters to my site to exclude CSRF from that URL path
```

class myCSRFFilter extends EssentialFilter {
  val csrfFilter = CSRFFilter()

  def apply(next: EssentialAction): EssentialAction = new EssentialAction {
    def apply(rh: RequestHeader): Iteratee[Array[Byte], Result] = {
      if (rh.uri.startsWith("/callback") || rh.uri.startsWith("/saml")) {
        next(rh)
      } else {
        csrfFilter(next)(rh)
      }
    }
  }
}
```
not ideal.. but for me this is an internal site, so i'm ok with the risk.

**Comment by leleuj** [comment]
OK. Thanks for the feedback.
