### ISSUE TITLE
Issue with oidc delegation implementation

### ISSUE THREAD

**Issue by codeGuy401** [pac4j/pac4j#185]
Hi,

Currently trying to implement openid connect authentication delegation implementation. I have everything configured according to: http://jasig.github.io/cas/development/integration/Delegate-Authentication.html. With that said, I am seeing a noSuchMethodError coming from the org.jasig.cas.support.pac4j.web.flow.ClientAction class, when it tries to invoke the getProtocol method on the BaseClient class. It looks as though this method and the protocol class were removed sometime after version 1.4 of pac4j-core. Am I missing something big here?

**Comment by codeGuy401** [comment]
Also, these are the dependencies I am using:
 <dependency>
            <groupId>org.pac4j</groupId>
            <artifactId>pac4j-oidc</artifactId>
            <version>1.7.1</version>
        </dependency>

        <dependency>
            <groupId>org.jasig.cas</groupId>
            <artifactId>cas-server-support-pac4j</artifactId>
            <version>4.0.2</version>
        </dependency>

**Comment by codeGuy401** [comment]
may have gotten around it by excluding pac4j-core from pac4j-oidc dependency.

**Comment by mmoayyed** [comment]
cas-server-support-pac4j for 4.0.2 only uses 1.7.0 at this point. So it makes sense that you end up having a few conflicts. If you are interested, please post a PR to the CAS project to update the dependency version which will then be included in 4.0.3

**Comment by mmoayyed** [comment]
Actually, I am wrong. CAS 4.0.2 uses 114.1
https://github.com/Jasig/cas/blob/4.0.x/cas-server-support-pac4j/pom.xml#L66

So yes, you'd have issues if you included 1.7.1.
