### ISSUE TITLE
generated package are not osgi compatible

### ISSUE THREAD

**Issue by hboumedane** [pac4j/pac4j#192]
Hi,

I'm using an OSGI framework and when I add a dependency for pac4j-core it's not working because the  pac4j-core it's not a bundle.

after looking to the code source i found that it's war an error in the pom.xml
the packaing is wrong : jar instead of bundle

**Comment by mmoayyed** [comment]
which OSGI framework is this?

**Comment by hboumedane** [comment]
apache felix

**Comment by leleuj** [comment]
Are your referring to the Maven packaging: https://github.com/pac4j/pac4j/blob/master/pac4j-core/pom.xml#L27? Or is it something that can be defined at the `maven-bundle-plugin` plugin level?

**Comment by hboumedane** [comment]
yes i'm referring to maven packaging https://github.com/pac4j/pac4j/blob/master/pac4j-core/pom.xml#L27 and to 
https://github.com/pac4j/pac4j/blob/master/pac4j-core/pom.xml#L117
you need to remove jar goal to have a osgi bundle.

**Comment by leleuj** [comment]
I'm not sure to follow you on this. Even without the `jar` goal, a `pac4j-core-1.8.0-SNAPSHOT.jar` artifact will be generated.

Would you mind pushing a pull request for this? To make our discussion easier. Thx.
