### ISSUE TITLE
Relax and open up callback specification for IndirectClients, e.g., OIDC

### ISSUE THREAD

**Issue by morungos** [pac4j/pac4j#193]
I've had a bit of a journey trying to configure OIDC for deployment. Basically, the passed redirect_uri for receiving the callback needs to be absolute, but that's actually not trivial to inject for a production application. For any request, the context can be used to derive it, but the Clients class initializes before any requests, so there's no context yet.

The easiest approach seemed to be to subclass OidcClient, but all the auth params are inaccessible to subclasses, so that can't cut it. 

My fallback was to try and subclass Clients, but for some reason it's `final`. Maybe that could be reconsidered? Then I could easily subclass it to ensure that any non-absolute URIs are completed from the request's context path. 

Maybe some of these classes could be opened a little. Or even better, completing a sent redirect_uri with a scheme, host, and context path derived somehow would just happen by default.

**Comment by leleuj** [comment]
We generally start by locking everything and open things when a request comes and it's necessary. So we could certainly remove some `final` and turn some `private` into `protected`.

Close to your need, you already have the capability to use relative callback urls with the `setEnableContextualRedirects` method (https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/IndirectClient.java#L205). In that case, the full callback url is computed based on the server name, scheme...

I guess you could use or extend this system. Just let me know.

**Comment by morungos** [comment]
Well, `setEnableContextualRedirects` doesn't actually happen for `OidcClient`, because it sets `isDirectRedirection` to true, so `setEnableContextualRedirects` never gets called. This is the problem I'm facing: there really seems to be no way to configure the OidcClient except by wiring the full callback URL explicitly, which makes configuration a problem. It admit I am more than a little confused about what a direct redirection is compared to a contextual one. 

I still think there's an issue with Clients, because it's a final class that's wired into the system. If it was an interface (best) or subclassable (OK) it'd be easier. I'm happy do make a PR to factor it into an interface, which feels right architecturally anyway.

And if you have any other smart ideas for a workaround, I still need one. Thanks for this help, though, I think I understand the issues better now.

**Comment by leleuj** [comment]
As you get into the code, things can look messy indeed.

We have two kinds of clients: `IndirectClient` refers to clients which need a redirection to an external provider (Facebook for example), `DirectClient` refers to client which receive credentials directly (JWT token passed to the url).

The concept of "direct redirection" is only valid for `IndirectClient`: to compute the redirection url to the external provider, it sometimes needs some external HTTP calls which may be useless. Imagine a login page with a form and a DB internal authentication and a "Log in with Facebook" button: I don't want to perform expensive computations just to display the right link in the Facebook button, so I don't want a direct redirection, I want an indirect one, and actually, the link points to the callback url with a specific parameter to say the redirection must be performed, it's a way to delay the external redirection link computation and save performance.

The code around the "contextual redirect" is not perfect, but I like the idea. So first, I would replace this "contextual redirect" logic by a `UrlStrategy` interface with a single method: `computeUrl(String callbackUrl, WebContext context)`. The first default implementation would be the `DefaultAbsoluteUrlStrategy` which checks it's an absolute url and returns it without any change.
You would need to create the `ServerRelativeUrlStrategy` where the `computeUrl` method code would come from `public String getContextualCallbackUrl(final WebContext context)`.
Finally, you could create your own `MyUrlStrategy`.

In the `OidClient`, you would need to replace the `getCallbackUrl()` by some `urlStrategy.computeUrl(getCallbackUrl(), context)`. However, there is a problem: we don't have a `context` available in the `internalInit` method, so maybe the signature should be changed with a  `Object context` input in the `init` method: this is a huge change though.

What do you think?

**Comment by morungos** [comment]
That sounds like it's heading in the same direction I ended up moving. I already added a redirection filter (I'm using Shiro with buji-pac4j) instead of a strategy, but the idea is similar: it finds the OidcClient and then creates the redirection needed. Because it's a filter it can send back a 302 to end up in at the right place. Anyway, all that works as I get out to the OIDC provider just fine. 

So I actually made a more improvised solution by writing my filter to include:

```
    protected URI fixRelativeCallback(HttpServletRequest httpRequest, URI location) throws URISyntaxException {
    	
    	List<NameValuePair> parameters = URLEncodedUtils.parse(location, "UTF-8");
    	for (ListIterator<NameValuePair> i = parameters.listIterator(); i.hasNext(); ) {
    		NameValuePair param = i.next();
    		if ("redirect_uri".equals(param.getName())) {
    			String value = param.getValue();
    			URIBuilder redirect = new URIBuilder(value);
    			if (redirect.getScheme() == null) {
    				redirect.setScheme(httpRequest.getScheme());
    				redirect.setHost(httpRequest.getServerName());
    				redirect.setPort(httpRequest.getLocalPort());
    				redirect.setPath(httpRequest.getContextPath() + redirect.getPath());
    				i.set(new BasicNameValuePair("redirect_uri", redirect.build().toString()));
    			}
    		}
    	}
    	
    	URIBuilder builder = new URIBuilder(location);
    	builder.removeQuery();
    	builder.addParameters(parameters);
    	return builder.build();
    }
```

This essentially patches the URI callback for a single request by adding in enough absolute information to generate a proper callback. No modifying the OidcClient at all. This avoids the need for the delegation of computing the relative callback in OidcClient in the absence of a context. 

I really don't know the nest solution, however, if it's this much effort to work around what is really a trivial issue (generating a URL which is relative to a request) then something is too strict in the framework and needs to be opened up a little.

**Comment by morungos** [comment]
Ah, OK. This won't cut it either, due to the additional requests sent. The client *really* needs the absolute callback, so the filtering is irrelevant. Scratch that previous solution. 

Right now, I'm not even sure there is a solution. Everything that I want to use as a hook is final. I think the only solution is a total clone + patch of OidcClient. Although technically I could subclass, I have to override 90% of the logic just to be able to wire in a change to the redirectUri, because it's private, read-only, initialized before a context is available, and not used through an accessor.

For now I'll just make a copy of OidcClient but I've had to spend a couple of days working through this. It should not be that hard.

**Comment by leleuj** [comment]
I opened two issues for what we said: https://github.com/pac4j/pac4j/issues/198 & https://github.com/pac4j/pac4j/issues/199 to keep track of our discussion.
