### ISSUE TITLE
Replace contextual callback by a UrlStrategy

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#198]
"
The code around the "contextual redirect" is not perfect, but I like the idea. So first, I would replace this "contextual redirect" logic by a `UrlStrategy` interface with a single method: `computeUrl(String callbackUrl, WebContext context)`. The first default implementation would be the `DefaultAbsoluteUrlStrategy` which checks it's an absolute url and returns it without any change.
You would need to create the `ServerRelativeUrlStrategy` where the `computeUrl` method code would come from `public String getContextualCallbackUrl(final WebContext context)`.
Finally, you could create your own `MyUrlStrategy`.
"

**Comment by leleuj** [comment]
See: https://github.com/pac4j/pac4j/issues/193

**Comment by mmoayyed** [comment]
:+1: Good idea.

**Comment by leleuj** [comment]
It should be close to the: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/http/DefaultAjaxRequestResolver.java

**Comment by chameleooo** [comment]
Hello Jérôme,

Do you have an ETA for this feature ?

**Comment by leleuj** [comment]
Version 1.9 is planned for March 2016.

But I have received several requests for this feature, so I'm likely to cut a 1.8.2 with that feature for end novembre.

**Comment by chameleooo** [comment]
It would be perfect.

**Comment by leleuj** [comment]
Here is the pull request: https://github.com/pac4j/pac4j/pull/349

**Comment by leleuj** [comment]
@chameleooo : any feedback on this?

**Comment by chameleooo** [comment]
I didn't try it yet. But it seems good. I may have time on Monday to try this. Did you intend to release a corresponding version of spring-security-pac4j ?

**Comment by leleuj** [comment]
Yes, with pac4j v1.8.1, you will have:
- j2e-pac4j v1.2.1
- spring-webmvc-pac4j v1.0.1
- spring-security-pac4j v1.4.0
- buji-pac4j v1.4.0
- play-pac4j v2.0.1

Releases are planned at the beginning of December.

**Comment by leleuj** [comment]
New PR: https://github.com/pac4j/pac4j/pull/365 to revert the `Clients` as an `InitializableObject` and not an `InitializableWebObject`.

The `Clients` holds a static configuration only depending on the callback url, it is not related to the web context while any `Client` is initialized during the first web request. Making the `Clients` object an `InitializableWebObject` is useless.
The dependence on the web context makes the `Clients` object a breaking change in the 1.8.x stream.

**Comment by chameleooo** [comment]
I'm trying to make it works but I saw that the callback url is still saved in the Client's service at the first call. In my case, I have multiple users who use my app using different adresses.
 
For example, for a saas service provider : client.saasprovider.com and service.client.com. In this example the first one who connects initialize the service and the other won't be able to login.

**Comment by leleuj** [comment]
Indeed, the initialization happens once and for all. You need another solution to be able to pick up the right clients for your users. I need more details to help you figure out a solution on this. Thanks

**Comment by chameleooo** [comment]
Why can't we just keep the relative callback URL in the `OAuthConfig` and resolve the full URL on-demand ?

**Comment by chameleooo** [comment]
You use a state parameter for some OAuth provider (like Google). Why is this needed ?

**Comment by leleuj** [comment]
Indeed, we rely on Scribe for OAuth protocol support. For performance reasons, the Scribe `Api` is only initialized once and there is only one instance. It's the most common use case.
That said, an implementation creating a new Scribe `Api` every time could certainly be developed.

The `state` parameter is a security measure: created and saved into session before redirecting to Google, returned after sucessful login to be checked against the one saved into session.

**Comment by chameleooo** [comment]
Indeed, I read in the google documentation that the state parameter could be used as a mechanism to protect from CSRF. But why did some providers use a state parameter and others don't ?

**Comment by leleuj** [comment]
I guess it's the way provider see security and the usefullness of this `state` parameter.

**Comment by chameleooo** [comment]
What if we parametrize the `requiresStateParameter()` of `Google2Client`. I made some tests and it doesn't seem to be a big deal.

What do you think about that solution ?

**Comment by chameleooo** [comment]
Here is why I did :
https://github.com/chameleooo/pac4j/commit/3ffc808672cb79916cb083f57963c4f7d5c9b5f1

**Comment by leleuj** [comment]
Sure. We can offer the option to disable it as long as it is enabled by default. Would you mind submitting a pull request for that?

**Comment by chameleooo** [comment]
Yes, I will work on that !

**Comment by chameleooo** [comment]
What do you think about the changes I made on `GoogleApi20`?

In my code, the `String getAuthorizationUrl(final OAuthConfig config)` method is exposed in both cases because `GoogleApi20` doesn't depend on the `Google2Client` and cannot know if the `state` param is used or not. Would you prefer that I create a new `GoogleApi20Stateless` ? This may duplicate the `AUTHORIZATION_URL`.

**Comment by leleuj** [comment]
The original source code is a bit hard to read, trying yo hack in the Scribe library. I need to upgrade the library by the way (https://github.com/pac4j/pac4j/issues/370).
I found your solution fairly elegant.

**Comment by chameleooo** [comment]
The corresponding PR : https://github.com/pac4j/pac4j/pull/372
