### ISSUE TITLE
Allow for arbitrary attributes on a profile

### ISSUE THREAD

**Issue by pledbrook** [pac4j/pac4j#207]
I'm currently working on an app that allows authentication through Twitter, Google and username/password. I want to attach any user that logs in through OAuth to a user instance in the database. My preferred way to link the two is through a custom attribute on the profile.

Unfortunately, it seems I can't do this because the attribute is ignored if it's not part of the attributes definition associated with that profile. I propose that pac4j allows any attributes to be added, even if they're not part of the attributes definition. It's then up to the developer to manage them.

**Comment by pledbrook** [comment]
I noticed that I could add the attribute I needed to `HttpProfile` without any problem because it didn't have an `AttributesDefinition`.

**Comment by leleuj** [comment]
You're right: the attributes definition really limits the attributes you can get, but it makes their retrieval easier: `getXX` (checked by compilation and IDE) instead of `getAttribute("XX")` (you may mispell the name of the attribute).

In your case, you could create a new profile and a new attributes definition because I'm sure this link is down by some custom code and you directly manipulate the user profile.

Though, I'm not against making extension easier. The first solution I'm thinking of is to add a global flag like `respectProfileDefinition` in the `ProfileHelper` (https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/ProfileHelper.java) you could turn off to allow more attributes (`true` by default). There might be better solutions.

I'm open to your contribution on this...

**Comment by pledbrook** [comment]
There are a few things to comment on here. First, if the attribute definitions are provided as a check on whether an attribute is known and valid, why not just add the corresponding setters on the profile classes? Sure, statically typed languages would require a cast, but I don't see why that would be a problem. Then the user would have auto-complete and no concerns about mistyping.

Second, the current code silently ignores attributes it knows nothing about. That leaves the developer very confused. I would prefer to see an exception here, such as `UnknownAttributeException`.

Third, I can't create a new profile as the `TwitterProfile` and `Google2Profile` are both created automatically. I'm using the Spring Security integration which doesn't provide an option to replace the current profile unless I write my own provider. So I'm relying on Groovy's ability to ignore visibility scopes to add the attribute.

I think my preferred solution is to allow arbitrary attributes by default and add setters to the profiles for known attributes. What do you think?

**Comment by leleuj** [comment]
You're right: let's keep the best of both worlds. Allow any attribute and convert / provide getter for defined attributes.

Would you mind providing a pull request for that?

**Comment by pledbrook** [comment]
I'll try but I can't get to it right away. Also, what tests should go with it?

**Comment by leleuj** [comment]
I guess the change is located in the `addAttribute` method of the `UserProfile` class: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/UserProfile.java#L85
So the test class should be updated accordingly: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/test/java/org/pac4j/core/profile/TestUserProfile.java#L45

**Comment by pledbrook** [comment]
You mention getters, but I suggested adding setters. That would mean updating existing classes like `TwitterClient` and `Google2Client` in pac4j-oauth. So do you agree with that part, i.e. adding setters?

On the test front, I take it there are no integration-style tests then?

**Comment by leleuj** [comment]
I was not mentioning getters (or maybe I was not clear ;-), but the `addAttribute` method which is dedicated to add an attribute: it's the method with the logic which must be changed.

**Comment by pledbrook** [comment]
> You're right: let's keep the best of both worlds. Allow any attribute and
> convert / provide _getter_ for defined attributes.

Sorry for being pedantic, but I want to make sure that we agree on exactly what changes should be made. I think in the above quote you meant to say "setter". Is that correct? If so, I will look at adding setters to some core `UserProfile` sub-classes.

**Comment by leleuj** [comment]
No problem.
Right now, if you take a look at the `addAttribute` method (the method which is used to add attribute to a profile) in the `UserProfile` class, you see that if no definition exists, the attribute is returned "as is" and if a profile definition exists, the attribute is converted. But if no converter exists (see the `AttributesDefinition` class), `null` is returned and that is the problem: attributes not present in the definition are lost.

So at first, I wanted you to change the `addAttribute` method, but there is an easier solution: in the https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/AttributesDefinition.java#L109, you should just return the `value` of the attribute and not `null` when no converter exists.

Does it make things clearer?

Of course, I could do the change by myself but I like to see people get involved on their idea.

**Comment by pledbrook** [comment]
I have quite a lot to work on for the next week or two at least, so this will be delayed.

**Comment by leleuj** [comment]
No problem.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/231
