### ISSUE TITLE
Upgrade to CAS client 3.4.1

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#213]
`pac4j-cas` module

Don't use version 3.4.0 (critical issue).

**Comment by mmoayyed** [comment]
:+1: we could probably upgrade to 3.4.1 snapshot.

**Comment by leleuj** [comment]
Yes, but we must of course have the 3.4.1 release be cut before pac4j v1.8 release.

**Comment by leleuj** [comment]
The 3.4.1 release is now available: http://search.maven.org/#artifactdetails%7Corg.jasig.cas.client%7Ccas-client-core%7C3.4.1%7Cjar

**Comment by mmoayyed** [comment]
I'll work on this. @leleuj do you have other issues for me to submit PRs for?

**Comment by leleuj** [comment]
This one can be addressed at the same time: https://github.com/pac4j/pac4j/issues/242

And when this issue will be fixed, we'll be able to close this one: https://github.com/pac4j/pac4j/issues/222 as well
