### ISSUE TITLE
SAML support is broken due to the use of the J2EContext

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#219]
Indeed, it only works in frameworks using the `J2EContext`, for others (like Sparkjava for which I just did the test), I get a `ClassCastException`.

The issue is here: https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/context/SAML2ContextProvider.java#L104

**Comment by leleuj** [comment]
@mmoayyed : I missed it but there is a big issue with the new SAML support because of the use of the `J2EContext`, I let you fix that.

**Comment by mmoayyed** [comment]
What is the use case here? Can you provide your test case with SparkJava plz?

I think that exists today because we need access to both the request and response which are part of J2EContext but I need a better a look at the code.

**Comment by leleuj** [comment]
In every implementation, there is a dedicated web context: `SparkWebContext`, `JavaWebContext` and `ScalaWebContext` for Play, `RatpackWebContext`... Only the j2e-pac4j and spring-security-pac4j libraries use the `J2EContext`.
So in every framework, a specific context is created which will generate a ClassCastException if you try to cast it to a J2EContext. In pac4j and its modules, you can only use the `WebContext` object.

You can see the issue pretty easily by running the demo on this specific branch: https://github.com/pac4j/spark-pac4j-demo/tree/pac4j-1.7.1
Click on the "Protected by SAML" link.

**Comment by mmoayyed** [comment]
I see. That is true, we need to move up the abstraction chain to use the generic `WebContext`. We also do need to move the request object there as well perhaps. Seems appropriate that a web context would carry a request.

**Comment by mmoayyed** [comment]
Starting work on this. Stay tuned.

**Comment by leleuj** [comment]
Great! There are always a lot of expectations on SAML.

**Comment by mmoayyed** [comment]
I did ask a question on the mailing list but didn't get a response; one thing I am very interested in is to evaluate our SAML support here to see what we can do enable an application to act as an IdP. Waiting for 1.8 to be released before I start work on that front.

**Comment by leleuj** [comment]
It's a huge twist for pac4j which has always been focused on **client** (not server) support.

**Comment by mmoayyed** [comment]
Good point. We may after all write the server components in CAS for example, etc, unless you plan to start a different project that focuses on server functionality :)

**Comment by mmoayyed** [comment]
By the way, WebContext has methods that wrap around Requests. Are there facilities to work with Responses?

**Comment by mmoayyed** [comment]
I would need abstract methods to set response headers, content types, encoding, and get the output stream. What is the best way to handle these?

**Comment by mmoayyed** [comment]
Looks like I may need to add a few more response-related methods to WebContext

**Comment by mmoayyed** [comment]
Redirect binding passing tests. Working on POSTs

**Comment by leleuj** [comment]
Response behaviours should be handled in the `WebContext`. Will rework the web context one day if it becomes unmanageable.
