### ISSUE TITLE
"file:" must be handled in SAML support

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#225]
Here: https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/metadata/SAML2IdentityProviderMetadataResolver.java#L86

**Comment by leleuj** [comment]
@mmoayyed : why did you close this one?

**Comment by mmoayyed** [comment]
Yes this is my bad. I assumed the issue was handled under #224.

**Comment by leleuj** [comment]
No problem.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/232
