### ISSUE TITLE
JWT Library?

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#226]
@leleuj I think JWT support in pac4j uses Nimbus right?

Have or had you also considered https://github.com/jwtk/jjwt?

**Comment by leleuj** [comment]
Yes, JWT support is based on Nimbus library. I have some trouble between OpenID connect support and JWT support because of the Nimbus libraries I assume. So it might a good way to go.

Will consider.

**Comment by mmoayyed** [comment]
I don't know much about Nimbus, but this seems dead simple to use, and is sort of backed by Les Hazelwood, whom I am sure you know.

**Comment by leleuj** [comment]
JWE (encryption) is not currently supported by this library: as we may have sensitive information in our user profile, we cannot only sign JWT.
So I don't think we can use this library.

**Comment by mmoayyed** [comment]
Thanks for the analysis. Sounds good.
