### ISSUE TITLE
Fix Javadoc

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#236]

**Comment by mmoayyed** [comment]
@leleuj can you elaborate a bit on this? when and how does javadoc fail? java 8 I assume is related?

**Comment by leleuj** [comment]
The Javadoc process does not fail, but if you run `mvn javadoc:aggregate`, there are several warnings to fix...

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/292
