### ISSUE TITLE
Fix integration tests

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#237]

**Comment by JacobASeverson** [comment]
I've opened a PR while I work through each of these failing integration tests because I'm noticing I'll have questions as I go. This will make it easy to highlight the code I'm talking about

**Comment by leleuj** [comment]
You haven't chosen the easiest way ;-) Fixing IT tests might be tricky!

**Comment by JacobASeverson** [comment]
I figure this is the easiest way to dive into the parts of the code I haven't seen yet while still doing something useful :-)

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/304
