### ISSUE TITLE
Create a LocalCachingAuthenticator

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#247]
For stateless use cases, the `Authenticator` may be called at each request. So it might be necessary to cache locally the result for the given credentials, to avoid any performance issue.

**Comment by mmoayyed** [comment]
How would you capture the result, if you have for example:

```
public class LocalCachingAuthenticator<T extends Credentials> implements Authenticator<T>
```

**Comment by mmoayyed** [comment]
assuming the authentication is delegated to something else. for example:

```
public class LocalCachingAuthenticator<T extends Credentials> implements Authenticator<T> {

    private Map<String, Object> cache;

    private final Authenticator<T> delegate;

    public LocalCachingAuthenticator(final Authenticator<T> delegate) {
        this.delegate = delegate;
    }

    @Override
    public void validate(final T credentials) {
        this.delegate.validate(credentials);

    }
}
```

**Comment by leleuj** [comment]
There might be an issue in the definition of the `DirectHttpClient` and `IndirectHttpClient`: both should have credentials inheriting from `HttpCredentials` (which may store a user profile). `TokenCredentials` and `UsernamePasswordCredentials` both inherit from `HttpCredentials`.

So I guess the cache should be a `Map<HttpCredentials, UserProfile>`: if no exception occurs, the credentials is saved with the associated user profile.

**Comment by leleuj** [comment]
Or maybe a `Map<HttpCredentials, Object>` would be enough where `Object` is `null` or another meaningless value. And the `equals` and  `hash` methods of the `HttpCredentials` would take into account the credentials values and the user profile identifier.

**Comment by leleuj** [comment]
@mmoayyed : in fact, there is an issue.

Here is my test:

```
private class OnlyOneCallAuthenticator implements UsernamePasswordAuthenticator {
  private int n = 0;
  public void validate(final UsernamePasswordCredentials credentials) {
    if (n > 0) {
      throw new IllegalArgumentException("Cannot call validate twice");
    }
    credentials.setUserProfile(new UserProfile());
    n++;
  }
}

@Test
public void testDoubleCalls() {
  final OnlyOneCallAuthenticator authenticator = new OnlyOneCallAuthenticator();
  final LocalCachingAuthenticator localCachingAuthenticator = new LocalCachingAuthenticator(authenticator, 10, 10, TimeUnit.SECONDS);
  final HttpCredentials credentials1 = new UsernamePasswordCredentials("a", "a", this.getClass().getName());
  localCachingAuthenticator.validate(credentials1);
  final HttpCredentials credentials2 = new UsernamePasswordCredentials("a", "a", this.getClass().getName());
  localCachingAuthenticator.validate(credentials2);
}
```

It throws an exception on the second call but it shouldn't, it should be taken from the cache, but the default `equals` should apply on references, not on the properties. Generating the `equals` and `hashCode` methods based on the `username` and `password` parameter makes the test pass.

Here is a PR to fix that: https://github.com/pac4j/pac4j/pull/275

What do you think?

**Comment by mmoayyed** [comment]
This makes sense. Equality should not be reference equality. Should always be based on fields. If we have classes that don't implement hashCode and equals(), equality will solely be determined based on object ref. I'll review the PR shortly.
