### ISSUE TITLE
Remove isAjax

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#248]
in favor of an automatic detection based on the X-Requested-With header.

Will open a discussion on the pac4j-dev mailing lists.

**Comment by leleuj** [comment]
https://groups.google.com/forum/?fromgroups#!topic/pac4j-dev/SQ5kmgQlsfY

**Comment by mmoayyed** [comment]
Good idea :+1:

**Comment by leleuj** [comment]
Pull requests:
https://github.com/pac4j/pac4j/pull/249
https://github.com/pac4j/j2e-pac4j/pull/19
https://github.com/pac4j/j2e-pac4j-demo/pull/17
https://github.com/pac4j/play-pac4j/pull/75
https://github.com/pac4j/play-pac4j-java-demo/pull/20
https://github.com/pac4j/play-pac4j-scala-demo/pull/19
