### ISSUE TITLE
IndirectBasicAuthClient logging ERROR on credentials exception

### ISSUE THREAD

**Issue by robgratz** [pac4j/pac4j#269]
I am new to using pac4j but am seeing a log message that doesn't seem like it should be shown as level ERROR.  In the retrieveCredentials(WebContext) method, there is a message logged at error when a CredentialsException is caught, but in my little experience with the library, this is an "expected" exception if the authentication header is not provided.  The way I am interpreting this functionality to work is the request is made without the header, an error is thrown requesting the header, then the request is made with it.  So, there shouldn't be an error message (and stacktrace) in the original request.  Apologies if I am not understanding the flow properly.

**Comment by leleuj** [comment]
You get it right. There might a glitch. From what I see, there is certainly a missing check on `null` credentials here: https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/client/indirect/IndirectBasicAuthClient.java#L88. I see it implemented in `FormClient` and `DirectHttpClient`.

What stack trace do you get? A `NullPointerException`?

**Comment by robgratz** [comment]
I am actually doing the null check in my Authenticator and if null, throwing BadCredentialsException.

**Comment by leleuj** [comment]
That use case is not properly addressed. you should return `null` instead of the `BadCredentialsException` and a `null` check should be added in the `IndirectBasicauthClient` and a `RequiresHttpAction.unauthorized("Requires authentication", context, realmName);` should be thrown.

Would you mind submitting a PR for that? Thanks

**Comment by robgratz** [comment]
Apologies, not very github literate yet.  Pull Request submitted.
