### ISSUE TITLE
Release pac4j 1.8

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#282]
I thought to mark the issue here so that we can keep track of timeline and discuss what might be left. Based on Github, I only see 3-4 issues remaining. @leleuj are there other items you are working on? Is there something I can work on?

**Comment by leleuj** [comment]
@mmoayyed  : thanks for proposing.

I will finish: https://github.com/pac4j/pac4j/issues/247 and https://github.com/pac4j/pac4j/issues/241 today. Then, we'll be good and I'll cut the RC1(likely this Thursday).

After or before the RC1, I'll fix the tests (https://github.com/pac4j/pac4j/issues/237, someone has already started some work on it) and the Javadocs (https://github.com/pac4j/pac4j/issues/236). Maybe we can upgrade the CAS server to version 4.1 as well (as it's now released): https://github.com/pac4j/pac4j/issues/179

So you can help on these issues or you can jump into new ones I planned for 1.8.1: https://github.com/pac4j/pac4j/issues/279, https://github.com/pac4j/pac4j/issues/278, https://github.com/pac4j/pac4j/issues/280 or https://github.com/pac4j/pac4j/issues/281

**Comment by mmoayyed** [comment]
>After or before the RC1, I'll fix the tests (#237, someone has already started some work on it) and the Javadocs (#236). Maybe we can upgrade the CAS server to version 4.1 as well (as it's now released): #179

Sounds great. Thank you. 

I'll review the issues you have for 1.8.1 and will pick ones I think I can help.

**Comment by leleuj** [comment]
@mmoayyed : as soon as I'll have released the RC1, one more thing you can help with is testing the j2e-pac4j and play-pac4j implementations...

**Comment by mmoayyed** [comment]
Sure thing.

**Comment by aratnam86** [comment]
@leleuj - When is 1.8 more likely to be released?

**Comment by mmoayyed** [comment]
next week Monday is probably the best bet I believe.

**Comment by leleuj** [comment]
Yes, we are waiting for one last feedback on https://github.com/pac4j/pac4j/issues/306

Likely on Monday.
