### ISSUE TITLE
SAML2 client not working if IdP is in different time zone

### ISSUE THREAD

**Issue by DanielVocke** [pac4j/pac4j#289]
Turns out the function that detemines whether a SAML2 authentication request is still valid does not take time zones into consideration.
```SAML2DefaultResponseValidator.isDateValid()``` returns false if the IdP is in a different time zone and leads to an invalid authentication request.

**Comment by DanielVocke** [comment]
as workaround until this is fixed, set the setMaximumAuthenticationLifetime to 24h:

```((SAML2DefaultResponseValidator) saml2Client.getResponseValidator()).setMaximumAuthenticationLifetime(24 * 3600 * 1000);```

it would probably be nice to expose that setter method on the interface as well in future...

**Comment by mmoayyed** [comment]
Thanks for the report. Looks like the time received is handled via joda time which should consider time zones, but the sp time is handled by system milliseconds which does not. I think both time instances should be based on jodatime to mitigate the problem.

**Comment by leleuj** [comment]
Thanks for reporting and the workaround. Would you mind proposing some PR to mitigate the problem?

**Comment by mmoayyed** [comment]
I'll put together a PR for this issue today.

**Comment by leleuj** [comment]
Thanks.
