### ISSUE TITLE
pac4j-oidc: NPE in OidcClient

### ISSUE THREAD

**Issue by aratnam86** [pac4j/pac4j#293]
In retrieveUserProfile method, if UserInfoEndpointURI is null, then userInfo would be null and would cause userInfo.toJWTClaimsSet() to throw NPE

**Comment by leleuj** [comment]
You're right: would you mind pushing a PR for that? Thanks

**Comment by aratnam86** [comment]
I am assuming you are mentioning about Pull Request when you say PR.
Also it seems I don't have enough permission to push my local changes through Git Desktop

**Comment by mmoayyed** [comment]
you should be able to push your changes to your own fork and submit a pull request from there. you don't push changes directly to pac4j.

**Comment by aratnam86** [comment]
PR #300 created
