### ISSUE TITLE
SAML support: NoClassDefFoundError: javax/servlet/ServletOutputStream

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#297]
When testing the SAML support with the https://github.com/pac4j/play-pac4j-scala-demo, I get the follwing error:

```
[ERROR] [10/01/2015 20:14:19.050] [application-akka.actor.default-dispatcher-3] [ActorSystem(application)] Uncaught fatal error from thread [application-akka.actor.default-dispatcher-3] shutting down ActorSystem [application]
java.lang.NoClassDefFoundError: javax/servlet/ServletOutputStream
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageSender.getMessageEncoder(SAML2WebSSOMessageSender.java:161)
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageSender.sendMessage(SAML2WebSSOMessageSender.java:74)
	at org.pac4j.saml.sso.impl.SAML2WebSSOMessageSender.sendMessage(SAML2WebSSOMessageSender.java:46)
```

Taking a look at the `Pac4jHTTPPostEncoder`, I see a (forgotten I imagine) reference to the HTTP servlet response: https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/transport/Pac4jHTTPPostEncoder.java#L14, which should be removed.

Maybe that explained the issue.

**Comment by leleuj** [comment]
FYI @mmoayyed

**Comment by mmoayyed** [comment]
will review.

**Comment by leleuj** [comment]
I took care of it: https://github.com/pac4j/pac4j/pull/305

It seems to be just references, but I need to test everything after all.

**Comment by mmoayyed** [comment]
This sort of thing I think can be prevented by adding checkstyle to the project, with a modest ruleset that caused build failures when unused imports are found.

**Comment by leleuj** [comment]
You're right: checking for unused imports would healp. Though, I'm not sure it's the problem here unfortunately.

**Comment by leleuj** [comment]
I see a `AbstractHttpServletResponseMessageEncoder` in the inheritance chain...

**Comment by mmoayyed** [comment]
You are right. Though we dont do anything with it, it seems to be referenced by the runtime. Shall we copy over the entire encoder config from parent classes and start from scratch? 

Sigh. Wish there was a better separation. I'll raise this issue with opensaml.

**Comment by leleuj** [comment]
Thanks for raising the issue on opensaml side. Yep, I'm trying to copy / paste what's needed to fix the problem...
I guess I will have the same problem for the `Pac4HTTPPostDecoder`...

**Comment by mmoayyed** [comment]
Created:
https://issues.shibboleth.net/jira/browse/OSJ-132

I suggest that you watch the issue and respond to comments Brent and others might have for you, since you are most familiar with the use case.

**Comment by leleuj** [comment]
After copy/pasting everything in the `Pac4jHTTPPostEncoder`, it works without changing the `Pac4jHTTPPostDecoder`: very strange! I think I will change both as well as the deflate encoder/decoder.

**Comment by leleuj** [comment]
The pull request to fix that: https://github.com/pac4j/pac4j/pull/310
