### ISSUE TITLE
pac4j-oidc: Single sign on failure

### ISSUE THREAD

**Issue by aratnam86** [pac4j/pac4j#298]
Even after successful oidc authentication, SSO fails because of technical exception caused by failure to find right client to handle the creds from the response

At present, retrieveCredentials method of OidcCleint return Oidc credentials without client name
```java
// Get authorization code
AuthorizationCode code = successResponse.getAuthorizationCode();
return new OidcCredentials(code);
```
resulting in following Exception
```java
org.pac4j.core.exception.TechnicalException: No client found for name: null
	at org.pac4j.core.client.Clients.findClient(Clients.java:119)
```

It could be fixed with the following code
```java
// Get authorization code
AuthorizationCode code = successResponse.getAuthorizationCode();

OidcCredentials creds = new OidcCredentials(code);
creds.setClientName(getName());
		
return creds;
```

**Comment by leleuj** [comment]
How do you get this technical exception? I've tested the OpenID Connect support with the latest j2e-pac4j and play-pac4j libraries and it worked.
In all cases, you're right: the client name should be saved with the credentials.

Would you mind sending a pull request for that?
I think the constructor should be changed to have two parameters: the code and the client name. To be sure none is forgotten.

**Comment by aratnam86** [comment]
The project that i am working on involves SSO by CAS which acts as server in most cases and client in case of a specific Oidc usecase.  CAS delegates authentication to pac4j-oidc first before trying to authenticate using CAS supported protocols. In this specific case, if client name is not specified, CAS tries to act as a server, even though it has successful authentication response from Oidc server.

PR #302 created.

**Comment by aratnam86** [comment]
Since I have changed the constructor parameters as you suggested, latest j2e-pac4j and play-pac4j libraries might have broken as the constructor has changed.

**Comment by leleuj** [comment]
OK. Thanks for sharing your use case. I don't expect any breaking change in the j2e-pac4j and play-pac4j libraries as they don't deal with `OidCredentials` directly.
