### ISSUE TITLE
pac4j-saml: Failure when verifying Recipient URL with default port in SAML response

### ISSUE THREAD

**Issue by jkacer** [pac4j/pac4j#299]
Pac4J 1.7.1 throws a validation error if a SAML response arrives with a value of SubjectConfirmationData/Recipient that does NOT contain a port number (because the default port is assumed). PAC4J compares the URL value against against a URL that always contains a port number.

I think this behavior is different from version 1.6.0.

Code responsible for the verification is in class  SAML2DefaultResponseValidator. In 1.6.0, it was class Saml2ResponseValidator.

See full discussion and details here: https://groups.google.com/forum/#!topic/pac4j-users/pfQQBu23_ME

**Comment by mmoayyed** [comment]
Can you update the metadata to remove the port?

**Comment by jkacer** [comment]
Misagh, the issue happens when the metadata does NOT contain the port. If I add the port (https://server:443/something) it works OK.

I could add the port everywhere but unfortunately we have our metadata already distributed for almost a year, so I would have to re-negotiate and re-test the system with all partner companies. That's almost impossible.

**Comment by leleuj** [comment]
So the real solution is to update the metadata which is not always practically possible. We could help and relax on the check of the port, some kind of improvement. Maybe it should be something we could enable or disable with a flag.

@jkacer : would you mind proposing a PR in that direction? We'll put in the 1.1.8 release (this Thursday) if possible.

**Comment by mmoayyed** [comment]
Yes exact-match comparisons would be a problem. The code should switch to URL comparisons.

**Comment by jkacer** [comment]
HI, here is the pull request:
https://github.com/pac4j/pac4j/pull/303

It ignores default ports for HTTP and HTTPS.


BTW, please have a look at SAML2DefaultResponseValidator:513
        // TODO Validate inResponseTo
I am pretty sure this TODO does not exist in 1.7.1/1.7.x anymore and there is a regular check of InResponseTo instead. This would mean that some code from 1.7.x did not get into 1.8.x.
We failed on this check several times last week with a partner company, that's why I remember it. They did not return InResponseTo; this passed fine with 1.6.0 but not with 1.7.1.
