### ISSUE TITLE
ParameterClient and release 1.8

### ISSUE THREAD

**Issue by pycloux** [pac4j/pac4j#314]
Hi All,

Quite a good idea to have added the ParameterClient to the HTTP module.
Question : we need it, please do you have a release date ?

Best regards,

PYC

**Comment by leleuj** [comment]
As you may have seen here: https://github.com/pac4j/pac4j/issues/282, the release was planned for yesterday but has been delayed to next Monday (one last check on SAML support must be made by someone and I've done today a fix on CAS support dependencies: https://github.com/pac4j/pac4j/issues/312).

So very very soon. I'll post a message on the mailing lists as soon as pac4j v1.8, j2e-pac4j v1.2 and play-pac4j v2.0 will be released.
