### ISSUE TITLE
Manage paths exclusion

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#315]
The default capabilities for path matching in implementations are generally too limited (in J2E or in Sparkjava), it would be great to be able to exclude paths (new `excludePath` parameter defined by a regexp: "^xxx$").

Let's create a `PathMatcher` and a  `DefaultExcludePathMatcher` which will be used by implementations.

**Comment by mmoayyed** [comment]
We could take inspiration from Spring's AntPathMatcher.

**Comment by leleuj** [comment]
That's an option, but in that case, I would need to copy/paste the `AntPatternMatcher` (from Spring). This is what Shiro did.
I was more thinking about using a regular expression which is more powerful, but forcing to use a full path matching expression (starting by `^` and ending by `$`) to avoid any security issue.

What do you think?

**Comment by mmoayyed** [comment]
Sure. That sounds simpler and more powerful.

**Comment by calvernaz** [comment]
Sorry for meddling, but as full path matching are you saying "/img/resource.png" or anything under "/img/" ?

**Comment by leleuj** [comment]
Both in fact. Anything you can describe with a regular expression: `^/img/resource\.png$` would only match your first example while `^/img/.*$`  would match both.

**Comment by calvernaz** [comment]
Oh of course I think I misread you! Great :+1:

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/318

Implemented for J2E: https://github.com/pac4j/j2e-pac4j/pull/25 & https://github.com/pac4j/j2e-pac4j-demo/pull/20
