### ISSUE TITLE
Dependency to Logback-Classic should have scope 'test'

### ISSUE THREAD

**Issue by jkacer** [pac4j/pac4j#317]
Project pac4j-saml has a dependency to logback-classic with the default scope (=compile). This may cause troubles if PAC4J is used in an application that does not use Logback and uses a different implementation of the SLF4J API (e.g. Log4J via the SLF4J-Log4J bridge).

I think this dependency should have scope = 'test' to be available during unit tests only. It should normally only depend on the SLF4J API. The actual logging library should be provided by the application using PAC4J.

What happened to me:
- PAC4J in CAS, which uses Log4J
- At startup, I got a warning about multiple SLF4J bindings available
- Logback got priority over Log4J
- I was not able to control logging using the usual log4j.xml file because Logback was used; there was no logback.xml in the application because it was initially set up for Log4J. By default, Logback sets all levels to DEBUG, which may not be appropriate.

**Comment by leleuj** [comment]
You're right: pac4j should only depend on slf4j and all concrete logging frameworks (logback, log4j) should be excluded so that the application can choose the appropriate logging library.

**Comment by mmoayyed** [comment]
:+1: :yum:

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/335

**Comment by jkacer** [comment]
Thanks :-)
