### ISSUE TITLE
Find / create a SAML online IdP for demos

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#328]

**Comment by mmoayyed** [comment]
you could try testshib, right? or is this a different matter?

**Comment by leleuj** [comment]
Yes, that's the matter. We partially use testshib and OpenFeide. The latter will be removed next year.
The first one is regularly broken mainly due to lost metadata.
So it would be great to have a SAML IdP without any issue.

**Comment by mmoayyed** [comment]
http://www.ssocircle.com/en/ could work

**Comment by mmoayyed** [comment]
we could deploy our own IdP on heroku. set up a Shibboleth IdP. perfectly doable.

**Comment by leleuj** [comment]
Thanks for the hint on this cloud provider (ssocircle). I almost forgot you are a specialist of Shibboleth: for WAR deployment, I would recommend OpenShift instead of Heroku. If you think you can do that easily, go ahead. We'll update all demos later on.

**Comment by mmoayyed** [comment]
What makes you prefer OpenShift better than Heroku? 

I have had a few issues with heroku as far as slug sizes and config, but everything else has been just fine.

**Comment by leleuj** [comment]
If I'm not mistaken, you need a wrapper to start a WAR on Heroku while it's straightforward with OpenShift. And Shibboleth, like CAS, must be installed as a Maven overlay, right?

**Comment by mmoayyed** [comment]
>And Shibboleth, like CAS, must be installed as a Maven overlay, right?

No it's very different. There is an installer script that you run that installs everything into an $IDP_HOME directory. There is no maven overlay. You get the entire package all at once. We have it dockerized though. Could use that to simplify things.

**Comment by leleuj** [comment]
So completely forget my advice ;-)

**Comment by leleuj** [comment]
What about onelogin and okta: they are SAML providers, aren't they? I saw that onelogin has a free plan.

**Comment by mmoayyed** [comment]
Sure they might work as well. 

I am working on adding saml2 web sso profile functionality to CAS. once that is done, I would think u can use that impl to test both pac4j and CAS via integration tests.

**Comment by leleuj** [comment]
We have many options, I think the easiest currently would be to use some free cloud SAML provider.

**Comment by leleuj** [comment]
I finally chose Okta.
