### ISSUE TITLE
Support for SAML authn extensions

### ISSUE THREAD

**Issue by afolgado** [pac4j/pac4j#329]
It looks like there's no way to customize the SAML authn requests, like adding Extensions like this:

	<saml2p:Extensions>
		<stork:QualityAuthenticationAssuranceLevel>3</stork:QualityAuthenticationAssuranceLevel>
		<stork:spSector>DEMO-SP</stork:spSector>
		<stork:spInstitution>xxxxx</stork:spInstitution>
		<stork:spApplication>DEMO-SP</stork:spApplication>
		<storkp:eIDSectorShare>true</storkp:eIDSectorShare>
		<storkp:eIDCrossSectorShare>true</storkp:eIDCrossSectorShare>
		<storkp:eIDCrossBorderShare>true</storkp:eIDCrossBorderShare>
		<storkp:RequestedAttributes>
			<stork:RequestedAttribute Name="http://www.stork.gov.eu/1.0/eIdentifier" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>
			<stork:RequestedAttribute Name="http://www.stork.gov.eu/1.0/givenName" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>
			<stork:RequestedAttribute Name="http://www.stork.gov.eu/1.0/surname" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>
		</storkp:RequestedAttributes>
		<storkp:AuthenticationAttributes>
			<storkp:VIDPAuthenticationAttributes>
				<storkp:SPInformation>
					<storkp:SPID>xxxxxxx</storkp:SPID>
				</storkp:SPInformation>
			</storkp:VIDPAuthenticationAttributes>
		</storkp:AuthenticationAttributes>
	</saml2p:Extensions>

or like choosing the issuer:

	<saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">xxxx</saml2:Issuer>

Is there any plans about implementing this feature? Thanks!

**Comment by mmoayyed** [comment]
There could be plans :) Not sure yet. Other priorities are taken over, but if you are willing to submit a PR, we'd be happy to take it.

**Comment by afolgado** [comment]
Ok, I'll try, but it looks complicated :)

Thanks.

**Comment by mmoayyed** [comment]
Do what you can, and we'll help you out.

**Comment by leleuj** [comment]
@afolgado : any update on this?

**Comment by Adrastos** [comment]
Yes, our IdP has recently provided us with custom integration libraries, and my organization has decided to go that way and not using pac4j-saml for now.

So priorities have changed and I can't dedicate any time on this right now.

Thanks for your support anyway.

**Comment by leleuj** [comment]
OK. Thanks.
