### ISSUE TITLE
pac4j-cas connection problem with self-signed certificate

### ISSUE THREAD

**Issue by xRomZak** [pac4j/pac4j#334]
I have faced SSL issue trying to integrate CAS REST client (pac4j 1.8).
As I've mentioned in the title I use self-signed certificate to communicate with CAS over HTTPS.

Previously I successfully used shiro-cas, where this problem was "solved" by custom `HttpURLConnectionFactory`/`AnyHostnameVerifier` which is passed as an argument to `org.jasig.cas.client.util.CommonUtils` to establish connections.

It seems that pac4j uses own utility class `org.pac4j.cas.util.HttpUtils` to establish connections and there is no ability to configure custom connection factory.

```java
org.pac4j.core.exception.TechnicalException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative names present
	at org.pac4j.cas.credentials.authenticator.CasRestAuthenticator.requestTicketGrantingTicket(CasRestAuthenticator.java:92)
	at org.pac4j.cas.credentials.authenticator.CasRestAuthenticator.validate(CasRestAuthenticator.java:67)
	at org.pac4j.cas.credentials.authenticator.CasRestAuthenticator.validate(CasRestAuthenticator.java:40)
	at org.pac4j.http.client.direct.DirectHttpClient.getCredentials(DirectHttpClient.java:70)
```

**Comment by leleuj** [comment]
I'm not sure why Misagh choose to create a specific `HttpUtils` class over the `CommonUtils` one from the CAS client, but I think it could be changed: @mmoayyed ?

@xRomZak : would you mind trying to jump into that issue and submit a pull request?

**Comment by mmoayyed** [comment]
CommonUtils I think ports over the apache http client, which seemed overkill for what we have here.

**Comment by leleuj** [comment]
Yes, we'd better avoid pulling such a dependency. @xRomZak : I guess you can somehow copy this behaviour on our current implementation.

**Comment by mmoayyed** [comment]
And since you are dealing with a self signed cert, I am not really inclined to support adding this type of feature, unless you have a better use case.

**Comment by xRomZak** [comment]
thanks for feedback. try to find a workaround.

**Comment by leleuj** [comment]
@xRomZak : what's the state of this? should we close it?

**Comment by xRomZak** [comment]
@leleuj you can close it. I have nothing to add.

**Comment by leleuj** [comment]
OK. Thanks

**Comment by juanjoDiaz** [comment]
@xRomZak did you find a workaround for this? Having the same issue.

My deployment is an intranet and it's mostly accessed directly through the IP (no DNS) so it's hard to get a valid certificate in place.
