### ISSUE TITLE
Account registration

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#339]
We certainly need a `ProfileWriter` for `LdapProfile`, `MongoProfile`... to create user accounts.

**Comment by leleuj** [comment]
Handle roles / permissions when saving / restoring the user profile.

**Comment by AzureusNation** [comment]
I would really appreciate if this could be squeezed in to 2.0. This would add so much more functionality and may more benefits for using this library.

**Comment by leleuj** [comment]
Yes, I'm considering this option more and more. We'll see after the RC2 release.

**Comment by leleuj** [comment]
@dfish3r :

As you may already know, pac4j uses Ldaptive to handle LDAP authentication (credentials validation): https://github.com/pac4j/pac4j/blob/master/pac4j-ldap/src/main/java/org/pac4j/ldap/credentials/authenticator/LdapAuthenticator.java

I'm currently working on enhancing the LDAP support by allowing the addition, modification and removal of a user in a LDAP.
I've started developing the user creation: https://github.com/leleuj/pac4j/blob/pac4j-339/pac4j-ldap/src/main/java/org/pac4j/ldap/profile/service/LdapProfileService.java#L74

I create a Ldap entry based on given attributes and save it in the LDAP using a `Connection` acquired from a `ConnectionFactory`. I followed the provided example: http://www.ldaptive.org/docs/guide/operations/add.html

Is this the right way to do things? Will it work for all LDAPs?
How can I set the password user? Like a regular attribute?

Thanks.

**Comment by dfish3r** [comment]
> Is this the right way to do things?

Looks ok, you might want to document that you don't support binary attribute values.

> Will it work for all LDAPs?

That's not a simple question. There are lots of ways to configure an LDAP that makes entry creation by an external client difficult. You should spin up a few test fixtures (OpenLDAP, ApacheDS, OpenDJ, etc) to confirm your code works, but know that authorization and schema will be brittle points in the process for your deployers.

> How can I set the password user? Like a regular attribute?

Yes.
Typically something like userPassword: {SHA}yP7QDr........rDhIw=

Also, I'm assuming none of your questions are asking about Active Directory :wink:

**Comment by leleuj** [comment]
Thanks for the feedback.

Sure. I'll take that into account in the documentation.

I've made it work for an embedded LDAP in my tests, so it's going to be mostly a base class for LDAP support. We'll see if adopters require / propose more specific implementations.
