### ISSUE TITLE
SAML2Client: direct or indirect redirection?

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#344]
I think that the `SAML2Client` should be defined with direct redirections.

**Comment by mmoayyed** [comment]
As I understand this, indirect clients work with a login form and redirection, while direct clients can be like rest where transactions don't require round-trip. Right? As such why would saml use direct?

**Comment by leleuj** [comment]
Ah! The concept of direct / indirect redirection has nothing to with the concept of direct / indirect client.

The redirection is direct if the client must redirect directly the user to the identity provider, it is indirect if the user is first redirected to the callback url then to the identity provider. This must be used if computing the redirection to the identity provider has a performance cost (like first calling the identity provider to exchange tokens or keys).
I assume that this is not the case for SAML, the redirection url to the identity provider can be computed without calling the identity provider.

Makes sense?

**Comment by mmoayyed** [comment]
>I assume that this is not the case for SAML, the redirection url to the identity provider can be computed without calling the identity provider.

Yes, true. Will review. Merci pour l'explication!

**Comment by mmoayyed** [comment]
So for this change, the direct redirection is defined via retrieveRedirectAction(), right?

**Comment by leleuj** [comment]
The redirection url (or POST form) is indeed computed by the `retrieveRedirectAction` method.

Here you see the logic where we choose which redirection url to return: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/IndirectClient.java#L126 If it's a direct redirection or if we target a protected url, we return the redirection url computed by the previous method. Otherwise, let's go first to the callback url and then to the identity provider: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/client/IndirectClient.java#L175

**Comment by millross** [comment]
This makes sense but is it documented anywhere? It confused me when writing vertx-pac4j (I’m fixing the relevant bug at present) so it would be good if this were documented in these terms. which are abundantly clear.

**Comment by leleuj** [comment]
You're right: there is some information in the Javadoc, but it's not enough: where do you expect to find those explanations?

**Comment by millross** [comment]
Do we have a wiki? Or general doc on configuring pac4j/writing new clients/understanding the terminology? It seems to me that anyone writing/submitting a new client should be aware of the difference as well as anyone writing a framework implementation. 

The difference between direct and indirect client made sense very quickly for me, but the subtle difference between direct/indirect redirection caught me out. If we have a doc outlining the difference between direct and indirect, then a logical place to cover the redirection distinction is in the section of that doc dealing with indirect clients.

**Comment by leleuj** [comment]
OK. I think I could add a "Create your own client" page in the wiki. I will do that...

**Comment by millross** [comment]
Nice one, and thanks. When I finish my fix on vertx-pac4j (actually I think I have the fix, but I want a test that exercises it and I’ve been playing around to define that test correctly, and minimally) I’ll be adding a comment in the vertx-pac4j framework around the code required so that the reason for that code is clear. The test will also let me ensure that I don’t regress :)

**Comment by leleuj** [comment]
I just added a new section: "Creating your own client" -> https://github.com/pac4j/pac4j/wiki/Clients#creatingyourownclient

**Comment by millross** [comment]
Awesome, thanks. I haven't gone through the wiki before so I will try to spend some time reading the whole wiki (in case there are other areas which might benefit from a link to that information).

**Comment by leleuj** [comment]
@mmoayyed : my final feeling is that the `SAML2Client` should perform direct redirections. Agreed?

**Comment by leleuj** [comment]
I've made tests (always the best way to understand) and things are not that easy: as SAML support POST binding, in that case, it cannot obviously a direct redirection.

**Comment by leleuj** [comment]
In the PR: https://github.com/pac4j/pac4j/pull/385

**Comment by mmoayyed** [comment]
Yes agreed.
