### ISSUE TITLE
Find / create a CAS server online for demos

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#352]
CAS users should not need to start a CAS server just for tests. username = pwd should be accepted for login and `https?://.*` should be defined fo services

**Comment by leleuj** [comment]
Deployed at Heroku: https://casserverpac4j.herokuapp.com

**Comment by mmoayyed** [comment]
and there already exists one by the CAS project. You really didnt have to do this :)

**Comment by leleuj** [comment]
You're right. I could have updated the configuration of our current deployed CAS server, but I guess it's meant to be deployed for every build (while I need something stable) or am I mistaken?

**Comment by leleuj** [comment]
And I wanted to test Openshift ;-)

**Comment by mmoayyed** [comment]
Not for every build but for every release. The only thing that it does not do is SSL which is a paid service :( does OpenShift offer that?

**Comment by leleuj** [comment]
Both (OpenShift and Jeroku) offer HTTPS urls, don't they?

**Comment by mmoayyed** [comment]
They do, but heroku's HTTPS is not free.

**Comment by mmoayyed** [comment]
see the warning https://jasigcas.herokuapp.com/login
