### ISSUE TITLE
Upgrade Dropbox support

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#362]
https://blogs.dropbox.com/developers/2015/11/dropbox-api-v2-launches-today/

**Comment by leleuj** [comment]
We'll stick to the DropBox support provided with Scribe.

**Comment by leleuj** [comment]
On June 28, 2017, API v1 will be turned off and the `DropBoxApi` has been removed from Scribe since version 2.6.0

**Comment by mmoayyed** [comment]
Related issue https://github.com/pac4j/pac4j/issues/608
