### ISSUE TITLE
IndirectBasicAuthClient says since 1.4.0

### ISSUE THREAD

**Issue by javazquez** [pac4j/pac4j#364]
https://github.com/pac4j/pac4j/blob/master/pac4j-http/src/main/java/org/pac4j/http/client/indirect/IndirectBasicAuthClient.java#L39

I used 1.7 and it was not there. Updating to 1.8 resolved my issue.

Thanks

**Comment by leleuj** [comment]
You're right: it's a bad copy/paste. Updated.
