### ISSUE TITLE
osgi import missing..

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#368]
I get error:
org.scribe.model.OAuthRequest cannot be found by org.pac4j.oauth_1.8.1.SNAPSHOT

missing import org.scribe.model

Also jar seems to include scribe packages so something also seems wrong there.

Please advise as to when this will be fixed.

Thanks

**Comment by leleuj** [comment]
Can you provide me more details on the expected configuration? Thanks

**Comment by garpinc** [comment]
I'm trying to figure it out.. I tried to use bundlor to figure out the right stuff and it claims a need for the following imports org.scribe.exceptions;version="0.0.0",org.scribe.services;version
 ="0.0.0",org.scribe.utils;version="0.0.0" which aren't in the scribe packages in the bundle but which most likely are referred to in some code in the packages that are. Which version of scribe did those packages come from and what is reason why they would be referring to those packages?

**Comment by garpinc** [comment]
I believe you need to include those missing packages from the version of scribe that were  included.. i.e: I see import org.scribe.exceptions.OAuthException; in org.scribe.extractors.Google2JsonExtractor.. Where is the codebase supposed to get that from? If I try to mix and match which bundles those packages come from I get Exception: Reason: Package uses conflict: Import-Package: org.scribe.exceptions

**Comment by leleuj** [comment]
The `pac4j-oauth` module has a `<Import-Package>*</Import-Package>` defined. Isn't it enough?

The `org.scribe` package comes the Scribe library. Maybe the `spring-security-pac4j` OSGI definition should be updated as well.

I don't have any OSGI container to make tests, I think the easiest for you is to checkout the source for `pac4j` and `spring-security-pac4j` and play with the OSGI configurations to find the right ones and then report back (as comments or pull requests). Thanks

**Comment by garpinc** [comment]
What I ended up doing is creating a new pac4j library for scribe by cloning 1.3.6 and then putting your modifications on top of it. Then I created manifest.mf using bundlor and this manifest file
[template.mf.txt](https://github.com/pac4j/pac4j/files/43229/template.mf.txt)

Finally I deleted all scribe packages from a clone of pac4j-auth and added following dependency to pom:
		<dependency>
			<groupId>org.scribe</groupId>
			<artifactId>scribe-pac4j</artifactId>
			<version>1.3.6</version>
		</dependency>


Now my feeling is why do we need to do any of this? Why are the new scribe classes in a pac4j scribe package. As I understand the conflict comes from trying to overlay code from the same package from two different sources. If it possible to just repackage the overrides?

**Comment by leleuj** [comment]
The classes in `org.scribe` in the `pac4j-oauth` module are extensions to the Scribe library. These classes are only meant to be internal so I think the best solution would be to rename the package in `org.pac4j.scribe` as you suggest and keep them in the `pac4j-oauth` module as they only relate to OAuth.

Can you submit a pull request for that? Thanks

**Comment by garpinc** [comment]
Unfortunately org.scribe.model.Response.Response(HttpURLConnection) is not a public method hence there is problem in ProxyRequest
Also:
org.scribe.model.Request.addHeaders(HttpURLConnection), org.scribe.model.Request.addBody(HttpURLConnection, byte[]) and org.scribe.model.Request.getByteBodyContents() are also not public presenting a problem for ProxyOAuthRequest

Later versions of scribe do have public constructor for Response and now there is an AbstractRequest that can be overridden.. I haven't even got pac4j working properly yet on my end with the jars I currently have. When I do I'll see if I can upgrade the scribe stuff but you might be better of doing that because you know what you were trying to accomplish.

**Comment by leleuj** [comment]
You're right: the `Scribe` library has changed a lot. We are at version 1.3.7, but the latest version is 2.0.0. I opened an issue for that: https://github.com/pac4j/pac4j/issues/370

Give it a try and if you don't succeed, ping me.

**Comment by garpinc** [comment]
As I said my work around was to separate the jars and make a new scribe jar with your modifications. That will do for now until 1.9 as far as i'm concerned.

**Comment by leleuj** [comment]
The plan is to update to Scribe 2.0 to be able to move Scribe-related modifications in a specific package (maybe library) and have proper OSGI defintions. It's targeted for version 1.9 because I'm currently working on the release unless someone submits the necessary pull requests (for 1.8.x).

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/461

**Comment by leleuj** [comment]
@garpinc : I just upgraded pac4j to Scribe 2.2. Specific Scribe components for pac4j are now in the `org.pac4j.scribe` package (https://github.com/pac4j/pac4j/tree/master/pac4j-oauth/src/main/java/org/pac4j/scribe). Should we upgrade the OSGI definition in the pom.xml file or is it enough?

**Comment by leleuj** [comment]
Assuming everything is ok. Feel free to re-open this one if you need some OSGI configuration update.
