### ISSUE TITLE
lack of XML External Entity Injection detection

### ISSUE THREAD

**Issue by wei-hai** [pac4j/pac4j#369]
in pac4j/pac4j-saml/src/main/java/org/pac4j/saml/transport/Pac4jHTTPPostDecoder.java, the method MessageDecodingException() does not detect potential "XML External Entity Injection" so that the hacker can easily uses the server to attack other computer, please throw SAXException when the injection is detected.

**Comment by leleuj** [comment]
There is no method named `MessageDecodingException` (only an exception): what method are you referring to? Would you mind submitting a pull request for this change? Thanks

**Comment by leleuj** [comment]
@wei-hal : any feedback on this?

**Comment by leleuj** [comment]
Closing this one as I don't get any feedback. Please reopen it if necessary.

**Comment by wei-hai** [comment]
in doDecode(), it shall throw SAXException if there is external entity in the message body to avoid external entity injection.

**Comment by mmoayyed** [comment]
This line:
https://github.com/pac4j/pac4j/blob/4dc9383ac54feaf0d7ec2de2d8013f92d1ceb9e7/pac4j-saml/src/main/java/org/pac4j/saml/util/Configuration.java#L63

Needs to be modified to include:
https://www.owasp.org/index.php/XML_External_Entity_(XXE)_Processing

```
String FEATURE = "http://apache.org/xml/features/disallow-doctype-decl";
      dbf.setFeature(FEATURE, true);

      // If you can't completely disable DTDs, then at least do the following:
      // Xerces 1 - http://xerces.apache.org/xerces-j/features.html#external-general-entities
      // Xerces 2 - http://xerces.apache.org/xerces2-j/features.html#external-general-entities
      FEATURE = "http://xml.org/sax/features/external-general-entities";
      dbf.setFeature(FEATURE, false);

      // Xerces 1 - http://xerces.apache.org/xerces-j/features.html#external-parameter-entities
      // Xerces 2 - http://xerces.apache.org/xerces2-j/features.html#external-parameter-entities
      FEATURE = "http://xml.org/sax/features/external-parameter-entities";
      dbf.setFeature(FEATURE, false);

      dbf.setXIncludeAware(false);
      dbf.setExpandEntityReferences(false);
```

**Comment by leleuj** [comment]
Thanks for the feedback. Would you mind submitting a PR for the fix

**Comment by leleuj** [comment]
Related: https://github.com/Jasig/cas/pull/1440

**Comment by mmoayyed** [comment]
Just to clarify this more, this is NOT a security vulnerability. According to the same OWASP doc, disabling DTDs takes care of all other attacks for the most part, which we do already. So this is a non-issue at this point though it does not hurt to include additional safety checks, which we have done now.
