### ISSUE TITLE
FacebookClient should have an appsecret_proof property

### ISSUE THREAD

**Issue by sbeitzel** [pac4j/pac4j#380]
Facebook allows a developer to select an option "Require app secret for server API calls". If this option is selected, then Facebook will refuse a request for profile info with an error, e.g.:

25317 [http-nio-8080-exec-8] DEBUG org.pac4j.oauth.client.BaseOAuthClient  - response code : 400 / response body : {"error"
:{"message":"API calls from the server require an appsecret_proof argument","type":"GraphMethodException","code":100,"fbtra
ce_id":"FFioji\/LajQ"}}

**Comment by leleuj** [comment]
"Require app secret for server API calls" means that the appplication secret needs to be passed along the access token to get the user profile, right?
Indeed, the `FacebookClient` should have an `appsecretProof` property and the appropriate getter and setter and send the application password when the property is `true`.

Would you mind submitting a pull request for this little change?

**Comment by sbeitzel** [comment]
Yes, I will do that. I made the change and verified that Facebook is happy with it, but I cannot say for sure that it is a complete solution since I still have not managed to complete an end-to-end run successfully.
