### ISSUE TITLE
Google2Client (OAuth): Not getting email addresses

### ISSUE THREAD

**Issue by AVGP** [pac4j/pac4j#382]
I am using pac4j-oauth to allow Facebook and Google Authentication. Facebook is working just fine and Google as well, but there's one thing that bothers me: I don't get the user email, even though it is requested.

Here's my code:

```java
  final Google2Client gClient = new Google2Client("KEY", "SECRET");
  gClient.setScope(Google2Client.Google2Scope.EMAIL); // also tried EMAIL_AND_PROFILE
```

then I see this in the logs:

```
root 2015-12-02 16:55:23,223 (DEBUG) [XNIO-1 I/O-2] : response code : 200 / response body : {
root  "kind": "plus#person",
root  "etag": "\"REDACTED\"",
root  "gender": "male",
root  "emails": [
root   {
root    "value": "REDACTED",
root    "type": "account"
root   }
root  ],
root  "objectType": "person",
root  "id": "REDACTED",
root  "displayName": "REDACTED",
root  "name": {
root   "familyName": "REDACTED",
root   "givenName": "REDACTED"
root  },
root  "url": "REDACTED",
root  "image": {
root   "url": "REDACTED",
root   "isDefault": false
root  },
root  "isPlusUser": true,
root  "language": "de",
root  "circledByCount": 6,
root  "verified": false,
root  "domain": "REDACTED"
root }
```

so the email is present as part of the `emails` array, but a few lines below:

```
root 2015-12-02 16:55:23,501 (DEBUG) [XNIO-1 I/O-2] : converted to => key : gender / value : MALE / class org.pac4j.core.profile.Gender
root 2015-12-02 16:55:23,501 (DEBUG) [XNIO-1 I/O-2] : converted to => key : displayName / value : REDACTED / class java.lang.String
root 2015-12-02 16:55:23,502 (DEBUG) [XNIO-1 I/O-2] : converted to => key : name.givenName / value : REDACTED / class java.lang.String
root 2015-12-02 16:55:23,503 (DEBUG) [XNIO-1 I/O-2] : converted to => key : name.familyName / value : REDACTED / class java.lang.String
root 2015-12-02 16:55:23,503 (DEBUG) [XNIO-1 I/O-2] : converted to => key : url / value : REDACTED / class java.lang.String
root 2015-12-02 16:55:23,504 (DEBUG) [XNIO-1 I/O-2] : converted to => key : image.url / value : REDACTED / class java.lang.String
root 2015-12-02 16:55:23,504 (DEBUG) [XNIO-1 I/O-2] : converted to => key : language / value : de / class java.util.Locale
root 2015-12-02 16:55:23,508 (DEBUG) [XNIO-1 I/O-2] : converted to => key : emails / value :  / class org.pac4j.oauth.profile.JsonList
```
Note the empty "value: " part when it converts the `emails` field.

This seems like a problem with pac4j-oauth somehow, but I'm not sure.
Any help is much appreciated - and if it should turn out to be a problem within pac4j-oauth, I'm grateful for any pointers on how to contribute a fix!

**Comment by leleuj** [comment]
The output (empty value) might be tricky as the configuration is done by default not to save the JSON raw value. Can you retest using `ProfileHelper.setKeepRawData(true)` and check the output? Thanks

**Comment by AVGP** [comment]
Thank you @leleuj for your super quick response!

So with your suggestion I am seeing this:

```
root 2015-12-02 17:19:45,519 (DEBUG) [XNIO-1 I/O-1] : converted to => key : emails / value : [{"value":"naumann@archilogic.com","type":"account"}] / class org.pac4j.oauth.profile.JsonList
```

but still the call for:

```java
StorageHelper.getProfile(exchange).getProfile();
```
returns

```
<CommonProfile> | id: REDACTED | attributes: {access_token=REDACTED, name.familyName=REDACTED, displayName=REDACTED, name.givenName=REDACTED, image.url=REDACTED, url=REDACTED} | roles: [] | permissions: [] | isRemembered: false |
```

I wonder right now if it's rather a problem in pac4j-undertow as the log suggests that pac4j-oauth gets the value right or am I misreading something?

**Comment by leleuj** [comment]
And you don't have anything returned by `profile.getEmail()`?

**Comment by AVGP** [comment]
Ah wait, no. That's a different problem and that's specific to our application.

I put it into the undertow-pac4j-demo and it works. It just didn't show up when the profile was stringified...

So this was a false alarm but you've been a huge help to me identifying the issue - thank you so much and again my apologies for taking your time!

**Comment by leleuj** [comment]
No problem. You're welcome.
