### ISSUE TITLE
pac4j-saml class loader issue

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#386]
In the org.pac4j.core.util.CommonHelper class in method org.pac4j.core.util.CommonHelper.getInputStreamFromName(String) it calls CommonHelper.class.getResourceAsStream(path);

I am running this is an osgi environment and hence this doesn't return anything.

Can you change this to 
Thread.currentThread().getContextClassLoader().getResourceAsStream(path);

This is a blocker on my end so if you could get this in snapshot build and let me know it would be awesome.. While you're at it instead or in addition to "resource:" can you allow spring's "classpath:" for consistency with the rest of my spring configuration.

Thanks,
Garry

**Comment by leleuj** [comment]
I plan to release pac4j v1.8.1 next week, so we need to do that before. And yes, we can add a "classpath:" support as well. Would you mind submitting a pull request for both changes? Thanks

**Comment by garpinc** [comment]
I will try.. Right now my priority is getting saml working and that's not going well as per my other ticket.

**Comment by leleuj** [comment]
Closing this one. Feel free to re-open it if necessary.
