### ISSUE TITLE
There seems to be a time issue with the saml auth.. Sometimes it works and sometimes it doesn't

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#391]
I get error: Authentication issue instant is too old or in the future.

Seems the root of it is this method
    private boolean isIssueInstantValid(final DateTime issueInstant) {
        return isDateValid(issueInstant, 0);
    }

I'm assuming it means either ssocircle or my computer is off but my pc is set automatically.. Seems there should be more tolerance here.

org.pac4j.saml.exceptions.SAMLException: Authentication issue instant is too old or in the future
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAuthenticationStatements(SAML2DefaultResponseValidator.java:627) [pac4j-saml-1.8.2-SNAPSHOT.jar:na]
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateAssertion(SAML2DefaultResponseValidator.java:393) [pac4j-saml-1.8.2-SNAPSHOT.jar:na]
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateSamlSSOResponse(SAML2DefaultResponseValidator.java:302) [pac4j-saml-1.8.2-SNAPSHOT.jar:na]
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validate(SAML2DefaultResponseValidator.java:150) [pac4j-saml-1.8.2-SNAPSHOT.jar:na]

**Comment by garpinc** [comment]
Or at least I should be able to modify the tolerance since I have no control over ssocircle

**Comment by garpinc** [comment]
I stand corrected.. The error appears to be happening even when validating authentication statements..

I put the following debug:
System.out.println("interval=" + interval + ",before=" + before.toDateTime(issueInstant.getZone())
					+ ",after=" + after.toDateTime(issueInstant.getZone()) + ",issueInstant=" + issueInstant);

and received:
interval=3600,before=2015-12-11T17:58:15.304Z,after=2015-12-11T16:54:15.304Z,issueInstant=2015-12-11T13:08:35.000Z

You can see that although I converted all times to to proper time zone it appears issueInstant is way off.. I was able to validate earlier but right now consistently the time is off..

**Comment by leleuj** [comment]
I have successfully tested pac4j-saml v1.8.1 with Okta, TestShib and OpenFeide.

Are you sure your SAML configuration is correct? Thanks

Otherwise, we'll link some demo with ssocircle to reproduce and fix the problem in a 1.8.2 version.

**Comment by garpinc** [comment]
It works fine if I increase interval (maxage) to 18000. So it's definitely a time issue. I live in Boston if that helps to reproduce. Ssocircle is testshib isn't it?

**Comment by leleuj** [comment]
I don't know: is there a way to setup a free ssocircle IdP to test?

**Comment by garpinc** [comment]
https://idp.ssocircle.com/sso/UI/Login

and select new user

**Comment by garpinc** [comment]
then you upload the sp metadata

**Comment by leleuj** [comment]
OK. I will do that for the Spring Security pac4j demo: it's the technology you use, isn't it?

**Comment by garpinc** [comment]
No actually I was just using it for testing and since it came up I wanted to point out the problem as I'm sure you will get others reporting the same. (It took me hours to figure out it was timing). My clients are on okta and ping federate..

**Comment by leleuj** [comment]
I just tested with ssocircle without any issue. See: https://github.com/pac4j/spring-security-pac4j-demo/commit/815995ae0962bab6d1b74197c71dae1803c28b02

**Comment by hugovalk** [comment]
ssocircle keeps your session alive for a very long time (like a day or so). Even when you have to fill in the captcha again, you still use the existing session. 

When you configure for example `samlConfig.setMaximumAuthenticationLifetime(1800)` when instantiating the saml2 client, you are basically saying that the session on ssocircle must not be older than 1800 seconds. 

When you get this error, log out in ssocircle and try again. If this solves your issue (it did for me) then configure the maximum authentication lifetime to match the session expiration time of ssocircle (I don't know how long that is).

**Comment by leleuj** [comment]
I'm not sure to follow you about the two different properties. The `maximumAuthenticationLifetime` sets the maximum lifetime of the SAML session on the IdP side while the pac4j authentication  lives as long as the web application lives.

**Comment by leleuj** [comment]
Closing this one. Feel free to re-open it if necessary.
