### ISSUE TITLE
Allow Clients to be extended

### ISSUE THREAD

**Issue by sbeitzel** [pac4j/pac4j#392]
`org.pac4j.core.client.Clients` is declared as `final` -- but why? In my application, I deploy the same WAR to different environments and apply environment-specific settings (such as URLs and connection strings) via an externally managed configuration file. For other classes that are part of our Shiro environment and which normally have such settings in shiro.ini, I simply extend the class and read and set the appropriate properties in the constructor. However, I'm unable to do this with Clients since, as noted, it's final.

Is there a good reason to make Clients final? If so, I'll just have to write some kind of property injector. If not, can we remove the final keyword from the class?

**Comment by leleuj** [comment]
The idea of `final` is to provide guidance on users and avoid them to override things as it's easy, before sharing their problem and looking for a cleaner solution if it exists. `Clients` being a container of clients, I assumed there were no use cases where you need to inherit from it.

Nonetheless, we have a first use case with dynamic clients loading (from database) in a "in progress" pull request.

So we can go that way. Would you mind submitting a pull request for that? It will likely go in a 1.8.2 version.

**Comment by leleuj** [comment]
@sbeitzel : I did the change via this PR: https://github.com/pac4j/pac4j/pull/404

**Comment by sbeitzel** [comment]
Cool deal. Thank you!
