### ISSUE TITLE
JwtAuthenticator uses the same secret for signing/encryption

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#393]
I would caution pac4j to not use a shared secret when dealing with JWT. There should be separate keys for signing and encryption. Was there a specific reason to use a shared key?

**Comment by leleuj** [comment]
"Making things easier", but it's not a good reason. I will add two secrets and deprecate the old one, for better security.

**Comment by mmoayyed** [comment]
Thanks. I would vote that we keep using the same secret that we have for both signing and encryption, if the encryption key is undefined. Just to sort of keep the same behavior. Encrypted keys are not always a requirement.
