### ISSUE TITLE
Add checkstyle / findbugs checks

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#402]

**Comment by mmoayyed** [comment]
So, how about I pick this up? Shall we use the same ruleset as CAS? or do you have another alternative?

**Comment by leleuj** [comment]
Thanks for proposing. @millross planned to work on that, first on vertx-pac4j then on pac4j. How about bootstrapping something on vertx-pac4j based on what we had on CAS?

I'm very reluctant with Checkstyle, but most Findbugs rules from CAS make sense for pac4j.

**Comment by leleuj** [comment]
@millross : any progress on this? My personal feeling is that if you lack the necessary time, you should rather focus on the asynchronous use of the new design of pac4j v1.9. I plan to do some exploratory work on that sooner or later.

**Comment by millross** [comment]
I've had no pac4j time at all, sorry (bar pushing a trivial update to vertx-pac4j to use 1.8.7). Work circumstances are pretty much preventing me from doing any side projects at present, I'm afraid :(

**Comment by leleuj** [comment]
Based on findbugs / PMD: https://github.com/pac4j/pac4j/pull/525
