### ISSUE TITLE
Init methods on the different Client's are not called

### ISSUE THREAD

**Issue by hugovalk** [pac4j/pac4j#410]
While trying to get the metadata for the `SAML2Client`, I noticed that the `init()` method on the `SAML2Client` is never called. 

The `init()` method of Clients.java is being called correctly. I would expect that in `Clients.internalInit()` the `init()` methods of all clients need to be called as well.

**Comment by leleuj** [comment]
Not exactly. The `init` method of the `Clients` does not call the `init(context)` of the clients.

The `init(context)` method of the clients are called implicitely when calling `redirect`, `getCredentials` or `getUserProfile`.
To get the SAML metadata, you need to explictely call the `init(context)` method of the `SAML2Client`.
