### ISSUE TITLE
Support setting/getting state parameter

### ISSUE THREAD

**Issue by Schlogen** [pac4j/pac4j#413]
Currently it's not possible to set the state parameter for OAuth 2 authorization URLs. I wouldn't mind submitting a PR, however I'd like to understand the reasoning behind the current implementation:

https://github.com/pac4j/pac4j/blob/master/pac4j-oauth/src/main/java/org/pac4j/oauth/client/BaseOAuth20Client.java#L70

Thanks!

**Comment by leleuj** [comment]
By default, the state parameter is generated in `getStateParameter` and you must say, by client, if the state parameter is required. Though, you could override this method and define it by yourself. The underlying Scribe API should also support state parameter to make the whole thing work.

Could you elaborate on `Currently it's not possible to set the state parameter`?

**Comment by Schlogen** [comment]
@leleuj Essentially I'm proposing to change the behavior of the BaseOAuth20Client to allow the user of the classes to set their own custom state data and then have the ability to retrieve it after the callback.

**Comment by leleuj** [comment]
I'm not against it, would you mind submitting a pull request to have a concrete implementation to talk about?

**Comment by Schlogen** [comment]
@leleuj Sure thing
