### ISSUE TITLE
Issue with CAS server URL starting with "login"

### ISSUE THREAD

**Issue by dkefer** [pac4j/pac4j#420]
When using a CAS server with URL starting with "login" (e.g. "login.example.com"), the library removes the string "login" when making the request to the CAS server in order to verify the token provided by client (i.e. it tries to connect to ".example.com").

Behaviour observed when using the following dependencies:

```
"org.pac4j" % "pac4j-cas" % "1.8.1-SNAPSHOT",
"org.pac4j" % "pac4j-core" % "1.8.1-SNAPSHOT",
"org.pac4j" % "play-pac4j-java" % "2.0.1-SNAPSHOT",
```

```
<dependency>
   <groupId>org.pac4j</groupId>
   <artifactId>spring-security-pac4j</artifactId>
   <version>1.3.0</version>
</dependency>
<dependency>
   <groupId>org.pac4j</groupId>
   <artifactId>pac4j-cas</artifactId>
   <version>1.7.1</version>
</dependency>
<dependency>
   <groupId>org.pac4j</groupId>
   <artifactId>pac4j-core</artifactId>
   <version>1.7.1</version>
</dependency>
```

**Comment by leleuj** [comment]
Notice pac4j v1.8.1 has been released (no more SNAPSHOTs).

I guess the problem is here: https://github.com/pac4j/pac4j/blob/master/pac4j-cas/src/main/java/org/pac4j/cas/client/CasClient.java#L269

Would you mind submitting a PR for that?

**Comment by dkefer** [comment]
Thanks, I created a PR with a fix which seems to work for me (I hope I understood the idea of that string replacement correctly).

**Comment by leleuj** [comment]
OK. Can you thus a simple test to check it works to protect us against any regression? Using your example...

**Comment by dkefer** [comment]
new PR...https://github.com/pac4j/pac4j/pull/421
