### ISSUE TITLE
Session is null

### ISSUE THREAD

**Issue by Schlogen** [pac4j/pac4j#435]
I'm currently having an issue where the getting of the state parameter from the session is returning null and failing the check on callback. Any ideas why that might be?

**Comment by Schlogen** [comment]
It seems like the names it was using to get the data were different. When the data was being set it was just "oauth". In the callback it was "Google2Client". Know why that might be?

**Comment by leleuj** [comment]
Very strange! I just tested it successfully on this demo: https://github.com/pac4j/spring-security-pac4j-demo
Either the name of the client is set explicitely or it's the name of the class (by default, in that case: "Google2Client").
Are you really sure about the "oauth" name?
