### ISSUE TITLE
Cannot build instance java.lang.ClassCastException: org.pac4j.oauth.profile.google2.Google2Email cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by aukevanleeuwen** [pac4j/pac4j#451]
I upgraded CAS 4.0.0 (bundled with pac4j 1.4.1) to CAS 4.0.4 (bundled with pac4j 1.7.0), but I have some issues with the Google2 integration.

Basically what I do is the following (first things are a bit CAS specific):
1. I authenticate with Google plus via the Clients (CAS pac4j integration)
2. When the AuthenticationHandler succeeds, but the PrincipalResolved doesn't (i.e. I don't have an account in my database that is linked to this particular social login) an exception is thrown by CAS with the principal information. I used to be able to to construct a `Google2Profile` from that information, but now it complains (see stacktrace).

I cannot figure out if I am using pac4j incorrectly or what is going on.

At some point a valid `Google2Profile` is constructed (during the authentication step (1)). This happens in `Google2Client#extractUserProfile(...)`:

```
@Override
    protected Google2Profile extractUserProfile(final String body) {
        final Google2Profile profile = new Google2Profile();
        final JsonNode json = JsonHelper.getFirstNode(body);
        if (json != null) {
            profile.setId(JsonHelper.get(json, "id"));
            for (final String attribute : OAuthAttributesDefinitions.google2Definition.getPrincipalAttributes()) {
                profile.addAttribute(attribute, JsonHelper.get(json, attribute));
            }
        }
        return profile;
    }
```

Here `profile.addAttribute()` is called with some sort of `json` representation (jackson I believe). 

However later on at step (2) I'm trying to use `ProfileHelper.buildProfile` to reconstruct the profile given the ID and a map of attributes (see the signature). This will construct a new instance of a `Google2Profile` and use the instance method `#build(id, attributes)` to fill the user profile with the correct information. 
Now at that point I'm feeding the `ProfileHelper.buildProfile` method with a map of attributes that are already converted (?) - this used to work in 1.4.1. At that point I'm not feeding it a map of jackson Json representations. Screenshot of some of the items that I feed that method:

![image](https://cloud.githubusercontent.com/assets/301092/12424079/d56a2ba2-bece-11e5-862e-31978960c3d9.png)

As you can see the the attributes are already converted to the pac4j domain, specifically a `JsonList` of `Google2Email` items. Now if you follow the stacktrace below you can see that when calling `ProfileHelper.buildProfile` the attributes are converted again and apparently somewhere in JsonList it assumes that if a list is fed, it will be a `List<String>` whereas the actual argument to that convert is a `List<Google2Email>`.

Am I using it wrong? It used to work? Any suggestions?

```
19.01.2016 16:17:30 ERROR [org.pac4j.core.profile.ProfileHelper] Cannot build instance
java.lang.ClassCastException: org.pac4j.oauth.profile.google2.Google2Email cannot be cast to java.lang.String
	at org.pac4j.oauth.profile.JsonList.<init>(JsonList.java:68)
	at org.pac4j.oauth.profile.converter.JsonListConverter.convert(JsonListConverter.java:45)
	at org.pac4j.oauth.profile.converter.JsonListConverter.convert(JsonListConverter.java:31)
	at org.pac4j.core.profile.AttributesDefinition.convert(AttributesDefinition.java:107)
	at org.pac4j.core.profile.UserProfile.addAttribute(UserProfile.java:90)
	at org.pac4j.core.profile.UserProfile.addAttributes(UserProfile.java:107)
	at org.pac4j.core.profile.UserProfile.build(UserProfile.java:63)
	at org.pac4j.core.profile.ProfileHelper.buildProfile(ProfileHelper.java:84)
	at nl.nrc.rs.web.flow.ExtractUserProfileFromPrincipalExceptionAction.getUserProfile(ExtractUserProfileFromPrincipalExceptionAction.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
```

**Comment by leleuj** [comment]
The  `ProfileHelper.buildProfile` has been created to be used in CAS applications side, not in the CAS server itself.
I have tested it successfully a long time ago but in version 1.9 (next one), I have fully rebuilt this "CAS serialization" and it works again with Google using OAuth 2.0 protocol. And it seems that the `Google2Client` has not changed between 1.4 and 1.9.

You should be able to use authentication delegate in CAS without specifying any principal resolver. See the demo: https://github.com/leleuj/cas-pac4j-oauth-demo/blob/4.0.x/cas-pac4j-oauth-client-demo/src/main/webapp/WEB-INF/deployerConfigContext.xml#L64

**Comment by aukevanleeuwen** [comment]
OK... that last point I knew but it was not really relevant for my use case (I think). But for the background information here is the use case:

1. I authenticate with the `org.jasig.cas.support.pac4j.authentication.handler.support.ClientAuthenticationHandler` with some social network
2. I look up the account that is linked to the successfully (via social network) logged in user. 
3. *If* the principal resolving failed, that means that I don't have an account for this social network user and I present the option to create an account based on this social network user (own CAS webflow implementation).

The way I implemented (3) was to see if an `org.jasig.cas.authentication.UnresolvedPrincipalException` was thrown and trying to reconstruct a `UserProfile` from that data. In pac4j 1.4.1 I could use the attributes that were stored on the principal (extracted from the exception) to recreate the profile using `ProfileHelper.buildProfile()`, but in 1.7.x this apparently doesn't work. 

How would I get a hold of the actual (succesfully logged in) `UserProfile` in my (extended) CAS webflow in such a case. Any pointers perhaps?

**Comment by leleuj** [comment]
I'm not sure why it worked, I would need to investigate. Because it's meant to work only after all attributes has been turned into strings (through the service tickets validation).
Here is how the CAS service ticket validation is simulated from an application point of view: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/test/java/org/pac4j/core/client/RunClient.java#L88

In that case, I would adapt attribute by attribute if necessary. Take the emails and turn the list of `Google2Email` into a list of  `String` by calling the `toString()` method.

**Comment by aukevanleeuwen** [comment]
It works, but it feels very brittle. But maybe it isn't because it's designed to work exactly this way. I.e. can I rely on the fact that if new attributes are added by external providers (Google, Twitter, Facebook) that the conversion of the attributes with `.toString()` is exactly that which I need to do to be able to call `ProfileHelper.buildProfile()`?

I can't think of a lot of other options. One thing I can think of is in my `PrincipalResolver` I return either some sort of a 'full principal' or a 'partly logged in' principal, which I then in my webflow later on use some sort of `instanceof` on. Is that a more proper way?

**Comment by leleuj** [comment]
It's a work around as this mechanism was not intented for your use case. I think it could be more easily handled with version 1.9 though, I will take a closer look.

It's not exactly an always-`toString` mechanism: when you have a list, the `toString` method must be called for each element to build a new list.

When you get your `UnresolvedPrincipalException`, do you have access to the credentials as the user profile is stored in it?

**Comment by aukevanleeuwen** [comment]
No, I lose the credential somewhere in `org.jasig.cas.authentication.PolicyBasedAuthenticationManager#authenticate()`:

```
        final AuthenticationBuilder builder = authenticateInternal(credentials);
        final Authentication authentication = builder.build();
        final Principal principal = authentication.getPrincipal();
        if (principal  instanceof NullPrincipal) {
            throw new UnresolvedPrincipalException(authentication);
        }
```

AFAICT the builder only has the principal (or the `NullPrincipal` by default), but the credentials are lost here. Looking at this I might subclass `PolicyBasedAuthenticationManager` and override `authenticateInternal()` to return an `AuthenticationBuilder` that will `build()` an `Authentication` that does have access to the credentials.. but that too feels rather messy.

Btw: I did make the exception for lists as did the code that you referenced earlier. Just not sure if I ever get a `Map` or a `Set` back or some other datastructure that I didn't anticipate.

**Comment by leleuj** [comment]
No `Map`, nor `Set` are returned for OAuth support.

**Comment by leleuj** [comment]
I just added this "profile auto-rebuild" capacity: https://github.com/pac4j/pac4j/pull/455

**Comment by aukevanleeuwen** [comment]
Thanks for the effort. It's probably going to take some time before it'll land in CAS I suppose. I'll stick with the workaround for now.

**Comment by leleuj** [comment]
You're welcome. pac4j 1.9 will likely go in CAS server 4.3.
