### ISSUE TITLE
Handle RSA and Eliptic curve signing for JSON Web Tokens

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#454]
I propose the following implementation:
- a `JwtSignature` interface with the `getSigner()` and `getVerifier()` methods
- a `HMACSignature` for HMAC signature
- a `ECDSASignature`  for Eliptic Curve signature
- a `RSASignature` for RSA signature

`*Signature` classes being used to build the `JwtGenerator` and `JwtAuthenticator`.

**Comment by garpinc** [comment]
Oh no.. I just ran into this error: Unsupported JWS algorithm ES256, must be HS256, HS384 or HS512

How soon before it is implemented?

**Comment by leleuj** [comment]
Planned for 1.9.1 so after the 1.9 release for which I must first finish: https://github.com/pac4j/pac4j/issues/558. That said, it could perfectly go into 1.9.

There are some other issues related to JWT support as well: https://github.com/pac4j/pac4j/issues/567, https://github.com/pac4j/pac4j/issues/568, https://github.com/pac4j/pac4j/issues/569 and https://github.com/pac4j/pac4j/issues/570.

The signers are different for the different family of encryption methods (ES, HS). The nimbusds jose library already supports all, but the pac4j JWT support must be changed to take that into account, which is feasible with various configurations (which I called `Signature` in my proposal above).

This is something you could perfectly work on and contribute to pac4j, if you find some free time.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/621

Signature and encryption configurations are now available: https://github.com/leleuj/pac4j/tree/pac4j-619/pac4j-jwt/src/main/java/org/pac4j/jwt/config
