### ISSUE TITLE
Null pointer exception serializing OidcProfile

### ISSUE THREAD

**Issue by baxterj** [pac4j/pac4j#458]
We have a problem using a shared session store with Pac4j oidc. There is a null pointer exception when Serializing OidcProfile.BearerAccessTokenBean,

The issue occurs in the toBean method, 

    public static BearerAccessTokenBean toBean(final BearerAccessToken token) {
            return new BearerAccessTokenBean(token.getValue(),
                    token.getLifetime(), token.getScope().toStringList());
    }

but at this time I am not sure if token is null or token.getScope() is null. I suspect the latter. @mmoayyed I know you worked on this previously, which do you think it might be? Would it be ok to use `null` in place of the null token / null scope list?

I will try to get this work planned in to our project, but in the mean time the issue is here if anyone else needs to work on it.

**Comment by leleuj** [comment]
Which version of the library do you use? If I remember well, it has been fixed in the latest 1.8.x.

**Comment by baxterj** [comment]
I think the code to do the actual serializing happened for 1.8, but I am experiencing trouble with that code. The original work is here I believe https://github.com/pac4j/pac4j/issues/194

**Comment by leleuj** [comment]
Yes, here is the fix I did for version 1.8.3: https://github.com/pac4j/pac4j/commit/00ac2e17d65ae3904e17e77db0e4a36a67e3f95b

Can you try this version and report if it solves the problem? Thanks

**Comment by baxterj** [comment]
Ah we're on 1.8.2.  Perfect, thanks for your time as always

**Comment by baxterj** [comment]
This issue has not been resolved. We still had the issue in our system and I have managed to reproduce locally by manually invoking a serialization of the SecurityContext. During authentication, OidcProfile#clear() is called, which sets the bearer access token to null, causing a NPE on the new first line of BearerAccessTokenBean#toBean...

OidcProfile.clear() line: 95    
ClientAuthenticationToken.eraseCredentials() line: 96   
ProviderManager.authenticate(Authentication) line: 210  

I understand this clearing to be a necessary part of authentication, so I will submit a patch to OidcProfile that properly handles (de)serialization cases where the access token is null.

**Comment by leleuj** [comment]
OK. Thanks. Can you please send patches for branch 1.8.x and master? I'll release a 1.8.6 version for this fix.

**Comment by baxterj** [comment]
We are using spring-security pac4j, so if you are able to release that as well with 1.8.6 it would be greatly appreciated

**Comment by leleuj** [comment]
Yes, a release 1.8.6 is planned: currently, there are two other open issues (related to CAS): they will be tested and merged soon and then, I'll cut a release, likely next week.

**Comment by leleuj** [comment]
@baxterj : I just released pac4j v1.8.6.

**Comment by baxterj** [comment]
Hi jerome, thanks for that. Would you be able to cut a version of spring-security-pac4j with 1.8.6?

**Comment by leleuj** [comment]
I can, though you can already use spring-security-pac4j 1.4.1 with any 1.8.x (and especially 1.8.6) version of pac4j.

**Comment by baxterj** [comment]
Ok, I guess it should work. I should be able to fiddle my pom to use the new release within spring-security-pac4j as a transitive dep.

**Comment by leleuj** [comment]
Exactly. Releasing all pac4j implementations would take a lot of time while we guarantee the backward compatibility for all 1.8.x versions.
