### ISSUE TITLE
Add a DirectFormClient

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#468]
The need arises to secure the /accessToken endpoint for the OAuth server support of the CAS server.

**Comment by mmoayyed** [comment]
+1

**Comment by leleuj** [comment]
PR for 1.8.x: https://github.com/pac4j/pac4j/pull/469

**Comment by leleuj** [comment]
The PR for 1.8 must be validated in the new OAuth server support for CAS. Then, I'll issue the same for the master branch.

**Comment by leleuj** [comment]
PR for master: https://github.com/pac4j/pac4j/pull/478
