### ISSUE TITLE
Trim client names

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#476]
Match names ignoring case as well.

**Comment by BatteryAcid** [comment]
Elaboration: 
`@RequiresAuthentication(clientName = "HeaderClient,AnonymousClient")`
A space between the comma and AnonymousClient seems to cause some breaking issues.
Thanks for tracking!

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/511
