### ISSUE TITLE
Don't include default port on https

### ISSUE THREAD

**Issue by jonathanlabin** [pac4j/pac4j#480]
In https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/http/RelativeCallbackUrlResolver.java#L36 the port number will be inserted into the URL even if it is the default HTTPS port.  This logic should really be of the form:
If ((http AND port != DEFAULT_PORT) OR (https AND port != DEFAULT_HTTP_PORT))

The corresponding DEFAULT_HTTP_PORT constant would also need to be created in https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/context/HttpConstants.java

**Comment by leleuj** [comment]
You're right. I just saw your PR: https://github.com/pac4j/pac4j/pull/481 which I'm going to review carefully.

**Comment by leleuj** [comment]
Your PR targets the master. I think it would be great to also fix this for the 1.8.x branch (in another pull request), so that we can include this fix in the 1.8.6 release.

In any case, many thanks for your help!

**Comment by jonathanlabin** [comment]
Sorry, new to this.  To also fix 1.8.x branch do I branch the 1.8.x repo and manually re-apply the same changes there or is there a more correct way starting from this bugfix branch that is targeting master?

**Comment by leleuj** [comment]
Generally, you can cherrypick (git command) the appropriate commit. That said, it might be tricky and we expect a slightly different solution in both branches. So the easiest way for you is to re-apply and update changes.

**Comment by jonathanlabin** [comment]
I didn't notice the need for a different solution between the branches (unless I missed something) but I still re-applied the changes manually since there are just a few.

**Comment by leleuj** [comment]
I was wrong indeed, same solution for both branches. Thanks.

It will go in the 1.8.6 release.
