### ISSUE TITLE
oidc override response_type

### ISSUE THREAD

**Issue by Raffiki** [pac4j/pac4j#492]
Response Type for OpendID Connect is set to `code` by default. What's the preferred way of overriding this? I need it to be `id_token`

https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/client/OidcClient.java#L251

**Comment by leleuj** [comment]
Currently, you can't easily change that value, but it should be feasible: there should be a setter and a getter for the response type.
Would you mind submitting a pull request?

**Comment by mmoayyed** [comment]
I think this change deals with the implicit flow. Does the client here officially support implicit, assuming that parameter name is changed?

**Comment by mmoayyed** [comment]
I also don't think the change is feasible in the long turn because there are other flows like hybrid where you could expect both code and id token.

**Comment by leleuj** [comment]
@mmoayyed : you raise a good point, but I think the change is feasible. Though, it's not just about changing the sent `response_type`, the whole `OidClient` must be changed as well.
For example, for the hybrid flow (and maybe we should only target this new one and define the `response_type` as an enum), in the `getCredentials` method, we should not expect a `code`, but directly an `access_token`and an `id_token`.

**Comment by mmoayyed** [comment]
Sounds good.

Have you tested the OidClient for implicit flow? I am looking around for possible test clients and have not found any that support this flow. With the changes for the issue, could I assume it'd be safe to use it for implicit?

**Comment by leleuj** [comment]
Currently, it won't work as a code is expected on the callback (and the implicit flow will return the access token and the id token), but I'm confident it could work with the appropriate changes.
Exactly like for the `CasOAuthWrapperClient` which does not currently support implicit flow, but could be changed to meet that requirement.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/627

**Comment by akram** [comment]
Hi guys,

it looks like this issue is saved, but I still can't figure out how to use implicit flow with it.
Any pointer, even with CasOAuthWrapperClient ?

**Comment by leleuj** [comment]
The `CasOAuthWrapperClient` supports the OAuth protocol while this issue refers to the OpenID Connect protocol. Or you meant `CasOidcWrapperClient`?

Here is an example for the implicit flow: https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/test/java/org/pac4j/oidc/run/RunIdentityServer4.java#L66
