### ISSUE TITLE
Allow UserProfile to note its Authencator

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#501]
Provide a way for the UserProfile abstraction to return back the authenticator that created it. This could be just the name of the client perhaps, or the authenticator class name, or the actual instance of the authenticator.

**Comment by leleuj** [comment]
Yes, we certainly want to know from the profile comes from.

**Comment by leleuj** [comment]
Addressed by: https://github.com/pac4j/pac4j/pull/520/files#diff-70ab4514de9ee2566aaa7a1a95b83a7eR61
