### ISSUE TITLE
allow PropertiesConfigFactory to support more than one client of the same type

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#522]
Introduce enumerable properties into the factory so it's able to work with "twitter.id.1" for instance.

**Comment by leleuj** [comment]
I don't think you want multiple Twitter instances, do you? Maybe your think more about SAML or CAS... It seems like an rare use case, isn't it?

**Comment by mmoayyed** [comment]
That was just an example, but probably it makes less sense to allow multiple twitter or FB accounts. SAML and CAS, definitely. I am dealing with a case now where the client wishes to delegate to 2 external CAS instances :)

**Comment by leleuj** [comment]
OK. That's a real example. But we could go so much further. For basic scenarios, the `PropertiesConfigFactory` does the job, but we should certainly propose some advanced configuration capability, like a groovy class (inhering from ConfigFactory) loaded on the fly...

**Comment by mmoayyed** [comment]
Yeah good idea; although it'd be best if the client/me really didnt have to start creating beans. That's a pattern I want to get away from. It would be nice when I need it, whether that is in XML or Groovy, etc but I really don't want to do the work :)
