### ISSUE TITLE
1.9 Release

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#533]
A quick survey of issues shows that 1.9 is almost complete. Is there anything left before a release can be cut?

**Comment by leleuj** [comment]
You're right: most of the work has been done for 1.9, though the upgrade of the J2E and Play implementations are revealing some improvements (like this one: https://github.com/pac4j/pac4j/issues/530 for re-usable tests across implementatios or this one: https://github.com/pac4j/pac4j/issues/528 to support more use cases) I'm adding along the way.
