### ISSUE TITLE
Add the ability to set a default client

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#535]
In garry fork ba3c351:

	private Client defaultClient;
In findClients:
		if (name == null && defaultClient != null) {
			return defaultClient;
		}

	public void setDefaultClient(Client defaultClient) {
		this.defaultClient = defaultClient;
	}

**Comment by leleuj** [comment]
What use cases do you want to address with that change?

**Comment by garpinc** [comment]
The use case is a client that wants to authorize at a particular url with a username and password. The client already exists and i'm modifying pac4j to suit but the client doesn't know about the clientName parameter and I don't want to have to change all the clients.

**Comment by leleuj** [comment]
I'm sorry but I don't understand. Currently, the `findClient(context)` is only used in the callback filter and the callback url is called with a `clientName` parameter after authenticating at a remote provider.
I don't see when this `findClient` method is called without any `clientName`.

**Comment by garpinc** [comment]
Although within the framework that is true nothing prevents an external application from making a request to the callback url. In my case I have a third party app that attempts to authenticate at /someurl with some_username and some_password and I want the one callback url to service authentications from both within the framework an this type of authentication. That third party app doesn't know about clientName but obviously I want it to use the formClient.

**Comment by leleuj** [comment]
The callback url must be called with a `client_name` otherwise, an error is returned. If you have a third app which posts credentials on your app, you certainly shouldn't use the app login page but provide a specific endpoint.

**Comment by garpinc** [comment]
Isn't the whole idea of security to reduce number of attack vectors?

**Comment by leleuj** [comment]
I'm not sure to understand what the security issue you try to highlight here. The callback url should always be called with a `client_name` parameter. It's the behaviour. All other use cases lead to an error.
In your case, I think there is a better way to define your security configuration.

**Comment by garpinc** [comment]
I'm trying to highlight that single sign on means single sign on.. i.e: one place where the credentials can  be provided.. If I add another place it's another attack vector. If a default is provided then there would be no error and if not the behavior would be as it is now hence nothing would change for most people who currently don't supply the default. What's your reservation?

**Comment by mmoayyed** [comment]
> The use case is a client that wants to authorize at a particular url with a username and password. The client already exists and i'm modifying pac4j to suit but the client doesn't know about the clientName parameter and I don't want to have to change all the clients.

Sorry, but I also have no idea what you are trying to accomplish. Could you elaborate on your use case and requirement? This is not clear to either of us. Start from the top. 

- You have an application
- You want to protect a particular url of that application
- You want to protect it with uid and password
- And what happens then?

**Comment by leleuj** [comment]
Someone else raises a similar need to "hide" the client_name: https://groups.google.com/forum/?fromgroups#!topic/pac4j-users/8kQTFguzhGM

The default client name would be the solution. Expecting a pull request for this issue.
