### ISSUE TITLE
Handle ajax requests to not redirect

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#536]
change in garpinc fork commit ba3c351

diff --git a/pac4j-http/src/main/java/org/pac4j/http/client/indirect/FormClient.java b/pac4j-http/src/main/java/org/pac4j/http/client/indirect/FormClient.java
index e70528f..edfd5cf 100644
--- a/pac4j-http/src/main/java/org/pac4j/http/client/indirect/FormClient.java
+++ b/pac4j-http/src/main/java/org/pac4j/http/client/indirect/FormClient.java
@@ -79,12 +79,6 @@
             credentials = getCredentialsExtractor().extract(context);
             logger.debug("usernamePasswordCredentials: {}", credentials);
             if (credentials == null) {
-				// it's an AJAX request -> unauthorized (instead of a
-				// redirection)
-				if (getAjaxRequestResolver().isAjax(context)) {
-					logger.info("AJAX request detected -> returning 401");
-					throw RequiresHttpAction.unauthorized("AJAX request -> 401", context, null);
-				} else {
 					String redirectionUrl = CommonHelper.addParameter(this.loginUrl, this.usernameParameter, username);
 					redirectionUrl = CommonHelper.addParameter(redirectionUrl, ERROR_PARAMETER, MISSING_FIELD_ERROR);
 					logger.debug("redirectionUrl: {}", redirectionUrl);
@@ -92,15 +86,9 @@
 					logger.debug(message);
 					throw RequiresHttpAction.redirect(message, context, redirectionUrl);
 				}
-            }
             // validate credentials
             getAuthenticator().validate(credentials);
         } catch (final CredentialsException e) {
-			// it's an AJAX request -> forbidden (instead of a redirection)
-			if (getAjaxRequestResolver().isAjax(context)) {
-				logger.info("AJAX request detected -> returning 403");
-				throw RequiresHttpAction.forbidden("AJAX request -> 403", context);
-			} else {
 				String redirectionUrl = CommonHelper.addParameter(this.loginUrl, this.usernameParameter, username);
 				String errorMessage = computeErrorMessage(e);
 				redirectionUrl = CommonHelper.addParameter(redirectionUrl, ERROR_PARAMETER, errorMessage);
@@ -109,7 +97,6 @@
 				logger.debug(message);
 				throw RequiresHttpAction.redirect(message, context, redirectionUrl);
 			}
-        }
 
         return credentials;
     }

**Comment by leleuj** [comment]
The source code is hardly readable. Can you explain what is the issue and the fix you propose?

**Comment by garpinc** [comment]
When an ajax client attempts to authenticate with pac4j to get a cookie originally in pac4j a redirect occured. Browsers redirect before the javascript gets back control and hence javascript doesn't work correctly. The correct behavior for ajax requests is not to redirect.

**Comment by leleuj** [comment]
You're right. As the `FormClient` performs some specific redirections, the AJAX capability should be taken into account. Waiting for the pull request (expecting some test to confirm the behaviour as well).

**Comment by leleuj** [comment]
Expecting a pull request for this change.
