### ISSUE TITLE
Create a way to specify callback url as the entity id

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#537]
garpinc fork ba3c351
diff --git a/pac4j-saml/src/main/java/org/pac4j/saml/client/SAML2Client.java b/pac4j-saml/src/main/java/org/pac4j/saml/client/SAML2Client.java
index b1336b6..910cc41 100644
--- a/pac4j-saml/src/main/java/org/pac4j/saml/client/SAML2Client.java
+++ b/pac4j-saml/src/main/java/org/pac4j/saml/client/SAML2Client.java
@@ -150,11 +150,9 @@
     }
 
     protected MetadataResolver initServiceProviderMetadataResolver(final WebContext context) {
-		String finalCallbackUrl = computeFinalCallbackUrl(context);
 		this.spMetadataResolver = new SAML2ServiceProviderMetadataResolver(this.configuration.getServiceProviderMetadataPath(),
-				this.configuration.getServiceProviderMetadataResource(), finalCallbackUrl,
-				(this.configuration.getServiceProviderEntityId().equals("CALLBACK_URL") ? finalCallbackUrl
-						: this.configuration.getServiceProviderEntityId()),
+                computeFinalCallbackUrl(context),
+                this.configuration.getServiceProviderEntityId(),
                 this.configuration.isForceServiceProviderMetadataGeneration(),
                 this.credentialProvider);
         return this.spMetadataResolver.resolve();

**Comment by leleuj** [comment]
The source code is hardly readable. Can you explain the objective of the improvement? in plain text

**Comment by garpinc** [comment]
In your https://github.com/pac4j/spring-security-pac4j-demo/blob/master/src/main/resources/securityContext.xml you had

I basically thought instead I could just refer to CALLBACK_URL and in those cases it would just put the callback url rather than hardcoding the config defined somewhere else. I'll submit a pull request for this change separately

**Comment by leleuj** [comment]
OK. I have nothing against it. @mmoayyed : any concern with having the `CALLBACK_URL` string interpreted as the callback url when defining the entity id?

**Comment by mmoayyed** [comment]
I guess I am not entirely clear on what this change proposes. What is the use case?

**Comment by garpinc** [comment]
In https://github.com/pac4j/spring-security-pac4j-demo/blob/master/src/main/resources/securityContext.xml  see where entity id is defined as the callback url.. This causes you to have to hard code the callback url in 2 places if that's what you want for the entity id. This proposes a keyword CALLBACK_URL that would set it to the callback url that you've already defined

**Comment by mmoayyed** [comment]
Cant pac4j determine the SP entity id automatically if it's left blank?

**Comment by garpinc** [comment]
Sounds reasonable to me. I guess I wasn't sure if you user may want entity id to be blank. If blank is not valid then sure instead we can make it so if it's blank then it's the callback url. I guess the only other concern would be then if you don't specify it, it just get's set and there are no errors so no feedback to user about an action item.. Your call..

**Comment by mmoayyed** [comment]
Thinking about this more, I think the SP entity id defined in the config is used to actually generate the SP metadata. So it's required to be there. We can't remove or modify it at all. The only way you wouldnt need that is when you decide to generate your metadata manually, without pac4j, and I don't think we should support that route at all. You specify the entity id, pac4j creates the metadata for you on startup and the same id ends up in your metadata. I am fine with that approach. So -1 on this so far.

**Comment by garpinc** [comment]
It's agreed that the entity id needs to be specified. As I said in your example https://github.com/pac4j/spring-security-pac4j-demo/blob/master/src/main/resources/securityContext.xml  the callback url is repeated. If someone wanted to use the callback url at this place then i don't see why they should have to repeat it. If they change the callback url at the other place then they will have to recreate the metadata anyway and now unless you change it again the entity id will be out of sync with the new callback url

**Comment by mmoayyed** [comment]
Gotcha. 

You mean there is:

```
<property name="serviceProviderEntityId" value="http://localhost:8080/callback?client_name=SAML2Client" />
```

and there is:

```
<property name="callbackUrl" value="http://localhost:8080/callback" />
```

Isnt that something you could easily remove with a shared property managed by Spring? 

Where you'd have:

```
<property name="serviceProviderEntityId" value="${the.callbackUrl}?client_name=SAML2Client" />
<property name="callbackUrl" value="${the.callbackUrl}" />
```

Then, you change it in one spot. I guess this only makes sense if you are using Spring. But otherwise, OK. We could proceed as you suggest. Thanks for the note.

**Comment by leleuj** [comment]
In fact, what your propose already exists in pac4j: if the `serviceProviderEntityId` is blank, the callback url is used for the service entity identifier: https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/metadata/SAML2ServiceProviderMetadataResolver.java#L54
