### ISSUE TITLE
Add logout redirect mecanism

### ISSUE THREAD

**Issue by patou** [pac4j/pac4j#54]
In the Google Apps UserService, the logout mecanisme create an logout url, which allow to go to a google url for logout from google server and after redirect to the application.

https://developers.google.com/appengine/docs/java/users/#Java_Signing_in_and_out :  

```
The Users API includes a method to generate a URL for signing out of the app. 
The  sign-out URL de-authenticates the user from the app, 
then redirects back to the app's   URL without displaying anything.
```

**Comment by leleuj** [comment]
New implementations based on pac4j v1.8 have an "application logout filter" which performs a local logout (the current user profile is removed from the session).
The idea here would be to perform a server logout after a local logout or not (depending on the fact that the server logout will call or not the application logout). It would depend on the current authenticated profile. So I imagine a new method in the `Client` like `logout(P profile, WebContext context);` and a new "logout filter" which would get the current authenticated profile, loop over all clients and call each logout method (unless we can directly link the profile to the client) to see if there is an url to redirect to.

**Comment by mavencode01** [comment]
@leleuj How can I perform a server logout after a local logout ? I'm experiencing this problem in the vertx wrapper https://github.com/pac4j/vertx-pac4j-demo/issues/37

**Comment by millross** [comment]
Possible to do this via a redirect action in shared logout logic @leleuj ? As you can see @mavencode01 is keen to see this too (and this is at the heart of the issue he reported on the play-pac4j impl as well as the vertx-pac4j impl). I'd like to limit the code impact on implementations where possible, so nicer to pass in all user profiles and let the clients figure out which belong to them and use them to perform server log out (if requested) I think.
