### ISSUE TITLE
Use CommonProfile everywhere instead of UserProfile

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#540]
`UserProfile` has been made abstract to promote the use of `CommonProfile`.

Currently, it's a bit messy about what kind of profile class is used as root profile through the source code: I propose to only use `CommonProfile`.

**Comment by mmoayyed** [comment]
+1

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/541
