### ISSUE TITLE
Pac4j Kerberos support

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#548]
I am faced with having to implement kerberos support in a pac4j/spring security enabled app. I have a decision point where either I use [spring-security-kerberos](http://projects.spring.io/spring-security-kerberos/) directly or If I need to start a pac4j project to support it. Any insight would be appreciated.

**Comment by leleuj** [comment]
I don't think spring-security-kerberos is a bad solution, Spring projects are generally good ones, though this one is not mainstream and the last commit is from February.
I have already received several requests about Kerberos support in pac4j. Adding Kerberos support to pac4j is a guarantee to be able to use Kerberos almost in every Java framework.

So I think it's mostly up to you: either you directly use the Spring project or you can spend time and contribute a new `pac4j-kerberos` module. This new module would be more than welcome.
I guess we would use direct clients like the basic auth or digest ones and have a specific `KerberosAuthenticator`. With further reflection, I think we can even leverage the CAS Kerberos support on the pac4j one? @mmoayyed

**Comment by garpinc** [comment]
Here's what I've come up with so far.. I'll make a module later if I can get it to work and if we can agree on direction. Specifically I'm told i need to support Spnego Negotiate.
[kerberos.zip](https://github.com/pac4j/pac4j/files/220869/kerberos.zip)

**Comment by leleuj** [comment]
I just took a quick look, but it seems fairly easy. But you use the Spring Security Kerberos module, don't you (I see: `org.springframework.security.kerberos.authentication.KerberosTicketValidator`)
If we want to create a `pac4j-kerberos` module, it must not depend on Spring Security, but it's certainly more work. Though, what you created is perfectly useful in the Spring Security pac4j implementation.

**Comment by garpinc** [comment]
If there is some ticket validator elsewhere (i.e: in CAS) I may be able to leverage that but perhaps it may need to be pulled out of that module into a common module.

**Comment by leleuj** [comment]
The service ticket validator in CAS is very specific, I don't think we could re-use it. Generally, for a new protocol support, I try to find the best plumbery library and build the pac4j module on top of that.

**Comment by mmoayyed** [comment]
I don't see much point in doing this. Kerb support is almost universally handled via JAAS, and there are plenty modules that already deal with Kerb and Jaas. Why would we want to repeat that experience when it's already done many many times?

**Comment by leleuj** [comment]
@mmoayyed  : so you do think that having a `pac4j-kerberos` module does not make any sense at all, don't you?

**Comment by garpinc** [comment]
I think application level security is where pac4j lives.

Spring thought it was necessary for Kerberos module. I can't see why this is different.
________________________________

**Comment by mmoayyed** [comment]
I don't, no. I can't speak to what Spring thought was necessary, but given the repository stats, I can't say this is really all that much used. Unless there is a compelling reason to redo what JAAS does, I see no reason to do this. Specially because, additionally, Kerb is more or less "dead". 

I am not opposed to you writing the code and contributing it. I am saying your time could be better spent elsewhere.

**Comment by mmoayyed** [comment]
> I think application level security is where pac4j lives.

Exactly. So, Authentication != Security. Pac4J handles authentication in some cases that makes sense, like Basic AuthN for example. But in general, I don't think the framework should focus on authentication as much as it does on security. Authentication can always be delegated, or passed along to some other framework when possible.

**Comment by leleuj** [comment]
To talk about trends: https://www.google.com/trends/explore#q=jaas%2C%20kerberos

**Comment by garpinc** [comment]
submitted a pull request #595

**Comment by leleuj** [comment]
Latest commit is more than three months ago. Closing for now. Feel free to re-open when you'll be ready to finish the PR.

**Comment by leleuj** [comment]
Reopened for @vidma
