### ISSUE TITLE
The "Double-Checked Locking is Broken" Declaration

### ISSUE THREAD

**Issue by loolooyyyy** [pac4j/pac4j#549]
I've recently found a nice article [The "Double-Checked Locking is Broken" Declaration](http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html)

While going through pac4j's source and up the class hierarchy (by the way I had trouble get a sample Jwt running and was looking for some help there :D 
) I can see InitializableWebObject uses double-check locking, according to the article it's broken:

```java
        if (!this.initialized) {
            synchronized (this) {
                if (!this.initialized) { // wont work, because of JVM optimization
                    internalInit(context);
                    this.initialized = true;
                }
            }
        }
```

Thought you should now.
regards

**Comment by millross** [comment]
It will, however, work if the initialized member is declared as volatile

**Comment by millross** [comment]
I've just checked the source and initialized is declared volatile, which means the double checked locking will behave correctly. This is mentioned in the article

**Comment by leleuj** [comment]
Exactly. The "double checked locking" didn't really work, but thanks to findbugs (and PMD) analysis, the problem was found and fixed in 1.9 by using the `volatile` keyword.

**Comment by ttaveira** [comment]
Doesn't this issue also exist in the [HttpSessionStorage](https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/storage/HttpSessionStorage.java) class, which apparently came from [Spring Security SAML](https://github.com/spring-projects/spring-security-saml/blob/master/core/src/main/java/org/springframework/security/saml/storage/HttpSessionStorage.java)?

**Comment by leleuj** [comment]
Not exactly. The property on which the double check applies is local to the method and not global and shared at the object level.
