### ISSUE TITLE
Callback URL Resolver for FormClient loginUrl

### ISSUE THREAD

**Issue by jonathanlabin** [pac4j/pac4j#552]
Apply the callback url resolver to the loginUrl field of org.pac4j.http.client.indirect.FormClient to dynamically generate URLS with the appropriate host and context root.

Without this this functionality, the context root must be specified for the field. In configurations with static config files (for example Shiro ini) this does not allow the application to be deployed with different context roots.

**Comment by leleuj** [comment]
Thanks. Would you mind submitting a pull request for that?
