### ISSUE TITLE
SAML integration: provided SP metadata is ignoring.

### ISSUE THREAD

**Issue by leofromgroza** [pac4j/pac4j#553]
We are using pac4j in our system. Also we have integration with ADFS, so we are using pac4j-saml module. When I try to resolve one bug in our system I found that SP metadata configuration property is [only used for generation of new SP metadata file](https://github.com/pac4j/pac4j/blob/pac4j-1.8.8/pac4j-saml/src/main/java/org/pac4j/saml/metadata/SAML2ServiceProviderMetadataResolver.java#L130-L147). It ignores all information that is stored there (AssertionConsumerServices, SingleLogoutService, NameIDFormats, etc)! I want to ask developers: why did you decide to make such architecture? Because of this I have problems with supporting backward compatibility.

**Comment by leleuj** [comment]
Reading current SP metadata file and mixing it with the current configuration to generate a new one would have been very complicated. Cannot you simply take your SP configuration and turn it into pac4j configuration?

**Comment by leofromgroza** [comment]
I tried but how can I configure multiple Assertion Consumer Services using pac4j?

**Comment by leleuj** [comment]
Looping @mmoayyed which knows better...

**Comment by mmoayyed** [comment]
I am not sure I understand. The metadata is generated, and then it's resolved and returned back to the caller. It is used. 

If you need more than one ACS Url, you need to massage the file by hand.
