### ISSUE TITLE
Do you think it is necessary to upgrade the scribe java 2.5.X

### ISSUE THREAD

**Issue by zawn** [pac4j/pac4j#556]
I think it is necessary to upgrade your current version of the scribe java, and I'm willing to do it. I hope to get your support

**Comment by leleuj** [comment]
Sure. We are at version 2.2.2 and the latest one is 2.5.3. The upgrade should not be too complicated unless things have really changed.
For the upgrade, you should check if some new Api are available to replace the ones in pac4j (https://github.com/pac4j/pac4j/tree/master/pac4j-oauth/src/main/java/org/pac4j/scribe/builder/api). And execute the manual tests to ensure nothing is broken: https://github.com/pac4j/pac4j/tree/master/pac4j-oauth/src/test/java/org/pac4j/oauth/run (except the `CasOAuthWrapperClient` which needs some external update from me).

**Comment by zawn** [comment]
![image](https://cloud.githubusercontent.com/assets/5005199/14732919/66dead68-0891-11e6-851a-ffeaabd835fa.png)
As shown above, I have to finish.
Except A and B after authorization by an authorization server does not redirect to redirect URI cause interruption test, the other blue label type has been successfully tested.

![qq 20160422133548](https://cloud.githubusercontent.com/assets/5005199/14733210/edc7f2d8-0893-11e6-99f9-ede02ddaa9b5.png)

![qq 20160422133611](https://cloud.githubusercontent.com/assets/5005199/14733212/f0749220-0893-11e6-91a4-f4df6758624e.png)

**Comment by zawn** [comment]
I try to fix   [RunOrcidClient](https://github.com/pac4j/pac4j/blob/master/pac4j-oauth/src/test/java/org/pac4j/oauth/run/RunOrcidClient.java)  error, but did not succeed.


Reference website:
 * https://members.orcid.org/api/oauth2
 * https://members.orcid.org/api/orcid-scopes

Similar problems:
https://groups.google.com/forum/#!topic/orcid-api-users/FOGhXEnxVVQ

**Comment by zawn** [comment]
Since OAuthService cancel signRequest method,
BaseOAuthClient call in into its subclasses

**Comment by zawn** [comment]
https://github.com/zawn/pac4j/commits/master

I've finished processing

**Comment by leleuj** [comment]
Excellent. I forgot to mention that the `RunOrcidClient` manual test does not work either. Would you mind creating a pull request from your master to pac4j/master? Thanks

**Comment by zawn** [comment]
I have submitted a pull request .

I see you are cas contributor, I want to implement a feature:
Own app by calling a third party app/sdk (such as Facebook) to obtain accessToken, then passed to our own Oauth2 Token endpoint (Implemented by Cas), in exchange our own accessToken.
This flow is much faster than the authorization code flow.

we hope pac4j provide a way to verify the token info.
E.g use https://developers.google.com/identity/protocols/OAuth2UserAgent#tokeninfo-validation

Do you have any good suggestions !

**Comment by leleuj** [comment]
Thanks for the pull request. See my comments.

Currently, access tokens returned by CAS can be validated against the /profile endpoint which returns the user profile associated with the access token. We don't support client credentials grant type, aka a service authenticating on CAS through OAuth protocol to get an access token. I recommend we talk about this on the CAS mailing list, I see more and more interest on OAuth flows.

**Comment by zawn** [comment]
This is our custom oauth2 flow, we are prepared to waste before implementation, now use CAS to do, so we need pac4j OAuth client to provide a method for obtaining profile through the existing access token (trusted_token)

[OAuth 2(Trusted_third_party_grant ).docx](https://github.com/pac4j/pac4j/files/242621/OAuth.2.Trusted_third_party_grant.docx)

Sorry, though Chinese, perhaps you can understand flow

I now want to use pac4j complete validation of third-party access token and get profile(Section 1.1.4 of the document)

thanks for the reply!

**Comment by leleuj** [comment]
Thanks for the explanations.

Why did you remove the Weibo and QQ clients? These were very interesting new supports. I'm sure a lot of pac4j users would use them. Can you add them back?

**Comment by leleuj** [comment]
I don't read chinese for sure. So you already have this trusted token: how do you validate it? And how is it linked to the user profile?
