### ISSUE TITLE
Handle security / callback / logout logic

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#558]

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/590
J2E:
https://github.com/pac4j/j2e-pac4j/pull/33 & https://github.com/pac4j/j2e-pac4j-demo/pull/24
Play:
https://github.com/pac4j/play-pac4j/pull/112 & https://github.com/pac4j/play-pac4j-java-demo/pull/34 + https://github.com/pac4j/play-pac4j-scala-demo/pull/32

**Comment by leleuj** [comment]
@mmoayyed @millross : this is the last main change for pac4j v1.9. With it, we reach a very mature stage of the framework as security behaviours are now implemented in the core and used by the implementations.

**Comment by mmoayyed** [comment]
Sounds great!

I am working on a few JWT-related issues. Between that and this issue, I think we should be well positioned for a 1.9 release.

**Comment by leleuj** [comment]
I plan to merge everything tomorrow for a release next wednesday. Just let me know if I need to wait for some fixes.

**Comment by mmoayyed** [comment]
Will do. I think I should have everything wrapped before the weekend but will keep you posted either way.
