### ISSUE TITLE
SAML Subject and Signature not trusted

### ISSUE THREAD

**Issue by saschak094** [pac4j/pac4j#564]
Hi, 

we are using pac4j for our SAML Authentication Mechanism. I am getting the following Exceptions after getting a valid SAMLResponse of the IDP 

```
org.pac4j.saml.exceptions.SAMLException: Signature is not trusted
	at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateSignature(SAML2DefaultResponseValidator.java:699)
```

Furthermore we also get this: 

`org.pac4j.saml.exceptions.SAMLException: No valid subject assertion found in response`

But the subject itself is set within the SAMLResponse: 
```
 <saml:Subject>
   <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified">A421324</saml:NameID>
   <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
            <saml:SubjectConfirmationData Recipient="https://address:443/callback?client_name=SAML2Client" NotOnOrAfter="2016-05-03T13:03:40.169Z" InResponseTo="_xy0hjmghiadfadfadfpmd45kzto4ewpq6lkkynmkimp0wjplypx"/>
    </saml:SubjectConfirmation>
  </saml:Subject>
```

Can you provide any help ? what Subject does pac4j expect ?

**Comment by mmoayyed** [comment]
It's about the subject. The error is telling you that the assertion signature cannot be trusted

**Comment by saschak094** [comment]
Is the subject I posted not a valid subject for pac4j ?

**Comment by mmoayyed** [comment]
Nothing wrong with it, but that's not the issue based on your logs. The issue is the first entry in your post.

**Comment by asmita2201** [comment]
@leleuj 
I am getting this exception. Please help.
org.pac4j.saml.exceptions.SAMLException: No valid subject assertion found in response at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validateSamlSSOResponse(SAML2DefaultResponseValidator.java:313) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.saml.sso.impl.SAML2DefaultResponseValidator.validate(SAML2DefaultResponseValidator.java:138) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.saml.sso.impl.SAML2WebSSOMessageReceiver.receiveMessage(SAML2WebSSOMessageReceiver.java:77) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.saml.sso.impl.SAML2WebSSOProfileHandler.receive(SAML2WebSSOProfileHandler.java:35) ~[pac4j-saml-2.1.0.jar:?] at org.pac4j.saml.client.SAML2Client.lambda$clientInit$0(SAML2Client.java:110) ~[pac4j-saml-

**Comment by leleuj** [comment]
Please use the pac4j-users mailing list for questions.
