### ISSUE TITLE
Add more clients into PropertiesConfigFactory

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#565]
Add the following:

1. DropBox
2. Github
3. Yahoo
4. Google
5. FourSquare
6. Windows Live

**Comment by leleuj** [comment]
Adding more clients would be great. But I think we need a better way to be able to configure almost anything like a `LdapAuthenticator`. My best thought so far was to define the configuration as a Groovy script (greatly inspired by what you did in CAS ;-)

**Comment by mmoayyed** [comment]
Help me understand this better please: how do you envision a groovy script doing client registration?

**Comment by leleuj** [comment]
Sure. Currently, we have the `ConfigFactory` interface to implement to build a `Config`:  https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/config/ConfigFactory.java This is used for the J2E implementation.

So the idea would be to create some Groovy class extending the `ConfigFactory` to build the `Config` and indicate the path to this Groovy class. That said, I was thinking of Groovy as it feels more dynamic, but it could maybe be in Java or in Javascript using the capabilities of the JVM.

**Comment by mmoayyed** [comment]
OK, I think I understand. Few concerns there:

- A groovy implementation of the config factory, as you noted, may point to some custom groovy script that builds and loads clients. Problem with that approach (regardless of whether it's groovy or JS, etc) is that someone has to write that script! I wouldn't want that, ever :) I'd much rather we ship "preconfigured" clients that folks can easily configure with key=value type of settings.

- Let developers write the groovy implementation and everything that follows afterwards. 

- Doing this via properties and such has the advantage of leveraging spring boot/cloud to proxy those beans and make them dynamic. A groovy/JS script basically amounts to the same thing, but on a more complicated level.

- If as we expect developers to write a groovy script that is loaded by the groovy ConfigFactory, why wouldnt they just write the thing in Java to begin with?! Specially if your target audience are developers with the know-how, why introduce a level of indirection for folks who are expected to use APIs directly?

**Comment by leleuj** [comment]
OK. I understand. So how do we handle advanced use cases with properties? Like setting a bean as the property of another bean. I think we would be very close to the INI configuration system of Shiro, wouldn't we?

**Comment by mmoayyed** [comment]
On a case by case works best I think. Two approaches:

1. The autoconfiguration of clients must account for advanced scenarios like that of above as you describe. It should be smart enough to autoconfigure the context and prep all beans and dependencies based on "guessing" what the ultimate intention is. If one isnt happy with that guess and how we think that client should work best, they can always tune it manually. We don't have to support every property and every feature of every client. Just what makes sense for the most.
2. We should design clients that do not have advanced requirements like that, to make #1 easier. Keep them simple as much as possible. A client that can accept and has 5 bean dependencies on other objects is much harder to construct with an opinion in mind than a client that just has a few boolean/string fields. I'd even argue that design is easier to work with anyway, regardless of approach here anyway. 

Eventually at some point, we'll extract a more comprehensive design out of all this. At this point, I think it's too soon to provide a super comprehensive flexible platform to handle all. Let's collect use cases and clients that folks are most interested in. Figure out who our majority are.

**Comment by leleuj** [comment]
Regarding point 2, I agree: we should design as simple as possible clients. Though, on the other side, we don't want to reinvent the wheel and use well-known libraries for the plumbery, like Ldaptive for the LDAP support. In that case, we have indeed a very simple `LdapAuthenticator`, but the Ldaptive `Authenticator` configuration is complex.
But yes, let's start small and see what happens...
