### ISSUE TITLE
Add a new client for Instagram

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#566]
Havent looked into this, but it's about to support Oauth2 or OIDC.

**Comment by leleuj** [comment]
It seems to be based on OAuth 2.0: https://www.instagram.com/developer/authentication/

Though, I don't see any Instagram Api in Scribe: 
https://github.com/scribejava/scribejava/tree/master/scribejava-apis/src/main/java/com/github/scribejava/apis

So it's about creating a specific Scribe Api and an InstagramClient based on the BaseOAuth2Client from pac4j. With a specific manual test in : https://github.com/pac4j/pac4j/tree/master/pac4j-oauth/src/test/java/org/pac4j/oauth/run

**Comment by mmoayyed** [comment]
Good overview. I'll look into it. Punting this for now to 1.9.1 or even later, as I don't think it can make the cut for 1.9, and that it's not needed really.

**Comment by leleuj** [comment]
Do you still plan to work on this? Closing for now. Feel free to reopen with a contribution.
