### ISSUE TITLE
ID Token JWTs should support all claims where possible.

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#568]
Claim generation with JWTs are fairly limited today. Allow wider and better support for all claims that OIDC might need specifically.

**Comment by leleuj** [comment]
@mmoayyed : starting to revisit this one: can you elaborate on this? I see limited checks on the claims that can be used: https://github.com/pac4j/pac4j/blob/master/pac4j-jwt/src/main/java/org/pac4j/jwt/profile/JwtGenerator.java#L158

**Comment by mmoayyed** [comment]
A JWT that is produced as an ID Token by OIDC should contain:

http://openid.net/specs/openid-connect-core-1_0.html#IDToken

Do we support all?

Additionally, claims that are produced by OIDC separate from the ID Token should support:

http://openid.net/specs/openid-connect-core-1_0.html#StandardClaims

Presently in CAS, we don't do any kind of mapping between original attribute names and claims that are required by the spec. That part is left to the user. For instance, if I resolve attribute "firstName" CAS will simply release that back to the RP. In reality, that claim really should have been "first_name" which the user has to know and then configure. I think this is fine for now, but perhaps, either somewhere in CAS or Pac4j, it would be nice to simply take a CAS principal and translate that to an oidc profile. I suspect that is more to do with CAS than pac4j here. 

PS pardon the typo. This is really about the JWTs. Not the claims. I'll correct it.

**Comment by leleuj** [comment]
OK. Thanks for the explanations. Some constants may be missing for these claims (either regarding JWT or OpenID Connect). I'll see how I can handle everything.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/623
