### ISSUE TITLE
Allow JWT support to use JWKS

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#570]
Signing and encryption is now only handled via secret keys. JWKS should also be supported.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/621

`SignatureConfiguration` can be built from JSON JWK fragment. Example: https://github.com/pac4j/pac4j/pull/621/files#diff-e49df8d064e64aeba3dc859dbbde6ba5R82
