### ISSUE TITLE
A direct client capable of responding with a negotiate header

### ISSUE THREAD

**Issue by garpinc** [pac4j/pac4j#574]
I have a scenario where prior to introduction of pac4j, a servlet protected by basic auth, would send back the WWW-Authenticate basic auth negotiation headers if basic auth wasn't already on the request. This all happened without any redirects.. 

When I introduced pac4j instead with IndirectBasicAuthClient I introduced a bug and various clients didn't follow redirects to the callback. 

As such I needed a way to use DirectBasicAuthClient but to respond with header on failure. This is also the case for the KerberosClient I developed. I implemented following interface:

public interface DirectExtended {
    void handleForbidden(final WebContext context);
}

so each client would have a method which I could invoke to respond with appropriate negotiation header.

Does this sound reason?

**Comment by leleuj** [comment]
I see your point and there are more and more requests for "customized" flows. pac4j v1.9 will propose something very easy: either you follow the regular flow or you throw a `RequiresHttpAction` to break the flow and do what you want.
