### ISSUE TITLE
[Question] Can pac4j used in a Scala/Spray application ?

### ISSUE THREAD

**Issue by hajime-moto** [pac4j/pac4j#592]
I'm trying to secure my [Spray](http://spray.io/) based single page web application. Will I be able to use pac4j to secure my Spray APIs ?

**Comment by leleuj** [comment]
There is currently no pac4j implementation for Spray, although I created: https://github.com/pac4j/spray-pac4j for it.

I don't know Spray, but if you were to develop it, you would need to create a specific `SprayWebContext` and maybe a `SprayHttpActionAdapter` if actions performed on the web context need to be turned into specific results.
You would need some interceptor mechanism to secure url which would rely on the [`DefaultSecurityLogic`](https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/engine/DefaultSecurityLogic.java), some controllers for callbacks handling (based on the [`DefaultCallbackLogic`](https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/engine/DefaultCallbackLogic.java)) and application logout (based on the [`DefaultApplicationLogoutLogic`](https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/engine/DefaultApplicationLogoutLogic.java)).

If you want to contribute this implementation, I'll be happy to provide you with more details.

**Comment by leleuj** [comment]
I'll open a discussion on the Spray mailing list in september (when people will be back from holidays).
