### ISSUE TITLE
Release 1.9.0 broke on JDK 7

### ISSUE THREAD

**Issue by LarsOL** [pac4j/pac4j#593]
Hey,

Just making you aware that the new version is broken for JDK 7.

I noticed Java 8 was mentioned in the release notes, but was the breakage intended? Especially for a minor release?

If it was intentional, do you have any plans to back port security fixes to Java 7 in the future?

Thanks

**Comment by leleuj** [comment]
Thanks for the feedback, but this is fully intended. Java 7 was end of life last year (2015) in April.

In fact, it's not a minor version, it's a major one: version 1.8.x is still based on Java 7 and will receive bug / security fixes, but our main efforts will be now focused on 1.9 stream.

**Comment by LarsOL** [comment]
Thanks for the quick reply,

And my bad, when I saw the version I assumed it was following "Semantic Versioning" which defines "MAJOR.MINOR.PATCH". 

Out of curiosity, what versioning specification are you using? And any tips for me on how to differentiate between them in future?

**Comment by leleuj** [comment]
X.Y.Z where Z is for minor / patch versions, X.Y for versions. The 1.9.0 version would be a 9.0.0 version using "semantic versioning".
Major versions: 1.8.x, 1.9.x, 2.0.x, 2.1.x, ...
