### ISSUE TITLE
cas-server-support-token generate JWT Problem

### ISSUE THREAD

**Issue by epa64** [pac4j/pac4j#600]
HI,
I used cas-server-support-token 4.2.2 and i am some problem to generate token.

The error message is : com.nimbusds.jose.JOSEException: The "A256GCM" encryption method is not supported by the JWE encrypter

CODE : 
       JwtGenerator<TestUserProfile> g = new JwtGenerator<TestUserProfile>(keySign,keyEncry);
		TestUserProfile profile = new TestUserProfile();
		profile.setId(mail);
		//
		g.setJwsAlgorithm(JWSAlgorithm.HS256);
		g.setJweAlgorithm(JWEAlgorithm.A256KW);
		logger.info("EPA LostPasswords Servlet key de cryptage  : "+g.getEncryptionSecret()+" Key de signature : "+g.getSigningSecret());
		String token = g.generate(profile);

I want to customized CAS to add new LostPassword Fonctionnality by TOKEN.

JDK 1.7

Best regards
Eric Papet

**Comment by leleuj** [comment]
You'd better use the CAS or pac4j mailing lists for such questions.

Very strange: A256GCM is the default algorithm and I've done many tests using it. Which version of the nimbus jose lib do you have in your overlay?

**Comment by epa64** [comment]
Thank's for your reply

Ok for the next post i will use CAS main list.

i use cas-server-support-token version 4.2.2 with dependancies nimbus-jose-jwt 4.1.1.

My jdk is 1.7

Best regards
Eric Papet

**Comment by epa64** [comment]
sorry nimbus-jose-jwt 4.11

**Comment by epa64** [comment]
Hi,
i resolved my problem.
It's the lenght of my shared key, but the error message is not good.

Best regards
Eric Papet

**Comment by leleuj** [comment]
Indeed, the error message is not good. You should raise an issue: https://bitbucket.org/connect2id/nimbus-jose-jwt/issues
