### ISSUE TITLE
[Question] Unauthenticated CSRF

### ISSUE THREAD

**Issue by wrobbins** [pac4j/pac4j#602]
Confused about CSRF workflows, they seem to only apply for authenticated endpoints. Adding an interceptor (for spring) like the following prevents unauthenticated requests. 

Is there a workaround ?

`
SecurityInterceptor crsfAuthorizerInterceptor = new SecurityInterceptor(config);
crsfAuthorizerInterceptor.setAuthorizers("csrf");
registry.addInterceptor(crsfAuthorizerInterceptor);
`

**Comment by leleuj** [comment]
Hi,

It's a good question for the mailing list:
https://groups.google.com/forum/?fromgroups#!forum/pac4j-users

pac4j aims to be a very easy and powerful security engine / library. So
default behaviours are extremely simple: authorizers apply after clients to
ensure authorizations are valid and authorizations can work on user
profiles and web context. That said, you can extend / tweak this behaviour
in many ways.

In your case, using an AnonymousClient will authenticate the user as an
AnonymousProfile and call the CSRF authorizer for unauthenticated requests.

Thanks.
Best regards,
Jérôme





2016-07-10 18:32 GMT+02:00 dude <notifications@github.com>:
