### ISSUE TITLE
Please keep published API docs available

### ISSUE THREAD

**Issue by johnrengelman** [pac4j/pac4j#605]
I've noticed that when a new version is published, that you replace the API docs and then redirect the existing URL to the new version.
This causes problems for other projects that are publishing Javadoc and linking against the Pac4J API.
For example, Ratpack, builds against a specific version of Pac4J (1.8.5 currently), and our Javadoc is built against that version of the API, but it is currently failing because the URL redirects to v1.8.8.
It would be really helpful to keep all the old versions of the API available so that users's can reference the docs for the version they are using.

**Comment by leleuj** [comment]
The idea is always to use the latest version of pac4j as they are all backward compatible for the same stream (1.8.x for example).

This is a side effect I didn't expect. You're the first one to have an issue with the Javadoc. I guess I'll need to keep all versions in the future.

So either I publish back the version 1.8.5 or Ratpack upgrades to 1.8.8 (it should just be a matter of switching the number version). It's up to you.
I'll come back to Ratpack in a few weeks to upgrade to pac4j v1.9.

**Comment by johnrengelman** [comment]
you don't need to do anything retroactive, going forward is fine. 
Once we release a version of Ratpack though, we are locked to a specific version of Pac4J unless the user decides to upgrade on their side.
So the links from our API docs need to point to the version we are shipping ideally.

**Comment by leleuj** [comment]
OK. I'll keep things "as is" and won't remove Javadocs anymore.
