### ISSUE TITLE
Computing redirect URLs no longer seems possible in 1.9

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#608]
Prior to pac4j 1.9, one could do this: 

```
final String redirectionUrl = indirectClient.getRedirectionUrl(webContext);
```

in 1.9, I thought I could do this:

```
indirectClient.getRedirectAction(webContext).getLocation();
```

However, this starts to throw an exception for a dropbox client because in order for the redirect action to be computed, pac4j starts to examine the context for a token, etc and that of course isn't available.

**Comment by leleuj** [comment]
The `getRedirectAction` method should never be called. Currently, it's only called for testing. The redirect action can be a 302, or a 200 (POST) for SAML also so in theory, you should handle both use cases. And it should work for DropBox as well as for the other clients. The method to call is `redirect`.

**Comment by leleuj** [comment]
As for DropBox, I'm surprised it doesn't work. Did you run the `RunDropBox` manual test?

**Comment by mmoayyed** [comment]
I did, yes. That surprisingly works. I am looking at CAS and see where I might have gone wrong since I can't see it's doing anything different just yet. Keeping this issue open until I make heads out of this.

**Comment by mmoayyed** [comment]
Figured this out. Turns out, DB client needs valid key and id before it can compute the URL. Some clients need it and some don't! I made sure CAS can recover if keys are misconfigured when calculating the redirect url.
