### ISSUE TITLE
Missing getRequestContent in WebContext

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#612]
Hi,

I'm trying to write a client by extending DirectClientV2 and I would like to be able to read the content of the request (I'm expecting a POST request with the credentials in a JSON document).

The current implementation of WebContext does not seem to provide a way to access this information.

Thanks :)

**Comment by leleuj** [comment]
Keep in mind that the `WebContext` must be implemented in all frameworks where pac4j is used: it's a very sensitive component. And I'm reluctant to add this method for now.

What the implementation do you use? With the `J2EContext` for example, you have access to the `HttpServletResponse` response directly.

Notice that you should create a `JsonCredentialsExtractor` here.

**Comment by victornoel** [comment]
Ok, I understand, I'm currently writing this `JsonCredentialsExtractor` and that's where I was looking for a generic way of accessing the Web request content.

I know in my case that it will be a `J2EContext`, so I can downcast the context to that, but I was wondering if there wasn't some need for a more generic approach to that (since my extractor won't be usable with anything else than a `J2EContext`).

I see it is not trivial because it means to choose a way to represent that content (a stream, a string, etc…) and force all implementors of WebContext to give it in that representation.

**Comment by leleuj** [comment]
Indeed, it's not an easy problem. Let's keep this issue open and marked as "FUTURE" to track the need.

**Comment by leleuj** [comment]
After some thinking on this, I think we should add:

- a `String getRequestContent()` method on the `WebContext` interface, with a default implementation throwing a "not implemented exception" (see: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/context/WebContext.java#L78) to make things backward compatible (at the compilation level) with existing implementations

- the appropriate implementation in the `J2EContext` class.

@victornoel : Do you mind submitting a pull request for that?

**Comment by mmoayyed** [comment]
I'll handle this.

**Comment by millross** [comment]
As a heads up, this approach is unlikely to work very well in at least the vert.x framework. I would prefer a generalised version of the method (which would mean an additional type parameter on the WebContext interface) where the type parameter would determine the type returned from GetRequestContent. That said, I'd far prefer a mechanism for accessing the underlying request (or context) full stop, to enable the coder to work within the parameters of their chosen framework.

**Comment by victornoel** [comment]
In the end, I wonder if it makes really sense to push this method at the interface level instead of simply having it in one of the implementation of the interface (such as `J2EContext`).

Because I'm not sure if we will ever need to generically access this information: there is a lot of chance this info will be only needed in code that already knows the subtype of `WebContext`.

At least it was the case for my original feature request :)

**Comment by victornoel** [comment]
(That's basically what @millross was saying if I understood well his point)

**Comment by millross** [comment]
Yeah, I think my concern is that by putting it on the interface it creates an expectation of it being provided in implementors for specific frameworks. I think it makes more sense to enable access to the underlying framework context (request, or in the case of vert.x routing context) than to have the method to return a string. This doesn't necessarily have to involve down casting though, just a generalisation of the WebContext to be WebContext<T> where T is the class of the underlying "context"/request info provider.

**Comment by victornoel** [comment]
So for example, what would be `T` in the case of Servlet/J2E? A j2e-pac4j class that would aggregates all the Servlet related objects such as the request, the response, etc?
Could be neat yes!

But then you enter a possible hell of type parametrisation to be able to propagate that information without downcasting: the client I was trying to write for example must then be parametrized by this `T`, and so on… no?

**Comment by millross** [comment]
No, you're right, we'd always end up down casting anyway to identify the type of the value returned by the "get context" method. So it doesn't help. I think probably better to offer the default method and say very clearly in Javadoc that some frameworks probably won't implement it, so it can't be relied on generally. But in that case isn't it just as easy for the custom clients to downcast anyway since they presumably have to know what framework they're going to work within? In which case it still doesn't seem right to expose the method generally via the interface.

**Comment by victornoel** [comment]
Yes, I agree, my original feature request is not so relevant in the end.
Maybe we should abandon that idea, so let's see what @leleuj thinks about all of it then :)

**Comment by leleuj** [comment]
The original request was to be able to parse the request body, assuming it's a JSON content.

We can of course do that directly in the different frameworks. Most specific web context implementations have some `getNativeRequest` method to get access to the specific request implementation and the JSON parsing could happen in different ways.

Though, the idea here is to offer only component: a `JsonCredentialsExtractor` which extracts JSON data (like a username, password or a token) from the request body and this requires a `String getRequestContent()` at the `WebContext` level. No type parameter, the extractor would always work on a `String` (or `InputStream`), **whatever the web context implementation**.

We could always have a default implementation throwing a "Not supported by this framework" exception and frameworks which cannot implement that method, would need to do things by hand.

It seems a good compromise to me, but `pac4j` already does so many things, that it's a big deal not to implement that one.

@millross : feel free to vote -1 against this feature

**Comment by millross** [comment]
In vert.x (or any other non-blocking framework) you cannot be guaranteed automatically to have the whole request body before you do authentication. I can conceive of an approach for vert.x but it would rely on additional vert.x configuration (to ensure body has been fully read before authenticating), and this is where the complication comes in. It is impossible to distinguish between an empty request body and one where the additional configuration has not been performed, meaning that the warning/error message where no request body is found can only be a recommendation to do the config, not an authoritative statement of what the coder has failed to configure.

It also requires additional documentation in the vert.x implementation when support is added for it.

Suggest in the first instance we stick with a “Not implemented for this framework” default exception as originally proposed. If there is a demand for vert.x to implement it, then we’ll cross the documentation bridge as part of that implementation. If no demand for vert.x to implement it, I’ll leave it unimplemented (and frankly if someone demands it for vertx-pac4j I’ll suggest they submit the PR for review rather than do it myself).

**Comment by leleuj** [comment]
OK. Let's do that. Thank you all. @victornoel : feel free to open a new PR with the `JsonExtracor`.

**Comment by victornoel** [comment]
@leleuj I'm not totally clear now: I wasn't planning to propose a generic `JsonExtractor` because I think it would be most certainly specific to my application… no?

**Comment by mmoayyed** [comment]
You should let the application handle the extraction; whatever the content is. There should be a way to get the content from the webcontext. Bypassing that and resolving back onto the native request/response object entirely defeats the purpose of using a webcontext and should be avoided.

**Comment by leleuj** [comment]
@victornoel : if you have a generic component which extracts username and password from a JSON content and returns a `UsernamePasswordCredentials`, it can make sense to propose it. At least, we have one the way to access the content of the request for that purpose.

**Comment by victornoel** [comment]
@leleuj ok, I will keep that in my mind for a PR!

**Comment by victornoel** [comment]
@leleuj FYI, I don't think I will contribute such an `JsonExtractor`.

In my current use case, I rely on Jersey's abstractions to parse the request content from JSON to a Java object (so I don't even take advantage of the new `getRequestContent` method…).
I feel like depending on the framework that is used, the way to parse a request content will be different: some use Jackson, others use something else, others do not provide a JSON deserializer, etc. Then the way to retrieve the Jackson `ObjectMapper` may be different depending on the framework, and so on… I don't want to put so much effort in making a generic `JsonExtractor` that I won't even use :)

**Comment by leleuj** [comment]
OK. No problem. This `JsonExtractor` may be a bit too particular. We'll see if people ask for it again.

Yes, "eat our own dog food" rules.
