### ISSUE TITLE
J2EContext's getPath() seems incorrect

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#613]
Hi,

I'm currently playing with pac4j in conjunction with dropwizard (jetty+jersey) and it seems that J2EContext.getPath() (used by the matchers) which is based on getServletPath returns an incorrect information. Shouldn't it be based on getPathInfo() instead?

For example when I access /appContext/login, getServletPath return "" and getPathInfo() returns /login.

Note that this happens inside the servlet itself (the Jersey one) and not inside a filter on the servlet container (for various reasons not important here).
So we should check that if it's happening inside a servlet filter (as it was intended to, for example for j2e-pac4j) it works as desired.

**Comment by leleuj** [comment]
It's not an easy topic, I remember spending times already on this.

Yes, indeed: `getPathInfo()` seems to be more logical than `getServletPath()`. Though, I tested it successfully with the J2E and Spring Security demos, but I suspect it may strongly depend on the mapping.

In the J2E demo, I have:

```xml
<filter-mapping>
   <filter-name>FacebookFilter</filter-name>
   <url-pattern>/facebook/*</url-pattern>
   <dispatcher>REQUEST</dispatcher>
</filter-mapping>
```

When calling the url: `http://localhost:8080/facebook/notprotected.jsp`,  I have:
- `request.getServletPath()` -> `/facebook/notprotected.jsp`
- `request.getPathInfo()` -> `null`

Same result for the mapping: `/facebook/notprotected.jsp` or `*.jsp`.

What's your mapping?

**Comment by victornoel** [comment]
It's the thing, I'm not using a `filter-mapping` at all because I'm trying to integrate pac4j directly with Jersey. Jersey has its own filters that are executed as part of the jersey servlet itself, not before by the container as with servlet's filters.

I'm not sure if:
1. maybe there is a generic way that works in both cases
2. my use case should really be supported generically (for now I extend `J2EContext` and redefine `getPath()` because I DO know I'm inside Jersey's servlet at the moment I create the context)
3. it's ok for pac4j to assume that `J2EContext` will always be used in filters… I ask because it's not defined as part of the j2e-pac4j but as part of pac4j-core…)

**Comment by leleuj** [comment]
The idea here is to handle as much as possible use cases, even if the default behaviour is for J2E filters.

So I think we should test the `getServletPath` value and if blank, return the `getPahtInfo`: would you mind submitting a pull request for that?

**Comment by victornoel** [comment]
Yes, that makes sense since an empty string is clearly useless in any case, so we can fallback on `getPathInfo()`.

And maybe if itself it is null or empty, we could have a third fallback method? but I'm not sure which… 
Maybe something like `request.getRequestURI().substring(request.getContextPath().length());` as advocated [here](http://stackoverflow.com/a/4278284)… but I'm not sure this case is not already covered by `getServletPath()`.

I'm preparing a PR :)

**Comment by victornoel** [comment]
Still, it's funny that we rely on `getServletPath()` first because its documentation really does not let assume that it will return the correct information…

And with dropwizard, in all my tests, even when using servlet filters (mapped to `/*` or to `/uri`), `getServletPath()` always return an empty string…

**Comment by leleuj** [comment]
In fact, `request.getRequestURI().substring(request.getContextPath().length());` works for me either. Does it work for you?

I think we can forget about the `getPathInfo()` method if the line above works for you and use it as fallback. Be sure to check for `null` values of the context path and request URI.

Thanks.

**Comment by victornoel** [comment]
Yep, it seems to work too… so let's only use that then

**Comment by victornoel** [comment]
Here it is, tell me what you think :)

**Comment by leleuj** [comment]
Excellent. Thanks.
