### ISSUE TITLE
OIDC Client with Identity Server 3  not working

### ISSUE THREAD

**Issue by Thomaswink80** [pac4j/pac4j#614]
Hello,

I want to try  pac4j with Spring Boot to authenticate and authorize on the Identity Server 3.
Unfortuntely, it's not working.
 
I am using the GoogleOidcClient class and setting the following parameters 

```

final GoogleOidcClient oidcClient = new GoogleOidcClient();
oidcClient.setClientID("test");
oidcClient.setSecret("6A23B244-5713-4A25-5E68-61B6B8A5E131");
oidcClient.setClientAuthenticationMethod(ClientAuthenticationMethod.CLIENT_SECRET_BASIC);
oidcClient.setDiscoveryURI("http://localhost:44333/connect/authorize");
oidcClient.setScope("openid");
Map<String, String> params= new HashMap<String,String>();
params.put("subject", "90342.ASDFJWFA" );
params.put("issuer", "http://localhost:8080/openid-connect-server-webapp/" );
params.put("redirectURI", "http://localhost:8100");
```

I am getting the following error message from the Identity server.
It seems that all the parameters are not recognized by the IdentityServer.

What am I doing wrong here ?

 

> 
> 18:07 [ERR] (IdentityServer3.Core.V
>  client_id is missing or too long
>  {
>   "SubjectId": "unknown",
>   "Flow": "AuthorizationCode",
>   "RequestedScopes": "",
>   "Raw": {}
> }

**Comment by leleuj** [comment]
The `GoogleOidcClient` is to login with Google using the OpenID Connect protocol, it has nothing to do with the Identity Server 3. Indeed, it does not work.

You need to use the generic `OidcClient`.

Please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
