### ISSUE TITLE
Errors into pac4j.org website

### ISSUE THREAD

**Issue by peyo** [pac4j/pac4j#615]
Hello,

You have 2 errors into your website pac4j.org :
- with the CAS documentation URL : replace https://jasig.github.io/cas/4.1.x/integration/Delegate-Authentication.html by https://apereo.github.io/cas/4.1.x/integration/Delegate- Authentication.html
- into the HTML page structure : last "small " tag is not closed

Regards

**Comment by leleuj** [comment]
Thanks for reporting the issues. It's fixed.
