### ISSUE TITLE
SAML2Client does not map ADFS role claims to user roles.

### ISSUE THREAD

**Issue by rhdunn** [pac4j/pac4j#633]
Using the `RequireAnyRoleAuthorizer` with a SAML2 client connected to an ADFS server, Role claims are not mapped to user roles, so the authorizer fails.

The ADFS roles are set as "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" claims. These appear as attributes, but do not appear as user roles.

**Comment by leleuj** [comment]
The link is broken, but it makes sense.

Would you mind submitting a PR for that?

**Comment by rhdunn** [comment]
That link is the claim ID (mapped to the SAML attribute name). See https://technet.microsoft.com/en-us/library/ee913589(v=ws.11).aspx for the claim type URIs supported by ADFS. See https://azure.microsoft.com/en-gb/documentation/articles/active-directory-token-and-claims/ for an example of the SAML XML.

I'll look into creating a PR.

**Comment by mmoayyed** [comment]
This can be closed now.

**Comment by leleuj** [comment]
OK. Thanks
