### ISSUE TITLE
nimbus-jose-jwt multiple dependencies in conflict between JWT and OIDC modules

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#636]
Gradle tells me:

```
com.nimbusds:nimbus-jose-jwt:4.22 -> 4.26
\--- org.pac4j:pac4j-jwt:1.9.1

com.nimbusds:nimbus-jose-jwt:[4.16,) -> 4.26
\--- com.nimbusds:oauth2-oidc-sdk:5.8
     \--- org.pac4j:pac4j-oidc:1.9.1
```

This is a problem.

**Comment by leleuj** [comment]
It was fixed a few days ago: https://github.com/pac4j/pac4j/commit/82f4178be08efbf41ba3384927a86062465d61fb#diff-e6725b703106cec1699a058fa91c9d66R16, but they cut too many releases. I'll fix it again.

**Comment by mmoayyed** [comment]
It would be well worth it to consider gradle as the pac4j build tool. Conflicts such as this can be easily detected.
