### ISSUE TITLE
Create a new wiki and improve documentation

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#641]

**Comment by mmoayyed** [comment]
Could we adopt the same model as CAS does? and move docs to source control directly?

**Comment by leleuj** [comment]
Yes, of course! What you did for CAS is my model here ;-) I'm currently moving the Github wiki into the Gihub pages: https://github.com/pac4j/pac4j/tree/gh-pages/wiki with Jekyll generation, then I'll add automatic Jekyll build and finally move the docs in the pac4j project with copy to the Github pages during the build.

**Comment by mmoayyed** [comment]
Very cool. If I can help, let me know plz.

**Comment by leleuj** [comment]
Writing a great documentation is a tremendous work and I realize the current documentation is way too light for all the capabilities pac4j offers. It's going to be easier when the documentation will be directly available in the pac4j project.

**Comment by leleuj** [comment]
The essential has been done, various improvements will follow when opportunities arise.
