### ISSUE TITLE
pac4j-saml: the velocity engine enforces an ISO-8859-1 input encoding instead of the designed UTF-8

### ISSUE THREAD

**Issue by pascalav** [pac4j/pac4j#642]
Hello,

There seemingly is a mistake in here, using the Velocity encoding defaults ISO-8859-1 as input, instead of the intended UTF-8:

https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/util/VelocityEngineFactory.java
>b9854a2 L26
>
>-props.setProperty(RuntimeConstants.ENCODING_DEFAULT, "UTF-8");
>+props.setProperty(RuntimeConstants.INPUT_ENCODING, "UTF-8");

Have a nice day.

**Comment by leleuj** [comment]
OK. Would you mind submitting a pull request for that? Thanks

**Comment by pascalav** [comment]
Sure. Here is done: https://github.com/pac4j/pac4j/pull/648 .

I could not find how to properly bind pull request to this issue. Maybe the reader-unfriendly "fixes #<ID>" would made it.

**Comment by leleuj** [comment]
"Closes #" does the binding.
