### ISSUE TITLE
Add a RunSAML2Client test

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#643]
From the lost class: `SAML2ClientIT` and subclasses...

**Comment by mmoayyed** [comment]
Thanks for tracking this.

I am thinking we should take this one step further: Build an embedded CAS server into pac4j for IT tests, and use that for both CAS and SAML tests. (We might optionally do one based on testshib but as you said, the service is a little unreliable). We might have an embedded CAS server in pac4j already, don't know, but it would be good to bump to CAS5 and have it be the external IdP for pac4j tests.

Sound good?

**Comment by mmoayyed** [comment]
Actually, thinking more about this: we don't need to embed. Probably could just run the tests manually and assume the env is up and running.

**Comment by leleuj** [comment]
Yes, I think it might be too much to have an embedded CAS server for that. For a major release, running the manual tests just takes a couple of minutes.

Thinking a little more about this, I think I removed the SAML test because we already check that via the various demos we have.
But we can certainly have one in pac4j (like for Facebook).

**Comment by leleuj** [comment]
Moving this one for 1.9.3, to start working on the 1.9.2 release.

I'll re-test the SAML support with manual tests on the demos (J2E & Play).
