### ISSUE TITLE
SAML AuthN requests are not signed, yet metadata says they should be

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#646]
Metadata generated by pac4j looks something like this:

```xml
<md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="true" 
protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol urn:oasis:names:tc:SAML:1.0:protocol urn:oasis:names:tc:SAML:1.1:protocol">
```

`AuthnRequestsSigned="true"`, yet pac4j is not actually signing authn requests. This setting should be taken into account when sending and building authn requests.

**Comment by mmoayyed** [comment]
Detected by CAS running in SAML2 mode:

```
<Metadata for [urn:mace:saml:pac4j.org] says authentication requests are signed, yet this authentication request is not>
```

**Comment by mmoayyed** [comment]
Still trying to make sense out of this. Pac4j definitely signs the authn requests based on that flag, however our encoder removes the signature before actually encoding it. In `Pac4jHTTPRedirectDeflateEncoder`, there is:

```java
 @Override
    protected void doEncode() throws MessageEncodingException {
        final MessageContext messageContext = this.getMessageContext();
        final SAMLObject outboundMessage = (SAMLObject)messageContext.getMessage();
        final String endpointURL = this.getEndpointURL(messageContext).toString();
        this.removeSignature(outboundMessage); //not sure why?
...
```

Behavior seems to be true for both opensaml 3.1 and 3.2.

**Comment by mmoayyed** [comment]
@leleuj This might be something for you to tackle or advise: assuming I can bypass the above issue, it appears that the `RunClient` machinery only handles GET and not POSTs. For SAML, the callback URL is always POSTed to by the IdP, and providing that url manually in the prompt does it no good.

**Comment by leleuj** [comment]
I need to take a closer look at this, we have some setting to indicate if the authentication request must be signed or not and this must be taken into account.

**Comment by mmoayyed** [comment]
Related post http://shibboleth.1660669.n2.nabble.com/HTTPRedirectDeflateEncoder-removing-AuthnRequest-signatures-tt7627970.html
