### ISSUE TITLE
Add support OAuth w/ DISQUS

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#65]
https://disqus.com/api/docs/auth/

**Comment by leleuj** [comment]
@mmoayyed : any plan on this?

**Comment by mmoayyed** [comment]
None yet. Lets mark it for 1.9 and I'll get around to it at some point. No high priority right now. I am focused on getting the SAML support working.

**Comment by leleuj** [comment]
Sure, SAML support is more important. Disqus could be supported in a 1.8.x as well.

**Comment by leleuj** [comment]
Do you still plan to work on this? Closing for now. Feel free to reopen with a contribution.
