### ISSUE TITLE
The attribute value of SAML profile is always a list

### ISSUE THREAD

**Issue by ruochao** [pac4j/pac4j#652]
From this: https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/client/SAML2Client.java#L223

Looks the attribute value is always like a list, even the value is single?
If this is true, then in CommonProfile, we have a lot of methods is convert value to string directly, do you think it's an issue?

**Comment by leleuj** [comment]
@ruochao : you raise a good point: by default, even single values are treated as lists. I guess it was done for consistency across all attributes, but indeed, the `CommonProfile` (from which inherited directly the `SAML2Profile`) has methods which expect single value (`String` mostly) so it won't work.

@mmoayyed do you confirm the issue or is there something we miss?

**Comment by mmoayyed** [comment]
This is an issue.

**Comment by leleuj** [comment]
@ruochao : would you mind submitting a PR to fix that by properly overriding the methods of the `CommonProfile` in the `SAML2Profile`? Thanks

**Comment by ruochao** [comment]
Sure, will do it.

**Comment by ruochao** [comment]
It will call profile.setAttribute for retrieving user profile, but the value is always list. So I think the attribute converter will not work either, right? Since it's checking if it's string.

I'm not sure which way is best to handle "getGender" and "getLocale" inside SAML2Profile class.

**Comment by leleuj** [comment]
Yes, things are not that easy. Generally, profiles are defined with attributes definition, but the `GenderConverter` applies to a `String`and not a strings list. And we already have attributes as string lists.

So I think you can keep the attributes as string lists and use the converters inside the new overriden `getGender` and `getLocale` methods.
