### ISSUE TITLE
Let the BooleanConverter instances to return false rather than null

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#654]
Example:

```java
public Boolean convert(final Object attribute) {
        if (attribute != null) {
            if (attribute instanceof Boolean) {
                return (Boolean) attribute;
            } 
            if (attribute instanceof String) {
                return Boolean.parseBoolean((String) attribute);
            }
        }
        return null; //not cool.
    }
```

> A method that returns either Boolean.TRUE, Boolean.FALSE or null is an accident waiting to happen. This method can be invoked as though it returned a value of type boolean, and the compiler will insert automatic unboxing of the Boolean value. If a null value is returned, this will result in a NullPointerException.

**Comment by leleuj** [comment]
Yes, it would be safer. I'll do it sooner unless you beat me.

**Comment by mmoayyed** [comment]
Sure thing. Go ahead. Going to be fairly busy until Wednesday
