### ISSUE TITLE
Automate the generation of SAML keystore for SP metadata

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#655]
The SAML functionality of pac4j requires that one does:

```
keytool -genkeypair -alias pac4j-demo -keypass pac4j-demo-passwd -keystore samlKeystore.jks -storepass pac4j-demo-passwd -keyalg RSA -keysize 2048 -validity 3650
```

Make this optional and automate this step. Let pac4j generate this keystore much like the SP metadata that is generated.

**Comment by leleuj** [comment]
I don't have a strong opinion on this. The `keytool` command is relatively common: won't it be too much work to develop that?

**Comment by mmoayyed** [comment]
I don't know :) Havent looked at what it would take to do this, but out-of-band processes are generally painful because:

1. Prone to error
2. Where is keytool?
3. Must we document it?
4. Cant do cloud deployments easily

**Comment by mmoayyed** [comment]
Just to clarify, I am trying to make it easier for folks to configure this stuff; those who may just have learned how to end an XML tag. Fairly different audience than what you may be used to in terms of developers.

**Comment by leleuj** [comment]
Understood. Do you plan that for 1.9.2 or 1.9.3?

**Comment by mmoayyed** [comment]
If we mean to go live with 1.9.2 in a couple of weeks, I think I can review and knock it out. Otherwise, we punt.

**Comment by leleuj** [comment]
Marked as 1.9.2, bu this can be postponed.
