### ISSUE TITLE
Let PropertiesConfigFactory reconize Google/Azure as OIDC clients

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#656]
The PropertiesConfigFactory generically creates an OidcClient. We may want to think about allowing that factory to also create instances of Azure and Google. Maybe something like `oidc.type` where the default would be the generic client, and types could be `azure`, `google`, etc.

**Comment by leleuj** [comment]
Yes, it makes sense. I like the `oidc.type`: fairly simple! I guess we can handle that for 1.9.2...
