### ISSUE TITLE
_site directory of docs should be removed and ignored

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#664]
Is it necessary to keep track of this directory in the repo? This is built and updated every time from source by GH right?

**Comment by leleuj** [comment]
No, we should not have it. I added it to `.gitignore`, but it does not seem to work.

**Comment by mmoayyed** [comment]
You probably should get it removed first, and then ignore it.

**Comment by leleuj** [comment]
Good point. Done. It fixes the issue.
