### ISSUE TITLE
Let the IpExtractor work on an alternative header name

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#677]
IpExtractor does this:

```
    public TokenCredentials extract(WebContext context) {
        String ip = context.getRemoteAddr();
        return ip == null?null:new TokenCredentials(ip, this.clientName);
    }
```

Add support so a header can be used instead, which might be useful for proxying scenarios.

**Comment by mmoayyed** [comment]
I think we might need a 1.8.10 or something for this patch as well.

**Comment by leleuj** [comment]
Yes, it makes sense and yes, we could have it for 1.8.x stream as well.

**Comment by leleuj** [comment]
@mmoayyed see: https://github.com/pac4j/pac4j/pull/679 for master and: https://github.com/pac4j/pac4j/pull/680 for the 1.8.x branch
