### ISSUE TITLE
Improve logging in case of Authentication failed

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#695]
Hi,

I noticed that when implementing an `Authenticator`, the only way it had to express that the credentials are not valid is by throwing a `BadCredentialsException`.

I also noticed that because of that, this exception is caught somewhere later and an error is logged like so:
```
ERROR [2016-09-29 15:47:46,367] org.ow2.petals.cockpit.server.security.CockpitAuthClient: Failed to retrieve or validate credentials
! org.pac4j.core.exception.BadCredentialsException: Bad credentials for: wrong
! at org.ow2.petals.cockpit.server.resources.MockAuthenticator.validate(UserSessionTest.java:154)
! at org.ow2.petals.cockpit.server.resources.MockAuthenticator.validate(UserSessionTest.java:1)
! at org.pac4j.core.client.IndirectClientV2.retrieveCredentials(IndirectClientV2.java:49)
! at org.pac4j.core.client.IndirectClient.getCredentials(IndirectClient.java:105)
! at org.pac4j.core.engine.DefaultCallbackLogic.perform(DefaultCallbackLogic.java:77)
...
```

I don't think it makes sense to log an error every time an user enter a wrong password.

I guess a solution would be to catch this particular exception and log a debug statement instead?

**Comment by leleuj** [comment]
Yes, in the `IndirectClientV2` and `DirectClientV2` classes, the log can be turned into an `INFO`.

Would you mind handling that?

**Comment by victornoel** [comment]
I think it's alright for this issue now, thanks!

**Comment by leleuj** [comment]
We still have this PR pending for 2.0: https://github.com/pac4j/pac4j/pull/696

**Comment by victornoel** [comment]
@leleuj it is not related I think, #696 is more about improving the use of the Exception and ensuring everything is is logged as it should… but this particular issue is ok with me at least :)
Well, we can still use this issue as a placeholder for discussion, but then the description should be updated.
