### ISSUE TITLE
Wrong exceptions thrown in LocalCachingAuthenticator

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#699]
Hi,

In my adventures around #697, I noticed that `LocalCachingAuthenticator` does not throw the correct exception in case of failure of `delegate.validate()`.

`cache.get` throws one of these three exceptions: `ExecutionException` (wrapping the checked `HttpAction` exception), `UncheckedExecutionException` (wrapping the unchecked `TechnicalException`, `CredentialsException` or any other `RuntimeException`) or `ExecutionError` (wrapping Error).

It seems that `LocalCachingAuthenticator.validate()` method should rethrow the original exceptions instead of wrapping any `Exception` into a `CredentialException`.

I don't use this component so I don't think I will have the time to submit a PR, but I thought it would be best to report the issue and this analysis at least :)

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/696

**Comment by victornoel** [comment]
@leleuj #696 does not contain fixes for this issue!

**Comment by leleuj** [comment]
You're right: I was part of it and removed, right?

**Comment by victornoel** [comment]
Yes, I think I still have a branch available locally with the fixes I made, I can submit it as a PR if you are interested, but I don't want to spend too much time on it, but it's a good basis for improvement if someone wants to change things.

**Comment by leleuj** [comment]
I think we can live with what we already have since you are the only reporter so far ;-)

So my feeling is: don't hesitate to close this issue if you don't have the time or don't think it's still worth it OR take your time to do it properly.

**Comment by victornoel** [comment]
erf, I will make a PR for what I have and we can see from there if something better is needed.
I think it is important for pac4j to fix this issue.

**Comment by leleuj** [comment]
PR: https://github.com/pac4j/pac4j/pull/722
