### ISSUE TITLE
Should the callback logic keep a previous session on authentication failure?

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#700]
Hi,

I noticed that after a first authentication via a callback succeeded, then if another authentication is done again on the callback and fails, then the previous session is kept.

Does it really make sense to do so? I would expect a failed authentication to clear out the previous session and authorization.

**Comment by leleuj** [comment]
Here is the idea: if you were authenticated and fail to login, you haven't lost your previous identity, you have failed to acquire a new one. Thus, we keep the old one.

Does it make more sense?

**Comment by victornoel** [comment]
If you see it like that yes :)

Optionally, it could make sense to add an option to choose between the two behaviours, but that's just an idea, I haven't thought so much about it...

**Comment by leleuj** [comment]
Marked as 2.0 if we'll find time to re-discuss during the version 2.0 development.

**Comment by leleuj** [comment]
@victornoel : have you given some more thoughts to this?

**Comment by victornoel** [comment]
@leleuj not really ^^

I think it depends on the application itself, because your use case is valid with some kind of applications, and my use case with another kind. It's also linked to the idea of multiprofile I guess…

So if we wanted to change current behaviour, I would say introduce an option to callbacklogic (in the same way there is the renew session or the multi profile option) to invalidate a profile on missed login.

We would keep current behaviour by default… no?

**Comment by leleuj** [comment]
I think the same debate has been going on quite some times lately (it's sound, no problem with that).

Are we addressing the right use cases? How extensible should we make the component?

In that case, I think we are (addressing the right use cases). I think other use cases are edge ones and subclassing the `CallbackLogic` class and the `saveUserProfile` method for that is enough for me.

**Comment by leleuj** [comment]
I'd like to close a few issues before the RC1.

@victornoel what are we doing on this?

**Comment by victornoel** [comment]
@leleuj no idea… I was going to say that we could simply forget about it, but I don't know how I can elegantly implement the desired behaviour via subclassing: when using dropwizard-pac4j, it's not easy to access the Filter manipulating the `CallbackLogic`, how is it done with the other frameworks?

**Comment by leleuj** [comment]
Generally, the filter is built with a default callback logic you can override by setter. It's just a matter of instantiating the subclassed logic instead of the default one.

Example in Play for the logout:

```java
public class ApplicationLogoutController extends Controller {

    private ApplicationLogoutLogic<Result, PlayWebContext> logic = new PlayApplicationLogoutLogic();
    // instead of DefaultApplicationLogoutLogic();
```

**Comment by victornoel** [comment]
This works for the developer of an integration such as play-pac4j or dropwizard-pac4j, but I was thinking about the user of this integration… how can one use play-pac4j or dropwizard-pac4j and implement this need? I don't see :/

**Comment by leleuj** [comment]
For Play, it is straightforward as the `CallbackController` is instantiated in the DI module (https://github.com/pac4j/play-pac4j-java-demo/blob/master/app/modules/SecurityModule.java#L118). I can set there the specific logic I want.

I'm not against this change if you have a good proposal which is necessary for Dropwizard.

**Comment by victornoel** [comment]
So, after some though, and thanks to the discussion in pac4j/jax-rs-pac4j#13, I think the best is that dropwizard-pac4j should give the possibility to easily use a custom `XXXFilter` with a different `XXXLogic`.
In that way, such use case as the one discussed here can be handled by users.

**Comment by leleuj** [comment]
I would not create anything specific in dropwizard as we already have this option (we did that for Play), you can define the `SecurityLogic` in the `Config` object (https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/config/Config.java#L159). We could do the same for the `CallbackLogic`. Thus, no need to create custom filters.

**Comment by victornoel** [comment]
@leleuj I will still need it for pac4j/jax-rs-pac4j#13 because the thing to override is in the jax-rs filter itself…

**Comment by victornoel** [comment]
but yeah, if there is setters for the logout logic and the callback logic, I will use it in jax-rs-pac4j then!
But only if the three of them are present :)

**Comment by victornoel** [comment]
Feel free to close this issue then @leleuj! great discussions and decisions :)
