### ISSUE TITLE
FormClient seems to return 403 instead of 401 sometimes

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#704]
Apparently, sometimes FormClient returns a 403 in case of authentication error (not authorization).

It should return a 401.

I guess it is happening in `org.pac4j.http.client.indirect.FormClient.retrieveCredentials(WebContext)`...

**Comment by leleuj** [comment]
Yes, I see a 403 in the `FormClient` source code. But I think it's a mistake: if the credentials validation fails (even if we have credentials), it should return a 401.
