### ISSUE TITLE
Move session renewal to SessionStore instead of subclasses of DefaultCallbackLogic

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#711]
Hi,

Why isn't session renewal one of the methods implemented by `SessionStore`s instead of putting the logic in subclasses of `DefaultCallbackLogic`?

`DefaultCallbackLogic` could simply contains the following:

```
    protected void renewSession(final WebContext context) {
        final SessionStore sessionStore = context.getSessionStore();
        if (sessionStore != null) {
            logger.debug("Discard old session and replace by a new one...");
            sessionStore.renewSession(context);
        }
    }
```

And `SessionStore` contains the following then:

```
void renewSession(WebContext context);
```

**Comment by millross** [comment]
What’s the use case for renewal? I don’t think this is something offered by all frameworks anyway (some do their own session management), but it could be a no-op for those frameworks’ session store implementations in which case it does make sense for it to be a SessionStore exposed operation.

Shouldn’t be JaxRsContext though, surely in the SessionStore interface.

**Comment by victornoel** [comment]
@millross oh yes, you are right about `JaxRsContext` :) I will correct this.

I don't know what is the use case actually for renewing session… I would prefer to have it not enabled by default actually!
But I was thinking that as long as there was some `SessionStore`, the concept of session renewal makes sense, so it could be implemented at the `SessionStore` level.

**Comment by millross** [comment]
What does session renewal mean? Throwing away all data in the session? If so this would rather be exceeding pac4j's authority. It's perfectly reasonable to have non-authentication/authorization information in the session. If we want to go down this route, our implementations need to be very strict about what they'll delete from a session - we shouldn't throw away the contents of a shopping basket, for example. In short, we can't assume we own everything in someone's session, unless what our session store really does is write to a map or similar which is written into the session with that key.

**Comment by victornoel** [comment]
@millross I'm not sure exactly, you can see the actual implementation for servlet-based container in `J2ERenewSessionCallbackLogic` from j2e-pac4j. @leleuj would better answer those questions I think.

In practice, currently, the session is invalidated and then a new session is created and is repopulated with the previous session attributes. I guess the idea was to prevent sessions from expiring, so after every new login (from the callback), the session would be renewed. So there is no worries about deleting stuffs for sure.

**Comment by millross** [comment]
I don't think the vert.x session implementation would support doing that. And I'm also not convinced we should prevent sessions from expiring, if they are configured to do so. So I'm 100% sure that renewSession would be a noop for vert.x (that said, if we are going to make the renewal of sessions a general behaviour then I agree with the movement to SessionStore so each framework can decide whether implementation is appropriate).

**Comment by millross** [comment]
Looking at vert.x the timeout is an idle timeout anyway, so there is no need for renewal. Reading/writing to the session resets the timeout clock, which achieves the same as the renewal intent you've mentioned.

**Comment by victornoel** [comment]
So you agree that for vert.x, it would mean simply making the session renewal a noop in the its `SessionStore` implementation instead of making it a noop inside the `DefaultCallbackLogic` as it is currently the case?

The issue is not about making session renewal mandatory, I'm just wondering why this specific functionality around the `SessionStore` is not inside the `SessionStore` implementation…

**Comment by victornoel** [comment]
(in the context of the 2.0.0 version of pac4j that is the next major version if I understood correctly)

**Comment by millross** [comment]
Completely and I think it's right to do this as the need for renewal is likely to be SessionStore specific.

**Comment by leleuj** [comment]
The session renewal is a security measure against https://en.wikipedia.org/wiki/Session_fixation

And indeed, the logic should be held in the `SessionStore`. So it could be a no-op implementation in Vert.x
This is what I already explored: https://github.com/leleuj/pac4j/blob/expcaslogout/pac4j-core/src/main/java/org/pac4j/core/context/session/SessionStore.java#L79 and planned to implement in the starting (I hope next week) version 2.0.

**Comment by millross** [comment]
Seems reasonable. I think I might ask the vert.x guys to offer session renewal on their session side so I could trigger it.

**Comment by victornoel** [comment]
@millross as long as you have a way to invalidate a session, it should be easy to implement session renewal on your side (simply save all the session attributes before and put them in a new session after). For example I don't think servlet abstractions provides session renewal, pac4j implements it itself. The same for other existing containers.

**Comment by millross** [comment]
I don't think this is feasible in vertx-web. Session spawning is handled for you by the web tier. There's no mechanism to spawn a new one via code.
