### ISSUE TITLE
Pac4J + Spring Boot?

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#717]
https://docs.google.com/document/d/1k-Cw8QiRHVA91nI-rww4Bh1ealU-qa0avBmUbDCofqQ/edit#heading=h.kdpv4vsgwf36

**Comment by leleuj** [comment]
@mmoayyed Any progress on this?

**Comment by leleuj** [comment]
@mmoayyed what's the final status on this?

The idea is appealing, but I don't really know what you have in mind to push this topic further.

Can you sketch out the solution you envision or close this issue if this is not really practical?

**Comment by mmoayyed** [comment]
Oh, sorry. I don't know how I missed your earlier notification. For a while, github emails somehow found their way into my spam box. 

So, we probably could start with pac4j-springboot-starter project similar to boot's model. The idea would be to auto-create pac4j objects based on a configuration scheme in a boot application. That's the general outline; practically I am not sure I'd have any time available to work on this. Perhaps something to icebox?

**Comment by leleuj** [comment]
No problem. I'm the first one to know how hard it is to be involved in two major projects and you're already doing so much for CAS.

I'll mark it as `FUTURE` and revisit it after the final release. Unless you do it before me.

**Comment by mmoayyed** [comment]
@leleuj what do you think about a sub-module here that basically acts as a starter module for Spring Boot? One that has AutoConfiguration type of classes that auto-create clients based on presence of settings or classes on the classpath, etc. Should we start with a separate project altogether maybe?

**Comment by leleuj** [comment]
Anything to start something on this is certainly a good idea.

We already have a `pac4j-config` module we can use to build a full pac4j configuration (`Config`) from properties (see: https://github.com/pac4j/pac4j/blob/master/pac4j-config/src/main/java/org/pac4j/config/client/PropertiesConfigFactory.java).

Maybe it's enough to build the pac4j configuration or we should check things in the classpath as well.

Given that strong dependency, I think we can start it as a submodule of the `pac4j` project.

**Comment by mmoayyed** [comment]
That all sounds really good to me. Could you create the project structure in master? I'll probably start this week on Friday. Should be quick!

**Comment by leleuj** [comment]
Sure. Here we go for the new module: https://github.com/pac4j/pac4j/tree/master/pac4j-springboot
It's very basic.

**Comment by mmoayyed** [comment]
I have started to work on this. Should have a pull request ready quite soon.

**Comment by leleuj** [comment]
@mmoayyed Did you finally prepare something on this?

**Comment by mmoayyed** [comment]
Yes, I am extracting this module from a project I worked on earlier. Been working on it on and off, and might be able to finalize before the GA release. I'll publish a WIP PR in the next few weeks for review.

**Comment by leleuj** [comment]
No hurry on this, I just wanted to check...

**Comment by leleuj** [comment]
Addressed by the new module: `pac4j-springboot`.
