### ISSUE TITLE
FacebookClient and Facebook API 2.8

### ISSUE THREAD

**Issue by ArkadyKarev** [pac4j/pac4j#740]
I trying to use FacebookClient (pac4j-oauth 1.9.3) with newly created FB application. Now all new apps will be created with api version 2.8 and this version cannot be downgraded, and I getting following error:
`[HttpCommunicationException: Failed to retrieve data / failed code : 400 and body : {"error":{"message":"(#12) bio field is deprecated for versions v2.8 and higher","type":"OAuthException","code":12,"fbtrace_id":"F\/E87eGaogN"}}]
`

**Comment by leleuj** [comment]
You should use version 1.9.4 (security fix).

With the `setFields` setter, you can control which fields are requested. We could also upgrade to use the version 2.8 API: https://github.com/pac4j/pac4j/blob/master/pac4j-oauth/src/main/java/org/pac4j/oauth/client/FacebookClient.java#L58

Would you mind submitting a PR for that (on the 1.9.x branch and on the master)? Thanks

**Comment by ArkadyKarev** [comment]
@leleuj Sure, i've already prepared commit, and have tested it locally.
