### ISSUE TITLE
JWT UserInfo response ignored

### ISSUE THREAD

**Issue by gpgekko** [pac4j/pac4j#747]
The code at [OidcProfileCreator.java, line 155](https://github.com/pac4j/pac4j/blob/master/pac4j-oidc/src/main/java/org/pac4j/oidc/profile/creator/OidcProfileCreator.java#L155) only processes information from the `getUserInfo` accessor, but the `parse` method called above explicitly sets the `claimsSet` property to `null` if the content is a JWT. I think there should be an `else` statement there that also checks the `getUserInfoJWT` accessor.

**Comment by leleuj** [comment]
Indeed, it might be some missing use case. For which OIDC provider did you encounter the issue?

Would you mind submitting a pull request for that?

**Comment by gpgekko** [comment]
I'll try to get a PR up today.

I encountered this while playing around with the settings of a private Keycloak instance. The application kept breaking when I enabled JWT. After a bit of digging I noticed that claims were missing from the profile.
