### ISSUE TITLE
Build support for SAML1 authN delegation

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#750]
We presently only support SAML2 SSO profiles. Have run into a few legacy apps where they only support SAML1 or SAML2 Http-Artifact. The former is easier to start with and support

**Comment by leleuj** [comment]
Sure. Go ahead.

You have now several things to tackle with SAML:

- move to IndirectClientV2 with a SamlRedirectActionBuilder, SamlCredentialsExtractor, SamlAuthenticator... (https://github.com/pac4j/pac4j/issues/622)
- reduce the source code base by using Spring especially for files handling (https://github.com/pac4j/pac4j/issues/721)
- add a SAML1Client (https://github.com/pac4j/pac4j/issues/750).

Either you do all in the same pass or one by one. Your choice. But this will be a big improvement as SAML is one of our key features.

**Comment by mmoayyed** [comment]
I'll probably start with this one first and then move onto the rest. To me at this point, this issue is a required feature.

**Comment by leleuj** [comment]
I just merged the latest PR for the "CAS internals support" refactoring. So you have a cleaned SAML support from this point.

**Comment by mmoayyed** [comment]
Update: I may end up backing out of this one, depending on how my client wishes to proceed. SimpleSAMLPHP seems like a much better option for this at this moment.

**Comment by leleuj** [comment]
No problem. As far as I know, we have never received any inquiry about SAML 1. It looks dead to me. I'm in favor of closing this issue.

**Comment by mmoayyed** [comment]
Discussed with client. Not needed. 

I will likely open up a separate issue to work on SAML2 Artifact delegation, once I get confirmation.
