### ISSUE TITLE
Break up the default logout logic and controller

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#754]
Break the ApplicationLogoutController and the DefaultLogoutLogic into composeable parts so each piece can individually be overridden if need be.

**Comment by millross** [comment]
Agree with this, we should be aiming for ease of changing the default behaviours. Subclassing is far less attractive than composition for this IMO

**Comment by leleuj** [comment]
Yes, I can only agree that composable parts are generally better.

That said, extensions should be made easy when it's a likely case like the new `ProfileDefinition` as most people want to change the returned user profile.
For logics, it was meant to be subclassed only as it should never change: it's really too complicated and dangerous for someone to play with that. I don't think it's a good idea to make easy to change the core logics of the pac4j security model.

**Comment by leleuj** [comment]
I'd like to close a few issues before the RC1.

@mmoayyed @millross whar are we doing on this?

**Comment by leleuj** [comment]
Closing. To be re-opened if necessary.
