### ISSUE TITLE
Azure AD Roles vs Attributes

### ISSUE THREAD

**Issue by sbuster** [pac4j/pac4j#756]
I've successfully authenticated against Azure AD and I have setup an application with a set of roles.  On my pac4j profiles I see an attribute value set that lists my roles, but I would expect this to be a value in the Role list, not the attribute list.  
In the uploaded image you can see the attribute has a setting, but there are roles.  However, in AD I add the user the 'Configurator' role.

![azure](https://cloud.githubusercontent.com/assets/547571/20578175/a8080fe8-b18b-11e6-9e8b-bab9386a1c6f.jpeg)

**Comment by leleuj** [comment]
I guess we should have a special [`AuthorizationGenerator`](http://www.pac4j.org/1.9.x/docs/clients.html#compute-roles-and-permissions) for AzureAD which turns these roles attributes into profile roles. It should not be too complicated.

Would you mind submitting a pull request for that?

**Comment by leleuj** [comment]
Any feedback on this?

**Comment by leleuj** [comment]
Closing this one. Feel free to reopen with a contribution.
