### ISSUE TITLE
FromAttributesAuthorizationGenerator should support other collections

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#758]
There exists:

```java
    public FromAttributesAuthorizationGenerator(String[] roleAttributes, String[] permissionAttributes) {
        this.roleAttributes = this.copyArray(roleAttributes);
        this.permissionAttributes = this.copyArray(permissionAttributes);
    }
```

Also add support for lists and perhaps sets, as convenience ctors.

Other generators likely need to be massaged as well.

**Comment by victornoel** [comment]
Let's simply accept `java.util.Collection` or even `java.lang.Iterable` and stay high-level (no array) maybe?

**Comment by leleuj** [comment]
I have no cut view on this, but we can certainly add some more constructors.

**Comment by mmoayyed** [comment]
I like Victor's proposal. Shall I do a PR then?

**Comment by leleuj** [comment]
Yes please.
