### ISSUE TITLE
Upgrade from 1.8.3 to 1.9.4 makes FacebookClient to generate sessionState parameters several times

### ISSUE THREAD

**Issue by alvarosanchez** [pac4j/pac4j#762]
Hi,

I'm using pac4j as part of  https://github.com/alvarosanchez/grails-spring-security-rest[Spring Security REST for Grails]. Your library has been just working fantastically well since 2014, so thanks for your awesome work.

I periodically try to upgrade to the latest version, and now I'm trying to upgrade from 1.8.3 to 1.9.4. What I found is that for OAuth 2.0 clients, sessionState gets generated twice. I have an `authenticate` action that does the redirect, and a `callback` action that receives the callback.

`authenticate`:
```groovy
BaseOAuthClient client = restOauthService.getClient(provider) //this returns a FacebookClient.
WebContext context = new J2EContext(request, response)
RedirectAction redirectAction = client.getRedirectAction(context)

//Redirect to redirectAction.getLocation()
```

The logs I see in the console:

```
DEBUG org.pac4j.oauth.client.BaseOAuth20Client - save sessionState: 11f63c2c18
DEBUG org.pac4j.oauth.client.BaseOAuth20Client - save sessionState: 9bda3caa9f
DEBUG org.pac4j.oauth.client.BaseOAuth20Client - authorizationUrl: https://www.facebook.com/v2.5/dialog/oauth?client_id=585495051532332&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth%2Fcallback%2Ffacebook&scope=public_profile%2Cemail&state=9bda3caa9f
```

Note the state generated twice.

Then, the callback comes from Facebook:

```groovy
WebContext context = new J2EContext(request, response)
BaseOAuthClient client = getClient(provider) //FacebookClient
Credentials credentials = client.getCredentials(context) //this throws the exception: State parameter mismatch: session expired or possible threat of cross-site request forgery
```

Logs:

```
DEBUG org.pac4j.oauth.client.BaseOAuth20Client - save sessionState: 9cb45af578
DEBUG org.pac4j.oauth.client.BaseOAuth20Client - sessionState: 9cb45af578 / stateParameter: 9bda3caa9f
```

For some reason, the state is generated 3 times, the 2nd is what gets sent to Facebook, and the 3rd is what gets compared.

Any idea what I might be doing wrong?

Thanks!

**Comment by leleuj** [comment]
Indeed, you're right, the `sessionState` is generated more than once.

Testing the Facebook support (https://github.com/pac4j/spring-security-pac4j-boot-demo), I see that it's generated twice, but it works eventually:

```
DEBUG 33505 --- [nio-8080-exec-2] o.pac4j.oauth.client.BaseOAuth20Client   : save sessionState: 49612562d1
DEBUG 33505 --- [nio-8080-exec-2] o.pac4j.oauth.client.BaseOAuth20Client   : save sessionState: 94b5aec0c8
DEBUG 33505 --- [nio-8080-exec-2] o.pac4j.oauth.client.BaseOAuth20Client   : authorizationUrl: https://www.facebook.com/v2.5/dialog/oauth?client_id=145278422258960&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fcallback%3Fclient_name%3DFacebookClient&scope=user_likes%2Cuser_about_me%2Cuser_birthday%2Cuser_education_history%2Cemail%2Cuser_hometown%2Cuser_relationship_details%2Cuser_location%2Cuser_religion_politics%2Cuser_relationships%2Cuser_website%2Cuser_work_history&state=94b5aec0c8
DEBUG 33505 --- [nio-8080-exec-3] o.p.c.e.J2ERenewSessionCallbackLogic     : === CALLBACK ===
DEBUG 33505 --- [nio-8080-exec-3] o.p.c.e.J2ERenewSessionCallbackLogic     : client: #FacebookClient# | name: FacebookClient | callbackUrl: http://localhost:8080/callback?client_name=FacebookClient | callbackUrlResolver: org.pac4j.core.http.DefaultCallbackUrlResolver@cd06ee1 | ajaxRequestResolver: org.pac4j.core.http.DefaultAjaxRequestResolver@6f00f034 |
DEBUG 33505 --- [nio-8080-exec-3] o.pac4j.oauth.client.BaseOAuth20Client   : sessionState: 94b5aec0c8 / stateParameter: 94b5aec0c8
```

In your case, there must be something else: I guess I remember someone having the same issue (on the mailing list): are you sure you don't several protected URLs called at the same time?

The OAuth has been strongly rebuilt in version 2.0, maybe the double generation has been fixed, I'll check that very soon.

**Comment by alvarosanchez** [comment]
In my case, the problem is that the session state gets generated again on the callback. The 3 lines I posted is really all the code that relates to pac4j. Where should I look at to find why the state is generated again?

**Comment by alvarosanchez** [comment]
I also noted in your example you use `client.redirect()` whereas I'm using `client.getRedirectAction()`. Would that difference matters?

**Comment by leleuj** [comment]
Isn't your callback a protected URL? 
Yes, the  `getRedirectAction()`  method returns the redirect action to perform while the `redirect` method actually performs the redirection on the web context. What do you do with the `RedirectAction` you retrieve?

**Comment by leleuj** [comment]
Did you try to put some breakpoint where the session state is generated just to see where the calls come from?

**Comment by leleuj** [comment]
Fixed in 2.0: the generation happens only once.

**Comment by alvarosanchez** [comment]
Thanks, I'll upgrade to 2.0

**Comment by leleuj** [comment]
2.0 is not ready yet, but the first RCs should come up in February...
