### ISSUE TITLE
Provide CasRestBasicAuthClient with CasConfiguration

### ISSUE THREAD

**Issue by jonathanlabin** [pac4j/pac4j#766]
Modify CasRestBasicAuthClient to retrieve loginURL from an instance of CasConfiguration rather than it's own casServerPrefixUrl field.

Be sure that the CallbackResolver is applied when resolving the loginURL.

See discussion at:
https://groups.google.com/d/msg/pac4j-users/NZPRbKFMe0c/tHec-xb_BQAJ

**Comment by leleuj** [comment]
@jonathanlabin do you plan to submit a PR?

**Comment by jonathanlabin** [comment]
Sorry, other projects came up at work recently that took priority.
I will still likely need this modification so that REST applications can dynamically receive configuration from the CallbackResolver.  However it's hard to know when that project will take priority again until it does.

**Comment by leleuj** [comment]
No problem. I'll do it when I have some time.

**Comment by leleuj** [comment]
@jonathanlabin See: https://github.com/pac4j/pac4j/pull/814
