### ISSUE TITLE
Make CasRestProfile inherit from the CasProfile instead of CommonProfile

### ISSUE THREAD

**Issue by jonathanlabin** [pac4j/pac4j#767]
Modify CasRestProfile so that it inherits from CasProfile.

This is driven by a desire to enable customization of CasRestAuthenticator that obtains a CasProfile for the user which contains profile attributes.

See discussion at:
https://groups.google.com/d/msg/pac4j-users/NZPRbKFMe0c/wWszyoTdBwAJ

**Comment by leleuj** [comment]
@jonathanlabin do you plan to submit a PR?

**Comment by jonathanlabin** [comment]
Sorry, other projects came up at work recently that took priority.
I will still likely need this modification so that REST applications can receive a cas profile during authentication.  However it's hard to know when that project will take priority again until it does.

**Comment by leleuj** [comment]
No problem. I'll do it when I have some time.

**Comment by leleuj** [comment]
@jonathanlabin Making the `CasRestProfile` inherit from the `CasProfile` does not really bring any value as long as the CAS REST clients return a `CasRestProfile`. And changing the REST clients to return a `CasProfile` makes things confusing as they by default really return a `CasRestProfile` (and thus a cast is required).

Also, customising the `CasRestAuthenticator` as I proposed initially may not be the best solution as the necessary `requestServiceTicket` and `validateServiceTicket` methods are part of the `AbstractCasRestClient`.

I will wait for your real implementation.

**Comment by leleuj** [comment]
Closing. Waiting for a proposal.
