### ISSUE TITLE
Consider producing milestone/release-candidate releases

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#769]
Freeze the codebase at known intervals to allow eager adopters to try without the dangers of receiving breaking snapshot changes.

**Comment by leleuj** [comment]
I can only agree, though you must notice that it's more work for pac4j (as you need a RC for the pac4j lib then a RC for the pac4j implem) than for CAS.

Let's plan a RC1 for April 2017.

**Comment by mmoayyed** [comment]
That seems way too late to me. How about end of December? [You don't really need to update all of the impls at the same time. This is just to make the lives of early core adopters easier]

**Comment by mmoayyed** [comment]
Plus, if you make an RC available soon it's much easier to ask the community to update the impl via PR incrementally.

**Comment by leleuj** [comment]
End December seems too early for me. Major changes are still expected (SAML, clients V2...)

How about end January / mid-February?

And indeed, we'll only upgrade the main implementations first.

**Comment by mmoayyed** [comment]
End of January is better. The sooner the better. (My vote is every month really) These are milestones; they can break things iif needed.

**Comment by victornoel** [comment]
So are we aiming for end of January 2.0.RC1 in the end?
Would be good to release RCs for the frameworks integrations as well, I will do it for jax-rs and dropwizard :)

**Comment by leleuj** [comment]
Yes, this is the Plan. I'd like to release RCs for the following implementations: j2e-pac4j, spring-webmvc-pac4j, play-pac4j and maybe buji-pac4j or spring-security-pac4j.

It might shift a little to February though, as the final release is planned for May.

**Comment by victornoel** [comment]
ok, cool, then I will do the same for jax-rs and dropwizard (which uses j2e), I won't start now, but first finish the 1.1.0 before I think.

**Comment by leleuj** [comment]
Closing this one as we agree on releasing Release Candidates before the final release. RC1 is planned for next week or so. RC2 for end February...
