### ISSUE TITLE
OIDC Implicit Flow query string issue

### ISSUE THREAD

**Issue by lionelg3** [pac4j/pac4j#771]
I found the following issue in the implicit flow with a PAC-OIDC client : 

When the succesful redirect request like this one is sent by the OIDC server : 
"http://localhost:8081/callback?client_name=OidcClient#access_token=eyJra....."

The request fail because params of the query string are not evaluate after "#".

PAC4J works fine if I change the "#" with "&" by hand.

According the specs, having "#" is a correct answer (http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse), but it can not be parse using standard servlet parser.

**Comment by leleuj** [comment]
Yes, you're right. In fact, we can't entirely support the implicit flow as it also needs to be handled front side (by Javascript code) while pac4j is a server-side library.
Though, we support the implicit flow anyway as we are able to start it.

**Comment by lionelg3** [comment]
I understand. I will try to use a regular expression in the reverse proxy.
