### ISSUE TITLE
Overwrite DeadboltHandler#getPermissionsForRole to @RoleBasedPermissions works

### ISSUE THREAD

**Issue by mikefarias** [pac4j/pac4j#772]
i'm following guide to use deadbolt library authorization.
I not be able to use `@RoleBasedPermissions` annotations. 
After check the actions implementation I found the use of `DeadboltHandler#getPermissionsForRole` that is not implemented by `Pac4jHandler` and returns empty list.

**Comment by heat** [comment]
+1
Same problem here

**Comment by leleuj** [comment]
This issue should have been opened in https://github.com/pac4j/play-pac4j directly.

Indeed, this method inherits the default behavior of the interface (an empty list of permissions).

In Deadbolt, permissions are linked to a role, so reading the documentation: "If you choose to associate permissions with roles, you should implement the getPermissionsForRole method. "

But it's not the case in pac4j as a user profile has roles and permissions and no specific link between them.

What do you expect this method to return? The list of the permissions of the user profile, regardless of the requested role?

**Comment by millross** [comment]
@leleuj Maybe we should permit injection of an object which provides access to permissions for a given role into the relevant handler (or even a function if it's not being done declaratively). Presumably getPermissionsForRole is likely to relate to an application-defined relationship outside pac4j. Then if this object is injected, we delegate to its permissions retriever for getPermissionsForRole, otherwise we use default behaviour?

Does this make sense?

**Comment by leleuj** [comment]
Yes, it seems indeed somehow outside the scope of pac4j. It should certainly be handled by the appropriate handler.

@mikefarias @heat : what's your proposal on this?

**Comment by heat** [comment]
@leleuj why not just return the `UserProfile#getPermissions` ? If pac4j aren't Role-Permission linked then all permisions are valid. 

My solution was extends and implements the method `Pac4jHandler` .

@millross  I agree, delegate would be a more elegant solution.

**Comment by leleuj** [comment]
@heat : yes, it seems the easiest solution. Would you mind submitting a PR for that?

**Comment by heat** [comment]
Sure. As soon as possible I submitting in correct Project play-pac4j

**Comment by leleuj** [comment]
Moving this discussion to: https://github.com/pac4j/play-pac4j/issues/163
