### ISSUE TITLE
Refactor database-based authenticators?

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#777]
Hi,

@wardr implemented its own `DbAuthenticator` (see [this discussion](https://groups.google.com/d/msg/pac4j-users/F3B1FBFvumg/QO1pn_h7DwAJ) on the mailing list) and reading the code, I was wondering if it wouldn't make sense to rebase pac4j's `MongoAuthenticator` and `DbAuthenticator` on top of something similar (he implemented his own password encoder, but that would of course be replaced by pac4j's).

The justification would be that both `MongoAuthenticator` and `DbAuthenticator` are two different ways of querying a database, and there is some duplication between the two of them.
In past I already tried to factor some code in the `MongoAuthenticator` because I wanted to use another library than the official mongo implementation. I think this is in the same vein, but more generic.
We would provide some implementations for mongo and jdbc like we currently do, and we could then let people subclass it and focus on their database needs without bothering with the common functionalities (see for example a [subclassing](https://github.com/wardr/dropwizard-pac4j-demo/blob/master/src/main/java/com/uberlogik/demo/security/JooqAuthenticator.java) of @wardr implementation).

WDYT @leleuj? :)

**Comment by leleuj** [comment]
Yes, it's an excellent suggestion. But I didn't do this refactoring because of: https://github.com/pac4j/pac4j/issues/342 and https://github.com/pac4j/pac4j/issues/339

To deal with account linking and registration, we'll need a `ProfileService` which is able to save a profile and query a profile by an identifier.

So we'll end up with:

1) a `MongoProfileService` and `MongoAuthenticator` sharing an `AbstractMongoDao`
2) a `DbProfileService` and `DbAuthenticator` sharing an `AbstractDbDao`.

Rather than a `MongoAuthenticator` and `DbAuthenticator` sharing an `AbstractAuthenticator`.

Does it make sense?

**Comment by victornoel** [comment]
@leleuj Why not have something generic for the `ProfileService` and the `Authenticator`, let's say `DaoProfileService` and `DaoAuthenticator` and both would need an `AbstractDao` (or even a interface) that provides all that is database-oriented to access users data.
Then `MongoDao`, `LdapDao` or `DbDao` would subclasses/implements `AbstractDao`.

This design answers the need for easily defining database-specific and schema-specific implementations by pac4j users. I feel like the functionalities of the `ProfileService` and `Authenticator` could be generic… 
No?

**Comment by leleuj** [comment]
I'm not sure to follow you, but maybe there is more to share between both authenticators than between the `MongoProfileService` and the `MongoAuthenticator` for example.
That said, these are fairly small classes so I don't think we should create a too complicated class hierarchy just to share a few methods.

A pull request would help getting a better vision of what we can do...

**Comment by victornoel** [comment]
Ok, I will try to find some time for a PR, not before next year though ;)

My main point was that I didn't like the fact that if someone wants to use its own db schema/driver, he would have to subclass every Service/Authenticator that needs access to the db one by one. I would have preferred to have generic implementations for each of these services/authenticator that would all need one implementation for the actual db accesses.

**Comment by leleuj** [comment]
@victornoel Don't start working on this. I will address this fairly naturally in the future PR for #339 and #342 (https://github.com/leleuj/pac4j/tree/pac4j-339).

**Comment by victornoel** [comment]
@leleuj alright, and sorry I never took the time to make a PR on that subject! it stills there in the corner of my mind though :)

**Comment by leleuj** [comment]
@victornoel see: https://github.com/pac4j/pac4j/pull/848 and especially this component: https://github.com/pac4j/pac4j/pull/848/files#diff-d54f601e4ac61aca76c3946c8d609263R26 shared between LDAP, SQL and MongoDB.

**Comment by victornoel** [comment]
Ok, I see what you meant, I think it's best you go on with your changes without worrying about what I had in mind, things changed too much since that time.
I will play with it and see how it feels soon :)
