### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by BerndSerker** [pac4j/pac4j#779]
The documentation needs a lot more sample implementations to make it easier to understand for new developers. Its a struggle to get the needed information, mostly a long search in source code files brings you closer to the answer.

For example, the authentication process for a login should be described in more detail:
  How calls the validate function?
  What happens in the security logic?
  ...

**Comment by leleuj** [comment]
Which framework do you use? The `README` file should give a pretty good understanding how pac4j works. Then, specific configurations may be detailed on the www.pac4j.org website.

For example, using [`j2e-pac4j`](https://github.com/pac4j/j2e-pac4j), you start reading what it is and what are the main concepts: `client`, `authorizer`, `SecurityFilter`, `CallbackFilter` and `LogoutFilter`. Then, you can read the required dependencies, the configuration, how to protect URLs using the security filter...
And especially:
```
You can protect (authentication + authorizations) the urls of your J2E application by using the SecurityFilter and defining the appropriate mapping. It has the following behaviour:

1) If the HTTP request matches the matchers configuration (or no matchers are defined), the security is applied. Otherwise, the user is automatically granted access.

2) First, if the user is not authenticated (no profile) and if some clients have been defined in the clients parameter, a login is tried for the direct clients.

3) Then, if the user has a profile, authorizations are checked according to the authorizers configuration. If the authorizations are valid, the user is granted access. Otherwise, a 403 error page is displayed.

4) Finally, if the user is still not authenticated (no profile), he is redirected to the appropriate identity provider if the first defined client is an indirect one in the clients configuration. Otherwise, a 401 error page is displayed.
```

Isn't it clear enough?

**Comment by leleuj** [comment]
Feel free to ask any question on the mailing list: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
