### ISSUE TITLE
TechnicalException:  Do not use the resource: or classpath: prefix for non-existing files

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#782]
Happy new year!

```
Do not use the resource: or classpath: prefix for non-existing files. Use a direct path (relative or absolute, no prefix)
```

Why would I want to use ANY sort of path when something is non-existing?

**Comment by leleuj** [comment]
Happy new year! This is exactly what the error message intends to say. The use case is for a non-existing keystore which will be automatically created. These prefixes must be clearly revisited in version 2.0.
