### ISSUE TITLE
IndirectClient are not initialised soon enough in getRedirectAction

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#787]
Hi,

I think that in the implementation of `IndirectClient.getRedirectAction()` the call to `init(Context)` should be at the beginning.

For example, it relies on `ajaxRequestResolver` in the beginning, and at that moment, we are not sure it has been correctly initialised (since `internalInit()` does verify that it is different than `null`).

**Comment by leleuj** [comment]
You're right. I wanted to delay the initialization as much as possible, but it should be at the beginning here.

Would you mind submitting a PR for that?

**Comment by victornoel** [comment]
ok

**Comment by victornoel** [comment]
two PR, one for v2 and one for v1.9 :)
