### ISSUE TITLE
Proposal: move BaseClient.retrieveCredentials to subclasses.

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#788]
Hi,

While browsing the clients code, I noticed that `BaseClient` was defining `retrieveCredentials` as abstract, but wasn't making any use of it.

Then each one of the two types of clients did make some use of it.

And finally, some of their subclass would implement it.

I think it would make more sense to have `BaseClient.retrieveCredentials` defined as abstract in each of the subclasses. Even though it would seem like code duplication, it seems more important to me to keep the declaration and usage of an abstract method in the same class for maintenance and code comprehension.

It is not really critical, but I thought I would raise the discussion here :)

**Comment by leleuj** [comment]
I see your point. I think you're right. When I opened the `BaseClient` class, I searched for the method caller of `retrieveCredentials`, I could not find it as you said. It feels weird I admit.

Would you mind submitting a PR for that?

**Comment by victornoel** [comment]
ok

**Comment by victornoel** [comment]
done :)
