### ISSUE TITLE
Consider using char[] instead of String for passwords

### ISSUE THREAD

**Issue by wardr** [pac4j/pac4j#809]
I see that UsernamePasswordCredentials has a String field for password.

The general recommendation (e.g. see Java Cryptography Architecture Reference Guide) is to use character arrays rather than a String to store passwords. This is to prevent the password getting cached in the JVM string pool or accidentally logged in plain text, 

Some guidelines suggest overwriting the array after use, but obviously whether that actually removes the data from memory depends entirely on the JVM implementation.

**Comment by victornoel** [comment]
That make sense yes. We must be careful that the whole chain of code handling the password do manipulate char arrays.

Note that the main backend we use for `PasswordEncoder`s, namely Spring Security, uses `CharSequence` to represent passwords. I'm not sure it is really compatible with the idea of having an array of char… this has to be investigated! What is funny is that when you look at implementations of Spring Security's `PasswordEncoder`, the convert the `CharSequence` into an array of char…

**Comment by wardr** [comment]
I suggest implementing a CharSequence and passing that around, e.g. something like this:

```
public class SecureString implements CharSequence {
  
  private final transient char[] value;

  public SecureString(char[] value) {
    if (value == null) {
      throw new IllegalArgumentException("Value must not be null");
    }
    this.value = value;
  }

  @Override
  public int length() {
    return value.length;
  }

  @Override
  public char charAt(int index) {
    return value[index];
  }

  @Override
  public CharSequence subSequence(int start, int end) {
    throw new UnsupportedOperationException();
  }

  public void clear() {
    Arrays.fill(value, '\u0000');
  }
}
```

**Comment by victornoel** [comment]
It could work, but we would need also a `toString()`, because some of the Spring Security implementations do call `toString()`… but it will defeat the whole idea, I know…

**Comment by wardr** [comment]
That's... unfortunate., Indeed adding toString would defeat the purpose -. but only for those packages/classes that abuse it.  We could always add a toString, mark it deprecated and use it anyway - that way at least things are covered for the cases where things are done correctly.

**Comment by victornoel** [comment]
And at the same time we could decide to see if there is no other security lib that do things correctly and use them instead of spring security!

**Comment by victornoel** [comment]
Hm, I have been looking around a bit, and this is what spring-security people have to say on the matter: https://github.com/spring-projects/spring-security/issues/3238

> You really cannot do much to reduce the life of the password in a Servlet container because the HttpServletRequest returns the HTTP parameters as a String. So Spring Security could take all the measures in the world to reduce the lifetime of the password but it wouldn't make a difference because the String would already exist.

I think this is why maybe it is isn't worth the effort to try to store passwords as char arrays in pac4j... @leleuj?

**Comment by wardr** [comment]
Good find. Yes, given that information, I agree with you.

**Comment by victornoel** [comment]
Still, it is not crazy to think about it, because I guess that some framework pac4j is integrated with are maybe providing passwords in the correct way...

**Comment by leleuj** [comment]
@wardr This is an excellent remark, but the guys from Spring Security are right, the String will be created by the `HttpServletRequest` in any case. In Play and Ratpack, we have the same issue (getting the value as String from the framework). I guess it's the same for Vert.x (@millross).

**Comment by leleuj** [comment]
Closing. To be re-opened if necessary.
