### ISSUE TITLE
Configure multiple Saml Clients on demand

### ISSUE THREAD

**Issue by tpraizler** [pac4j/pac4j#815]
I could only find examples that show how to set a saml client as part of the application init. Is there a way to add clients to the Config on demand? is this supported?

If it is supported, how is it possible to know where to redirect which user?

So for example if I have the following clients:

```
Saml2Client client1 = new Saml2Client(cfg); /* https://client1.oktapreview.com/app/sso/saml/metadata */
Saml2Client client2 = new Saml2Client(cfg); /* https://client2.oktapreview.com/app/sso/saml/metadata */
val clients = new Clients(s"https://myapp/api/saml/oktaCallback", client1, client2)
val config = new Config(clients)
```

my end point looks like this:

```
  def oktaLogin = Secure("SAML2Client") { profiles =>
    Action.async { implicit request =>
      val email = profiles.head.getId
      login(email)
    }
  }
```

How would client1 users will be redirected to the correct idp?

**Comment by leleuj** [comment]
Please ask your questions on the pac4j-users mailing list: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users

To answer your question, each client has a name, which is by default its class name. So to use two `Saml2Client`,  you need to give them different names.
Example:

```java
Saml2Client client1 = new Saml2Client(cfg); /* https://client1.oktapreview.com/app/sso/saml/metadata */
client1.setName("saml1");
Saml2Client client2 = new Saml2Client(cfg); /* https://client2.oktapreview.com/app/sso/saml/metadata */
client2.setName("saml2");
```

And then, to use the first SAML client:

```scala
def oktaLogin = Secure("saml1") { profiles =>
    Action.async { implicit request =>
      val email = profiles.head.getId
      login(email)
    }
  }
```

**Comment by tpraizler** [comment]
Thanks.

But how can I do it dynamically? 
Is there a way to add clients and use them without loading my app and adding new routes?

**Comment by leleuj** [comment]
It really depends on what you mean by "dynamically", but this goes towards a custom solution. You may find this extension useful as well: https://github.com/jkacer/pac4j-extensions @jkacer

**Comment by tpraizler** [comment]
Thanks! I will take a look.

"dynamically" means without the need to restart the application.
I want to keep using one endpoint:

```
  def oktaLogin = Secure("SAML2Client") { profiles =>
    Action.async { implicit request =>
      val email = profiles.head.getId
      login(email)
    }
  }

```

While configuring new saml clients that will use my only Secure endpint.

**Comment by tpraizler** [comment]
I can create another stackable action that will wrap Secure. but the question is if I can add \ set new clients into org.pac4j.core.config.Config instance? 
maybe something like: 

```
val clients = config.getClients()
config.setClients(clients :+ newClient)
```

**Comment by leleuj** [comment]
You can choose on the fly the client which will be used for authentication (if necessary) by using the `client_name` parameter in the query string.
I think you can add clients this way, but you'll need to call the `reinit()` method on the clients to be sure they are properly initialized (especially the callback URL).

**Comment by tpraizler** [comment]
Thanks!

About the reinit(), sounds like this might work as a work around.
Need to handle dynamic remove of client, and also dynamic add of a client.
Do you think this might be a valid enhancement (Do create a way to do it safly) ?

**Comment by tpraizler** [comment]
@leleuj what do you think?

**Comment by leleuj** [comment]
@tpraizler What do you have in mind with "valid enhancement"? I have the feeling that pac4j already address most use cases. When it comes to dynamic clients loading, I think it's more an extension and you should likely join your efforts with @jkacer

**Comment by tpraizler** [comment]
I agree that managing dynamic clients is an extension to pac4j. 
But at the end of the day, I will need to set the pac4j Clients instance dynamically. 
At the moment it has only setClients method, which is not ideal for dynamically managing the clients.
In order to manage dynamic clients I will need: 
- get clients -> set clients (old + new) -> reInit()
- Also will need to make this operation thread safe.

It would be great if Clients had:
- `addClient(client: Client)`
- `removeClient(name: String)`
- make sure both are thread safe.

What do you think?

**Comment by jkacer** [comment]
Hi Thomas!
Just to explain you what the extension does:
- It keeps all client definitions in a relational database, so they can be added/removed/modified while the application is running.
- It exposes a new implementation of Clients which encapsulates loading and initialization of clients themselves.
- You can simply reinitialize the Clients at any time - the clients will be forgotten and completely fresh instances will be used instead. Some old clients may be dropped, some may be added, some may be modified.

Does this solve your requirement? (I know you don't probably need the database part, though.)

**Comment by tpraizler** [comment]
Thanks @jkacer ! I will check it out, and see if it can work for me!
