### ISSUE TITLE
Alternative to the use of metadata url \ resource

### ISSUE THREAD

**Issue by tpraizler** [pac4j/pac4j#816]
Is there a way to provide the certificate and the sso url instead of the metadata resource?

**Comment by leleuj** [comment]
Please ask your questions on the pac4j-users mailing list: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users

No, you cannot and I don't know any IdP which would not provide its metadata.

**Comment by tpraizler** [comment]
Thank you! will join that group!
