### ISSUE TITLE
Twitter email not accessible

### ISSUE THREAD

**Issue by lucaspouzac** [pac4j/pac4j#846]
Hi, 

I try pac4j-2.0.0-RC1 with TwitterClient, but email is not accessible. Is it normal ?

> // System.out.println("Profiles : " + profiles);
Profiles : [#TwitterProfile# | id: *** | attributes: {utc_offset=-28800, friends_count=0, profile_image_url_https=https://abs.twimg.com/sticky/default_profile_images/default_profile_3_normal.png, listed_count=0, default_profile_image=true, favourites_count=0, description=, is_translator=false, created_at=Sun Feb 05 18:57:49 CET 2017, protected=false, screen_name=***, profile_link_color=1DA1F2, geo_enabled=false, profile_background_color=F5F8FA, lang=fr, profile_sidebar_border_color=C0DEED, profile_text_color=333333, verified=false, profile_image_url=http://abs.twimg.com/sticky/default_profile_images/default_profile_3_normal.png, time_zone=Pacific Time (US & Canada), contributors_enabled=false, profile_background_tile=false, access_token=***, follow_request_sent=false, statuses_count=0, default_profile=true, following=false, profile_use_background_image=true, followers_count=0, name=***, access_secret=***, location=, profile_sidebar_fill_color=DDEEF6, notifications=false} | roles: [] | permissions: [] | isRemembered: false |]

> // System.out.println("Email : " + profiles.get(0).getEmail());
Email : null

Twitter application settings are correct.

**Comment by leleuj** [comment]
Unfortunately, they don't return the user email. You can find many discussions about that over internet. I'm not sure it will ever change.

And please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
