### ISSUE TITLE
Can we configure SAML client to get the IdP metadata from a url?

### ISSUE THREAD

**Issue by n99** [pac4j/pac4j#863]
At least Shibboleth IdPs expose their metadata as a url for initial and subsequent downloads.
Could Pac4J grab IdP metadata from a url?

This would be useful when an application is started up and if the IdP updates its metadata?
Cheers

**Comment by leleuj** [comment]
Reading this: http://www.pac4j.org/1.9.x/docs/clients/saml.html, you'll see that you can pass an URL for the IdP metadata (version 1.9). In version 2.0, the ability remains.
