### ISSUE TITLE
Prefer 303 over 302 for redirecting after a POST on the callback URL

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#866]
Hi,

This is more for discussion than a bug per-se, but according to the HTTP specification, after POST, it would be wiser to use [303](https://en.wikipedia.org/wiki/HTTP_303) to redirect than [302](https://en.wikipedia.org/wiki/HTTP_302).

From the [302](https://en.wikipedia.org/wiki/HTTP_302) page on wikipedia:
> Many web browsers implemented this code in a manner that violated this standard, changing the request type of the new request to GET, regardless of the type employed in the original request (e.g. POST).[1] For this reason, HTTP/1.1 (RFC 2616) added the new status codes 303 and 307 to disambiguate between the two behaviours, with 303 mandating the change of request type to GET, and 307 preserving the request type as originally sent. Despite the greater clarity provided by this disambiguation, the 302 code is still employed in web frameworks to preserve compatibility with browsers that do not implement the HTTP/1.1 specification.

See also https://blog.jayway.com/2012/10/17/what-you-may-not-know-about-http-redirects/ for example that explains the same.

**Comment by leleuj** [comment]
Yes, a 303 HTTP code should be used when redirecting after a POST. Yet, we must think about it carefully because sometimes it's easier to use a well-known code even if it's not exactly the appropriate one (remember the logout 204 vs 200 HTTP code discussion).

Marked as "discussion" for version 3.0.0.

**Comment by victornoel** [comment]
I remember the previous discussion :)

I was thinking that if we restricted this behaviour to HTTP/1.1, then the browser would understand a 303 (and thus that it could be integrated in v2 as with the 204 HTTP code)

**Comment by victornoel** [comment]
FTR mainly the problem is with things like Apache HttpClient, Jersey Client and so on. They are usually more strict by default with regard to the specifications and don't follow 302 after POST for example.

**Comment by victornoel** [comment]
Should we do this?

**Comment by leleuj** [comment]
Yes, like the 204 HTTP code, we are at the beginning of the 3.0 development, so let's give it a try... We'll see if we eventually revert it or not.

**Comment by leleuj** [comment]
@victornoel I strongly refactored the way HTTP actions are handled in v4. And I submitted the following PR regarding this issue: https://github.com/pac4j/pac4j/pull/1223
