### ISSUE TITLE
Introduce WebContext.getProtocol()

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#867]
It would be good to have access to the HTTP version via a method (usually named like that by servlet and other implementations of HTTP requests) called `getProtocol()`.

In particular, it would be useful to implement something like #866, either in pac4j or in user code (which is my current use case :).

It could also be added to pac4j 1.9.x.

**Comment by leleuj** [comment]
Yes, it's a good idea. I tagged it for version 3.0.0, but we could do that right now for version 2.0.0. What's the emergency on this?

**Comment by victornoel** [comment]
None to me, I think it will be needed for #866 mainly in pac4j.
Also I'm not 100% sure all integrations will be able to provide it easily.

**Comment by millross** [comment]
Agreed, for example I don't know the implications for vert.x so would prefer if it could be something which can return UnsupportedOperationException or similar to allow for future implementation when the implications are clearer.

**Comment by millross** [comment]
Or we could have an option to return unknown for the protocol and use a 302 in that case. 

By the way, do we have concrete examples of where using a 302 rather than a 303 is causing us problems?

**Comment by millross** [comment]
Actually I think for vert.x it's quite easy, having read the docs :) Don't know about other implementations, but as far as the vert.x one goes it's ok. I would suggest having the option to return Unknown though and use a default behaviour for that case, if other implementations aren't so straightforward.

**Comment by victornoel** [comment]
@millross: concerning getProtocol itself, it could make sense to return HTTP/1.0 by default. I know that with bare jax-rs (without any knowledge of the underlying container like servlet or grizzly2), I couldn't find a way to get this information, but I didn't look for long though.

Concerning the 302/303 question, let's discuss it on the other issue, but mainly the problem is with things like Apache HttpClient, Jersey Client and so on. They are usually more strict by default with regard to the specifications.
