### ISSUE TITLE
Check that the default client really exists in the clients list

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#870]

**Comment by victornoel** [comment]
By the way, we could use this opportunity to index the clients by their name in the Clients configuration class, instead of having each of the Client tracks its own name (which implies that there can be duplicates and that retrieving a client from its name is not the quickest).

**Comment by leleuj** [comment]
We ensure each client has a unique name during the initialization. So there can't be any duplicate. That said, a map would offer better performance than iterating over a list.

I will only handle the default client part for now. Created: https://github.com/pac4j/pac4j/issues/874
