### ISSUE TITLE
UserProfile::setLinkedId should allow null value

### ISSUE THREAD

**Issue by millross** [pac4j/pac4j#871]
For decoding of Json-stored user profile data in vertx sessions. I can build a custom json-serializer for UserProfile but really shouldn't have to maintain one. 

I can't see any clear reason why prevent this. At the very least if you want to prevent unsetting of a linked id, you should wrap the null check on the provided linked id in code to validate we have already been linked. 

I'll submit a PR but until this is done, vertx-pac4j will remain broken (and this is a blocker to fixing it).

**Comment by millross** [comment]
I'm working on this and will submit a PR soon

**Comment by leleuj** [comment]
My idea was that it doesn't make any sense to link an account to another account having the `null` identifier. That said, I did not provide any way to remove the link so there is an issue in my reasoning  here.
You can safely remove the check.

**Comment by leleuj** [comment]
Reverted the master to 2.0.0-RC3-SNAPSHOT...
