### ISSUE TITLE
Issue with hmac token validator

### ISSUE THREAD

**Issue by andre-doherty** [pac4j/pac4j#881]
hello,

I have identified an issue with the current base code of pac4j-oicd.
The provider i am currently trying to interface with (france connect) only support HS256 for token signing.

So we have this code in OidcProfileCreator which check the metadata config and intends to instanciate an idTokenValidator accordingly : 
else if (CommonHelper.isNotBlank(configuration.getSecret()) && (jwsAlgorithm == JWSAlgorithm.HS256 || jwsAlgorithm == JWSAlgorithm.HS384 || jwsAlgorithm == JWSAlgorithm.HS512)) {
            this.idTokenValidator = createHMACTokenValidator(jwsAlgorithm, _clientID, _secret);
        }

The problem here is that the test jwsAlgorithm == JWSAlgorithm.HS256 fails as the instance of JWSAlgorithm doesn't match the static one, and so we end with an invalid idTokenValidator.
Indeed the jwsAlgorithm is instanciated in nimbus as new JWSAlgorithm("HS256").
see com.nimbusds.openid.connect.sdk.op.OICDProviderMetadata>>parse().

I will open an issue on this library as i don't know why the helper JWSAlgorithm.parse() is not used in this case. Of course if it was used instead the above test would be successful.
The alternative would be of course to implements the check in a different way, aka comparing the name field.

André

**Comment by leleuj** [comment]
The guys from Nimbus are fairly reactive. So contact them and ask for a fix, they should be able to provide a release very soon. If they don't, we'll fix it on our side.

Keep us posted.

**Comment by andre-doherty** [comment]
Yes, that's what i did. For the record, here is the link to the bug report i opened today regarding this subject : https://bitbucket.org/andre_doherty/oauth-2.0-sdk-with-openid-connect-extensions/issues/1/oidcprovidermetadata-doesnt-make-use-of

**Comment by leleuj** [comment]
Great! Thanks

**Comment by andre-doherty** [comment]
Hello,
They are indeed very reactive. 
The issue has been fixed and is embedded in version 5.24.2
With mention : 
> The recommended comparison is with .equals

**Comment by leleuj** [comment]
OK. Would you mind submitting a PR to upgrade the version and use `equals`? Thanks

**Comment by andre-doherty** [comment]
Sure no pb
