### ISSUE TITLE
Possible improvement to StringConverter

### ISSUE THREAD

**Issue by julioa** [pac4j/pac4j#882]
Hi,

I've found that class org.pac4j.core.profile.converter.StringConverter returns null when trying to convert some non-string classes due to its default behavior inherited from AbstractAttributeConverter.

I think this can been improved adding next code to the class:

   @Override
    protected String internalConvert(final Object attribute) {
        if (attribute == null) {
            return null;
        } else {
            return attribute.toString();
        }
    }

I haven't created a PR since I don't know if the current behavior is what this class is meant to do.

**Comment by leleuj** [comment]
This is the intended behavior. We just want to keep the expected class type (here: `String`).
