### ISSUE TITLE
Support LDAP authentication via configuration

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#883]

**Comment by leleuj** [comment]
PR in progress: https://github.com/pac4j/pac4j/pull/887

@mmoayyed @dima767 It's been a while since I wanted to add LDAP support via properties for pac4j. After thinking about this, I realized I had (almost) the same needs than in the CAS server: https://apereo.github.io/cas/5.0.x/installation/Configuration-Properties.html#ldap-authentication

An incredible work has already been done by the two of us in the `cas-server-core-configuration` module. So I came up to copy/paste two classes directly: the `AbstractLdapProperties` and the `LdapAuthenticationProperties` and create a new `LdaptiveAuthenticatorBuilder`, built from the `Beans` and `LdapAuthenticationConfiguration` classes.

Would it make sense and be possible to extract some `ldaptive-configurer` project/module only dedicated to build a Ldaptive `Authenticator` from properties (which would be then used by CAS and pac4j)?

**Comment by mmoayyed** [comment]
That's probably a good idea for CAS, but not so much for Pac4j. Those components don't just deal with LDAP authentication; they deal with anything LDAP related, which means there would be way too many components/module that need reorganization to use the new configurer module. I am not quite seeing the benefit here, specially without anyone financially sponsoring the work and without a good use case. 

It will be much simpler if you started defining your own abstractions and kept them independant. It's also strange if someone pulled pac4j and noticed there is a cas-server-support-ldaptive-something-something is on the classpath. "Why am I using a CAS server when I just want ldap authentication?" The sort of suggestion you have probably is a better contribution to ldaptive directly.

**Comment by leleuj** [comment]
Of course, it would be a `ldaptive-authenticator-builder` project (outside CAS and pac4j), with nothing specific to CAS, nor to pac4j. Actually, you already have it for pac4j with the three classes in the `org.pac4j.config.ldaptive` package: I think it could be used by CAS by creating a `CasLdapProperties` inheriting from the `LdapAuthenticationProperties`.

It's too late for CAS v5.1.0, but I have the feeling it's feasible.
