### ISSUE TITLE
OIDC : provider metadata ignored and suggesting improving configuration 

### ISSUE THREAD

**Issue by andre-doherty** [pac4j/pac4j#886]
hello,
It looks like some elements available in the SP metadata are ignored such as : 
- scopes_supported
- id_token_signing_alg_values_supported 

=> The client integration would be simpler if there was less configuration in the shiro.ini file. 

Also it might be useful if the metadata could be loaded from a resource instead of being fetched from a distant url : the discoveryURI setting is somehow compulsory however the sp doesnt always serve such a file).

**Comment by leleuj** [comment]
Yes, there is always room for improvement. Maybe we could re-use the resource definition mechanism we already have for SAML for example.

**Comment by gpgekko** [comment]
The newly added `logoutUrl` could also be optimised to use the available metadata under `getEndSessionEndpointURI()`.

**Comment by leleuj** [comment]
Sure. To be added in the future pull request...

**Comment by leleuj** [comment]
We started the development of version 3.0 only a few weeks ago, so it's perfect for this contribution...

**Comment by leleuj** [comment]
@andre-doherty : any update on this?

**Comment by andre-doherty** [comment]
Hello Jérôme,

Sorry i haven't been able to find the time to cover that issue yet.
I should hopefully get back into that topic in the next coming months and
then i will be than happy to contribute to the project.

Regards

Andre

**Comment by leleuj** [comment]
No problem. Thanks for the follow-up.

As I'm sorting issues, I close this one. Feel free to re-open it with your contribution.
