### ISSUE TITLE
pac4j-jwt should support key id header field for both signing and encrypting JWTs

### ISSUE THREAD

**Issue by lcsanchez** [pac4j/pac4j#888]
JWS RFC: https://tools.ietf.org/html/rfc7515#section-4.1.4
JWE RFC: https://tools.ietf.org/html/rfc7516#section-4.1.6

This `kid` field is helpful for consumers of JWTs when trying to identify which key (from a set) was used to either sign or encrypt the JWT.

**Implementation Ideas:**
The underlying `nimbus-jose-jwt` library already has support for the `kid` header.

https://static.javadoc.io/com.nimbusds/nimbus-jose-jwt/4.16/com/nimbusds/jose/JWSHeader.html
https://static.javadoc.io/com.nimbusds/nimbus-jose-jwt/4.16/com/nimbusds/jose/JWEHeader.html

I believe we'd just need to add the notion of a key id to the the [SignatureConfiguration](https://github.com/pac4j/pac4j/blob/master/pac4j-jwt/src/main/java/org/pac4j/jwt/config/signature/SignatureConfiguration.java) interface. We can then query for this field and [include it in the header](https://github.com/pac4j/pac4j/blob/master/pac4j-jwt/src/main/java/org/pac4j/jwt/config/signature/RSASignatureConfiguration.java#L62).

I can put together a pull request for this work if all of that sounds like a good idea...

**Comment by leleuj** [comment]
Sure. Don't hesitate to propose some PR for that? We'll see if that can fit in v2.0.

**Comment by leleuj** [comment]
We started the development of version 3.0 only a few weeks ago, so it's perfect for this contribution...

**Comment by leleuj** [comment]
@lcsanchez : any update on this?

**Comment by leleuj** [comment]
Closing for now. Feel free to reopen with your contribution.
