### ISSUE TITLE
Define constants for "isAuthenticated", "isRemembered", etc.

### ISSUE THREAD

**Issue by rwalkerands** [pac4j/pac4j#892]
There are a lot of string literals that are intended for use in user code. E.g., `DefaultAuthorizationChecker` has `"isAuthenticated"`, `"isRemembered"`, etc.

At least for these values that are to appear in user code, please define constants for them, so that I can say, e.g., something like:

```
    @Pac4JSecurity(authorizers = AuthorizationConstants.IS_AUTHENTICATED)
```

**Comment by leleuj** [comment]
Yes, it would be better. We already have the `HttpConstants` and `Pac4jConstants` classes, but it could be a new one.
Feel free to submit a pull request for that.

**Comment by millross** [comment]
Good call

**Comment by rwalkerands** [comment]
I will do a pull request.

What is your preference?

- Add them to HttpConstants?
- Add them toPac4jConstants?
- Make a new class?

**Comment by leleuj** [comment]
It does not fit well in `HttpConstants` and  `Pac4jconstants`. I would create a new `DefaultAuthorizers` class for this.
