### ISSUE TITLE
Optional dependencies of pac4j-config should be marked as optional

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#896]
@leleuj 

pac4j-config depends on many artefacts that not everybody wants (saml, cas, etc).

Since dropwizard-pac4j depends on pac4j-config, it means that every user of dropwizard-pac4j HAS to depend on all these optional dependencies.

So I think they should be marked as optional.

Be careful because doing so means that classes that refer to these dependencies won't be instantiable at all if they are not in the classpath... that's not an easy thing to manage!

Another solution would be to mark pac4j-config as optional in dropwizard-pac4j but I'm pretty sure other users of pac4j-config will be bothered by this question!

For me it is a blocker for releasing v2 :)

**Comment by victornoel** [comment]
After looking at the code of pac4j-config and how it is used in dropwizard-pac4j, I think it should be better to make dependencies optional in pac4j-config.

I guess it shouldn't be so hard to do it because it seems that each class is self-sufficient. Some experiment must be made I guess, I'm not 100% sure of how java decide to load classes exactly :)

**Comment by leleuj** [comment]
Despite the splitting of the `PropertiesConfigFactory` class, I'm not sure this is feasible. I have a strange error when running the dropwizard-pac4j-demo with dependencies as `optional`. Did you give it a try?

**Comment by victornoel** [comment]
I think that when java instantiate/use a class, it needs all the referenced classes to be in the classpath, but it's ok if these classes are not themselves instantiable.
I will make some tests (by making various things optional) with `dropwizard-pac4j-demo` and see what happens on my side :)

**Comment by victornoel** [comment]
First of all, dropwizard-pac4j-demo DOES use the facilities of pac4j-config for saml, ldap and facebook, so you DO need them in its classpath. If you make them optional in pac4j-config, it is normal that you have to add them as the dependencies of dropwizard-pac4j-demo.

Now, regarding making pac4j-config dependencies optional, I think the problem is as follow:
1. In the case of dropwizard-pac4j, `Pac4jFactory` only refers to `PropertiesConfigFactory`, it's ok, we want to keep pac4j-config as a normal dependency. So I think nothing should be changed from the point of view of dropwizard-pac4j or any other integration that relies on pac4j-config.

2. `PropertiesConfigFactory` refers to the various client-specifics classes such as `LdapAuthenticatorBuilder`, it could have been ok, but since it instantiates those classes in its constructor, it means that as soon as `PropertiesConfigFactory` is instantiated, `LdapAuthenticatorBuilder` (for example) will, and thus it will need the `org.ldaptive` package in the classpath.

It is this second point that is problematic: `PropertiesConfigFactory` should never instantiate the client-specific classes EXCEPT at the moment we know we want them to be instantiated.
So you should extract the logic in `LdapAuthenticatorBuilder` and others that checks if it is needed (i.e., the call to `getProperty(LDAP_TYPE, i)` in `PropertiesConfigFactory` in order to delay the instantiation of `LdapAuthenticatorBuilder` until we know `ldap.type` is actually present in the configuration.

Like this, anybody using pac4j-config can choose to use only the dependencies she needs and it will be ok.

**Comment by leleuj** [comment]
Yes, that's the idea. But it requires a real refactoring: https://github.com/pac4j/pac4j/pull/901

I now tested it successfully with the demo. What do you think?

**Comment by victornoel** [comment]
It looks good yes :) Thanks!
