### ISSUE TITLE
support async SessionStore

### ISSUE THREAD

**Issue by tpraizler** [pac4j/pac4j#897]
I think that SessionStore should also have async api.

If I have 3 servers, and I want a user to have the same session, I need to keep the session in a central datastore, for example, Redis, and I use only the async api when working with Redis.

In order to properly implement the SessionStrore api, I will need to block, and break the async functionality.

**Comment by leleuj** [comment]
Yes, this is something we have in mind more globally (make things async). See: https://github.com/pac4j/pac4j/issues/180

But this is definitely not easy.

**Comment by millross** [comment]
See also https://github.com/millross/pac4j-async/tree/master/pac4j-async-core/src/main/java/org/pac4j/async/core/session - an experiment to determine what changes need to be made to offer pac4j a fully async API. This includes an Async session store API.

However, in your scenario, if your code calling pac4j is fundamentally expecting to call a blocking API, then an async SessionStore API won't help you - you''ll still need to block a thread somewhere (using CompletableFuture::get or join for example). Async either gets wrapped to block at some point or is async end to end.

**Comment by millross** [comment]
One thing we've already learned during the experimental work is that there are going to need to be some fairly substantial changes in the core API to enable as much commonality as possible between async and sync APIs (e.g. common WebContext parents).

**Comment by tpraizler** [comment]
@millross my code is not directly calling the pac4j api, I use the CallbackController in play, which is using `DefaultCallbackLogic` which eventually calling the `SessionStore`.

**Comment by millross** [comment]
Isn’t DefaultCallbackLogic sync and blocking?

**Comment by tpraizler** [comment]
Yes it is. I think we are talking about the same thing. 
Even if the asyncStore will be used it will need to be blocked.

**Comment by millross** [comment]
Yeah, it will be a while before I get the end-to-end async API into a viable shape unfortunately, and before it can be joined up with the sync API there will need to be significant change in the sync API to maximise concept reuse (and only differ where we have to diverge sync from async). There will, for example, need to be async versions of all logics, webcontext, authorizers etc. In some cases it will be possible to wrap non-blocking sync elements in an easy async wrapper, in others there will need to be specific non-blocking implementations, but at the moment I'm still (when time permits) teasing out the divergences in terms of APIs.

**Comment by millross** [comment]
Feel free to look at the experimental repository - if you want you're welcome to submit PRs relating to asynchronous callback logic (it will certainly help me out, I get about 15-20 min a day at best, and the existing vertx-pac4j implementation gets priority, plus I also have other stuff I need to do with that time). My main focus right now is DefaultSecurityLogic's async version so we wouldn't necessarily overlap, but you might identify some of the other divergences from the sync API we need to prepare for.

**Comment by leleuj** [comment]
I'm trying to rationalize a bit the opened issues. So closing this one in favor of https://github.com/pac4j/pac4j/issues/180
