### ISSUE TITLE
CouchDB authenticator

### ISSUE THREAD

**Issue by eroux** [pac4j/pac4j#902]
We would like to use pac4j for our next app, but we're using CouchDB as our database and would thus like to use a CouchDB authenticator. It seems relatively straightforward to create one based on pac4J-mongo and using the [ektorp](https://github.com/helun/Ektorp) library. Does the idea seem reasonable? If so, if we move forward in that direction, we'll produce a PR.

**Comment by victornoel** [comment]
Just a quick question: why use pac4j-mongo and not simply directly write an ektorp-based authenticator? Or did you mean use pac4j-mongo as a template for writing a pac4j-couchdb?

I think you are right that it is going to be straightforward, and I'm pretty sure @leleuj will accept any PR for this :)

Byt the way, at one time we thought about reusing common logic between database-based authenticator (see #777), it wasn't done, but if you feel like it would make sense once again (maybe after writing a first implementation to get an idea), please tell us :)

**Comment by eroux** [comment]
I was thinking of using pac4j-mongo as a model for pac4j-couch indeed. I note your suggestion, but I'm not sure i want to go that far into touching the code...

**Comment by victornoel** [comment]
ok great :) just give us some feedback on this refactor thing if it makes sense! But yeah, don't bother with it :)

**Comment by leleuj** [comment]
Providing a `pac4j-couchdb` module would be really appreciated. Yes, it makes sense to base your implementation on the `ektorp` library and it should look like the `pac4j-mongo` module.

Just to correct what @victornoel said, we actually have a common logic shared between the `DbProfileService`, `MongoProfileService` and `LdapProfileService`: the [AbstractProfileService](https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/profile/service/AbstractProfileService.java) component. So you should certainly create a `CouchdbProfileService` implementing the `AbstractProfileService` (to validate credentials but also to create, update and delete users).

**Comment by victornoel** [comment]
Yes, sorry @leleuj :) it's true there is the `AbstractProfileService`, I forgot that you did more refactoring after the discussion!

**Comment by eroux** [comment]
If it's supposed to be in 3.0.0, what branch should I make the pull request against?

**Comment by leleuj** [comment]
You should make your PR against the master, although it won't be merged before the final 2.0 release (in a few weeks/days).

**Comment by victornoel** [comment]
Any reason why we wouldn't integrate it in 2.0.0? or 2.1.0 or something like this?

**Comment by leleuj** [comment]
I had in mind it could take some time to develop it, but indeed, it's an addition, it can go into 2.0.0 or 2.0.1 as soon as it's ready.

**Comment by leleuj** [comment]
Now marked as 2.0.0

**Comment by eroux** [comment]
Ok thanks! Another thing: there doesn't seem to be any reasonable way to mock a couchdb database in java, is it ok if I run the tests in an actual local database and ignore the tests if there is none?

**Comment by victornoel** [comment]
@eroux I've you seen this: https://github.com/petmongrels/mcouch? never tried it though!

**Comment by eroux** [comment]
Oh, I didn't notice it, thanks! It looks pretty old and unmaintained, but maybe it still works, I'll see if I can make use of it.
