### ISSUE TITLE
index on the sql backend

### ISSUE THREAD

**Issue by eroux** [pac4j/pac4j#903]
The [doc for sql](http://www.pac4j.org/docs/authenticators/sql.html) currently only states to create a table. In my experience, creating indexes on the fields that will be queried significantly improves performance. Looking at the code, I think asking users to also run

```sql
ALTER TABLE `users` ADD UNIQUE KEY `username` (`username`), ADD UNIQUE KEY `linkedid` (`linkedid`);
```

would be helpful (removing the `UNIQUE` keyword if entries are not supposed to be unique). I can't really test though.

**Comment by victornoel** [comment]
Where do you want to ask user to do that? In the documentation?

**Comment by eroux** [comment]
yes, thinking about it, it should me more like

```sql
ALTER TABLE `users` ADD PRIMARY KEY (`id`), ADD KEY `username` (`username`), ADD KEY `linkedid` (`linkedid`);
```

**Comment by victornoel** [comment]
Ok, that could make sense to add that yes I guess… make a PR? :)

**Comment by leleuj** [comment]
Yes, the indexes part is missing. Would you mind submitting a PR for that?

**Comment by eroux** [comment]
I'll focus on #902 first, but I can do that afterwards
