### ISSUE TITLE
max-age in set-cookie header may not be negative

### ISSUE THREAD

**Issue by swiftrs** [pac4j/pac4j#914]
As stated in https://tools.ietf.org/html/rfc2109, the `max-age` parameter in an `set-cookie` header may not be negative:
> Max-Age=delta-seconds
      Optional.  The Max-Age attribute defines the lifetime of the
      cookie, in seconds.  The delta-seconds value is a decimal non-
      negative integer. [...]

However, in [Cookie.java](https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/context/Cookie.java) it is initalized with `-1`.

I discovered this bug while testing a Ratpack application using REST-assured. After enabling `CsrfTokenGeneratorAuthorizer` all tests failed.

**Comment by leleuj** [comment]
0 means "expires now" while -1 means the cookie lasts the whole session (until the browser is closed).

**Comment by swiftrs** [comment]
Hmm, looking at the newer [RFC-6265](https://tools.ietf.org/html/rfc6265#section-5.2.2) a negative value is allowed, but is treated like 0:

> Let delta-seconds be the attribute-value converted to an integer.
   If delta-seconds is less than or equal to zero (0), let expiry-time
   be the earliest representable date and time.  Otherwise, let the
   expiry-time be the current date and time plus delta-seconds seconds.

**Comment by leleuj** [comment]
The spec is right of course, but I think most frameworks consider -1 as a session cookie, in that case, the max-age property is omitted.

With the `CsrfTokenGeneratorAuthorizer`, I just did the test for J2E and a `org.pac4j.core.context.Cookie` is created with max-age -1 then a `javax.servlet.http.Cookie` (with max-age equals -1) and the max-age property is copied from one to the other. Nonetheless, the `pac4jCsrfToken` is created without a max-age property. So the J2E framework knows how to deals with cookies where max-age equals -1.

For Ratpack, this is maybe not the case. So we should have a check to only set the max-age property if it's not -1. Here: https://github.com/ratpack/ratpack/blob/master/ratpack-pac4j/src/main/java/ratpack/pac4j/internal/RatpackWebContext.java#L220

Would you mind doing a test in that way?

**Comment by swiftrs** [comment]
Thanks for coming back on his.
Adding the check 
```
    if (cookie.getMaxAge() >= 0) {
      newCookie.setMaxAge(cookie.getMaxAge());
    }
```
does the trick. The cookie does not contain a max-age property anymore.
Shall I file a pull request?

BTW, two days ago I proposed another fix to `RatpackWebContext` you might be interested in: https://github.com/ratpack/ratpack/issues/1219

**Comment by leleuj** [comment]
Good! Yes, you should submit a PR and yes, the second issue is likely to happen.

Currently, `ratpack-pac4j` is stuck to pac4j v1.8, which is really a problem. I proposed to create a `ratpack-pac4j` library in the `pac4j` organization (first as a copy/paste of the existing library), but things are pending... See: https://github.com/ratpack/ratpack/issues/1034

Please let me know if you want to help on this.

**Comment by swiftrs** [comment]
I've added the changes to the aforementioned PR.

**Comment by leleuj** [comment]
Regarding Ratpack, I will focus my efforts on the new library: https://github.com/pac4j/ratpack-pac4j which is currently the mirror of the official ratpack-pac4j module, but will be upgraded to pac4j v2.0 soon.
