### ISSUE TITLE
Usage with Siteminder?

### ISSUE THREAD

**Issue by b-long** [pac4j/pac4j#918]
I'm sorry to raise this as an issue, but I'm wondering if anyone can speak to usage of pac4j with CA Siteminder (CA SSO).

I didn't see much discussion of this on the web, nor did I see any references to Siteminder in the [pac4j documentation](http://www.pac4j.org/docs/).  

Is it a design that works well?  Are their known issues?  Is anyone willing to share their insight as a pac4j wiki page?

Thanks in advance!

**Comment by leleuj** [comment]
Please use the mailing list for this kind of question: https://groups.google.com/forum/?hl=en#!forum/pac4j-users

The truth is that I have never heard about such integration. That said, Siteminder, as a proprietary software, is a bit far from the Open Source world.

**Comment by b-long** [comment]
Ah, so sorry about that.  Will do and thanks for sharing the link! 👍
