### ISSUE TITLE
Update API to not return nulls, but sensitive defaults or optionals

### ISSUE THREAD

**Issue by giflw** [pac4j/pac4j#926]
With the advent of​ lambda in Java and the influence of functional paradigm, and the problems that NPE can arise, it's interesting to avoid null as much as possible, changing nulls to sensitive default values or using optionals.

**Comment by leleuj** [comment]
@giflw : can you elaborate on your proposal?

**Comment by giflw** [comment]
Yes :relaxed:. I'll try to do until next Sunday.

**Comment by giflw** [comment]
I'll try to explain what I was thinking using some examples from pac4j itself (commit 682a374f8e9e18310fd49f0b4a3bb4bb5ee77c00). As it is a security framework, I think its worthy to reason about this:

+ CommonHelper class
    ```
    /**
     * Add a new parameter to an url.
     *
     * @param url   url
     * @param name  name of the parameter
     * @param value value of the parameter
     * @return the new url with the parameter appended
     */
    public static String addParameter(final String url, final String name, final String value) {
        if (url != null) {
            final StringBuilder sb = new StringBuilder();
            sb.append(url);
            if (name != null) {
                if (url.indexOf("?") >= 0) {
                    sb.append("&");
                } else {
                    sb.append("?");
                }
                sb.append(name);
                sb.append("=");
                if (value != null) {
                    sb.append(urlEncode(value));
                }
            }
            return sb.toString();
        }
        return null;
    }
    ```
    Is this example from pac4j code, we hava a method that is supposed to return **String**, but can return null too, but the null return is unexpected, as it's not documented (@return in javadoc). In this case, the method could throw `IllegalArgumentException` if url is null, or return an `Optional`, avoiding `NullPointerException` when trying to use the returned value.
    
+ ParameterExtractor class
	```
     /**
     * Extract the right credentials. It should throw a {@link CredentialsException} in case of failure.
     *
     * @param context the current web context
     * @return the credentials
     */
    
    @Override
    public TokenCredentials extract(WebContext context) {
        final String method = context.getRequestMethod();
        if (HTTP_METHOD.GET.name().equalsIgnoreCase(method) && !supportGetRequest) {
            throw new CredentialsException("GET requests not supported");
        } else if (HTTP_METHOD.POST.name().equalsIgnoreCase(method) && !supportPostRequest) {
            throw new CredentialsException("POST requests not supported");
        }

        final String value = context.getRequestParameter(this.parameterName);
        if (value == null) {
            return null;
        }

        return new TokenCredentials(value);
    }
    ```
    This case is identical to the previous. The javadoc states that the returns is **the credentials** and in case of failure it throws **CredentialsException**, but there is a undocumented null return. It shouldn't throw **CredentialsException** as it has no credentials, or return an empty `TokenCredentials` or an `Optional`. In this case, if an empty credential would be returned, it should have an `isValid()` method added to the `Credentials` abstract class.

+ BaseClient class
	```
    /**
     * Get the user profile based on the provided credentials.
     *
     * @param credentials credentials
     * @param context web context
     * @return the user profile
     */
    
    @Override
    public final U getUserProfile(final C credentials, final WebContext context) {
        init();
        logger.debug("credentials : {}", credentials);
        if (credentials == null) {
            return null;
        }

        U profile = retrieveUserProfile(credentials, context);
        if (profile != null) {
            profile.setClientName(getName());
            if (this.authorizationGenerators != null) {
                for (AuthorizationGenerator<U> authorizationGenerator : this.authorizationGenerators) {
                    profile = authorizationGenerator.generate(context, profile);
                }
            }
        }
        return profile;
    }
    ```
    This is one of main points in my opinion. The method says it returns user profile (`getUserProfile()`), the javadoc says that too. But in fact, that is a null return undocumented. There is only 2 ways to note that: looking into sources or getting a `NullPointerException` in runtime. There is a couple of things that could be done here to clarify this situation or to avoid it, and I list some I can think about:
    
    - rename the method from `getUserProfile` to `getUserProfileOrNull`: I think this is ugly, but effective
    - change the return type to `Optional<UserProfile>`, stating that not always will be possible to return an `UserProfile`: I think this is more ellegant and equally effective
    - add `isValid()` (or something similar) to `UserProfile` and return an static constant representing and invalid profile. I think this is less easy to acknowledge, but make `UserProfile` an optional entity by itself. When needed, one can return `UserProfile.INVALID_PROFILE` or some other instance that return `false` on `isValid()` call.
    	```
        public abstract class UserProfile implements Serializable, Externalizable {

    			public static final UserProfile INVALID_PROFILE = new UserProfile(false);
                
                private final boolean valid;
                
                protected UserProfile(boolean valid){
                	this.valid = valid;
                }
                
                public boolean isValid(){
                	return valid;
                }
                ....
		}
        ```
Best regards 😄

**Comment by leleuj** [comment]
You're completely right in all your examples, my main question is what should be the scope of these changes (as most of them would be breaking changes)?
I think we should open a discussion on this on the pac4j-dev mailing list: would you mind doing that? Thanks (mostly a copy/paste of your last post)

**Comment by giflw** [comment]
Posted on pac4j-dev: https://groups.google.com/forum/?fromgroups#!topic/pac4j-dev/eL-J18klc3k

**Comment by leleuj** [comment]
Thanks, we'll see if someone jumps into that discussion...

**Comment by leleuj** [comment]
This PR feels almost good, let's merge it and move on. And fix the issues in another PR...

**Comment by leleuj** [comment]
Unfortunately, there were too many issues with your PR (it doesn't even compile!), so I finally reverted it.
I let you reopen the same PR or a smaller one (it should make things easier).

**Comment by giflw** [comment]
In fact just the core was compiling, but only the main sources. I was waiting to have some stability on the changes before replicating then on all modules. I'll open a new PR.
