### ISSUE TITLE
Let the CallbackLogic be called with its own default client

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#938]
During some discussion on the ML (https://groups.google.com/d/topic/pac4j-users/qjorvxOmSrk/discussion), it became clear that the way pac4j currently work with respect to the callback endpoint is limiting.

Basically this is how I understand it works currently:
 - ~~there is one callback url for the whole application (configured in the `Config`)~~
 - there is one callback filter setup
 - the callback logic knows which client is concerned by a callback request thanks to an http parameter

This is one would be useful I think:
 - ~~the possibility to configure a callback url per client~~
 - the possibility to configure the client on a callback filer (so that it can be passed to the callback logic)
 
And by the way, it would make sense to move the `findClient` method of the `Clients` class out of it and inside the `CallbackLogic`, there is no reason for the configuration to have this kind of knowledge I think...

I guess there is some relations to #854 but I'm not 100% sure ^^

Some of this could be done for 2.x (e.g. client's name in the `CallbackLogic.perform` call), but I guess that we will wait for 3.x to have something complete, clean and coherent if we do it.

EDIT: actually the `callbackurl` is already configurable per client, so in the end, there is only the need for choosing a default client per filter!
We should discuss this, but I can open another issue for the refactoring of the `findClient` method (for 3.x)

**Comment by leleuj** [comment]
From the pac4j core POV, you can have as many callback endpoints as you want (as well as the `Config`). This may be limited by the implementation library though. But it's generally easier to only have one callback endpoint.

What do you want to change exactly?

About the `findClient` method, you raise a good point: I have the feeling it belongs to the `Clients` component more than to the `CallbackLogic` one, but I wouldn't be too assertive on this? Maybe you can find good reasons to move it out...

#854 is more about initialization: done once and making things a bit too stateful for asynchronism or done only when required and a little more stateless and non-blocking.

**Comment by victornoel** [comment]
Ok, sorry for the confusion with all the changes :)

Basically, I'm asking for:
> the possibility to configure the client on a callback filter (so that it can be passed to the callback logic)

So in practice, in pac4j-core: add a `defaultClient` parameter to the `perform` method of `CallbackLogic` and take it into account when looking for the client to use (so, select it based on, in this order: http request parameter, `defaultClient` from `perform` method and finally, `defaultClient` from `Config`).

**Comment by leleuj** [comment]
OK. That's clear.

Oh I think you want different default clients on different callback endpoints right? To avoid having a `client_name` parameter?

Maybe we'll end up with some `ClientResolver` in the `CallbackLogic` and a `DefaultClientResolver` which has the current behaviour. It looks like an interesting step for v3. I remember several discussions on using paths instead of the `client_name` parameter for client resolution. The `defaultClient` could certainly be part of this resolver.

**Comment by victornoel** [comment]
Seems good to me :)

**Comment by leleuj** [comment]
I'm not 100% sure of the solution, but the default client will be settable at the endpoint level instead of the `Config` level, the `Clients` component should have less logic in the future to be able to have various client retrieval mechanisms at the endpoint level.
