### ISSUE TITLE
Do not force storing profile is session with CallbackLogic?

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#939]
Another spin-off (like #938) of the discussion in the mailing list (https://groups.google.com/d/topic/pac4j-users/qjorvxOmSrk/discussion).

Is there any reason for the `CallbackLogic` to force the storage of the profile in the session?

A use case is the following:
 - the indirect client is used to authenticate a request and returns a jwt token via a header (this last part is not handled by pac4j by default, it is possible in jax-rs-pac4j because you can configure a `CallbackFilter` so that it lets you implement what happens once the authentication succeeded with the indirect client)
 - another direct client (http header) is configured to authenticate requests with the jwt token as a header.

There is no need for sessions there.

It seems a bit hacky to do all of that though, I would thus also be interested in other point of view to do this kind of things, I'm not sure it is currently possible to do that cleanly, is it?

**Comment by leleuj** [comment]
Indirect clients are for UI login, so for a user to enter his login and password and authenticates. How could a JWT returned as header could be useful to him?
If it's a matter of user login/password, use a direct client (like `DirectBasicAuthClient`)?

**Comment by victornoel** [comment]
Ok, so let's consider this kind of use case not supported (as discussed also in the ml : )

Does it mean we always enforce the use of sessions for indirect clients?

**Comment by leleuj** [comment]
Both ideas are linked I think: indirect clients are used by users so they should only login once thus the use of the session. Although, you can certainly disable that behaviour with a specific `SessionStore`.

That said, I still don't fully understand your web flow: the user logins via a form and the JWT is returned as an HTTP header: how can that work?

**Comment by victornoel** [comment]
About the web flow I'm talking about:
 1. You have an auth API: a SPA (or any other REST client) makes a request to an endpoint to get a JWT token from a login/pass pair. This JWT represents the user session. It is returned via body or header, it's not important.
 2. All requests made for this user session is done by using the JWT token in a header of the requests

Currently, with pac4j, you can't use one client to implement this, you need either to:
 - do step 1 by hand and use a (direct) client for step 2.
 - use an indirect client, tweaked as discussed before (no session, no redirections, not used by protected paths, only by a callback endpoint) for step 1 and another (direct) client for step 2.

I realise writing this that in a way, the need of this use case is to be able to represent the session with something else than an HTTP Session (here a JWT token).

**Comment by leleuj** [comment]
For sure, you have two kinds of authentication thus two kinds of clients: one validates user/pass, the user one validates JWT tokens.
For step 1, as it's a SPA, I have the feeling it could be a direct client where you send your credentials.
If you use an indirect client, indeed, you don't need the web session and you could "inject" a `NoSessionStore` or just forget about the issue.

**Comment by victornoel** [comment]
> For step 1, as it's a SPA, I have the feeling it could be a direct client where you send your credentials.

I never thought about doing it like this… great idea, I will explore it in my app to see if it works.

Ok, let's consider this a non-issue, the answer being that you can simply use a NOOP `SessionStore` if needed and that for now `IndirectClient` are strongly tied to sessions.

**Comment by victornoel** [comment]
@eroux I think for your application you could have:
 - one direct client configured with your custom extractor as discussed to retrieve the body and authenticate it against the couchdb authenticator to protect the "/login" endpoint, which would then simply return the generated JWT (using `JwtGenerator`). You should thus use the `@Pac4JSecurity` with the name of the client passed as a parameter to protect the endpoint in your resource class.
 - one direct client from pac4j-http for header configured with a jwt authenticator to protect the rest of the URLs.
