### ISSUE TITLE
error message improvement

### ISSUE THREAD

**Issue by eroux** [pac4j/pac4j#941]
Following [this thread](https://groups.google.com/forum/#!topic/pac4j-users/qjorvxOmSrk), here are a few error messages that could be improved:

- [ ] `NullPointerException` ([example](https://github.com/BuddhistDigitalResourceCenter/auth-api/tree/e320047cd29563934d74981286f3f7b26cef59e6)) should be caught and replaced by an error message asking for a servlet container handling sessions (or automatically switching the sessions to off), related to https://github.com/pac4j/pac4j/issues/939 [full log](https://pastebin.com/AXA1Rmz5)
- [ ] `TechnicalException: callbackUrl cannot be blank` ([example](https://github.com/BuddhistDigitalResourceCenter/auth-api/tree/a5d625d88eae0d60d5fb11a2511f477e52d69c85)) could point to the Config documentation and stating that a callbackUrl should be provided in the Config object [full log](https://pastebin.com/piXz9nVk)
- [ ] `TechnicalException: request cannot be null ` ([example](https://github.com/BuddhistDigitalResourceCenter/auth-api/tree/9ab813ff642162f2c5620fa59eb55cff9dc95d52)) can be triggered by the fact that `ServletJaxRsContextFactoryProvider` cannot be used in a non-servlet environment, which is not quite explicit in the error message, but maybe that's a jax-rs-pac4j error and it should be reported there? [full log](https://pastebin.com/mHbRazUs)

**Comment by millross** [comment]
NullPointerException (example) should be caught and replaced by an error message asking for a servlet container handling sessions (or automatically switching the sessions to off), related to #939 => Should be no mention of servlet containers in pac4j-core for the very simple reason that servlet containers aren't the only pac4j use-case (e.g. vert.x, play). The message should however insist that sessions should be available or similar.

**Comment by victornoel** [comment]
for the record, some of these proposed message errors are related to jax-rs-pac4j, so we should see how we can adapt the message if it's to be printed by pac4j-core :)

@eroux you had some stacktraces logs I think also, could you put  the links to them, so that we don't have to run the project to see the errors you are talking about? thanks!

**Comment by eroux** [comment]
I've updated the comment with the full logs. Warning: they will only be available one month before being deleted from pastebin. 

I agree that the servlet container thing should not be in the core pac4j message, but maybe the best way to handle it would be to raise an exception that would be caught by jax-rs-pac4j?

**Comment by victornoel** [comment]
Thanks
I think for the last one, it could even be caught earlier during the initialisation process by jax-rs-pac4j...

For the first one, I think we should introduce more checks to ascertain there is a session store in case one is needed by some of the components used, either at pac4j-core level (for example DefaultCallbackLogic expects session to be present for now, this is related to #939 btw) or at specific integration level (for example if the `readFromSession` parameter of `@Pac4jProfile` is true in jax-rs-pac4j).

**Comment by millross** [comment]
I don't know my modern JEE well, but is there any way we can make SessionStore part of the constructor where it's required, and validate non-null? Or are we dependent on setter properties? It seems wrong to me that we should be identifying a missing session store so late in the process, and the most logical approach to solve this would be constructor injection, but that's only valid if it's viable for our supported implementations plus any others we see on the horizon.

**Comment by victornoel** [comment]
@millross there is case when you don't want session management actually.
It's setup automatically (in the constructor as you say in jax-rs-pac4j) in the case where it is expected to be present, but if the user makes a mistake and use the jax-rs-pac4j classes for session-enabled containers with a session-less container, then it fails with a cryptic error. Hence the need for meaningful error messages.

I'm not sure yet if it's the responsibility of pac4j-core to notice this situation or jax-rs-pac4j, but it is sure that pac4j-core has all the information about that situation (i.e., some component is used that requires session management while the sessionstore is not setup in the `WebContext`).

**Comment by millross** [comment]
Fair comment, but it would be nice to identify as early as possible if we're configuring with session-requiring components where there will be no session.

**Comment by victornoel** [comment]
I agree, yes :)

**Comment by leleuj** [comment]
About the `sessionStore`, this is properly implemented for J2E by providing a default one: https://github.com/pac4j/pac4j/blob/master/pac4j-core/src/main/java/org/pac4j/core/context/J2EContext.java#L57 as well as in Play: https://github.com/pac4j/play-pac4j/blob/master/src/main/java/org/pac4j/play/PlayWebContext.java#L65 with a null-check.

Maybe it's more related to the JAX-RS implementation here.

Regarding the "callbackUrl cannot be null", I find the message fairly explicit without quoting the documentation but this might be me ;-)

I guess the `request cannot be null` is more related to the JAX-RS implementation also.

**Comment by victornoel** [comment]
> Maybe it's more related to the JAX-RS implementation here.

Yes, I think you are right.

> Regarding the "callbackUrl cannot be null", I find the message fairly explicit without quoting the documentation but this might be me ;-)

the `callbackUrl` is one of those things that have no default value and that MUST be provided by the user (in opposition to most of the other things in pac4j), so for users, it always seems strange, especially when they are new, to get this error. That's why I thought it could make sense to add a message saying, with the error, "Configure it on the client or in the Config"… ultimately, all the information is already there, I think @eroux is looking for some help for first time user discovering the framework.

**Comment by leleuj** [comment]
No problem then on the "callbackUrl" error message: it's an easy fix. @eroux or @victornoel : would you mind submitting a first PR for that? Thanks

**Comment by victornoel** [comment]
Ok, I will soon (most certainly not before this week-end :) as well as submit some PR for jax-rs-pac4j.
