### ISSUE TITLE
in-memory ProfileService

### ISSUE THREAD

**Issue by eroux** [pac4j/pac4j#942]
I think it would be very useful to have an InMemoryServiceProvider to mock a service provider in tests. This would simplify the task of test writing quite a lot. Currently I'm using a CouchServiceProvider using a mocked CouchDB to get this result, but it's uselessly cumbersome

**Comment by eroux** [comment]
If you think it's a good idea I can probably make a quick pull request, just tell me what you think

**Comment by leleuj** [comment]
`ServiceProvider`, you mean `ProfileService`? In any case, it's certainly a good idea to have some in memory mock.

**Comment by eroux** [comment]
yes, `ProfileService`, sorry! Should I build it into `pac4j-core` or a new `pac4j-mem`?

**Comment by leleuj** [comment]
Let's put that in the `pac4j-core` module, for now, to avoid having too many modules.

**Comment by eroux** [comment]
ok thanks! Sorry for my annoying questions, but what's the most appropriate path? would `org.pac4j.core.util.inMemoryProvider` be ok?

**Comment by leleuj** [comment]
I would say: `org.pac4j.core.profile.service.InMemoryProfileService`.

**Comment by eroux** [comment]
is it ok to extend `AbstractProfileService<CommonProfile>` or should I create an `InMemoryProfile`?

**Comment by leleuj** [comment]
I think it's better to keep the generic: `InMemoryProfileService<U extends CommonProfile>`...
