### ISSUE TITLE
couch parameters in pac4j-config

### ISSUE THREAD

**Issue by eroux** [pac4j/pac4j#943]
I'm planning to make a pull request to add a `CouchAuthenticatorBuilder` in pac4j-config, please comment

**Comment by leleuj** [comment]
What would it be used for? Some fluent API builder to instantiate a `CouchProfileService`?

**Comment by eroux** [comment]
yes, I'm trying to use the `PropertiesConfigFactory` and I'd like to set my CouchDB parameters there. It would be on the same model as sql or ldap. Or is there something I didn't understand correctly?

**Comment by leleuj** [comment]
Sorry, forget my comment, I read this issue too quickly. Indeed, in the `pac4j-config`.

You're right. It would be really close to what we have for LDAP or SQL.

**Comment by eroux** [comment]
Well, thinking about it, if you accept #942, I think it would be quite relevant to add a `inmemory.passwordEncoder` that would create an `InMemoryProfileService` witht the associated `passwordEncoder`, this would simplify the overhead of testing configuration quite a lot. If that's OK for you I'll do that

**Comment by leleuj** [comment]
We started the development of version 3.0 only a few weeks ago, so it's perfect for this contribution...

**Comment by leleuj** [comment]
@eroux : any update on this?

**Comment by leleuj** [comment]
I'm sorting issues. Closing this one for now. Feel free to reopen with your contribution.
