### ISSUE TITLE
Expose (Issuer) EntityID and AuthnContext from recieved SAML 2 assertion as attributes

### ISSUE THREAD

**Issue by rrenomeron** [pac4j/pac4j#947]
Add mechanism to return the issuer EntityID and AuthnContext via the UserProfile so they can be used by downstream authentication and/or authorization processes.

Doing this unconditionally is a fairly straightforward change (I think) to saml/sso/impl/SAML2DeafultResponseValidator; making it optional might take a bit of thought.

**Comment by leleuj** [comment]
I don't want to do that by default, but this should be extensible really easily. Waiting for your proposal...

**Comment by rrenomeron** [comment]
I would like to understand the reluctance to simply add these attribute values as opposed to adding configuration to make it optional.  To me, adding configuration to do this would be a more invasive patch, both to pac4j and for the consumer (CAS).

**Comment by leleuj** [comment]
Sure. By design, the `UserProfile` stores the profile of the user: an identifier and attributes (and some other things). It's not generally meant to store authentication attributes (here I mean the issuer and the AuthnContext).

**Comment by rrenomeron** [comment]
Would it be better to have them be part of the SAML2Profile class?  There are already authentication-related attributes available via getters there (e.g. NotBefore/NotOnOrAfter).

**Comment by leleuj** [comment]
You're right. There is a gap between the intended design and what we practically implemented.

I think we need to store separately the authentication attributes. I just opened: https://github.com/pac4j/pac4j/issues/948 for that. It should be fairly straightforward as the `authenticationAttributes` should work exactly like the `attributes` map.

So regarding this issue, either you do #948 first or directly work on this one.
