### ISSUE TITLE
Transform org.pac4j.core.exception.TechnicalException for Rest API

### ISSUE THREAD

**Issue by PhanNN** [pac4j/pac4j#949]
Hello, 

I want to transform this exception

org.pac4j.core.exception.TechnicalException: Ticket granting ticket request failed: null 401(401)
	at org.pac4j.cas.credentials.authenticator.CasRestAuthenticator.requestTicketGrantingTicket(CasRestAuthenticator.java:98)

When authenticating user failed, I have this exception. I tried to use exceptionhandling().authenticationEntryPoint but it didn't handle this exception. I think it only handles for AuthenticationException. 
But when I used @ExceptionHandler with TechnicalException, it can't handle. 

@ExceptionHandler(TechnicalException.class)
	@ResponseBody
	public ResponseEntity<Object> exceptionHandler(TechnicalException e) {

		HashMap<String, Object> msg = Maps.newHashMap();
		msg.put("error", HttpStatus.UNAUTHORIZED);
		msg.put("message", "Invalid credentials");
		return new ResponseEntity<>(msg, HttpStatus.UNAUTHORIZED);
	}

Could you pls give me an idea for this issue?

Thank you so much.

**Comment by victornoel** [comment]
@PhanNN which framework are you using with pac4j?

**Comment by PhanNN** [comment]
Hello @victornoel,
I'm using Spring boot.

**Comment by victornoel** [comment]
@PhanNN ok, so it would be best to first ask the question on the pac4j-user mailing list (http://www.pac4j.org/mailing-lists.html) and if you want to open an issue, use one of the spring integration projects to report it: https://github.com/pac4j?utf8=%E2%9C%93&q=spring (the one you use :).

**Comment by PhanNN** [comment]
Oops, Thanks :)

**Comment by victornoel** [comment]
For the record: https://groups.google.com/d/topic/pac4j-users/msN-F7YeS6U/discussion

Also, I'm not 100% sure it is normal that a `TechnicalException` is thrown in this situation (but I'm not familiar with pac4j-cas, @leleuj will know more, let's wait for his opinion). We will reopen if it's a problem, until then, transforming the exception should work, but it's more a spring question than a pac4j question I guess...

**Comment by leleuj** [comment]
This error happens when the CAS server does not reply properly: https://github.com/pac4j/pac4j/blob/master/pac4j-cas/src/main/java/org/pac4j/cas/credentials/authenticator/CasRestAuthenticator.java#L73

I think there is a more general question when dealing with "unexpected errors": should we hide them or throw them (my current choice in most cases)?

**Comment by victornoel** [comment]
@leleuj if I understand well, the error comes from the fact that the client is maybe misconfigured or the CAS server, not that the user can't be authenticated by CAS.
If it is the case, then I agree that an error should be thrown like it is the case now and the problem fixed by the administrator of the application...

**Comment by PhanNN** [comment]
It's occur when I type wrong password, so I don't think this issue related to CAS misconfiguration. 
When using password correctly, the flow works normally.
Ticket granting ticket request failed: null 401

401 error when CAS authenticate failed.


=============================================================
WHO: phannguyen
WHAT: Supplied credentials: [phannguyen]
ACTION: AUTHENTICATION_FAILED
APPLICATION: CAS
WHEN: Tue Jun 27 11:44:57 ICT 2017
CLIENT IP ADDRESS: 0:0:0:0:0:0:0:1
SERVER IP ADDRESS: 0:0:0:0:0:0:0:1
=============================================================

>
2017-06-27 11:44:57,534 ERROR [org.apereo.cas.support.rest.TicketsResource] - <1 errors, 0 successes>
org.apereo.cas.authentication.AuthenticationException: 1 errors, 0 successes
        at org.apereo.cas.authentication.PolicyBasedAuthenticationManager.evaluateProducedAuthenticationContext(

**Comment by victornoel** [comment]
Ok, so it seems to me we are hitting a bug in pac4j-cas, could you maybe open an issue in the pac4j repository with what you just explained and the error you just showed?
Thanks a lot :)

**Comment by victornoel** [comment]
oups sorry, deleted my previous comment, we alrealy are in pac4j ^^

**Comment by leleuj** [comment]
It looks like a bug eventually: we should return `null` when receiving a 401 error instead of throwing a `TechnicalException`.

@PhanNN would you mind submitting a fix? Thanks

**Comment by PhanNN** [comment]
@leleuj : yes, we should return null value for ticketGrantingTicketId and also set null profile for **credentials**
What do you think?

**Comment by leleuj** [comment]
I'm in line with the idea.
