### ISSUE TITLE
About coding style

### ISSUE THREAD

**Issue by tianyin** [pac4j/pac4j#955]
I read `CONTRIBUTING.md` and checked out `.editorconfig`.
(it seems that we use EditorConfig for code-style control)
However, there're still a number of style violations.

I run `CheckStyle` with the `LineLength < 140` rule (specified in `.editorconfig`) and there are `57` lines longer than `140` chars.

Similarly, the indent is not always consistent. 
I run `CheckStyle` with the "indent as 4 space" rule (specified in `.editorconfig`) and there're 18 violations.
For example, in `pac4j-core/src/main/java/org/pac4j/core/client/Clients.java`,
line 39 uses a `tab` as indentation instead of spaces; same as Line 138--140, Line 173--177. 
(there're also violations of other rules such as `end_of_line = lf`, etc)

As a more general question, shall we use `CheckStyle` or something alike to enforce the code style as a part of integration testing?
Relying on Editor/IDE settings seems not very effective :(

Thanks!

**Comment by victornoel** [comment]
That can't be a bad thing to enforce these things :)

**Comment by leleuj** [comment]
I generally have the feeling that using Checkstyle is mostly a waste of time, but I'll follow the agreement on this.

**Comment by victornoel** [comment]
To me, it's useful only when there is multiple people working on the same project and you don't want to bother with verifying and each and every PR for style.

Checkstyle itself, I don't know well… would be good enough to run an editorconfig utility and fail the build if it's not valid w.r.t. the editorconfig file? Something like this: https://github.com/slang800/editorconfig-tools (not sure there is an official tool… I thought there was but can't find it anymore…)

**Comment by victornoel** [comment]
Actually maybe https://github.com/jedmao/eclint is better…

**Comment by tianyin** [comment]
`eclint` is cool as we've already adopted `.editorconfig`.

The nice thing about CheckStyle is that it is the de facto style checker for Maven projects,
so it can be directly integrated into the build process.
For `eclint`, we perhaps need to add an ad hoc scripts if we want to do this.

@leleuj what's the problem of CheckStyle? (just want to understand a little bit more)

**Comment by leleuj** [comment]
"ugly side of Checkstyle" is a bit too much, but indeed I don't think Checkstyle is so necessary.

You can properly format your source code and break a few style rules of a project, it's not a big deal from my POV...

That being said, I'll accept a PR using Checkstyle to match our `.editorconfig`.

**Comment by leleuj** [comment]
If we are to add a style checker, this must be automatically run during the build phase. I haven't seen any Maven plugin for `eclint` which is less known also so that leaves us with `Checkstyle` I think, a lot more popular and Maven integrated.

@tianyin : can you prepare a PR with Checkstyle? Thanks

**Comment by tianyin** [comment]
sure. I'll submit today.

~t
