### ISSUE TITLE
username never filled in legacy mode

### ISSUE THREAD

**Issue by eroux** [pac4j/pac4j#957]
When reading a profile in legacy mode, the `username` field is never filled, which makes all calls to `update` [fail](https://github.com/pac4j/pac4j/blob/0f59217e807627e0f52771d6a40f4ad707b61beb/pac4j-core/src/main/java/org/pac4j/core/profile/service/AbstractProfileService.java#L88) in the ProfileService. The reason username cannot be filled is that it [cannot be specified](https://github.com/pac4j/pac4j/blob/0f59217e807627e0f52771d6a40f4ad707b61beb/pac4j-core/src/main/java/org/pac4j/core/profile/service/AbstractProfileService.java#L58) in the attributes of the legacy mode and is [never filled](https://github.com/pac4j/pac4j/blob/0f59217e807627e0f52771d6a40f4ad707b61beb/pac4j-core/src/main/java/org/pac4j/core/profile/service/AbstractProfileService.java#L228) in the `username` attribute. Note that it is filled in the `id` attribute, which I have difficulties to understand... why not just having the `id` as `id` and the `username` as `username`? I can make a PR in this direction but I'd like comments first, to be sure it's the correct one.

**Comment by leleuj** [comment]
This feels tricky, but it was the behavior we had in 1.9 where this legacy mode existed first. That's why I kept the behavior.

That said, we could maybe populate the username as well in legacy mode, to make things backward compatible but also a bit more consistent.

**Comment by eroux** [comment]
Well, maybe an option to keep the old behavior would be ok? maybe turned off by default?

**Comment by eroux** [comment]
As a side note, I'm [working around it](https://github.com/BuddhistDigitalResourceCenter/auth-api/blob/master/src/main/java/io/bdrc/auth/server/BDRCProfileService.java#L47) by overriding `convertAttributesToProfile`.

**Comment by leleuj** [comment]
Wouldn't it be enough to save the username in the username attribute as well as in the identifier?

**Comment by eroux** [comment]
well, then we don't have the id of the profile (it would be replaced by the username), I think that would make the profileServices confused? For instance the InMemoryProfileService relies on the `id` field to save a profile, if it points to the username, it will save the profile in the wrong place, same for the CouchProfileService...

**Comment by leleuj** [comment]
I see your point, but if you don't really need that old legacy behavior, why don't you use the new mode (with the serialized profile)?

**Comment by eroux** [comment]
Well, I guess something is unclear to me... For me there are two different behaviors:

1. saving each field separately in the database
2. having the content of the `username` field of the database in the `id` field of the fetched profile

I want `1.` for practical reasons: I use CouchDB so there's no point for me to serialize everything in a big string, I find it much clearer to have separate fields... but clearly, I think `2.` is completely bogus and I don't want it. The question is thus to know if the legacy mode is the union of 1 and 2 or just 2? I guess I can get away from 1 if 2 comes with it automatically... Also, something is really unclear in the documentation: is the legacy mode deprecated? Will it be in the future?

**Comment by leleuj** [comment]
No, we have two different behaviors: either every field is saved separately in the DB or the main fields are saved plus the serialized profile (as not all field types can be easily saved in the DB).

I planned to kill the legacy mode, but I'm not so sure about this. It makes sense to have it for already existing databases.

legacy mode: 'getIdAttribute()' + linkedid + 'getUsernameAttribute()' + attributes
new mode: 'getIdAttribute()' + linkedid + serializedprofile

I guess the solution could be to use the username only if no identifier is found in the storage system. This should be more or less backward compatible.

**Comment by eroux** [comment]
ok, I'll just switch to the new mode but will not make pull request for this

**Comment by leleuj** [comment]
Closing for now. We'll see if someone else raises the point.
