### ISSUE TITLE
How can I get session store information from sessionId

### ISSUE THREAD

**Issue by xhe** [pac4j/pac4j#963]
Hello, I want to ask if it is possible to retrieve session information from sessionId directly.

In my situation, I have an auth service running pac4JSaml, once user is authenticated, pac4JSaml service is sending user to our UI service in NodeJS.

Now for security reason, I want to have auth service to send user to NodeJS with url of http://nodeserver/auth_callback, and then in the callback, nodeJS can issue and api request to pac4J auth service to retrieve the authentication jwt token. All these steps should be between server to server, and user should not see it from browser, so no hacker can hack it.

Now, I thought to save session info for pack4JSaml auth service to be saved in mongoDB (this is successful), and then when nodeJS is sending api request, the session information should be easily retrieved.

But I failed, NodeJS can send api to auth-service, but when auth server is receiving this API request, it does NOT know the session.

So I tested by sending these headers to Pac4J Auth Server:

```
{ 'X-AUTH-TOKEN': 'faked',
     cookie: { SESSION: '7ac7d46f-afad-4ec2-8bb7-d5d650057c08' },
     Accept: 'application/json' } }

```
I thought as long as I am sending SESSION in cookie header, then below code should work:

```
final WebContext context = new J2EContext(request, response);
		String token =  (String) context.getSessionAttribute(SESSION_NAME_TOKEN);;
		String atts = 	(String) context.getSessionAttribute(SESSION_NAME_ATTRIBUTES);

```
Unfortunately, I still failed.

My question is how can I use session in NodeJS without any browser being used here? If that is not possible, any idea how to use SessionStorage to retrieve session information from sessionId using WebContext?

Thanks

**Comment by leleuj** [comment]
Please ask your question on the mailing list: http://www.pac4j.org/mailing-lists.html
