### ISSUE TITLE
Release pac4j v2.1.0: Past due by 8 days

### ISSUE THREAD

**Issue by mmoayyed** [pac4j/pac4j#965]
Should we release this, or push the date back? See milestones.

**Comment by leleuj** [comment]
I don't think we are in a hurry, waiting for a mandatory fix, so I'd prefer to postpone to the end of the month.

**Comment by mmoayyed** [comment]
That's fine with me too.

PS In general, it's not a good idea to set expectations and release dates, if they cannot be met. It's best to follow what is laid down, otherwise no point in managing policy ad-hoc.

**Comment by leleuj** [comment]
You're right. I removed the release date. No pressure.
