### ISSUE TITLE
CAS delegate Issue

### ISSUE THREAD

**Issue by rinkuvatscs** [pac4j/pac4j#970]
@leleuj  
 I am using CAS 5.0.4 . I want to delegate my request to Oauth 2 Server for Autentication. i checked CasOauthWrapperClient but is not working for me. I changed my CAS 5.1.1 then i able to configure GenericOauth20Client with below properties

cas.authn.pac4j.oauth2[0].id=[ID]
cas.authn.pac4j.oauth2[0].secret=[SECRET]
cas.authn.pac4j.oauth2[0].authUrl=
cas.authn.pac4j.oauth2[0].tokenUrl=[AUTH URL]
cas.authn.pac4j.oauth2[0].profileUrl=[PROFILE URL]
cas.authn.pac4j.oauth2[0].profilePath=[NOT CLEAR WHY USING]
cas.authn.pac4j.oauth2[0].profileVerb=GET
 
Now after configuring above Properties in CAS 5.1.1 i am able to one link GenericOauth20 in 'OR login with' block.

But i am not able to understand its creating wrong redirect_url or i am doing something wrong.

Example:
My CAS Server(5.1.1) is running on 7000 which is acting as client and my another cas server(5.0.4) is running on 8443 from where i want to authenticate. Please check below image.

![image](https://user-images.githubusercontent.com/13444403/29165879-f1d0fa5e-7de1-11e7-90f8-112abe4bb35f.png)

Please suggest way how i can move ahead using CAS 5.0.4 or CAS 5.1.1.
Thanks in Advance.

**Comment by leleuj** [comment]
Plase use the CAS or pac4j-users mailing lists.
