### ISSUE TITLE
Missing AttributeConsumingServiceIndex into AuthnRequest

### ISSUE THREAD

**Issue by fmartelli** [pac4j/pac4j#979]
SAML2AuthnRequestBuilder does not take care of AttributeConsumingServiceIndex AuthnRequest attribute. Maye should be better to provide client configuration with a new parameter to specify service index to be specified into the request. The builder should take care of this parameter by specifying its value through setAttributeConsumingServiceIndex() method of AuthnRequest object.

**Comment by mmoayyed** [comment]
Closed via https://github.com/pac4j/pac4j/pull/980
