### ISSUE TITLE
Binding not properly generated in SAML metadata

### ISSUE THREAD

**Issue by leleuj** [pac4j/pac4j#989]
After some investigation I noticed that even if i alter the Pac4j config object by setting: cfg.setDestinationBindingType(SAMLConstants.SAML2_REDIRECT_BINDING_URI);
the generated meta-data file still does not alter the assertionBinding. Which i can see the SAML2MetaDataGenerator line 197.. it's hardcoded to only do SAML2_POST_BINDING_URI.
The resulting assertion binding is set to: <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location=" ... " index="0"/>

**Comment by richard77** [comment]
+1 Thanks for resolving in #1012 
Was not able to push fixes in time.

**Comment by papegaaij** [comment]
This 'fix' breaks our SSO-flows badly. This 'destination binding type' is now used for both the authn request and the response binding. It is uncommon to use post binding for the authn request, while it is common to use it for the response. After this change, this is no longer possible to configure
