### ISSUE TITLE
RelativeUrlResolver doesn't consider application context path

### ISSUE THREAD

**Issue by mizgeliko** [pac4j/pac4j#993]
Before reporting any issue, please use the mailing lists: http://www.pac4j.org/mailing-lists.html

**Comment by leleuj** [comment]
The `RelativeUrlResolver` assumes you have provided the right path. By design.

**Comment by millross** [comment]
Agree with Jérôme. Not every web framework is tightly coupled to the concept of an application context path. If you want that approach, it shouldn't be part of core. No reason why there couldn't be a RelativeUrlResolverWithContextPath exposed for frameworks where context path is important.

**Comment by mizgeliko** [comment]
Guys, it is not a big deal to write own resolver, but from my point of view "relative" means an attempt to avoid hardcoding and context can't be a part of right path.

**Comment by millross** [comment]
And from my point of view, relative is not relative to context path, it's relative to the server/port combination. This also would appear to be Jérôme's view too.

**Comment by millross** [comment]
Feel free to submit a PR for one which is context-path based and not in core, but in the appropriate framework implementation.

**Comment by victornoel** [comment]
at least in jax-rs-pac4j, I implemented something like that I think: https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/pac4j/JaxRsUrlResolver.java

**Comment by leleuj** [comment]
Yes, "relative" here means server/port, nothing more. We could easily add the path to the generated URL, please submit a PR for further discussion.
