### ISSUE TITLE
Provide a default java.security.Principal implementation

### ISSUE THREAD

**Issue by victornoel** [pac4j/pac4j#996]
Following a discussion in pac4j/j2e-pac4j#44, we decided with @leleuj to move jax-rs-pac4j's `java.security.Principal` implementation into pac4j-core since it was only specific to pac4j and could be useful for other  frameworks.

@leleuj question: where do I put it in the source tree? I was thinking in the `profile` package…

**Comment by leleuj** [comment]
Yes, it makes sense to put that in the the `profile` package.
